In [1]:
%%capture
!pip install textacy
!pip install faiss-gpu
!pip install chromadb
!pip install nltk
!pip install sentence_transformers

In [2]:
%%capture
# Initiliase Ollama server on a thread

#Download ollama
!curl -fsSL https://ollama.com/install.sh | sh
import subprocess
process = subprocess.Popen("ollama serve", shell=True) #runs on a different thread
#Download model
!ollama pull llama3
!pip install ollama
import ollama
model_name = 'llama3'

Couldn't find '/root/.ollama/id_ed25519'. Generating new private key.
Your new public key is:

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILznwp/xrtEPw/zMAI0c2aoJYWr4igWgIyeNbDGcLdhl

time=2025-06-26T23:04:53.594Z level=INFO source=routes.go:1235 msg="server config" env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_CONTEXT_LENGTH:4096 OLLAMA_DEBUG:INFO OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/root/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NEW_ENGINE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://* vscode-file://*] OLLAMA_SCHED_SPREAD:false ROCR_VISIBLE_DEVICES: http_proxy: https_proxy: no_proxy:]"
time=2025-06-26T23:04:53.595Z level=INFO source=images.go:476 msg="total blobs: 0"
time=2025-06-26T23:04:53.595Z level=INFO source=images.go:483 msg="total unused blobs removed: 0"
time=2025-06-26T23:04:53.595Z level=INFO source=routes.go:1288 msg="Listening on 127.0.0.1:11434 (version 0.9.3)"
time=2025-06-26T23:04:53.596Z level=INFO source=gpu.go:217 msg="looking for compatible GPUs"
time=2025-06-26T23:04:53.963Z level=INFO source=types.go:130 msg="inference compute" id=GPU-c23d3adf-c490-01aa-967f-af8c942e005d library=cuda variant=v12 compute=7.5 driver=12.6 name="Tesla T4" total="14.7 GiB" available="14.6 GiB"
time=2025-06-26T23:04:53.963Z level=INFO source=types.go:130 msg="inference compute" id=GPU-a8699652-45ca-2565-e9ff-2e5b3378d4e6 library=cuda variant=v12 compute=7.5 driver=12.6 name="Tesla T4" total="14.7 GiB" available="14.6 GiB"

[GIN] 2025/06/26 - 23:04:53 | 200 |      56.166µs |       127.0.0.1 | HEAD     "/"

time=2025-06-26T23:04:54.543Z level=INFO source=download.go:177 msg="downloading 6a0746a1ec1a in 16 291 MB part(s)"
time=2025-06-26T23:05:10.350Z level=INFO source=download.go:177 msg="downloading 4fa551d4f938 in 1 12 KB part(s)"
time=2025-06-26T23:05:11.519Z level=INFO source=download.go:177 msg="downloading 8ab4849b038c in 1 254 B part(s)"
time=2025-06-26T23:05:12.700Z level=INFO source=download.go:177 msg="downloading 577073ffcc6c in 1 110 B part(s)"
time=2025-06-26T23:05:13.845Z level=INFO source=download.go:177 msg="downloading 3f8eb4da87fa in 1 485 B part(s)"

[GIN] 2025/06/26 - 23:05:29 | 200 | 35.099433737s |       127.0.0.1 | POST     "/api/pull"

In [3]:
import re
import asyncio
import pandas as pd
import numpy as np
from pydantic import BaseModel
from ollama import AsyncClient
import textacy.datasets
import requests
import json
from sentence_transformers import SentenceTransformer
from textwrap import shorten
import nltk
from textacy.representations.vectorizers import Vectorizer
from sklearn.metrics.pairwise import cosine_similarity
import chromadb
import torch

2025-06-26 23:05:51.412118: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1750979151.636976      35 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1750979151.700713      35 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

In [4]:
legal_topics = {
    "0": "None",
    "1": "involuntary confession",
    "2": "habeas corpus",
    "3": "plea bargaining: the constitutionality of and/or the circumstances of its exercise",
    "4": "retroactivity (of newly announced or newly enacted constitutional or statutory rights)",
    "5": "search and seizure (other than as pertains to vehicles or Crime Control Act)",
    "6": "search and seizure, vehicles",
    "7": "search and seizure, Crime Control Act",
    "8": "contempt of court or congress",
    "9": "self-incrimination (other than as pertains to Miranda or immunity from prosecution)",
    "10": "Miranda warnings",
    "11": "self-incrimination, immunity from prosecution",
    "12": "right to counsel (cf. indigents appointment of counsel or inadequate representation)",
    "13": "cruel and unusual punishment, death penalty (cf. extra legal jury influence, death penalty)",
    "14": "cruel and unusual punishment, non-death penalty (cf. liability, civil rights acts)",
    "15": "line-up",
    "16": "discovery and inspection (in the context of criminal litigation only, otherwise Freedom of Information Act and related federal or state statutes or regulations)",
    "17": "double jeopardy",
    "18": "ex post facto (state)",
    "19": "extra-legal jury influences: miscellaneous",
    "20": "extra-legal jury influences: prejudicial statements or evidence",
    "21": "extra-legal jury influences: contact with jurors outside courtroom",
    "22": "extra-legal jury influences: jury instructions (not necessarily in criminal cases)",
    "23": "extra-legal jury influences: voir dire (not necessarily a criminal case)",
    "24": "extra-legal jury influences: prison garb or appearance",
    "25": "extra-legal jury influences: jurors and death penalty (cf. cruel and unusual punishment)",
    "26": "extra-legal jury influences: pretrial publicity",
    "27": "confrontation (right to confront accuser, call and cross-examine witnesses)",
    "28": "subconstitutional fair procedure: confession of error",
    "29": "subconstitutional fair procedure: conspiracy (cf. Federal Rules of Criminal Procedure: conspiracy)",
    "30": "subconstitutional fair procedure: entrapment",
    "31": "subconstitutional fair procedure: exhaustion of remedies",
    "32": "subconstitutional fair procedure: fugitive from justice",
    "33": "subconstitutional fair procedure: presentation, admissibility, or sufficiency of evidence (not necessarily a criminal case)",
    "34": "subconstitutional fair procedure: stay of execution",
    "35": "subconstitutional fair procedure: timeliness",
    "36": "subconstitutional fair procedure: miscellaneous",
    "37": "Federal Rules of Criminal Procedure",
    "38": "statutory construction of criminal laws: assault",
    "39": "statutory construction of criminal laws: bank robbery",
    "40": "statutory construction of criminal laws: conspiracy (cf. subconstitutional fair procedure: conspiracy)",
    "41": "statutory construction of criminal laws: escape from custody",
    "42": "statutory construction of criminal laws: false statements (cf. statutory construction of criminal laws: perjury)",
    "43": "statutory construction of criminal laws: financial (other than in fraud or internal revenue)",
    "44": "statutory construction of criminal laws: firearms",
    "45": "statutory construction of criminal laws: fraud",
    "46": "statutory construction of criminal laws: gambling",
    "47": "statutory construction of criminal laws: Hobbs Act; i.e., 18 USC 1951",
    "48": "statutory construction of criminal laws: immigration (cf. immigration and naturalization)",
    "49": "statutory construction of criminal laws: internal revenue (cf. Federal Taxation)",
    "50": "statutory construction of criminal laws: Mann Act and related statutes",
    "51": "statutory construction of criminal laws: narcotics includes regulation and prohibition of alcohol",
    "52": "statutory construction of criminal laws: obstruction of justice",
    "53": "statutory construction of criminal laws: perjury (other than as pertains to statutory construction of criminal laws: false statements)",
    "54": "statutory construction of criminal laws: Travel Act, 18 USC 1952",
    "55": "statutory construction of criminal laws: war crimes",
    "56": "statutory construction of criminal laws: sentencing guidelines",
    "57": "statutory construction of criminal laws: miscellaneous",
    "58": "jury trial (right to, as distinct from extra-legal jury influences)",
    "59": "speedy trial",
    "60": "miscellaneous criminal procedure (cf. due process, prisoners' rights, comity: criminal procedure)",
    "61": "voting",
    "62": "Voting Rights Act of 1965, plus amendments",
    "63": "ballot access (of candidates and political parties)",
    "64": "desegregation (other than as pertains to school desegregation, employment discrimination, and affirmative action)",
    "65": "desegregation, schools",
    "66": "employment discrimination: on basis of race, age, religion, illegitimacy, national origin, or working conditions.",
    "67": "affirmative action",
    "68": "slavery or indenture",
    "69": "sit-in demonstrations (protests against racial discrimination in places of public accommodation)",
    "70": "reapportionment: other than plans governed by the Voting Rights Act",
    "71": "debtors' rights",
    "72": "deportation (cf. immigration and naturalization)",
    "73": "employability of aliens (cf. immigration and naturalization)",
    "74": "sex discrimination (excluding sex discrimination in employment)",
    "75": "sex discrimination in employment (cf. sex discrimination)",
    "76": "Indians (other than pertains to state jurisdiction over)",
    "77": "Indians, state jurisdiction over",
    "78": "juveniles (cf. rights of illegitimates)",
    "79": "poverty law, constitutional",
    "80": "poverty law, statutory: welfare benefits, typically under some Social Security Act provision.",
    "81": "illegitimates, rights of (cf. juveniles): typically inheritance and survivor's benefits, and paternity suits",
    "82": "handicapped, rights of: under Rehabilitation, Americans with Disabilities Act, and related statutes",
    "83": "residency requirements: durational, plus discrimination against nonresidents",
    "84": "military: draftee, or person subject to induction",
    "85": "military: active duty",
    "86": "military: veteran",
    "87": "immigration and naturalization: permanent residence",
    "88": "immigration and naturalization: citizenship",
    "89": "immigration and naturalization: loss of citizenship, denaturalization",
    "90": "immigration and naturalization: access to public education",
    "91": "immigration and naturalization: welfare benefits",
    "92": "immigration and naturalization: miscellaneous",
    "93": "indigents: appointment of counsel (cf. right to counsel)",
    "94": "indigents: inadequate representation by counsel (cf. right to counsel)",
    "95": "indigents: payment of fine",
    "96": "indigents: costs or filing fees",
    "97": "indigents: U.S. Supreme Court docketing fee",
    "98": "indigents: transcript",
    "99": "indigents: assistance of psychiatrist",
    "100": "indigents: miscellaneous",
    "101": "liability, civil rights acts (cf. liability, governmental and liability, nongovernmental; cruel and unusual punishment, non-death penalty)",
    "102": "miscellaneous civil rights (cf. comity: civil rights)",
    "103": "First Amendment, miscellaneous (cf. comity: First Amendment)",
    "104": "commercial speech, excluding attorneys",
    "105": "libel, defamation: defamation of public officials and public and private persons",
    "106": "libel, privacy: true and false light invasions of privacy",
    "107": "legislative investigations: concerning internal security only",
    "108": "federal or state internal security legislation: Smith, Internal Security, and related federal statutes",
    "109": "loyalty oath or non-Communist affidavit (other than bar applicants, government employees, political party, or teacher)",
    "110": "loyalty oath: bar applicants (cf. admission to bar, state or federal or U.S. Supreme Court)",
    "111": "loyalty oath: government employees",
    "112": "loyalty oath: political party",
    "113": "loyalty oath: teachers",
    "114": "security risks: denial of benefits or dismissal of employees for reasons other than failure to meet loyalty oath requirements",
    "115": "conscientious objectors (cf. military draftee or military active duty) to military service",
    "116": "campaign spending (cf. governmental corruption):",
    "117": "protest demonstrations (other than as pertains to sit-in demonstrations): demonstrations and other forms of protest based on First Amendment guarantees",
    "118": "free exercise of religion",
    "119": "establishment of religion (other than as pertains to parochiaid:)",
    "120": "parochiaid: government aid to religious schools, or religious requirements in public schools",
    "121": "obscenity, state (cf. comity: privacy): including the regulation of sexually explicit material under the 21st Amendment",
    "122": "obscenity, federal",
    "123": "due process: miscellaneous (cf. loyalty oath), the residual code",
    "124": "due process: hearing or notice (other than as pertains to government employees or prisoners' rights)",
    "125": "due process: hearing, government employees",
    "126": "due process: prisoners' rights and defendants' rights",
    "127": "due process: impartial decision maker",
    "128": "due process: jurisdiction (jurisdiction over non-resident litigants)",
    "129": "due process: takings clause, or other non-constitutional governmental taking of property",
    "130": "privacy (cf. libel, comity: privacy)",
    "131": "abortion: including contraceptives",
    "132": "right to die",
    "133": "Freedom of Information Act and related federal or state statutes or regulations",
    "134": "attorneys' and governmental employees' or officials' fees or compensation or licenses",
    "135": "commercial speech, attorneys (cf. commercial speech)",
    "136": "admission to a state or federal bar, disbarment, and attorney discipline (cf. loyalty oath: bar applicants)",
    "137": "admission to, or disbarment from, Bar of the U.S. Supreme Court",
    "138": "arbitration (in the context of labor-management or employer-employee relations) (cf. arbitration)",
    "139": "union antitrust: legality of anticompetitive union activity",
    "140": "union or closed shop: includes agency shop litigation",
    "141": "Fair Labor Standards Act",
    "142": "Occupational Safety and Health Act",
    "143": "union-union member dispute (except as pertains to union or closed shop)",
    "144": "labor-management disputes: bargaining",
    "145": "labor-management disputes: employee discharge",
    "146": "labor-management disputes: distribution of union literature",
    "147": "labor-management disputes: representative election",
    "148": "labor-management disputes: antistrike injunction",
    "149": "labor-management disputes: jurisdictional dispute",
    "150": "labor-management disputes: right to organize",
    "151": "labor-management disputes: picketing",
    "152": "labor-management disputes: secondary activity",
    "153": "labor-management disputes: no-strike clause",
    "154": "labor-management disputes: union representatives",
    "155": "labor-management disputes: union trust funds (cf. ERISA)",
    "156": "labor-management disputes: working conditions",
    "157": "labor-management disputes: miscellaneous dispute",
    "158": "miscellaneous union",
    "159": "antitrust (except in the context of mergers and union antitrust)",
    "160": "mergers",
    "161": "bankruptcy (except in the context of priority of federal fiscal claims)",
    "162": "sufficiency of evidence: typically in the context of a jury's determination of compensation for injury or death",
    "163": "election of remedies: legal remedies available to injured persons or things",
    "164": "liability, governmental: tort or contract actions by or against government or governmental officials other than defense of criminal actions brought under a civil rights action.",
    "165": "liability, other than as in sufficiency of evidence, election of remedies, punitive damages",
    "166": "liability, punitive damages",
    "167": "Employee Retirement Income Security Act (cf. union trust funds)",
    "168": "state or local government tax",
    "169": "state and territorial land claims",
    "170": "state or local government regulation, especially of business (cf. federal pre-emption of state court jurisdiction, federal pre-emption of state legislation or regulation)",
    "171": "federal or state regulation of securities",
    "172": "natural resources - environmental protection (cf. national supremacy: natural resources, national supremacy: pollution)",
    "173": "corruption, governmental or governmental regulation of other than as in campaign spending",
    "174": "zoning: constitutionality of such ordinances, or restrictions on owners' or lessors' use of real property",
    "175": "arbitration (other than as pertains to labor-management or employeremployee relations (cf. union arbitration)",
    "176": "federal or state consumer protection: typically under the Truth in Lending; Food, Drug and Cosmetic; and Consumer Protection Credit Acts",
    "177": "patents and copyrights: patent",
    "178": "patents and copyrights: copyright",
    "179": "patents and copyrights: trademark",
    "180": "patents and copyrights: patentability of computer processes",
    "181": "federal or state regulation of transportation regulation: railroad",
    "182": "federal and some few state regulations of transportation regulation: boat",
    "183": "federal and some few state regulation of transportation regulation:truck, or motor carrier",
    "184": "federal and some few state regulation of transportation regulation: pipeline (cf. federal public utilities regulation: gas pipeline)",
    "185": "federal and some few state regulation of transportation regulation: airline",
    "186": "federal and some few state regulation of public utilities regulation: electric power",
    "187": "federal and some few state regulation of public utilities regulation: nuclear power",
    "188": "federal and some few state regulation of public utilities regulation: oil producer",
    "189": "federal and some few state regulation of public utilities regulation: gas producer",
    "190": "federal and some few state regulation of public utilities regulation: gas pipeline (cf. federal transportation regulation: pipeline)",
    "191": "federal and some few state regulation of public utilities regulation: radio and television (cf. cable television)",
    "192": "federal and some few state regulation of public utilities regulation: cable television (cf. radio and television)",
    "193": "federal and some few state regulations of public utilities regulation: telephone or telegraph company",
    "194": "miscellaneous economic regulation",
    "195": "comity: civil rights",
    "196": "comity: criminal procedure",
    "197": "comity: First Amendment",
    "198": "comity: habeas corpus",
    "199": "comity: military",
    "200": "comity: obscenity",
    "201": "comity: privacy",
    "202": "comity: miscellaneous",
    "203": "comity primarily removal cases, civil procedure (cf. comity, criminal and First Amendment); deference to foreign judicial tribunals",
    "204": "assessment of costs or damages: as part of a court order",
    "205": "Federal Rules of Civil Procedure including Supreme Court Rules, application of the Federal Rules of Evidence, Federal Rules of Appellate Procedure in civil litigation, Circuit Court Rules, and state rules and admiralty rules",
    "206": "judicial review of administrative agency's or administrative official's actions and procedures",
    "207": "mootness (cf. standing to sue: live dispute)",
    "208": "venue",
    "209": "no merits: writ improvidently granted",
    "210": "no merits: dismissed or affirmed for want of a substantial or properly presented federal question, or a nonsuit",
    "211": "no merits: dismissed or affirmed for want of jurisdiction (cf. judicial administration: Supreme Court jurisdiction or authority on appeal from federal district courts or courts of appeals)",
    "212": "no merits: adequate non-federal grounds for decision",
    "213": "no merits: remand to determine basis of state or federal court decision (cf. judicial administration: state law)",
    "214": "no merits: miscellaneous",
    "215": "standing to sue: adversary parties",
    "216": "standing to sue: direct injury",
    "217": "standing to sue: legal injury",
    "218": "standing to sue: personal injury",
    "219": "standing to sue: justiciable question",
    "220": "standing to sue: live dispute",
    "221": "standing to sue: parens patriae standing",
    "222": "standing to sue: statutory standing",
    "223": "standing to sue: private or implied cause of action",
    "224": "standing to sue: taxpayer's suit",
    "225": "standing to sue: miscellaneous",
    "226": "judicial administration: jurisdiction or authority of federal district courts or territorial courts",
    "227": "judicial administration: jurisdiction or authority of federal courts of appeals",
    "228": "judicial administration: Supreme Court jurisdiction or authority on appeal or writ of error, from federal district courts or courts of appeals (cf. 753)",
    "229": "judicial administration: Supreme Court jurisdiction or authority on appeal or writ of error, from highest state court",
    "230": "judicial administration: jurisdiction or authority of the Court of Claims",
    "231": "judicial administration: Supreme Court's original jurisdiction",
    "232": "judicial administration: review of non-final order",
    "233": "judicial administration: change in state law (cf. no merits: remand to determine basis of state court decision)",
    "234": "judicial administration: federal question (cf. no merits: dismissed for want of a substantial or properly presented federal question)",
    "235": "judicial administration: ancillary or pendent jurisdiction",
    "236": "judicial administration: extraordinary relief (e.g., mandamus, injunction)",
    "237": "judicial administration: certification (cf. objection to reason for denial of certiorari or appeal)",
    "238": "judicial administration: resolution of circuit conflict, or conflict between or among other courts",
    "239": "judicial administration: objection to reason for denial of certiorari or appeal",
    "240": "judicial administration: collateral estoppel or res judicata",
    "241": "judicial administration: interpleader",
    "242": "judicial administration: untimely filing",
    "243": "judicial administration: Act of State doctrine",
    "244": "judicial administration: miscellaneous",
    "245": "Supreme Court's certiorari, writ of error, or appeals jurisdiction",
    "246": "miscellaneous judicial power, especially diversity jurisdiction",
    "247": "federal-state ownership dispute (cf. Submerged Lands Act)",
    "248": "federal pre-emption of state court jurisdiction",
    "249": "federal pre-emption of state legislation or regulation. cf. state regulation of business. rarely involves union activity. Does not involve constitutional interpretation unless the Court says it does.",
    "250": "Submerged Lands Act (cf. federal-state ownership dispute)",
    "251": "national supremacy: commodities",
    "252": "national supremacy: intergovernmental tax immunity",
    "253": "national supremacy: marital and family relationships and property, including obligation of child support",
    "254": "national supremacy: natural resources (cf. natural resources - environmental protection)",
    "255": "national supremacy: pollution, air or water (cf. natural resources environmental protection)",
    "256": "national supremacy: public utilities (cf. federal public utilities regulation)",
    "257": "national supremacy: state tax (cf. state tax)",
    "258": "national supremacy: miscellaneous",
    "259": "miscellaneous federalism",
    "260": "boundary dispute between states",
    "261": "non-real property dispute between states",
    "262": "miscellaneous interstate relations conflict",
    "263": "incorporation of foreign territories",
    "264": "federal taxation, typically under provisions of the Internal Revenue Code",
    "265": "federal taxation of gifts, personal, business, or professional expenses",
    "266": "priority of federal fiscal claims: over those of the states or private entities",
    "267": "miscellaneous federal taxation (cf. national supremacy: state tax)",
    "268": "legislative veto",
    "269": "executive authority vis-a-vis congress or the states",
    "270": "miscellaneous",
    "271": "real property",
    "272": "personal property",
    "273": "contracts",
    "274": "evidence",
    "275": "civil procedure",
    "276": "torts",
    "277": "wills and trusts",
    "278": "commercial transactions"
}

In [5]:
# Load Supreme Court dataset
sc = textacy.datasets.SupremeCourt()
sc.download()

# Area code classification for 15 labels
# print(sc.issue_areas)

mapper = sc.issue_area_codes

# Create a DataFrame from the dataset
# cases = [{"id": record.meta["issue"] ,"text": record.text , "actual_class": str(mapper[record.meta['issue_area']]) } for record in sc.records()]


# cases_df = pd.DataFrame(cases)

cases_df = pd.read_csv("/kaggle/input/labels-web-of-law/279_labels_data.csv")

# cases_df = cases_df[:100]
# Display the first few rows of the dataset
cases_df.head()
# cases_df = cases_df[:100]

100%|██████████| 111M/111M [00:01<00:00, 110MB/s]

   Unnamed: 0                                               text  label
0           0  halliburton oil cementing v walker mrearl babc...    209
1           1  rehearing denied dec mrclaude t barnes salt la...     63
2           2  rehearing denied dec appeal district court uni...    216
3           3  mr walter j cummings jr washington dc petition...    108
4           4  mra devitt vaneck washington dc petitioner mr ...    196

In [6]:
def parse_text_to_dict(text):
    result_dict = {}
    lines = text.strip().split('\n')
    for line in lines:
        line = line.strip()
        if not line or ':' not in line:
            continue
        match = re.match(r"^(.*?):\s*(.*)$", line)
        if match:
            category = match.group(1).strip()
            values = [word.strip() for word in match.group(2).split(',')]
            result_dict[category] = values
    return result_dict

def clean_text(text):
    if not isinstance(text, str):
        text = str(text)
    return re.sub(r'[^a-zA-Z0-9 ]', '', text).strip().lower()

def filter_result_dict(result_dict, valid_categories):
    cleaned_valid_categories = {clean_text(str(value)): key for key, value in valid_categories.items()}
    cleaned_result_dict = {clean_text(key): values for key, values in result_dict.items()}
    final_result = {}
    for cleaned_key, values in cleaned_result_dict.items():
        if cleaned_key in cleaned_valid_categories:
            original_key = cleaned_valid_categories[cleaned_key]
            final_result[original_key] = values
    return final_result

In [7]:
# Collect results
all_results = {}

for key, topic in legal_topics.items():
    prompt = f"""
Give me a list of words and phrases (at least 10 for each) which would be present in a case text to classify it into the following category.
Do not write any explanation or warnings. This is a python style dictionary, read it and reply accordingly for the key value pair. Do not return empty results.
        {{'{topic}': []}}

Format the output in the following way:
{topic}: word1, word2, phrase1, phrase2 ...
"""
    response = ollama.chat(model=model_name, messages=[
        {'role': 'user', 'content': prompt}
    ])
    result_dict = parse_text_to_dict(response['message']['content'])
    filtered = filter_result_dict(result_dict, {key: topic for key, topic in legal_topics.items()})
    all_results.update(filtered)

time=2025-06-26T23:06:12.241Z level=INFO source=sched.go:788 msg="new model will fit in available VRAM in single GPU, loading" model=/root/.ollama/models/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa gpu=GPU-c23d3adf-c490-01aa-967f-af8c942e005d parallel=2 available=15720382464 required="6.2 GiB"
time=2025-06-26T23:06:12.450Z level=INFO source=server.go:135 msg="system memory" total="31.4 GiB" free="29.0 GiB" free_swap="0 B"
time=2025-06-26T23:06:12.451Z level=INFO source=server.go:175 msg=offload library=cuda layers.requested=-1 layers.model=33 layers.offload=33 layers.split="" memory.available="[14.6 GiB]" memory.gpu_overhead="0 B" memory.required.full="6.2 GiB" memory.required.partial="6.2 GiB" memory.required.kv="1.0 GiB" memory.required.allocations="[6.2 GiB]" memory.weights.total="4.1 GiB" memory.weights.repeating="3.7 GiB" memory.weights.nonrepeating="411.0 MiB" memory.graph.full="560.0 MiB" memory.graph.partial="677.5 MiB"
llama_model_loader: loaded meta data with 22 key-value pairs and 291 tensors from /root/.ollama/models/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = Meta-Llama-3-8B-Instruct
llama_model_loader: - kv   2:                          llama.block_count u32              = 32
llama_model_loader: - kv   3:                       llama.context_length u32              = 8192
llama_model_loader: - kv   4:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   7:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:                       llama.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 2
llama_model_loader: - kv  11:                           llama.vocab_size u32              = 128256
llama_model_loader: - kv  12:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  13:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  14:                         tokenizer.ggml.pre str              = llama-bpe
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  17:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 128000
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 128009
llama_model_loader: - kv  20:                    tokenizer.chat_template str              = {% set loop_messages = messages %}{% ...
llama_model_loader: - kv  21:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_0:  225 tensors
llama_model_loader: - type q6_K:    1 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q4_0
print_info: file size   = 4.33 GiB (4.64 BPW)
load: special tokens cache size = 256
load: token to piece cache size = 0.8000 MB
print_info: arch             = llama
print_info: vocab_only       = 1
print_info: model type       = ?B
print_info: model params     = 8.03 B
print_info: general.name     = Meta-Llama-3-8B-Instruct
print_info: vocab type       = BPE
print_info: n_vocab          = 128256
print_info: n_merges         = 280147
print_info: BOS token        = 128000 '<|begin_of_text|>'
print_info: EOS token        = 128009 '<|eot_id|>'
print_info: EOT token        = 128009 '<|eot_id|>'
print_info: LF token         = 198 'Ċ'
print_info: EOG token        = 128009 '<|eot_id|>'
print_info: max token length = 256
llama_model_load: vocab only - skipping tensors
time=2025-06-26T23:06:12.815Z level=INFO source=server.go:438 msg="starting llama server" cmd="/usr/local/bin/ollama runner --model /root/.ollama/models/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa --ctx-size 8192 --batch-size 512 --n-gpu-layers 33 --threads 2 --parallel 2 --port 39691"
time=2025-06-26T23:06:12.815Z level=INFO source=sched.go:483 msg="loaded runners" count=1
time=2025-06-26T23:06:12.815Z level=INFO source=server.go:598 msg="waiting for llama runner to start responding"
time=2025-06-26T23:06:12.816Z level=INFO source=server.go:632 msg="waiting for server to become available" status="llm server not responding"
time=2025-06-26T23:06:12.837Z level=INFO source=runner.go:815 msg="starting go runner"
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: Tesla T4, compute capability 7.5, VMM: yes
load_backend: loaded CUDA backend from /usr/local/lib/ollama/libggml-cuda.so
load_backend: loaded CPU backend from /usr/local/lib/ollama/libggml-cpu-skylakex.so
time=2025-06-26T23:06:12.934Z level=INFO source=ggml.go:104 msg=system CPU.0.SSE3=1 CPU.0.SSSE3=1 CPU.0.AVX=1 CPU.0.AVX2=1 CPU.0.F16C=1 CPU.0.FMA=1 CPU.0.BMI2=1 CPU.0.AVX512=1 CPU.0.LLAMAFILE=1 CPU.1.LLAMAFILE=1 CUDA.0.ARCHS=500,600,610,700,750,800,860,870,890,900,1200 CUDA.0.USE_GRAPHS=1 CUDA.0.PEER_MAX_BATCH_SIZE=128 compiler=cgo(gcc)
time=2025-06-26T23:06:12.941Z level=INFO source=runner.go:874 msg="Server listening on 127.0.0.1:39691"
llama_model_load_from_file_impl: using device CUDA0 (Tesla T4) - 14992 MiB free
time=2025-06-26T23:06:13.067Z level=INFO source=server.go:632 msg="waiting for server to become available" status="llm server loading model"
llama_model_loader: loaded meta data with 22 key-value pairs and 291 tensors from /root/.ollama/models/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = Meta-Llama-3-8B-Instruct
llama_model_loader: - kv   2:                          llama.block_count u32              = 32
llama_model_loader: - kv   3:                       llama.context_length u32              = 8192
llama_model_loader: - kv   4:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   7:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:                       llama.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 2
llama_model_loader: - kv  11:                           llama.vocab_size u32              = 128256
llama_model_loader: - kv  12:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  13:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  14:                         tokenizer.ggml.pre str              = llama-bpe
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  17:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 128000
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 128009
llama_model_loader: - kv  20:                    tokenizer.chat_template str              = {% set loop_messages = messages %}{% ...
llama_model_loader: - kv  21:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_0:  225 tensors
llama_model_loader: - type q6_K:    1 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q4_0
print_info: file size   = 4.33 GiB (4.64 BPW)
load: special tokens cache size = 256
load: token to piece cache size = 0.8000 MB
print_info: arch             = llama
print_info: vocab_only       = 0
print_info: n_ctx_train      = 8192
print_info: n_embd           = 4096
print_info: n_layer          = 32
print_info: n_head           = 32
print_info: n_head_kv        = 8
print_info: n_rot            = 128
print_info: n_swa            = 0
print_info: n_swa_pattern    = 1
print_info: n_embd_head_k    = 128
print_info: n_embd_head_v    = 128
print_info: n_gqa            = 4
print_info: n_embd_k_gqa     = 1024
print_info: n_embd_v_gqa     = 1024
print_info: f_norm_eps       = 0.0e+00
print_info: f_norm_rms_eps   = 1.0e-05
print_info: f_clamp_kqv      = 0.0e+00
print_info: f_max_alibi_bias = 0.0e+00
print_info: f_logit_scale    = 0.0e+00
print_info: f_attn_scale     = 0.0e+00
print_info: n_ff             = 14336
print_info: n_expert         = 0
print_info: n_expert_used    = 0
print_info: causal attn      = 1
print_info: pooling type     = 0
print_info: rope type        = 0
print_info: rope scaling     = linear
print_info: freq_base_train  = 500000.0
print_info: freq_scale_train = 1
print_info: n_ctx_orig_yarn  = 8192
print_info: rope_finetuned   = unknown
print_info: ssm_d_conv       = 0
print_info: ssm_d_inner      = 0
print_info: ssm_d_state      = 0
print_info: ssm_dt_rank      = 0
print_info: ssm_dt_b_c_rms   = 0
print_info: model type       = 8B
print_info: model params     = 8.03 B
print_info: general.name     = Meta-Llama-3-8B-Instruct
print_info: vocab type       = BPE
print_info: n_vocab          = 128256
print_info: n_merges         = 280147
print_info: BOS token        = 128000 '<|begin_of_text|>'
print_info: EOS token        = 128009 '<|eot_id|>'
print_info: EOT token        = 128009 '<|eot_id|>'
print_info: LF token         = 198 'Ċ'
print_info: EOG token        = 128009 '<|eot_id|>'
print_info: max token length = 256
load_tensors: loading model tensors, this can take a while... (mmap = true)
load_tensors: offloading 32 repeating layers to GPU
load_tensors: offloading output layer to GPU
load_tensors: offloaded 33/33 layers to GPU
load_tensors:        CUDA0 model buffer size =  4155.99 MiB
load_tensors:   CPU_Mapped model buffer size =   281.81 MiB
llama_context: constructing llama_context
llama_context: n_seq_max     = 2
llama_context: n_ctx         = 8192
llama_context: n_ctx_per_seq = 4096
llama_context: n_batch       = 1024
llama_context: n_ubatch      = 512
llama_context: causal_attn   = 1
llama_context: flash_attn    = 0
llama_context: freq_base     = 500000.0
llama_context: freq_scale    = 1
llama_context: n_ctx_per_seq (4096) < n_ctx_train (8192) -- the full capacity of the model will not be utilized
llama_context:  CUDA_Host  output buffer size =     1.01 MiB
llama_kv_cache_unified: kv_size = 8192, type_k = 'f16', type_v = 'f16', n_layer = 32, can_shift = 1, padding = 32
llama_kv_cache_unified:      CUDA0 KV buffer size =  1024.00 MiB
llama_kv_cache_unified: KV self size  = 1024.00 MiB, K (f16):  512.00 MiB, V (f16):  512.00 MiB
llama_context:      CUDA0 compute buffer size =   560.00 MiB
llama_context:  CUDA_Host compute buffer size =    24.01 MiB
llama_context: graph nodes  = 1094
llama_context: graph splits = 2
time=2025-06-26T23:06:15.327Z level=INFO source=server.go:637 msg="llama runner started in 2.51 seconds"

[GIN] 2025/06/26 - 23:06:19 | 200 |   7.75566245s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:06:21 | 200 |  1.473110369s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:06:25 | 200 |  3.982337403s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:06:29 | 200 |  3.950831402s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:06:31 | 200 |  2.233463799s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:06:33 | 200 |  1.867457298s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:06:35 | 200 |  1.876543014s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:06:40 | 200 |  5.294741597s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:06:42 | 200 |   1.80001571s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:06:44 | 200 |  2.079006043s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:06:46 | 200 |  2.023770056s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:06:48 | 200 |  2.039767903s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:06:51 | 200 |  2.921978754s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:06:55 | 200 |  4.206898856s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:06:57 | 200 |  2.497988512s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:00 | 200 |  2.264017371s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:02 | 200 |  2.359792931s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:06 | 200 |  3.875342817s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:09 | 200 |  3.350549224s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:12 | 200 |  2.892775623s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:15 | 200 |  2.750607701s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:17 | 200 |  2.420013393s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:20 | 200 |  2.494891569s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:22 | 200 |  2.171547479s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:24 | 200 |  2.381305478s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:27 | 200 |   2.99850217s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:30 | 200 |  2.354570914s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:37 | 200 |  7.454512571s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:50 | 200 | 12.625787933s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:52 | 200 |  2.145208057s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:55 | 200 |  2.669325259s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:07:57 | 200 |  2.780929289s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:08:00 | 200 |  2.869613294s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:08:05 | 200 |  4.340588003s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:08:12 | 200 |  7.416072051s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:08:14 | 200 |  2.437374344s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:08:17 | 200 |  2.750347443s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:08:19 | 200 |   1.56887975s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:08:21 | 200 |  2.094873868s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:08:24 | 200 |  2.704176491s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:08:50 | 200 | 26.038412665s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:08:52 | 200 |  2.239804341s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:09:08 | 200 | 16.101466422s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:09:11 | 200 |  3.096627904s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:09:14 | 200 |  2.662783172s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:09:17 | 200 |  3.416214546s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:09:20 | 200 |  2.753609238s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:09:23 | 200 |  3.400161098s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:09:26 | 200 |  3.043050547s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:09:29 | 200 |  2.304935584s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:09:31 | 200 |  2.383847914s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:09:40 | 200 |  9.239478959s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:09:43 | 200 |  2.780423827s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:09:46 | 200 |  2.840210405s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:09:49 | 200 |  3.019607989s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:09:51 | 200 |   2.12501564s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:09:53 | 200 |  2.250961736s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:09:56 | 200 |  2.152787073s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:10:01 | 200 |  5.021481391s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:10:04 | 200 |  3.547712704s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:10:08 | 200 |  3.985280686s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:10:10 | 200 |  1.832934986s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:10:13 | 200 |  2.854646092s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:10:16 | 200 |  3.473334302s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:10:18 | 200 |  1.958720118s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:10:20 | 200 |    1.9012481s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:10:23 | 200 |  2.832090308s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:10:34 | 200 | 11.090853241s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:10:37 | 200 |  2.655429131s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:10:46 | 200 |  8.990478955s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:10:59 | 200 | 13.218621665s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:00 | 200 |  1.016533356s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:02 | 200 |  2.416921193s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:04 | 200 |  2.018536266s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:06 | 200 |   1.45208164s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:23 | 200 | 17.052650647s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:25 | 200 |  2.291502585s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:27 | 200 |  2.234042791s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:29 | 200 |  1.343968589s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:34 | 200 |  5.364621297s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:36 | 200 |  2.349233207s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:39 | 200 |  2.102182328s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:41 | 200 |  2.699318481s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:44 | 200 |  2.621501701s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:47 | 200 |  2.707926548s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:49 | 200 |  2.421551989s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:51 | 200 |  1.959556552s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:54 | 200 |  3.092698626s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:11:57 | 200 |  3.348387053s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:12:00 | 200 |  2.119380194s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:12:12 | 200 | 12.407658028s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:12:14 | 200 |   2.44688282s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:12:18 | 200 |  3.853043721s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:12:23 | 200 |  4.235145491s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:12:26 | 200 |  3.980261784s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:12:32 | 200 |  5.216087502s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:12:34 | 200 |  2.596822419s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:12:36 | 200 |  2.154795478s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:12:39 | 200 |    2.0634658s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:12:48 | 200 |  9.544841742s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:12:50 | 200 |  2.020120365s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:12:59 | 200 |  8.626031319s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:13:01 | 200 |  1.980256951s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:13:04 | 200 |   3.07827333s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:13:06 | 200 |   2.03170815s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:13:09 | 200 |  3.111347158s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:13:17 | 200 |  8.350852713s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:13:20 | 200 |  2.272277246s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:13:24 | 200 |  4.834267741s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:13:26 | 200 |  1.661726046s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:13:28 | 200 |  2.023379398s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:13:31 | 200 |  2.728851943s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:13:33 | 200 |  2.511784971s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:13:37 | 200 |  3.393548568s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:13:53 | 200 | 16.559276917s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:13:56 | 200 |   2.99455522s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:13:59 | 200 |  2.667947048s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:14:03 | 200 |  3.662922034s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:14:14 | 200 | 11.294420178s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:14:17 | 200 |  3.368724941s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:14:20 | 200 |  2.496550774s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:14:32 | 200 | 11.907998355s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:14:34 | 200 |  2.446554781s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:14:42 | 200 |  8.346918948s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:14:45 | 200 |  2.759507651s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:14:48 | 200 |  2.330387942s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:14:50 | 200 |  2.825773486s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:14:53 | 200 |  2.276991793s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:14:55 | 200 |  2.132865766s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:14:58 | 200 |  2.811460951s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:14:59 | 200 |   1.58304304s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:15:02 | 200 |  2.802020424s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:15:04 | 200 |  2.110075665s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:15:07 | 200 |  2.560122266s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:15:09 | 200 |  2.684112561s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:15:14 | 200 |  4.390050666s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:15:16 | 200 |  1.878500724s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:15:18 | 200 |  2.009731271s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:15:23 | 200 |  5.125225851s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:15:33 | 200 | 10.189310957s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:15:35 | 200 |  2.058915974s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:15:38 | 200 |  2.691271438s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:15:46 | 200 |  7.909223285s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:15:53 | 200 |  7.181117538s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:01 | 200 |  8.408507414s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:03 | 200 |  2.202406617s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:06 | 200 |  2.488080525s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:08 | 200 |  2.144386557s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:11 | 200 |  3.157696058s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:13 | 200 |  1.960662277s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:28 | 200 | 14.312081491s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:31 | 200 |  2.990221531s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:32 | 200 |  1.847934771s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:35 | 200 |  3.020256279s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:39 | 200 |  3.644778676s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:41 | 200 |  1.855863416s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:44 | 200 |  2.628040253s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:47 | 200 |  3.273553718s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:49 | 200 |  1.905373335s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:51 | 200 |  2.460616722s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:54 | 200 |  2.540340079s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:56 | 200 |   2.13199626s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:16:58 | 200 |  2.181867661s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:01 | 200 |  2.698048401s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:03 | 200 |  2.445592893s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:05 | 200 |  2.245036657s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:10 | 200 |  4.272722872s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:12 | 200 |  1.949989594s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:13 | 200 |  1.441248985s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:15 | 200 |  1.990506625s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:18 | 200 |  2.931123414s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:19 | 200 |  1.449731216s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:22 | 200 |  2.569012428s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:24 | 200 |  2.364299867s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:27 | 200 |  2.319072141s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:29 | 200 |  2.395536967s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:33 | 200 |  3.514842827s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:36 | 200 |  2.940206349s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:38 | 200 |  2.202079046s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:41 | 200 |  3.382918987s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:44 | 200 |  2.465031499s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:47 | 200 |  2.876904539s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:17:53 | 200 |  6.896055651s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:18:24 | 200 | 30.641601869s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:18:30 | 200 |  6.112224197s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:18:43 | 200 | 12.521393633s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:18:55 | 200 | 12.281149014s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:18:58 | 200 |  3.436826769s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:19:01 | 200 |  2.469212886s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:19:05 | 200 |  4.404591155s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:19:08 | 200 |  2.851543993s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:19:11 | 200 |  3.217499099s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:19:15 | 200 |  3.253904195s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:19:18 | 200 |  3.730478511s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:19:20 | 200 |  1.352935477s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:19:22 | 200 |  2.236713423s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:19:25 | 200 |  2.635444397s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:19:28 | 200 |  3.196359892s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:19:32 | 200 |  4.466609152s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:19:35 | 200 |  2.972496835s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:19:37 | 200 |  2.174854446s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:19:40 | 200 |  2.707019261s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:19:43 | 200 |   2.75956866s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:20:04 | 200 | 21.559703276s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:20:12 | 200 |  7.845036444s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:20:16 | 200 |  3.348060559s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:20:19 | 200 |  3.405575615s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:20:27 | 200 |  8.077858382s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:20:29 | 200 |  1.466227513s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:20:32 | 200 |  3.724446402s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:20:35 | 200 |  2.705044039s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:20:38 | 200 |  2.894973975s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:20:41 | 200 |  2.799803396s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:20:43 | 200 |  2.286434644s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:20:46 | 200 |  2.849160996s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:20:48 | 200 |  2.571433827s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:20:51 | 200 |  2.201290943s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:20:54 | 200 |  3.220988592s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2025/06/26 - 23:20:56 | 200 |  1.934457175s |       127.0.0.1 | POST     "/api/chat"

In [8]:
# Output
for category_id, terms in all_results.items():
    print(f"Category {category_id}:")
    print(terms)

Category 1:
["'forced", 'coerced', 'extracted', 'under duress', 'against will', 'compelled', 'pressured', 'intimidated', 'threatened', "blackmailed'}"]
Category 2:
["'petition'", "'writ'", "'in custody'", "'unlawful detention'", "'judicial remedy'", "'protective writ'", "'right to counsel'", "'due process violation'}"]
Category 4:
["'repeal", 'revocation', 'annulment', 'retroactive application', 'effective date', 'prospective', 'retrospective', 'applicability', 'scope', 'constitutionality', 'statutory construction', 'legislative intent', 'prior law', 'amendment', "revision'}"]
Category 5:
["'warrantless", 'probable cause', 'reasonable suspicion', 'exigent circumstances', 'knock-and-announce', 'consent search', 'search incident to arrest', 'scope of search', 'protective sweep', "inventory search'}"]
Category 6:
["['police'", "'officer'", "'vehicle stop'", "'traffic violation'", "'probable cause'", "'warrantless search'", "'reasonably suspicion'", "'motor vehicle'", "'highway patrol'", "'roadside stop'", "'driver's license']}"]
Category 7:
["'warrantless", 'probable cause', 'Fourth Amendment', 'reasonable suspicion', 'exigent circumstances', 'knock and announce', 'search incident to arrest', 'scope of the search', "protect or serve'", "'exigent circumstances justify", 'without a warrant', 'officer safety', "fleeing felon rule'}"]
Category 8:
['disobey', 'disrespect', 'disregard', 'defiance', 'insubordination', 'contemptuous', 'scornful', 'flout', 'trifle with', 'disregardful', 'phrase1', 'phrase2']
Category 9:
["'confession", 'incriminating statement', 'own testimony', 'self-admission', 'contradictory statements', 'own evidence', 'damaging admission', 'harmful disclosure', 'voluntary statement', 'voluntary confession', 'own words', 'own admissions', "own declarations'}"]
Category 10:
["'right'", "'to remain'", "'silent'", "'anything'", "'you'", "'say'", "'may'", "'be'", "'used'", "'against'", "'you'", "'in'", "'a'", "'court'", "'of'", "'law'}"]
Category 11:
["'accused'", "'not guilty'", "'plea'", "'protection against self-incrimination'", "'privilege against self-incrimination'", "'right to remain silent'", "'fifth amendment rights'", "'exclusionary rule'", "'Miranda warning'}"]
Category 12:
["'counsel'", "'indigent'", "'appointment'", "'representation'", "'inadequate'", "'representation'", "'court'", "'hearing'", "'proceedings'", "'litigation'", "'judgment'", "'trial'", "'arraignment'", "'defense'", "'plea'", "'sentencing'}"]
Category 13:
["'petitioner", 'habeas corpus', 'capital', 'punishment', 'appeal', 'conviction', 'sentence', 'trial', 'lethal injection', "execution'}"]
Category 14:
["'punishment", 'prison', 'inmate', 'sentence', 'judge', 'law', 'constitutional', 'liberty', 'due process', 'equal protection', 'cruel', 'unusual', 'harsh', 'excessive', 'arbitrary', 'discriminatory', 'disproportionate', 'unjust', 'inhumane', 'barbaric', 'penal code', 'criminal procedure', "Fourth Amendment'}"]
Category 15:
["['police officer'", "'witnesses'", "'identical'", "'height'", "'build'", "'facial features'", "'recognition'", "'surveillance'", "'investigation'", "'criminal justice']}"]
Category 16:
["'search warrant", 'surveillance footage', 'law enforcement investigation', 'evidence collection', 'crime scene analysis', 'witness testimony', 'court order', 'subpoena', 'document review', 'records request', 'information gathering', 'legal procedure', 'case study', 'trial preparation', 'legal discovery', 'inspection report', "due diligence'}"]
Category 17:
["'tried'", "'indicted'", "'charged'", "'convicted'", "'punished'", "'prosecuted'", "'due process'", "'twice accused'", "'once punished'}"]
Category 18:
["['judgment'", "'after'", "'fact'", "'retroactive'", "'imposed'", "'posteriorly'", "'subsequent'", "'following'", "'consequential'", "'inconsistent']"]
Category 27:
['']
Category 37:
["'indictment", 'charges', 'defendant', 'jurisdiction', 'subpoena', 'preliminary hearing', 'arraignment', 'bail', 'trial', 'verdict', 'conviction', 'appeal', 'judicial review', 'habeas corpus', 'writ', "petition'}"]
Category 58:
["'independent'", "'impartial'", "'neutral'", "'biased'", "'prejudiced'", "'unaffected'", "'untainted'", "'jury nullification'", "'judgment of law'", "'fact-finding'}"]
Category 59:
["['prompt'", "'expeditious'", "'hasty'", "'summary judgment'", "'quickly decided'", "'fast tracked'", "'rapid adjudication'", "'swift justice'", "'accelerated process'", "'brief hearing'", "' expedited hearing']}"]
Category 61:
["['ballot'", "'candidate'", "'election'", "'polls'", "'vote'", "'registered'", "'balloting'", "'electorate'", "'primary'", "'referendum'", "'cast your ballot'", "'exercise your right to vote'", "'make your voice heard']}"]
Category 62:
["['act'", "'rights'", "'amendments'", "'voting'", "'reform'", "'civil'", "'liberty'", "'equality'", "'justice'", "'fairness'", '"it\'s time to get in line"', '"don\'t be silenced"]}']
Category 63:
["'petition", 'candidate', 'election', 'voting rights', 'political party', 'nomination', 'primary', 'referendum', 'initiative', 'campaign', 'democracy', 'representative', "elector'}"]
Category 64:
['']
Category 65:
["['separate'", "'integration'", "'busing'", "'school zones'", "'racial imbalance'", "'equal access'", "'students of color'", "'federal mandate'", "'court orders'", "'Brown v Board'", "'civil rights act'", "'Jim Crow laws']}"]
Category 67:
["'diversity", 'equal opportunity', 'non-discriminatory', 'anti-bias training', 'inclusionary policies', 'equity initiatives', 'workplace accommodations', 'hiring practices', 'employee development programs', "cultural sensitivity'}"]
Category 68:
["'enslavement'", "'forced labor'", "'human trafficking'", "'unfree labor'", "'bondage'", "'captivity'", "'slave trade'", "'indentured servitude'", "'servile status'", "'oppression'", "'reduction to bondage'", "'kidnapping for ransom'", "'trafficking in persons'}"]
Category 69:
['']
Category 71:
["'lawsuit", 'creditor', 'bankruptcy', 'debt', 'payment', 'claim', 'lawsuit', 'judgment', 'collection', "creditor rights'}"]
Category 72:
["'forced removal'", "'exile'", "'expulsion'", "'emigration'", "'repatriation'", "'extradition'", "'law enforcement agency'", "'Border Control'", "'immigration detention center'", "'asylum seeker'", "'refugee status'}"]
Category 73:
['extraterrestrial workers', 'intergalactic migrants', 'cosmic job seekers', 'out-of-this-world employees', 'universal workforce', 'planetary labor market', 'celestial employment opportunities', 'space-related careers', 'alien work permits', 'immigration reform for ETs']
Category 74:
["'patriarchal society", 'gender bias', 'discriminatory practices', 'unequal treatment', 'sexual harassment', 'unequal pay', 'workplace inequality', 'gender-based violence', 'stereotyping', "prejudice'}"]
Category 75:
["['discrimination'", "'employment'", "'gender'", "'bias'", "'unfair treatment'", "'prejudice'", "'inequality'", "'diversity'", "'inclusion'", "'comparable work'", "'equal pay'", "'Title VII'", "'Equal Pay Act']}"]
Category 76:
["['federal'", "'tribal'", "'reservation'", "'sovereign'", "'land'", "'water'", "'mineral'", "'resource'", "'management'", "'authority'", "'trust'", "'government'", "'rights'", "'powers'", "'jurisdiction'", "'laws'", "'regulations']}"]
Category 77:
["'tribal'", "'Indian country'", "'state authority'", "'sovereign immunity'", "'Tribal court'", "'federal-state relations'", "'jurisdictional dispute'", "'Native American rights'", "'Sovereign nation'", "'Federal Indian Law'", "'plenary power'", "'Indian Commerce Clause'}"]
Category 78:
["'arrested", 'detained', 'imprisoned', 'minor', 'criminal law', 'delinquent', 'neglected', 'abandoned', 'welfare', "child protective services'}"]
Category 79:
['impoverished', 'destitute', 'underprivileged', 'socio-economic', 'economic inequality', 'right to a decent standard of living', 'fundamental human rights', 'vulnerable population', 'poverty alleviation program', 'access to basic necessities ...']
Category 104:
['advertisement', 'promotional', 'marketing', 'sale', 'purchase', 'business', 'corporation', 'product', 'service', 'consumer', 'customer', 'retailer', 'wholesaler', 'distributor', 'franchise', 'trademark', 'contract']
Category 109:
["'oath", 'affirmation', 'non-communist', 'communist', 'ideology', 'allegiance', 'declaration', 'commitment', 'patriotic', "patriotically'}"]
Category 115:
["['objection'", "'moral'", "'principled'", "'non-combatant'", "'pacifist'", "'exemption'", "' conscientious exemption'", "'alternative service'", "'community service'", "'war resistance'", "'draft evasion'", "'military conscription'", "'refusal of duty']}"]
Category 116:
["'", "'donation'", "'reform'", "'election'", "'contribution'", "'candidate'", "'lobbying'", "'politician'", "'financial disclosure'", "'public official'", "'corporate funding'", "'527 committee'", "'dark money'", "'money in politics'", "'vote buying'", "'gerrymandering'", "'pacs'", "'superpac'", "'individual donor'}"]
Category 118:
["'congregation'", "'right to worship'", "'church and state separation'", "' religious liberty'", "'freedom of conscience'", "'worship services'", "'ministerial exception'", "'sabbath observance'", "'censorship of religious speech'", "'parish boundaries'", "'ecclesiastical law'}"]
Category 119:
[")': ['sect'", "'denomination'", "'congregation'", "'faith'", "'worship'", "'ritual'", "'practice'", "'doctrines'", "'dogma'", "'credos'", "'divine right'", "'ecclesiastical jurisdiction'", "'spiritual authority'", "'sacred institutions'", "'church-state relations']}"]
Category 122:
["'curse'", "'foul language'", "'vulgar'", "'profanity'", "'indecent'", "'lewd'", "'off-color'", "'coarse'", "'unprintable'", "'uncouth'", "'unseemly'", "'expletive deleted'", '"don\'t swear"', '"use foul language"', '"unacceptable language"}']
Category 132:
["['death'", "'assisted suicide'", "'end of life'", "'hospice care'", "'physician assisted death'", "'terminally ill'", "'quality of life'", "'medical ethics'", "'euthanasia'", "'dying with dignity'", "'life support'", "'palliative care']}"]
Category 133:
["['request'", "'records'", "'publicly'", "'available'", "'exempt'", "'classifications'", "'agency'", "'information'", "'act'", "'statute'", "'regulation'", "'disclose'", "'privileged'", "'harmful'", "'national security'", "'classified']}"]
Category 134:
["['fees'", "'compensation'", "'licenses'", "'charges'", "'expenses'", "'remuneration'", "'salary'", "'wages'", "'reimbursement'", "'allowance'", "'court costs'", "'judicial expenses'", "'fines'", "'penalties'", "'claims'", "'demands'", "'requests for payment']}"]
Category 135:
["'speech'", "'rights'", "'free'", "'expression'", "'protected'", "'advertising'", "'endorsement'", "'spokesperson'", "' advertisement'", "'marketing'}"]
Category 137:
["'petition", 'motion', 'request', 'application', 'lawyer', 'attorney', 'court', 'justice', 'supreme', 'judge', 'certification', 'discipline', 'ethics', 'rules', 'regulations', 'bar association', 'admission requirements', "disbarment proceedings'"]
Category 138:
["['labor'", "'management'", "'employer'", "'employee'", "'relation'", "'dispute'", "'resolution'", "'negotiation'", "'agreement'", "'conflict'", "'mediation'", "'settlement'", "'contract'", "'collective bargaining']}"]
Category 141:
['employment', 'wages', 'hours', 'labor', 'law', 'regulation', 'compliance', 'overtime', 'benefits', 'workplace', '']
Category 142:
["'worker'", "'injury'", "'illness'", "'safety'", "'hazard'", "'OSHA'", "'regulation'", "'compliance'", "'recordkeeping'", "'inspector'", "'citation'", "'penalty'", "'standard'}"]
Category 143:
["['dispute'", "'member'", "'unionized'", "'labor'", "'collective bargaining'", "'grievance'", "'arbitration'", "'negotiation'", "'contractual obligation'", "'workplace issue'", "'industrial relations'", "'labour dispute'", "'worker representation']}"]
Category 158:
["['conjunction'", "'unrelated'", "'separate'", "'disjointed'", "'scattered'", "'random'", "'unconnected'", "'diverse'", "'heterogeneous'", "'mixed'", "'eclectic'", "'varied'", "'distinct'", "'different']}"]
Category 159:
["'monopoly", 'competition', 'market', 'regulation', 'prohibition', 'restraint', 'unfair', 'deceptive', 'predatory', 'price-fixing', 'conspiracy theory', 'Sherman Act', 'Clayton Act', "Federal Trade Commission'}"]
Category 160:
["['acquisition'", "'consolidation'", "'takeover'", "'buyout'", "'mergitation'", "'amalgamation'", "'absorption'", "'combination'", "'founding'", "'merging']}"]
Category 161:
['creditor', 'debt', 'financial', 'insolvency', 'liquidation', 'moratorium', 'restructuring', 'trustee', 'chapter7', 'chapter11', 'voluntary', 'involuntary', 'insolvent', 'filing', 'petition', 'discharge', 'reorganization']
Category 165:
['']
Category 166:
["'award'", "'compensatory'", "'actual'", "'reimbursement'", "'remedy'", "'vindication'", "'accountability'", "'penalty'", "'reprisal'", "'deterrent'}"]
Category 167:
["'benefit", 'pension', 'plan', 'fund', 'security', 'income', 'retiree', 'retirement', '401k', "ERISA'}"]
Category 168:
["'property tax", 'local income tax', 'sales tax', 'county tax', 'city tax', 'municipal tax', 'state income tax', 'excise tax', 'assessment', 'real estate tax', "town tax'}"]
Category 169:
["['aboriginal'", "'native'", "'indigenous'", "'landrights'", "'sovereignty'", "'treaty'", "'reservation'", "'tribal'", "'claimant'", "'selfgoverning'", "'federaljurisdiction'", "'jurisdictionaldispute']}"]
Category 170:
['']
Category 171:
["'SEC", 'Securities Exchange Act', 'Federal Register', 'registered offering', 'prospectus', 'disclosure statement', 'regulatory body', 'compliance requirements', 'filing fees', 'registration statement', "publicly traded company'}"]
Category 173:
['bribery', 'embezzlement', 'fraud', 'corruption', 'scandal', 'abuse', 'mismanagement', 'nepotism', 'favoritism', 'cronyism', 'government official', 'public servant', 'political appointee', 'regulatory capture', 'lack of transparency']
Category 175:
["'award'", "'binding'", "'complaint'", "'dispute resolution'", "'final decision'", "'hearing'", "'jurisdiction'", "'mediation'", "'non-binding'", "'panel'", "'process'", "'resolution'", "'review'", "'settlement'}"]
Category 194:
["'antitrust", 'competition policy', 'regulatory framework', 'market structure', 'price control', 'industry standards', 'consumer protection', 'trade liberalization', 'deregulation', 'free market', "government intervention'}"]
Category 203:
["['removal'", "'comity'", "'primarily'", "'cases'", "'civil'", "'procedure'", "'deference'", "'foreign'", "'judicial'", "'tribunals'", "'First'", "'Amendment'", "'cf'", "'criminal'", "'removal'", "'judicial'", "'courts']}"]
Category 205:
["['rule'", "'proceedure'", "'supreme'", "'evidence'", "'appellate'", "'litigation'", "'circuit'", "'state'", "'admiralty'", "'federal'", "'civil'", "'court'", "'procedure'", "'process'", "'hearing'", "'jurisdiction']}"]
Category 206:
["['administrative'", "'agency'", "'actions'", "'procedures'", "'judicial'", "'review'", "'official'", "'regulatory'", "'compliance'", "'enforcement'", "'statute'", "'constitution'", "'mandate'", "'scope'", "'jurisdiction'", "'standards'", "'requirements'", "'process'", "'petition'", "'appeal'", "'remedy'", "'relief']}"]
Category 208:
["['theater'", "'arena'", "'stadium'", "'concert hall'", "'auditorium'", "'exhibition center'", "'meeting space'", "'event space'", "'ballroom'", "'banquet hall']}"]
Category 245:
["'judicial review", 'high court', 'appeal process', 'appellate jurisdiction', 'certiorari petition', 'writ of mandamus', 'Supreme Court justices', 'appeals procedure', 'highest court', "judicial appeal'", "'appeal from the order", 'notice of appeal', 'appellants claims', 'respondents answer', 'appeal briefs', 'motions in aid', 'trial court record', 'evidence presented', "lower court decision'}"]
Category 246:
["['jurisdiction'", "'diversity'", "'judicial'", "'power'", "'venue'", "'forum'", "'court'", "'right'", "'claim'", "'petitioner'", "'respondent'", "'transferred'", "'removed'", "'remanded']}"]
Category 247:
["'submerge", 'land', 'territorial', 'boundary', 'jurisdiction', 'dispute', 'claim', 'right', 'sovereign', "authority'}"]
Category 248:
["['preemption'", "'state jurisdiction'", "'judicial review'", "'congressional intent'", "'supremacy clause'", "'exclusive jurisdiction'", "'federal law supersedes'", "'state court power limited by'", "'federal supremacy doctrine'", "'intergovernmental immunity'", "'sovereign immunity'", "'state sovereign immunity'", "'judges bound by federal law'", "'preemptive strike against state claims']}"]
Category 249:
["['pre-emption'", "'state'", "'legislation'", "'regulation'", "'business'", "'rarely'", "'involves'", "'union'", "'activity'", "'constitutional'", "'interpretation'", "'Court'", "'says'", "'it'", "'does'", "'federal'", "'cf'", "'state']"]
Category 250:
["'ownership", 'land', 'submerged', 'act', 'federal', 'state', 'property', 'boundary', 'sea', 'ocean', 'continental', 'shelf', 'jurisdiction', 'dispute', 'treaty', 'agreement', 'negotiation', 'claim', 'lawsuit', "litigation'}"]
Category 259:
["['state'", "'authority'", "'powers'", "'jurisdiction'", "'conflict'", "'compromise'", "'cooperation'", "'agreement'", "'federalism'", "'divided sovereignty'", "'dual authority'", "'intergovernmental relations'", "'subnational government']}"]
Category 260:
["['state'", "'border'", "'dispute'", "'conflict'", "'neighboring'", "'jurisdiction'", "'territory'", "'landmark'", "'international'", "'agreement'", "'negotiation'", "'mediation'", "'resolution']}"]
Category 261:
['']
Category 262:
["['dispute'", "'diplomacy'", "'negotiations'", "'treaty'", "'agreement'", "'conflict resolution'", "'mediation'", "'sanctions'", "'embargo'", "'international incident'", "'border disagreement'", "'trade war'", "'diplomatic crisis']}"]
Category 263:
["'annexation", 'acquisition', 'colonisation', 'colonialism', 'imperialism', 'territorial expansion', 'expansionist policy', 'annexed land', 'incorporated territory', "absorbed jurisdiction'}"]
Category 264:
["'taxation", 'revenue', 'code', 'federal', 'internal', 'provision', 'agency', 'authority', 'compliance', "filing'}"]
Category 265:
['']
Category 268:
["['veto'", "'congressional'", "'lawmaking'", "'presidential power'", "'executive authority'", "'statute'", "'constitutional limits'", "'legislative action'", "'judicial review'", "'checks and balances']}"]
Category 269:
["'appoint'", "'authorize'", "'legislate'", "'congressional approval'", "'presidential power'", "'checks and balances'", "'separation of powers'", "'veto'", "'override'", "'federalism'", "'state's rights'", "'concurrent power'}"]
Category 270:
["['hobby'", "'interest'", "'activity'", "'pursuit'", "'venture'", "'project'", "'endeavor'", "'mission'", "'objective'", "'goal'", "'target'", '"that\'s a first"', '"it\'s all about"', "'whatever floats your boat']}"]
Category 271:
['deed', 'conveyance', 'estate', 'ownership', 'land', 'parcel', 'property', 'title', 'survey', 'lot', 'piece of land', 'plot of ground', 'realty', 'real estate', 'ownership interest', 'freehold', 'leasehold', 'fee simple', 'easement', 'right of way', 'tenancy in common', 'condominium']
Category 272:
['asset', 'belongings', 'estate', 'property', 'possessions', 'heirloom', 'inheritance', 'valuation', 'appraisal', 'ownership', 'rights', 'interests', 'titles', 'deeds', 'conveyance', 'transfer', 'liquidation', 'bankruptcy']
Category 273:
["['agreement'", "'terms'", "'conditions'", "'negotiate'", "'binding'", "'obligations'", "'commitment'", "'pact'", "'understanding'", "'arrangement'", "'written'", "'verbal'", "'document'", "'agreed'", "'contractual'", "'provisions']}"]
Category 274:
["['confidential'", "'document'", "'sensitive'", "'protected'", "'privileged'", "'sealed'", "'locked'", "'secure'", "'classified'", "'secret'", "'top-secret'", "'need-to-know'", "'must-hold'", "'high-level'", "'national-security'", "'government-issued']}"]
Category 275:

In [9]:
# records = list(sc.records())
# df = pd.DataFrame(records)

# # Inspect
# print(df.head())

In [10]:
import torch
from sentence_transformers import SentenceTransformer
import chromadb
import re
import gc
import pandas as pd
from tqdm import tqdm

def clean_text(text):
    if not isinstance(text, str):
        text = str(text)
    return re.sub(r'[^a-zA-Z0-9 ]', '', text).strip().lower()

def classify_case_rag(case_text, classification_dict, chroma_client, collection_name="temp_case_classification", model=None):
    """
    Dynamically classify a case using RAG by querying relevant legal topics.
    """
    device = "cuda" if torch.cuda.is_available() else "cpu"

    # Initialize model if not passed in
    if model is None:
        model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2").to(device)
        if torch.cuda.device_count() > 1:
            print(f"Using {torch.cuda.device_count()} GPUs.")
            model = torch.nn.DataParallel(model)

    # Encode helper
    def encode_text(text):
        if isinstance(text, list):
            encoded = model.module.encode(text, convert_to_tensor=True) if torch.cuda.device_count() > 1 else model.encode(text, convert_to_tensor=True)
        else:
            encoded = model.module.encode([text], convert_to_tensor=True)[0] if torch.cuda.device_count() > 1 else model.encode([text], convert_to_tensor=True)[0]
        return encoded.to(device)

    # Check and build ChromaDB collection if needed
    if collection_name not in [c.name for c in chroma_client.list_collections()]:
        collection = chroma_client.create_collection(name=collection_name)
        print("Creating new ChromaDB collection and populating...")

        for class_name, keywords in classification_dict.items():
            unique_ids = [f"{class_name}_{clean_text(k)}" for k in keywords]
            batch_embeddings = encode_text(keywords)
            collection.add(
                embeddings=[emb.cpu().tolist() for emb in batch_embeddings],
                metadatas=[{"class_name": class_name}] * len(keywords),
                ids=unique_ids
            )
    else:
        collection = chroma_client.get_collection(name=collection_name)

    # Embed case text
    case_embedding = encode_text(case_text)

    # Query top N relevant keywords
    results = collection.query(query_embeddings=[case_embedding.cpu().tolist()], n_results=3)
    retrieved_classes = [m["class_name"] for m in results["metadatas"][0]] if results["metadatas"] else []

    if not retrieved_classes:
        return "None"

    retrieved_text = "\n".join(set(retrieved_classes))

    # Prompt for LLaMA classification
    prompt = f"""
    You are an AI assistant trained in Supreme Court case classification. Given the following retrieved categories,
    classify the new case into the most appropriate class.

    Retrieved Relevant Categories:
    {retrieved_text}

    Please reply with the category number only.
    """

    response = ollama.chat(model='llama3', messages=[
        {"role": "system", "content": '''
            You are an expert in Supreme Court cases and legal classifications. Your task is to analyze the provided text of a Supreme Court case and classify it into one of the following predefined categories:

            Instructions:
            1. Carefully analyze the text and identify the primary category it belongs to.
            2. Provide only the category name as the response and nothing else.
            3. If uncertain, select the most relevant category based on the case's primary legal focus.
            4. Response should only be the class number.
        '''},
        {"role": "user", "content": prompt}
    ])

    category_response = response['message']['content'].strip()
    del case_embedding
    torch.cuda.empty_cache()
    return category_response


# -- Load dataset and classification keywords --
# records = list(sc.records())  # Your case records source
# cases_df = pd.DataFrame(records)

filtered_result = all_results

# -- Process and classify all cases --
def process_cases_rag(cases_df, filtered_result, output_file="classified_cases.csv", overwrite_collection=False):
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2").to(device)
    if torch.cuda.device_count() > 1:
        model = torch.nn.DataParallel(model)

    chroma_db_path = "./chroma_db"
    chroma_client = chromadb.PersistentClient(path=chroma_db_path)

    if overwrite_collection and "temp_case_classification" in [c.name for c in chroma_client.list_collections()]:
        chroma_client.delete_collection("temp_case_classification")
        print("Deleted existing collection.")

    classified_cases = []

    for idx, row in tqdm(cases_df.iterrows(), total=len(cases_df)):
        case_text = row.get("text", "")
        if not case_text.strip():
            print(f"Skipping empty case at index {idx}")
            continue

        try:
            with torch.no_grad():
                class_name = classify_case_rag(
                    case_text, 
                    classification_dict=filtered_result, 
                    chroma_client=chroma_client, 
                    model=model
                )
            classified_cases.append({
                "id": row.get("id", f"row_{idx}"),
                "predicted_class": class_name
            })
        except Exception as e:
            print(f"Error processing case {idx}: {e}")
            continue

        torch.cuda.empty_cache()
        gc.collect()

    df_out = pd.DataFrame(classified_cases)
    df_out.to_csv(output_file, index=False)
    print(f"Saved classified results to {output_file}")


# -- Run the process --
process_cases_rag(cases_df, filtered_result, output_file="classified_cases.csv", overwrite_collection=True)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

  0%|          | 0/8417 [00:00<?, ?it/s]

Creating new ChromaDB collection and populating...

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 1/8417 [00:01<3:05:01,  1.32s/it]

Error processing case 0: Expected IDs to be unique, found duplicates of: 10_you in add.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:33 | 200 |  375.053902ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 2/8417 [00:02<2:28:52,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:34 | 200 |   125.34094ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 3/8417 [00:02<1:58:44,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:34 | 200 |  101.026605ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 4/8417 [00:03<1:44:50,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:35 | 200 |  185.528077ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 5/8417 [00:04<1:40:18,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:36 | 200 |  169.682232ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 6/8417 [00:04<1:37:14,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:36 | 200 |  148.152549ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 7/8417 [00:05<1:34:20,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:37 | 200 |  136.060756ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 8/8417 [00:05<1:31:05,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:38 | 200 |  141.197197ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 9/8417 [00:06<1:29:26,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:38 | 200 |  142.841849ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 10/8417 [00:07<1:28:34,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:39 | 200 |  155.295774ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 11/8417 [00:07<1:28:10,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:39 | 200 |  138.498382ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 12/8417 [00:08<1:27:31,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:40 | 200 |  141.277578ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 13/8417 [00:09<1:27:21,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:41 | 200 |  154.582156ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 14/8417 [00:09<1:28:01,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:41 | 200 |  182.922005ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 15/8417 [00:10<1:28:46,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:42 | 200 |  151.941579ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 16/8417 [00:10<1:28:16,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:43 | 200 |  141.987755ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 17/8417 [00:11<1:29:19,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:43 | 200 |   141.94174ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 18/8417 [00:12<1:28:19,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:44 | 200 |  156.376342ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 19/8417 [00:12<1:28:01,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:44 | 200 |  146.671322ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 20/8417 [00:13<1:27:38,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:45 | 200 |  152.759776ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 21/8417 [00:14<1:27:34,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:46 | 200 |  176.836387ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 22/8417 [00:14<1:28:39,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:46 | 200 |  158.189132ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 23/8417 [00:15<1:28:34,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:47 | 200 |  148.727233ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 24/8417 [00:15<1:28:18,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:48 | 200 |  142.663494ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 25/8417 [00:16<1:27:29,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:48 | 200 |  148.261329ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 26/8417 [00:17<1:27:28,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:49 | 200 |   139.84689ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 27/8417 [00:17<1:26:53,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:49 | 200 |  138.653092ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 28/8417 [00:18<1:26:43,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:50 | 200 |  156.597138ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 29/8417 [00:19<1:27:08,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:51 | 200 |  179.935994ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 30/8417 [00:19<1:28:22,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:51 | 200 |  166.206549ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 31/8417 [00:20<1:28:38,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:52 | 200 |  148.113539ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 32/8417 [00:20<1:28:03,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:53 | 200 |  118.438368ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 33/8417 [00:21<1:27:00,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:53 | 200 |  143.317533ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 34/8417 [00:22<1:26:23,  1.62it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:54 | 200 |  141.204734ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 35/8417 [00:22<1:26:38,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:54 | 200 |  139.474937ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 36/8417 [00:23<1:26:29,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:55 | 200 |  150.925133ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 37/8417 [00:24<1:26:45,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:56 | 200 |  162.228332ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 38/8417 [00:24<1:27:19,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:56 | 200 |  182.023293ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 39/8417 [00:25<1:28:44,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:57 | 200 |  156.088745ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 40/8417 [00:25<1:28:27,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:58 | 200 |  147.750948ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 41/8417 [00:26<1:27:45,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:58 | 200 |  145.529335ms |       127.0.0.1 | POST     "/api/chat"

  0%|          | 42/8417 [00:27<1:26:51,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:59 | 200 |  144.495734ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 43/8417 [00:27<1:27:03,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:24:59 | 200 |  142.928666ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 44/8417 [00:28<1:27:33,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:00 | 200 |  152.327618ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 45/8417 [00:29<1:27:27,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:01 | 200 |   169.78217ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 46/8417 [00:29<1:28:07,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:01 | 200 |  189.230699ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 47/8417 [00:30<1:29:38,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:02 | 200 |  144.567539ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 48/8417 [00:31<1:28:12,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:03 | 200 |  138.569046ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 49/8417 [00:31<1:29:11,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:03 | 200 |  138.380358ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 50/8417 [00:32<1:29:15,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:04 | 200 |  172.605494ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 51/8417 [00:32<1:29:35,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:05 | 200 |   136.61596ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 52/8417 [00:33<1:27:53,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:05 | 200 |  165.948162ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 53/8417 [00:34<1:28:13,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:06 | 200 |   147.77843ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 54/8417 [00:34<1:28:04,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:06 | 200 |  141.742856ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 55/8417 [00:35<1:27:26,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:07 | 200 |  141.824264ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 56/8417 [00:36<1:26:36,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:08 | 200 |  143.694059ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 57/8417 [00:36<1:26:41,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:08 | 200 |  138.262067ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 58/8417 [00:37<1:26:14,  1.62it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:09 | 200 |   158.13339ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 59/8417 [00:37<1:26:28,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:10 | 200 |  173.958883ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 60/8417 [00:38<1:31:20,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:10 | 200 |  139.770128ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 61/8417 [00:39<1:30:20,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:11 | 200 |  146.763295ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 62/8417 [00:39<1:29:46,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:12 | 200 |  140.014245ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 63/8417 [00:40<1:28:41,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:12 | 200 |  168.412452ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 64/8417 [00:41<1:29:10,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:13 | 200 |  175.274513ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 65/8417 [00:41<1:29:26,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:13 | 200 |   146.30719ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 66/8417 [00:42<1:28:51,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:14 | 200 |  121.548948ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 67/8417 [00:43<1:28:56,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:15 | 200 |  143.736593ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 68/8417 [00:43<1:28:50,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:15 | 200 |  196.755764ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 69/8417 [00:44<1:30:11,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:16 | 200 |  156.101585ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 70/8417 [00:45<1:29:10,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:17 | 200 |  145.296387ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 71/8417 [00:45<1:28:13,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:17 | 200 |  141.923119ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 72/8417 [00:46<1:27:05,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:18 | 200 |  148.135716ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 73/8417 [00:46<1:27:12,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:19 | 200 |  133.345683ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 74/8417 [00:47<1:26:29,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:19 | 200 |  145.528396ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 75/8417 [00:48<1:26:27,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:20 | 200 |  113.559335ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 76/8417 [00:48<1:24:58,  1.64it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:20 | 200 |  173.869751ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 77/8417 [00:49<1:27:10,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:21 | 200 |  161.372952ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 78/8417 [00:50<1:28:21,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:22 | 200 |  158.157235ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 79/8417 [00:50<1:28:20,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:22 | 200 |  140.783211ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 80/8417 [00:51<1:27:18,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:23 | 200 |  136.185033ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 81/8417 [00:51<1:26:35,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:24 | 200 |  151.862184ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 82/8417 [00:52<1:26:34,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:24 | 200 |  141.617277ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 83/8417 [00:53<1:26:37,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:25 | 200 |  137.502541ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 84/8417 [00:53<1:26:39,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:25 | 200 |  142.111344ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 85/8417 [00:54<1:26:04,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:26 | 200 |  150.877505ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 86/8417 [00:55<1:26:32,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:27 | 200 |  180.075897ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 87/8417 [00:55<1:27:57,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:27 | 200 |  153.863961ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 88/8417 [00:56<1:28:42,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:28 | 200 |  150.778129ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 89/8417 [00:56<1:29:01,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:29 | 200 |  144.141726ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 90/8417 [00:57<1:27:49,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:29 | 200 |  138.229169ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 91/8417 [00:58<1:27:12,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:30 | 200 |  166.565512ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 92/8417 [00:58<1:28:49,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:31 | 200 |  177.335574ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 93/8417 [00:59<1:30:23,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:31 | 200 |  146.915147ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 94/8417 [01:00<1:29:10,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:32 | 200 |  140.324424ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 95/8417 [01:00<1:29:14,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:32 | 200 |  142.374589ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 96/8417 [01:01<1:27:48,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:33 | 200 |  164.601827ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 97/8417 [01:02<1:27:39,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:34 | 200 |  175.113765ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 98/8417 [01:02<1:28:43,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:34 | 200 |  148.821981ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 99/8417 [01:03<1:28:24,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:35 | 200 |  141.493163ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 100/8417 [01:03<1:27:47,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:36 | 200 |  141.337876ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 101/8417 [01:04<1:29:24,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:36 | 200 |  143.012403ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 102/8417 [01:05<1:29:05,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:37 | 200 |  171.796924ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 103/8417 [01:05<1:29:25,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:38 | 200 |  145.543013ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 104/8417 [01:06<1:28:04,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:38 | 200 |  147.627272ms |       127.0.0.1 | POST     "/api/chat"

  1%|          | 105/8417 [01:07<1:27:42,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:39 | 200 |  117.169812ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 106/8417 [01:07<1:25:58,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:39 | 200 |  147.433659ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 107/8417 [01:08<1:26:30,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:40 | 200 |  140.879234ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 108/8417 [01:09<1:26:26,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:41 | 200 |    141.7976ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 109/8417 [01:09<1:26:45,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:41 | 200 |  111.553748ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 110/8417 [01:10<1:25:02,  1.63it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:42 | 200 |  145.499492ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 111/8417 [01:10<1:25:37,  1.62it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:43 | 200 |  169.245711ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 112/8417 [01:11<1:26:39,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:43 | 200 |  176.652884ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 113/8417 [01:12<1:27:28,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:44 | 200 |  116.529532ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 114/8417 [01:12<1:26:41,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:44 | 200 |  148.875455ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 115/8417 [01:13<1:27:58,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:45 | 200 |  137.192612ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 116/8417 [01:14<1:27:53,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:46 | 200 |  136.740087ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 117/8417 [01:14<1:28:20,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:46 | 200 |  140.094017ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 118/8417 [01:15<1:27:33,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:47 | 200 |  192.235211ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 119/8417 [01:15<1:28:57,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:48 | 200 |  139.263974ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 120/8417 [01:16<1:27:19,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:48 | 200 |  145.899716ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 121/8417 [01:17<1:26:57,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:49 | 200 |  137.478554ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 122/8417 [01:17<1:26:01,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:49 | 200 |  146.416216ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 123/8417 [01:18<1:26:32,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:50 | 200 |  141.785116ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 124/8417 [01:19<1:27:02,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:51 | 200 |  172.662555ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 125/8417 [01:19<1:28:34,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:51 | 200 |  134.855021ms |       127.0.0.1 | POST     "/api/chat"

  1%|▏         | 126/8417 [01:20<1:29:15,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:52 | 200 |  174.708051ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 127/8417 [01:21<1:29:33,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:53 | 200 |  139.863605ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 128/8417 [01:21<1:28:12,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:53 | 200 |   115.80982ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 129/8417 [01:22<1:26:10,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:54 | 200 |  158.486473ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 130/8417 [01:22<1:26:43,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:55 | 200 |  176.967084ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 131/8417 [01:23<1:27:39,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:55 | 200 |  177.389612ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 132/8417 [01:24<1:28:21,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:56 | 200 |  148.144815ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 133/8417 [01:24<1:28:14,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:56 | 200 |  138.850762ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 134/8417 [01:25<1:27:14,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:57 | 200 |  144.417386ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 135/8417 [01:26<1:26:24,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:58 | 200 |  139.709194ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 136/8417 [01:26<1:25:53,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:58 | 200 |  158.070946ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 137/8417 [01:27<1:25:38,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:25:59 | 200 |  175.697708ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 138/8417 [01:27<1:27:50,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:00 | 200 |  169.642243ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 139/8417 [01:28<1:28:12,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:00 | 200 |  145.200268ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 140/8417 [01:29<1:29:01,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:01 | 200 |  142.194066ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 141/8417 [01:29<1:28:24,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:02 | 200 |  145.112412ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 142/8417 [01:30<1:27:49,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:02 | 200 |   169.57568ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 143/8417 [01:31<1:27:42,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:03 | 200 |   172.02078ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 144/8417 [01:31<1:27:59,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:03 | 200 |  147.266451ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 145/8417 [01:32<1:27:32,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:04 | 200 |   143.57402ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 146/8417 [01:33<1:26:39,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:05 | 200 |  147.945329ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 147/8417 [01:33<1:26:53,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:05 | 200 |  140.651245ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 148/8417 [01:34<1:26:09,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:06 | 200 |  136.257027ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 149/8417 [01:34<1:25:58,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:07 | 200 |  154.054498ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 150/8417 [01:35<1:25:56,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:07 | 200 |  166.293025ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 151/8417 [01:36<1:26:18,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:08 | 200 |  145.838039ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 152/8417 [01:36<1:25:58,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:08 | 200 |  176.264112ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 153/8417 [01:37<1:27:13,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:09 | 200 |  153.639639ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 154/8417 [01:38<1:27:12,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:10 | 200 |    146.4553ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 155/8417 [01:38<1:27:15,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:10 | 200 |  139.442629ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 156/8417 [01:39<1:27:41,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:11 | 200 |  118.020773ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 157/8417 [01:39<1:25:48,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:12 | 200 |  185.696409ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 158/8417 [01:40<1:27:22,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:12 | 200 |  169.164815ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 159/8417 [01:41<1:27:33,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:13 | 200 |  126.081506ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 160/8417 [01:41<1:26:07,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:13 | 200 |  143.356353ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 161/8417 [01:42<1:25:32,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:14 | 200 |  142.730156ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 162/8417 [01:43<1:25:45,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:15 | 200 |  116.418149ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 163/8417 [01:43<1:24:57,  1.62it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:15 | 200 |  137.978884ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 164/8417 [01:44<1:24:35,  1.63it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:16 | 200 |  134.970145ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 165/8417 [01:44<1:24:50,  1.62it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:17 | 200 |   142.43583ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 166/8417 [01:45<1:26:31,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:17 | 200 |  159.646883ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 167/8417 [01:46<1:28:17,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:18 | 200 |  200.501055ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 168/8417 [01:46<1:30:57,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:19 | 200 |  129.529208ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 169/8417 [01:47<1:28:38,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:19 | 200 |  145.322286ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 170/8417 [01:48<1:27:13,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:20 | 200 |  157.212143ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 171/8417 [01:48<1:26:53,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:20 | 200 |  181.540258ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 172/8417 [01:49<1:29:04,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:21 | 200 |  154.470032ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 173/8417 [01:50<1:28:39,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:22 | 200 |  149.193809ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 174/8417 [01:50<1:28:04,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:22 | 200 |  138.130306ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 175/8417 [01:51<1:27:55,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:23 | 200 |  142.649519ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 176/8417 [01:52<1:27:06,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:24 | 200 |  176.443014ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 177/8417 [01:52<1:28:09,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:24 | 200 |  157.584986ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 178/8417 [01:53<1:28:12,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:25 | 200 |  144.445027ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 179/8417 [01:53<1:27:21,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:26 | 200 |  135.012974ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 180/8417 [01:54<1:26:19,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:26 | 200 |  140.081831ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 181/8417 [01:55<1:25:30,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:27 | 200 |  141.366457ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 182/8417 [01:55<1:25:22,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:27 | 200 |  114.482561ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 183/8417 [01:56<1:24:28,  1.62it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:28 | 200 |  136.547343ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 184/8417 [01:57<1:24:33,  1.62it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:29 | 200 |  150.447481ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 185/8417 [01:57<1:25:18,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:29 | 200 |  189.807838ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 186/8417 [01:58<1:27:27,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:30 | 200 |  146.844745ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 187/8417 [01:58<1:28:31,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:31 | 200 |  142.432005ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 188/8417 [01:59<1:28:54,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:31 | 200 |  151.385946ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 189/8417 [02:00<1:29:37,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:32 | 200 |  143.316359ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 190/8417 [02:00<1:29:26,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:33 | 200 |  143.783111ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 191/8417 [02:01<1:28:09,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:33 | 200 |  139.212404ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 192/8417 [02:02<1:26:23,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:34 | 200 |  137.850226ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 193/8417 [02:02<1:25:53,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:34 | 200 |  138.518974ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 194/8417 [02:03<1:25:54,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:35 | 200 |  152.645152ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 195/8417 [02:04<1:26:49,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:36 | 200 |  177.341095ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 196/8417 [02:04<1:27:44,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:36 | 200 |  147.385652ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 197/8417 [02:05<1:27:16,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:37 | 200 |  143.687618ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 198/8417 [02:05<1:26:46,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:38 | 200 |  137.864443ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 199/8417 [02:06<1:26:46,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:38 | 200 |  141.235112ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 200/8417 [02:07<1:26:24,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:39 | 200 |  144.522027ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 201/8417 [02:07<1:25:43,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:40 | 200 |  180.529172ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 202/8417 [02:08<1:27:22,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:40 | 200 |  168.334959ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 203/8417 [02:09<1:27:45,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:41 | 200 |  164.158473ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 204/8417 [02:09<1:29:03,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:41 | 200 |  140.057546ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 205/8417 [02:10<1:28:09,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:42 | 200 |  144.574115ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 206/8417 [02:11<1:28:05,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:43 | 200 |  162.719703ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 207/8417 [02:11<1:29:06,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:43 | 200 |  147.233635ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 208/8417 [02:12<1:28:10,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:44 | 200 |  140.924057ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 209/8417 [02:13<1:27:27,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:45 | 200 |  139.750641ms |       127.0.0.1 | POST     "/api/chat"

  2%|▏         | 210/8417 [02:13<1:27:03,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:45 | 200 |   146.07356ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 211/8417 [02:14<1:26:00,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:46 | 200 |  174.858666ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 212/8417 [02:14<1:27:52,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:47 | 200 |  179.631063ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 213/8417 [02:15<1:28:26,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:47 | 200 |  149.429144ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 214/8417 [02:16<1:27:54,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:48 | 200 |  139.127574ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 215/8417 [02:16<1:27:58,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:48 | 200 |  115.020852ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 216/8417 [02:17<1:26:57,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:49 | 200 |  150.318634ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 217/8417 [02:18<1:27:51,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:50 | 200 |  188.358926ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 218/8417 [02:18<1:30:21,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:51 | 200 |  148.411334ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 219/8417 [02:19<1:31:29,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:51 | 200 |  132.628317ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 220/8417 [02:20<1:29:20,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:52 | 200 |  180.087816ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 221/8417 [02:20<1:30:09,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:52 | 200 |  146.933348ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 222/8417 [02:21<1:28:31,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:53 | 200 |  133.109115ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 223/8417 [02:22<1:26:57,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:54 | 200 |  136.220484ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 224/8417 [02:22<1:26:35,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:54 | 200 |  120.045263ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 225/8417 [02:23<1:24:56,  1.61it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:55 | 200 |  181.764998ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 226/8417 [02:23<1:26:52,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:56 | 200 |  178.520526ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 227/8417 [02:24<1:27:50,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:56 | 200 |  149.391741ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 228/8417 [02:25<1:27:35,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:57 | 200 |  143.236673ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 229/8417 [02:25<1:27:47,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:58 | 200 |  138.119728ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 230/8417 [02:26<1:27:04,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:58 | 200 |  171.274112ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 231/8417 [02:27<1:28:05,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:26:59 | 200 |   158.30303ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 232/8417 [02:27<1:27:52,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:00 | 200 |  147.069438ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 233/8417 [02:28<1:28:32,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:00 | 200 |  144.524556ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 234/8417 [02:29<1:28:35,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:01 | 200 |  161.372631ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 235/8417 [02:29<1:28:59,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:01 | 200 |  152.918395ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 236/8417 [02:30<1:28:15,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:02 | 200 |   146.23625ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 237/8417 [02:31<1:27:35,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:03 | 200 |  141.388377ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 238/8417 [02:31<1:27:25,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:03 | 200 |  145.498092ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 239/8417 [02:32<1:26:59,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:04 | 200 |  170.044454ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 240/8417 [02:33<1:28:19,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:05 | 200 |  163.788447ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 241/8417 [02:33<1:28:19,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:05 | 200 |  144.630886ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 242/8417 [02:34<1:27:36,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:06 | 200 |  143.594376ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 243/8417 [02:34<1:27:38,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:07 | 200 |  112.645214ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 244/8417 [02:35<1:25:40,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:07 | 200 |  148.008594ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 245/8417 [02:36<1:25:30,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:08 | 200 |  139.095011ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 246/8417 [02:36<1:24:58,  1.60it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:08 | 200 |  181.179774ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 247/8417 [02:37<1:27:56,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:09 | 200 |  135.978911ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 248/8417 [02:38<1:26:32,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:10 | 200 |  147.529068ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 249/8417 [02:38<1:28:32,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:10 | 200 |  125.912369ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 250/8417 [02:39<1:27:53,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:11 | 200 |  178.991075ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 251/8417 [02:40<1:29:16,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:12 | 200 |  147.504325ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 252/8417 [02:40<1:29:14,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:12 | 200 |  140.172283ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 253/8417 [02:41<1:28:39,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:13 | 200 |  119.045315ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 254/8417 [02:42<1:27:31,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:14 | 200 |  180.554028ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 255/8417 [02:42<1:29:16,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:14 | 200 |  152.322896ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 256/8417 [02:43<1:29:08,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:15 | 200 |  140.768577ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 257/8417 [02:43<1:28:01,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:16 | 200 |  141.933716ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 258/8417 [02:44<1:27:08,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:16 | 200 |  169.044386ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 259/8417 [02:45<1:27:18,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:17 | 200 |  178.970697ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 260/8417 [02:45<1:28:40,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:18 | 200 |   146.35266ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 261/8417 [02:46<1:27:10,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:18 | 200 |   139.73748ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 262/8417 [02:47<1:26:52,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:19 | 200 |  144.324484ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 263/8417 [02:47<1:26:19,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:19 | 200 |  151.083305ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 264/8417 [02:48<1:26:27,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:20 | 200 |  173.888705ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 265/8417 [02:49<1:29:07,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:21 | 200 |  188.874402ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 266/8417 [02:49<1:31:46,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:22 | 200 |  154.172791ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 267/8417 [02:50<1:31:01,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:22 | 200 |  123.720388ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 268/8417 [02:51<1:28:26,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:23 | 200 |  143.701986ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 269/8417 [02:51<1:27:36,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:23 | 200 |  140.032783ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 270/8417 [02:52<1:26:31,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:24 | 200 |  134.517433ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 271/8417 [02:53<1:26:00,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:25 | 200 |  148.449518ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 272/8417 [02:53<1:26:04,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:25 | 200 |  180.034599ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 273/8417 [02:54<1:26:51,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:26 | 200 |  161.730506ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 274/8417 [02:54<1:27:31,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:27 | 200 |  147.338758ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 275/8417 [02:55<1:26:53,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:27 | 200 |  136.064868ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 276/8417 [02:56<1:26:16,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:28 | 200 |   140.44087ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 277/8417 [02:56<1:26:05,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:28 | 200 |  123.551385ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 278/8417 [02:57<1:25:41,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:29 | 200 |  142.142706ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 279/8417 [02:58<1:27:10,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:30 | 200 |  150.488226ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 280/8417 [02:58<1:27:42,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:30 | 200 |  137.704879ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 281/8417 [02:59<1:27:52,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:31 | 200 |  137.026646ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 282/8417 [03:00<1:27:00,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:32 | 200 |   148.60586ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 283/8417 [03:00<1:27:00,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:32 | 200 |  178.921431ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 284/8417 [03:01<1:28:10,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:33 | 200 |  145.750383ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 285/8417 [03:02<1:27:51,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:34 | 200 |  139.856449ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 286/8417 [03:02<1:26:57,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:34 | 200 |  114.997129ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 287/8417 [03:03<1:25:24,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:35 | 200 |  163.993955ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 288/8417 [03:03<1:26:46,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:36 | 200 |  180.199456ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 289/8417 [03:04<1:27:58,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:36 | 200 |  146.777284ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 290/8417 [03:05<1:27:14,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:37 | 200 |  140.346338ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 291/8417 [03:05<1:26:17,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:37 | 200 |  143.212908ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 292/8417 [03:06<1:25:23,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:38 | 200 |  138.333016ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 293/8417 [03:07<1:25:19,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:39 | 200 |  165.035418ms |       127.0.0.1 | POST     "/api/chat"

  3%|▎         | 294/8417 [03:07<1:25:48,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:39 | 200 |  180.791293ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 295/8417 [03:08<1:27:19,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:40 | 200 |   142.81661ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 296/8417 [03:09<1:26:40,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:41 | 200 |  143.996576ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 297/8417 [03:09<1:26:57,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:41 | 200 |  137.837009ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 298/8417 [03:10<1:26:38,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:42 | 200 |  166.620278ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 299/8417 [03:10<1:26:51,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:43 | 200 |  163.699656ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 300/8417 [03:11<1:27:25,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:43 | 200 |  144.893206ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 301/8417 [03:12<1:27:09,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:44 | 200 |  138.998207ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 302/8417 [03:12<1:26:42,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:45 | 200 |  139.077248ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 303/8417 [03:13<1:26:35,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:45 | 200 |  139.123876ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 304/8417 [03:14<1:26:13,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:46 | 200 |  181.974978ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 305/8417 [03:14<1:28:08,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:46 | 200 |  146.721848ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 306/8417 [03:15<1:27:16,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:47 | 200 |   136.29146ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 307/8417 [03:16<1:26:27,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:48 | 200 |  140.687532ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 308/8417 [03:16<1:26:10,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:48 | 200 |  180.691431ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 309/8417 [03:17<1:26:43,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:49 | 200 |  154.536953ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 310/8417 [03:18<1:27:14,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:50 | 200 |  147.436729ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 311/8417 [03:18<1:27:05,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:50 | 200 |  137.406591ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 312/8417 [03:19<1:26:34,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:51 | 200 |  140.689193ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 313/8417 [03:19<1:26:19,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:52 | 200 |  188.381755ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 314/8417 [03:20<1:30:26,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:52 | 200 |  119.257823ms |       127.0.0.1 | POST     "/api/chat"

  4%|▎         | 315/8417 [03:21<1:28:42,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:53 | 200 |  122.300254ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 316/8417 [03:21<1:26:47,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:54 | 200 |  164.738192ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 317/8417 [03:22<1:27:14,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:54 | 200 |  141.708267ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 318/8417 [03:23<1:26:53,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:55 | 200 |  184.362226ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 319/8417 [03:23<1:28:37,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:56 | 200 |  143.256119ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 320/8417 [03:24<1:27:23,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:56 | 200 |  143.507047ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 321/8417 [03:25<1:26:42,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:57 | 200 |  176.801831ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 322/8417 [03:25<1:27:22,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:57 | 200 |  150.055487ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 323/8417 [03:26<1:27:04,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:58 | 200 |  143.619992ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 324/8417 [03:27<1:26:37,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:59 | 200 |  146.324196ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 325/8417 [03:27<1:27:46,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:27:59 | 200 |  139.644697ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 326/8417 [03:28<1:27:08,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:00 | 200 |  166.266381ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 327/8417 [03:29<1:27:58,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:01 | 200 |    146.8454ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 328/8417 [03:29<1:27:29,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:01 | 200 |  140.297471ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 329/8417 [03:30<1:27:33,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:02 | 200 |    143.4478ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 330/8417 [03:31<1:26:50,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:03 | 200 |  175.420367ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 331/8417 [03:31<1:27:25,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:03 | 200 |  144.888537ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 332/8417 [03:32<1:27:08,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:04 | 200 |   117.87048ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 333/8417 [03:32<1:24:54,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:05 | 200 |   146.95393ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 334/8417 [03:33<1:24:46,  1.59it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:05 | 200 |  138.004727ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 335/8417 [03:34<1:26:03,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:06 | 200 |  142.411337ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 336/8417 [03:34<1:26:32,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:06 | 200 |  177.865254ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 337/8417 [03:35<1:27:27,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:07 | 200 |  155.447737ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 338/8417 [03:36<1:28:04,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:08 | 200 |  143.680051ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 339/8417 [03:36<1:27:34,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:08 | 200 |  144.164697ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 340/8417 [03:37<1:26:40,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:09 | 200 |   159.34206ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 341/8417 [03:38<1:26:28,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:10 | 200 |   145.29657ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 342/8417 [03:38<1:26:18,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:10 | 200 |  146.984393ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 343/8417 [03:39<1:27:21,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:11 | 200 |  143.757972ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 344/8417 [03:40<1:27:43,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:12 | 200 |  141.644485ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 345/8417 [03:40<1:27:35,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:12 | 200 |  157.476283ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 346/8417 [03:41<1:28:24,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:13 | 200 |  141.535056ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 347/8417 [03:42<1:27:42,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:14 | 200 |    139.3651ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 348/8417 [03:42<1:27:08,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:14 | 200 |   178.89693ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 349/8417 [03:43<1:29:31,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:15 | 200 |  144.618123ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 350/8417 [03:44<1:29:29,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:16 | 200 |  144.062575ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 351/8417 [03:44<1:28:54,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:16 | 200 |  180.333355ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 352/8417 [03:45<1:30:10,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:17 | 200 |  146.638131ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 353/8417 [03:45<1:28:36,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:18 | 200 |  139.920452ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 354/8417 [03:46<1:27:25,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:18 | 200 |   137.11677ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 355/8417 [03:47<1:26:52,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:19 | 200 |  184.029175ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 356/8417 [03:47<1:28:08,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:20 | 200 |  148.033751ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 357/8417 [03:48<1:27:50,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:20 | 200 |  112.006488ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 358/8417 [03:49<1:28:25,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:21 | 200 |  139.849474ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 359/8417 [03:49<1:27:15,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:22 | 200 |  173.998653ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 360/8417 [03:50<1:28:18,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:22 | 200 |  143.455806ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 361/8417 [03:51<1:28:30,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:23 | 200 |  141.566375ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 362/8417 [03:51<1:27:39,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:23 | 200 |  153.423627ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 363/8417 [03:52<1:28:31,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:24 | 200 |  160.989332ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 364/8417 [03:53<1:28:46,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:25 | 200 |  148.153992ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 365/8417 [03:53<1:28:11,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:25 | 200 |  150.744234ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 366/8417 [03:54<1:27:20,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:26 | 200 |  178.330517ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 367/8417 [03:55<1:27:54,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:27 | 200 |   150.54208ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 368/8417 [03:55<1:27:41,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:27 | 200 |  139.559684ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 369/8417 [03:56<1:27:22,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:28 | 200 |  138.207177ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 370/8417 [03:57<1:26:34,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:29 | 200 |  140.793078ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 371/8417 [03:57<1:25:57,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:29 | 200 |   176.01628ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 372/8417 [03:58<1:27:41,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:30 | 200 |   149.43368ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 373/8417 [03:59<1:27:16,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:31 | 200 |  137.567049ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 374/8417 [03:59<1:26:54,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:31 | 200 |  136.749085ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 375/8417 [04:00<1:27:37,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:32 | 200 |  162.781728ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 376/8417 [04:01<1:28:26,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:33 | 200 |  146.685707ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 377/8417 [04:01<1:27:41,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:33 | 200 |  141.287049ms |       127.0.0.1 | POST     "/api/chat"

  4%|▍         | 378/8417 [04:02<1:26:20,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:34 | 200 |  145.310383ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 379/8417 [04:02<1:25:48,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:35 | 200 |  175.234989ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 380/8417 [04:03<1:26:43,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:35 | 200 |  159.294537ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 381/8417 [04:04<1:27:03,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:36 | 200 |  140.836105ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 382/8417 [04:04<1:26:34,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:36 | 200 |  137.986595ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 383/8417 [04:05<1:25:26,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:37 | 200 |  140.362743ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 384/8417 [04:06<1:24:37,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:38 | 200 |  166.753963ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 385/8417 [04:06<1:25:24,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:38 | 200 |  182.032522ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 386/8417 [04:07<1:26:45,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:39 | 200 |  142.701245ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 387/8417 [04:08<1:26:00,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:40 | 200 |   133.70406ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 388/8417 [04:08<1:25:22,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:40 | 200 |  137.878678ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 389/8417 [04:09<1:25:29,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:41 | 200 |  178.586541ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 390/8417 [04:10<1:27:05,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:42 | 200 |  148.608041ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 391/8417 [04:10<1:26:35,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:42 | 200 |  136.805996ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 392/8417 [04:11<1:25:51,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:43 | 200 |  139.117033ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 393/8417 [04:11<1:25:17,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:43 | 200 |  122.175827ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 394/8417 [04:12<1:24:36,  1.58it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:44 | 200 |  176.797231ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 395/8417 [04:13<1:26:12,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:45 | 200 |  169.693245ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 396/8417 [04:13<1:27:08,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:45 | 200 |   146.25857ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 397/8417 [04:14<1:26:38,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:46 | 200 |  138.226626ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 398/8417 [04:15<1:25:59,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:47 | 200 |  142.718983ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 399/8417 [04:15<1:25:53,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:47 | 200 |  170.608127ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 400/8417 [04:16<1:26:39,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:48 | 200 |  142.019172ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 401/8417 [04:17<1:26:17,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:49 | 200 |  149.191105ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 402/8417 [04:17<1:25:56,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:49 | 200 |  115.590108ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 403/8417 [04:18<1:24:54,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:50 | 200 |  167.032075ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 404/8417 [04:18<1:25:39,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:51 | 200 |  176.633224ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 405/8417 [04:19<1:27:08,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:51 | 200 |  149.250116ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 406/8417 [04:20<1:27:46,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:52 | 200 |  140.175101ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 407/8417 [04:20<1:27:05,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:53 | 200 |  139.946185ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 408/8417 [04:21<1:26:31,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:53 | 200 |   156.22056ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 409/8417 [04:22<1:26:44,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:54 | 200 |  146.026491ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 410/8417 [04:22<1:26:26,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:55 | 200 |  135.505879ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 411/8417 [04:23<1:25:39,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:55 | 200 |  167.778433ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 412/8417 [04:24<1:28:03,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:56 | 200 |  171.231739ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 413/8417 [04:24<1:29:03,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:57 | 200 |  145.534971ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 414/8417 [04:25<1:28:05,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:57 | 200 |  121.679704ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 415/8417 [04:26<1:26:22,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:58 | 200 |  139.425776ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 416/8417 [04:26<1:25:58,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:58 | 200 |  181.113639ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 417/8417 [04:27<1:27:42,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:28:59 | 200 |  143.071102ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 418/8417 [04:28<1:27:10,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:00 | 200 |  142.625764ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 419/8417 [04:28<1:26:43,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:00 | 200 |  142.980112ms |       127.0.0.1 | POST     "/api/chat"

  5%|▍         | 420/8417 [04:29<1:27:03,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:01 | 200 |  157.295585ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 421/8417 [04:30<1:26:57,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:02 | 200 |  144.826139ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 422/8417 [04:30<1:26:14,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:02 | 200 |  138.579197ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 423/8417 [04:31<1:25:33,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:03 | 200 |  142.973258ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 424/8417 [04:32<1:25:31,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:04 | 200 |  144.551728ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 425/8417 [04:32<1:25:40,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:04 | 200 |  139.056116ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 426/8417 [04:33<1:26:08,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:05 | 200 |   172.04331ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 427/8417 [04:34<1:27:11,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:06 | 200 |  154.655894ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 428/8417 [04:34<1:27:06,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:06 | 200 |  160.536869ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 429/8417 [04:35<1:27:26,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:07 | 200 |  139.064792ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 430/8417 [04:35<1:26:24,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:08 | 200 |  142.804917ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 431/8417 [04:36<1:25:56,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:08 | 200 |  141.410103ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 432/8417 [04:37<1:25:36,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:09 | 200 |  135.121391ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 433/8417 [04:37<1:24:45,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:09 | 200 |  142.471466ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 434/8417 [04:38<1:25:11,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:10 | 200 |  177.181363ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 435/8417 [04:39<1:26:52,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:11 | 200 |  157.821587ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 436/8417 [04:39<1:28:44,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:12 | 200 |   154.76063ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 437/8417 [04:40<1:28:27,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:12 | 200 |  140.787692ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 438/8417 [04:41<1:26:42,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:13 | 200 |   138.19637ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 439/8417 [04:41<1:25:39,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:13 | 200 |  141.181832ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 440/8417 [04:42<1:25:28,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:14 | 200 |  156.157832ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 441/8417 [04:43<1:25:29,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:15 | 200 |  174.329748ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 442/8417 [04:43<1:26:51,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:15 | 200 |  148.796703ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 443/8417 [04:44<1:26:32,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:16 | 200 |  111.958912ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 444/8417 [04:44<1:24:34,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:17 | 200 |  142.351764ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 445/8417 [04:45<1:25:05,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:17 | 200 |  164.118122ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 446/8417 [04:46<1:26:34,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:18 | 200 |  162.895507ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 447/8417 [04:47<1:29:01,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:19 | 200 |  138.121941ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 448/8417 [04:47<1:27:27,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:19 | 200 |  136.161788ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 449/8417 [04:48<1:26:31,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:20 | 200 |  181.537048ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 450/8417 [04:48<1:27:43,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:21 | 200 |  153.769249ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 451/8417 [04:49<1:28:15,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:21 | 200 |  139.360485ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 452/8417 [04:50<1:27:45,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:22 | 200 |  142.941904ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 453/8417 [04:50<1:27:13,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:23 | 200 |  159.266665ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 454/8417 [04:51<1:27:32,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:23 | 200 |   144.03378ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 455/8417 [04:52<1:26:52,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:24 | 200 |  141.372619ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 456/8417 [04:52<1:26:44,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:25 | 200 |  179.593121ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 457/8417 [04:53<1:27:56,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:25 | 200 |   120.48204ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 458/8417 [04:54<1:26:00,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:26 | 200 |  155.199603ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 459/8417 [04:54<1:26:47,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:27 | 200 |  169.229322ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 460/8417 [04:55<1:29:05,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:27 | 200 |  164.382713ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 461/8417 [04:56<1:28:46,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:28 | 200 |  138.705548ms |       127.0.0.1 | POST     "/api/chat"

  5%|▌         | 462/8417 [04:56<1:27:27,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:29 | 200 |  141.117592ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 463/8417 [04:57<1:26:45,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:29 | 200 |  163.526529ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 464/8417 [04:58<1:26:43,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:30 | 200 |  154.249253ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 465/8417 [04:58<1:27:47,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:30 | 200 |  135.259167ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 466/8417 [04:59<1:27:42,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:31 | 200 |  137.418689ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 467/8417 [05:00<1:27:15,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:32 | 200 |   157.67474ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 468/8417 [05:00<1:27:38,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:32 | 200 |  144.129753ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 469/8417 [05:01<1:27:58,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:33 | 200 |   152.51144ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 470/8417 [05:02<1:27:28,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:34 | 200 |  156.489972ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 471/8417 [05:02<1:27:25,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:34 | 200 |  144.888258ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 472/8417 [05:03<1:26:54,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:35 | 200 |  142.087555ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 473/8417 [05:04<1:26:22,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:36 | 200 |  140.270385ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 474/8417 [05:04<1:25:38,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:36 | 200 |  161.237413ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 475/8417 [05:05<1:26:08,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:37 | 200 |  143.652808ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 476/8417 [05:06<1:26:05,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:38 | 200 |  117.614631ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 477/8417 [05:06<1:24:09,  1.57it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:38 | 200 |   139.92911ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 478/8417 [05:07<1:24:33,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:39 | 200 |  123.958126ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 479/8417 [05:07<1:24:37,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:40 | 200 |   181.26632ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 480/8417 [05:08<1:26:05,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:40 | 200 |  146.464273ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 481/8417 [05:09<1:26:17,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:41 | 200 |  139.247583ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 482/8417 [05:09<1:25:45,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:42 | 200 |  144.818783ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 483/8417 [05:10<1:25:28,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:42 | 200 |  158.307072ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 484/8417 [05:11<1:25:43,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:43 | 200 |  150.760863ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 485/8417 [05:11<1:26:29,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:44 | 200 |  139.864014ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 486/8417 [05:12<1:26:06,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:44 | 200 |   149.79822ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 487/8417 [05:13<1:25:38,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:45 | 200 |  141.920994ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 488/8417 [05:13<1:25:18,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:45 | 200 |  184.641298ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 489/8417 [05:14<1:26:53,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:46 | 200 |  141.524739ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 490/8417 [05:15<1:26:12,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:47 | 200 |  150.804108ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 491/8417 [05:15<1:25:58,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:47 | 200 |  179.902176ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 492/8417 [05:16<1:27:11,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:48 | 200 |  145.646469ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 493/8417 [05:17<1:26:26,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:49 | 200 |  140.355227ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 494/8417 [05:17<1:25:38,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:49 | 200 |  137.284164ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 495/8417 [05:18<1:25:51,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:50 | 200 |  179.081386ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 496/8417 [05:19<1:27:24,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:51 | 200 |  145.960773ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 497/8417 [05:19<1:26:44,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:51 | 200 |  138.313674ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 498/8417 [05:20<1:26:01,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:52 | 200 |  118.068818ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 499/8417 [05:21<1:25:20,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:53 | 200 |   181.96505ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 500/8417 [05:21<1:27:08,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:53 | 200 |  120.389753ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 501/8417 [05:22<1:26:04,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:54 | 200 |  146.484653ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 502/8417 [05:22<1:25:54,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:55 | 200 |  176.189845ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 503/8417 [05:23<1:26:52,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:55 | 200 |  155.753879ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 504/8417 [05:24<1:26:47,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:56 | 200 |  141.535353ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 505/8417 [05:24<1:26:25,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:57 | 200 |  139.691922ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 506/8417 [05:25<1:25:50,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:57 | 200 |  132.159513ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 507/8417 [05:26<1:24:50,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:58 | 200 |    160.9143ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 508/8417 [05:26<1:28:00,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:59 | 200 |  125.125563ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 509/8417 [05:27<1:27:06,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:29:59 | 200 |  142.895248ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 510/8417 [05:28<1:26:42,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:00 | 200 |  172.328186ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 511/8417 [05:28<1:28:07,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:01 | 200 |  152.188606ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 512/8417 [05:29<1:28:29,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:01 | 200 |  134.248148ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 513/8417 [05:30<1:26:56,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:02 | 200 |  161.989369ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 514/8417 [05:30<1:27:27,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:03 | 200 |  146.637038ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 515/8417 [05:31<1:26:33,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:03 | 200 |  140.517348ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 516/8417 [05:32<1:26:12,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:04 | 200 |  135.009623ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 517/8417 [05:32<1:25:42,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:05 | 200 |  168.181597ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 518/8417 [05:33<1:26:31,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:05 | 200 |  144.369963ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 519/8417 [05:34<1:26:14,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:06 | 200 |  137.296616ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 520/8417 [05:34<1:26:00,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:06 | 200 |  145.740675ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 521/8417 [05:35<1:25:44,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:07 | 200 |  157.736067ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 522/8417 [05:36<1:25:59,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:08 | 200 |  142.947171ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 523/8417 [05:36<1:25:16,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:08 | 200 |  140.938855ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 524/8417 [05:37<1:24:54,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:09 | 200 |  137.065608ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 525/8417 [05:38<1:24:29,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:10 | 200 |  145.506416ms |       127.0.0.1 | POST     "/api/chat"

  6%|▌         | 526/8417 [05:38<1:24:34,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:10 | 200 |  179.929513ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 527/8417 [05:39<1:27:37,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:11 | 200 |  148.201128ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 528/8417 [05:40<1:27:02,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:12 | 200 |  148.868872ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 529/8417 [05:40<1:26:24,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:12 | 200 |  120.351237ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 530/8417 [05:41<1:24:56,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:13 | 200 |  142.482338ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 531/8417 [05:41<1:24:55,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:14 | 200 |  137.970353ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 532/8417 [05:42<1:24:02,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:14 | 200 |  143.767492ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 533/8417 [05:43<1:24:25,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:15 | 200 |  163.185418ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 534/8417 [05:43<1:25:09,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:16 | 200 |  167.571755ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 535/8417 [05:44<1:26:12,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:16 | 200 |  119.759703ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 536/8417 [05:45<1:24:30,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:17 | 200 |  148.441621ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 537/8417 [05:45<1:24:53,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:18 | 200 |   175.33733ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 538/8417 [05:46<1:26:26,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:18 | 200 |  157.048974ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 539/8417 [05:47<1:26:06,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:19 | 200 |  140.749471ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 540/8417 [05:47<1:25:45,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:19 | 200 |  139.758342ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 541/8417 [05:48<1:25:17,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:20 | 200 |  135.371335ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 542/8417 [05:49<1:25:13,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:21 | 200 |  150.426168ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 543/8417 [05:49<1:28:29,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:22 | 200 |  184.310476ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 544/8417 [05:50<1:28:54,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:22 | 200 |  160.646959ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 545/8417 [05:51<1:28:33,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:23 | 200 |  141.912122ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 546/8417 [05:51<1:27:29,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:23 | 200 |  114.846002ms |       127.0.0.1 | POST     "/api/chat"

  6%|▋         | 547/8417 [05:52<1:25:42,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:24 | 200 |  179.028815ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 548/8417 [05:53<1:27:03,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:25 | 200 |  148.091957ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 549/8417 [05:53<1:27:15,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:25 | 200 |  141.006216ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 550/8417 [05:54<1:26:01,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:26 | 200 |  140.320872ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 551/8417 [05:55<1:25:02,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:27 | 200 |  179.707393ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 552/8417 [05:55<1:26:21,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:27 | 200 |  145.277038ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 553/8417 [05:56<1:25:51,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:28 | 200 |  143.572878ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 554/8417 [05:57<1:25:52,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:29 | 200 |  136.734197ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 555/8417 [05:57<1:25:01,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:29 | 200 |  183.577481ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 556/8417 [05:58<1:27:27,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:30 | 200 |  165.755785ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 557/8417 [05:59<1:28:59,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:31 | 200 |  188.886131ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 558/8417 [05:59<1:30:21,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:31 | 200 |  148.739693ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 559/8417 [06:00<1:29:11,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:32 | 200 |  146.860267ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 560/8417 [06:01<1:28:02,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:33 | 200 |  153.399863ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 561/8417 [06:01<1:27:13,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:33 | 200 |  149.097048ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 562/8417 [06:02<1:26:22,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:34 | 200 |  142.521789ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 563/8417 [06:03<1:28:02,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:35 | 200 |  138.121189ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 564/8417 [06:03<1:26:59,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:35 | 200 |   162.72633ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 565/8417 [06:04<1:27:07,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:36 | 200 |  143.256993ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 566/8417 [06:05<1:26:40,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:37 | 200 |  140.808795ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 567/8417 [06:05<1:25:57,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:37 | 200 |  161.975671ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 568/8417 [06:06<1:26:10,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:38 | 200 |  141.361572ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 569/8417 [06:07<1:25:49,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:39 | 200 |  144.858717ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 570/8417 [06:07<1:25:47,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:39 | 200 |  137.814223ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 571/8417 [06:08<1:25:35,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:40 | 200 |  153.971287ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 572/8417 [06:09<1:25:53,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:41 | 200 |  145.027468ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 573/8417 [06:09<1:26:06,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:41 | 200 |  140.371513ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 574/8417 [06:10<1:25:34,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:42 | 200 |  141.994465ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 575/8417 [06:11<1:24:46,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:43 | 200 |  160.397322ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 576/8417 [06:11<1:25:07,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:43 | 200 |   149.16004ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 577/8417 [06:12<1:24:47,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:44 | 200 |  137.307802ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 578/8417 [06:12<1:24:18,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:45 | 200 |   134.53424ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 579/8417 [06:13<1:23:58,  1.56it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:45 | 200 |  180.216169ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 580/8417 [06:14<1:25:27,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:46 | 200 |  146.719104ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 581/8417 [06:14<1:25:53,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:47 | 200 |  138.689768ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 582/8417 [06:15<1:25:56,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:47 | 200 |  143.716309ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 583/8417 [06:16<1:25:21,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:48 | 200 |  153.754288ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 584/8417 [06:16<1:25:41,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:48 | 200 |   115.58366ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 585/8417 [06:17<1:24:21,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:49 | 200 |  143.484715ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 586/8417 [06:18<1:24:12,  1.55it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:50 | 200 |  163.851255ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 587/8417 [06:18<1:25:15,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:50 | 200 |  180.960505ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 588/8417 [06:19<1:28:02,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:51 | 200 |  147.641581ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 589/8417 [06:20<1:27:00,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:52 | 200 |  144.550769ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 590/8417 [06:20<1:26:11,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:52 | 200 |   146.46207ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 591/8417 [06:21<1:26:10,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:53 | 200 |   145.09754ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 592/8417 [06:22<1:26:15,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:54 | 200 |  143.225431ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 593/8417 [06:22<1:25:51,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:54 | 200 |  137.883231ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 594/8417 [06:23<1:25:09,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:55 | 200 |  158.528693ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 595/8417 [06:24<1:25:34,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:56 | 200 |  138.920747ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 596/8417 [06:24<1:25:26,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:56 | 200 |  144.758469ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 597/8417 [06:25<1:25:07,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:57 | 200 |  182.022469ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 598/8417 [06:26<1:26:16,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:58 | 200 |  124.371413ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 599/8417 [06:26<1:25:08,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:58 | 200 |  142.046882ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 600/8417 [06:27<1:25:39,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:30:59 | 200 |  164.924143ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 601/8417 [06:28<1:26:20,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:00 | 200 |  125.333661ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 602/8417 [06:28<1:25:11,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:00 | 200 |  165.088517ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 603/8417 [06:29<1:26:29,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:01 | 200 |   142.68719ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 604/8417 [06:30<1:26:32,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:02 | 200 |  181.654929ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 605/8417 [06:30<1:28:17,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:02 | 200 |  144.321429ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 606/8417 [06:31<1:27:24,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:03 | 200 |  148.538441ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 607/8417 [06:32<1:27:01,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:04 | 200 |  155.051954ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 608/8417 [06:32<1:27:05,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:04 | 200 |  142.833126ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 609/8417 [06:33<1:26:09,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:05 | 200 |  113.071213ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 610/8417 [06:34<1:24:40,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:06 | 200 |  179.226042ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 611/8417 [06:34<1:26:06,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:06 | 200 |   147.71387ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 612/8417 [06:35<1:25:37,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:07 | 200 |  142.105902ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 613/8417 [06:36<1:25:00,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:08 | 200 |  133.286717ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 614/8417 [06:36<1:24:19,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:08 | 200 |  180.090725ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 615/8417 [06:37<1:25:35,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:09 | 200 |  142.239403ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 616/8417 [06:38<1:25:27,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:10 | 200 |  146.206989ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 617/8417 [06:38<1:25:28,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:10 | 200 |  139.114616ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 618/8417 [06:39<1:25:52,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:11 | 200 |  165.916333ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 619/8417 [06:40<1:26:19,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:12 | 200 |  138.382316ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 620/8417 [06:40<1:25:38,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:12 | 200 |  139.550169ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 621/8417 [06:41<1:25:27,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:13 | 200 |  166.076451ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 622/8417 [06:41<1:26:30,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:14 | 200 |  144.617489ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 623/8417 [06:42<1:25:56,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:14 | 200 |  140.800781ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 624/8417 [06:43<1:25:13,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:15 | 200 |  138.220275ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 625/8417 [06:43<1:24:34,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:16 | 200 |  158.909208ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 626/8417 [06:44<1:26:12,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:16 | 200 |  144.439086ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 627/8417 [06:45<1:25:16,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:17 | 200 |  124.110918ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 628/8417 [06:45<1:24:40,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:18 | 200 |  182.496696ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 629/8417 [06:46<1:27:52,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:18 | 200 |  146.011894ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 630/8417 [06:47<1:26:54,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:19 | 200 |  144.976938ms |       127.0.0.1 | POST     "/api/chat"

  7%|▋         | 631/8417 [06:47<1:26:19,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:20 | 200 |  156.556102ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 632/8417 [06:48<1:26:08,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:20 | 200 |  141.442314ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 633/8417 [06:49<1:26:10,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:21 | 200 |  141.693256ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 634/8417 [06:49<1:25:54,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:22 | 200 |   134.49559ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 635/8417 [06:50<1:25:06,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:22 | 200 |  160.714293ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 636/8417 [06:51<1:25:28,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:23 | 200 |  145.921859ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 637/8417 [06:51<1:25:40,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:24 | 200 |  142.634108ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 638/8417 [06:52<1:25:53,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:24 | 200 |  157.402886ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 639/8417 [06:53<1:26:16,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:25 | 200 |  146.025719ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 640/8417 [06:53<1:26:15,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:26 | 200 |   116.58963ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 641/8417 [06:54<1:26:45,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:26 | 200 |  145.288641ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 642/8417 [06:55<1:26:22,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:27 | 200 |  170.363138ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 643/8417 [06:55<1:27:00,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:28 | 200 |   170.65404ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 644/8417 [06:56<1:27:58,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:28 | 200 |  149.891692ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 645/8417 [06:57<1:27:14,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:29 | 200 |  139.528914ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 646/8417 [06:57<1:25:56,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:30 | 200 |  146.666914ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 647/8417 [06:58<1:25:49,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:30 | 200 |  152.807847ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 648/8417 [06:59<1:26:29,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:31 | 200 |  151.146191ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 649/8417 [06:59<1:27:02,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:32 | 200 |  142.214729ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 650/8417 [07:00<1:25:47,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:32 | 200 |  160.817968ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 651/8417 [07:01<1:25:53,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:33 | 200 |  144.640538ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 652/8417 [07:01<1:27:39,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:34 | 200 |  152.177193ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 653/8417 [07:02<1:28:24,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:34 | 200 |  154.842354ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 654/8417 [07:03<1:28:13,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:35 | 200 |  160.994453ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 655/8417 [07:04<1:28:09,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:36 | 200 |  152.280945ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 656/8417 [07:04<1:27:55,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:36 | 200 |  147.460113ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 657/8417 [07:05<1:30:11,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:37 | 200 |  141.644592ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 658/8417 [07:06<1:28:13,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:38 | 200 |  142.812703ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 659/8417 [07:06<1:27:39,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:38 | 200 |  140.627064ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 660/8417 [07:07<1:26:40,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:39 | 200 |  165.640667ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 661/8417 [07:08<1:26:54,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:40 | 200 |  150.475505ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 662/8417 [07:08<1:26:37,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:40 | 200 |  143.870843ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 663/8417 [07:09<1:26:58,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:41 | 200 |  147.241355ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 664/8417 [07:10<1:26:16,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:42 | 200 |  157.720335ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 665/8417 [07:10<1:26:00,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:42 | 200 |  139.706804ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 666/8417 [07:11<1:24:58,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:43 | 200 |  138.191019ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 667/8417 [07:12<1:24:31,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:44 | 200 |  164.478794ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 668/8417 [07:12<1:25:14,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:44 | 200 |  142.006118ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 669/8417 [07:13<1:25:01,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:45 | 200 |  143.921925ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 670/8417 [07:14<1:24:59,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:46 | 200 |  145.104805ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 671/8417 [07:14<1:25:06,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:46 | 200 |  158.697855ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 672/8417 [07:15<1:25:14,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:47 | 200 |  141.664837ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 673/8417 [07:15<1:24:56,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:48 | 200 |  116.113622ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 674/8417 [07:16<1:23:42,  1.54it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:48 | 200 |  183.567633ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 675/8417 [07:17<1:25:06,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:49 | 200 |  144.846876ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 676/8417 [07:17<1:24:42,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:50 | 200 |  138.664409ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 677/8417 [07:18<1:25:32,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:50 | 200 |  139.856468ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 678/8417 [07:19<1:25:15,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:51 | 200 |  158.746869ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 679/8417 [07:19<1:25:26,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:52 | 200 |  143.339418ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 680/8417 [07:20<1:25:00,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:52 | 200 |  146.652144ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 681/8417 [07:21<1:25:08,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:53 | 200 |  158.351597ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 682/8417 [07:21<1:25:32,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:54 | 200 |  157.209296ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 683/8417 [07:22<1:25:22,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:54 | 200 |  146.335935ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 684/8417 [07:23<1:25:08,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:55 | 200 |  146.589551ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 685/8417 [07:23<1:24:57,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:56 | 200 |  145.091699ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 686/8417 [07:24<1:24:50,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:56 | 200 |  151.084812ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 687/8417 [07:25<1:24:57,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:57 | 200 |  138.445639ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 688/8417 [07:25<1:24:33,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:58 | 200 |  165.809288ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 689/8417 [07:26<1:25:34,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:58 | 200 |  142.093097ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 690/8417 [07:27<1:25:35,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:59 | 200 |  143.445911ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 691/8417 [07:27<1:25:11,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:31:59 | 200 |  133.774406ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 692/8417 [07:28<1:24:47,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:00 | 200 |  174.586275ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 693/8417 [07:29<1:26:56,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:01 | 200 |  156.164113ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 694/8417 [07:29<1:27:27,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:02 | 200 |  145.184255ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 695/8417 [07:30<1:26:29,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:02 | 200 |   145.48435ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 696/8417 [07:31<1:26:27,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:03 | 200 |  138.787963ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 697/8417 [07:31<1:25:46,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:04 | 200 |  157.352848ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 698/8417 [07:32<1:25:45,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:04 | 200 |  142.899822ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 699/8417 [07:33<1:26:58,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:05 | 200 |  153.142379ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 700/8417 [07:33<1:26:49,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:06 | 200 |  175.609809ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 701/8417 [07:34<1:28:09,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:06 | 200 |  155.363561ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 702/8417 [07:35<1:27:18,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:07 | 200 |   148.25488ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 703/8417 [07:35<1:26:40,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:08 | 200 |  141.164564ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 704/8417 [07:36<1:25:41,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:08 | 200 |  141.295061ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 705/8417 [07:37<1:25:23,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:09 | 200 |   145.83105ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 706/8417 [07:37<1:25:29,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:10 | 200 |  122.949662ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 707/8417 [07:38<1:27:39,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:10 | 200 |  181.298503ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 708/8417 [07:39<1:28:55,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:11 | 200 |  146.628979ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 709/8417 [07:40<1:27:39,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:12 | 200 |   141.22081ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 710/8417 [07:40<1:26:34,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:12 | 200 |  143.257723ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 711/8417 [07:41<1:25:58,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:13 | 200 |  158.022204ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 712/8417 [07:42<1:26:09,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:14 | 200 |  141.877286ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 713/8417 [07:42<1:25:33,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:14 | 200 |  146.817682ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 714/8417 [07:43<1:26:19,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:15 | 200 |  163.784708ms |       127.0.0.1 | POST     "/api/chat"

  8%|▊         | 715/8417 [07:44<1:26:39,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:16 | 200 |  143.863934ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 716/8417 [07:44<1:26:03,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:16 | 200 |   132.53504ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 717/8417 [07:45<1:25:16,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:17 | 200 |   159.28224ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 718/8417 [07:46<1:25:47,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:18 | 200 |  140.471417ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 719/8417 [07:46<1:25:31,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:18 | 200 |  144.156046ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 720/8417 [07:47<1:25:01,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:19 | 200 |  156.693442ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 721/8417 [07:48<1:24:56,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:20 | 200 |  140.048796ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 722/8417 [07:48<1:24:31,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:20 | 200 |  144.713289ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 723/8417 [07:49<1:25:06,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:21 | 200 |  144.752554ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 724/8417 [07:50<1:25:26,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:22 | 200 |  124.877634ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 725/8417 [07:50<1:24:18,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:22 | 200 |  175.137732ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 726/8417 [07:51<1:25:34,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:23 | 200 |  177.723197ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 727/8417 [07:52<1:26:30,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:24 | 200 |  141.978708ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 728/8417 [07:52<1:26:40,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:24 | 200 |  147.328193ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 729/8417 [07:53<1:26:28,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:25 | 200 |  121.975917ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 730/8417 [07:54<1:25:23,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:26 | 200 |  146.436725ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 731/8417 [07:54<1:25:45,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:26 | 200 |  134.832804ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 732/8417 [07:55<1:25:09,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:27 | 200 |  179.629649ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 733/8417 [07:56<1:25:55,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:28 | 200 |  137.511648ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 734/8417 [07:56<1:26:04,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:28 | 200 |  143.664964ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 735/8417 [07:57<1:25:00,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:29 | 200 |  161.921741ms |       127.0.0.1 | POST     "/api/chat"

  9%|▊         | 736/8417 [07:58<1:25:27,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:30 | 200 |  145.927729ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 737/8417 [07:58<1:25:44,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:30 | 200 |  144.083663ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 738/8417 [07:59<1:25:44,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:31 | 200 |  175.804545ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 739/8417 [08:00<1:26:32,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:32 | 200 |  141.631348ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 740/8417 [08:00<1:26:40,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:32 | 200 |  143.699166ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 741/8417 [08:01<1:25:45,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:33 | 200 |   143.47382ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 742/8417 [08:02<1:25:03,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:34 | 200 |   136.74509ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 743/8417 [08:02<1:24:44,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:34 | 200 |  139.648109ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 744/8417 [08:03<1:25:10,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:35 | 200 |  165.157479ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 745/8417 [08:04<1:26:18,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:36 | 200 |  145.768493ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 746/8417 [08:04<1:27:13,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:36 | 200 |  156.308981ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 747/8417 [08:05<1:26:37,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:37 | 200 |  162.167063ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 748/8417 [08:06<1:27:33,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:38 | 200 |  184.068683ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 749/8417 [08:06<1:28:10,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:38 | 200 |  119.165492ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 750/8417 [08:07<1:26:37,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:39 | 200 |  116.218053ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 751/8417 [08:08<1:24:24,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:40 | 200 |  171.561345ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 752/8417 [08:08<1:25:43,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:40 | 200 |  167.477565ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 753/8417 [08:09<1:27:21,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:41 | 200 |  146.075005ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 754/8417 [08:10<1:26:28,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:42 | 200 |  148.802956ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 755/8417 [08:10<1:26:19,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:42 | 200 |  127.193875ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 756/8417 [08:11<1:25:01,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:43 | 200 |  143.438512ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 757/8417 [08:12<1:25:13,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:44 | 200 |  179.287409ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 758/8417 [08:12<1:27:15,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:45 | 200 |  150.827304ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 759/8417 [08:13<1:26:38,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:45 | 200 |  148.045893ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 760/8417 [08:14<1:25:51,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:46 | 200 |  139.812889ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 761/8417 [08:14<1:25:27,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:47 | 200 |  143.731639ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 762/8417 [08:15<1:25:02,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:47 | 200 |  138.709894ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 763/8417 [08:16<1:24:18,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:48 | 200 |  141.971851ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 764/8417 [08:16<1:24:34,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:49 | 200 |  156.146421ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 765/8417 [08:17<1:25:58,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:49 | 200 |  144.911843ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 766/8417 [08:18<1:25:59,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:50 | 200 |  123.451623ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 767/8417 [08:18<1:24:49,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:51 | 200 |  171.373995ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 768/8417 [08:19<1:26:47,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:51 | 200 |  153.494075ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 769/8417 [08:20<1:26:19,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:52 | 200 |  140.050484ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 770/8417 [08:20<1:25:35,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:53 | 200 |  142.408599ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 771/8417 [08:21<1:25:23,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:53 | 200 |  142.277948ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 772/8417 [08:22<1:25:45,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:54 | 200 |  154.300224ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 773/8417 [08:22<1:26:00,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:55 | 200 |   140.96099ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 774/8417 [08:23<1:25:32,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:55 | 200 |  140.312528ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 775/8417 [08:24<1:24:59,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:56 | 200 |  160.767749ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 776/8417 [08:24<1:25:18,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:57 | 200 |  117.643092ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 777/8417 [08:25<1:23:36,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:57 | 200 |  120.773478ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 778/8417 [08:26<1:23:36,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:58 | 200 |  176.145313ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 779/8417 [08:26<1:24:40,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:59 | 200 |  148.433018ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 780/8417 [08:27<1:23:56,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:32:59 | 200 |  139.643921ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 781/8417 [08:28<1:23:55,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:00 | 200 |  143.030502ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 782/8417 [08:28<1:23:54,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:01 | 200 |  161.407691ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 783/8417 [08:29<1:25:24,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:01 | 200 |  143.050172ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 784/8417 [08:30<1:24:48,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:02 | 200 |  118.541891ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 785/8417 [08:30<1:23:42,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:03 | 200 |   144.69124ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 786/8417 [08:31<1:23:34,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:03 | 200 |  168.687418ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 787/8417 [08:32<1:24:58,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:04 | 200 |  147.576564ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 788/8417 [08:32<1:24:52,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:05 | 200 |  148.776499ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 789/8417 [08:33<1:25:02,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:05 | 200 |  143.366135ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 790/8417 [08:34<1:24:54,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:06 | 200 |  142.215156ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 791/8417 [08:34<1:24:49,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:07 | 200 |  177.866379ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 792/8417 [08:35<1:26:16,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:07 | 200 |  122.297355ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 793/8417 [08:36<1:25:33,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:08 | 200 |  166.310742ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 794/8417 [08:37<1:27:13,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:09 | 200 |  122.628157ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 795/8417 [08:37<1:25:55,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:09 | 200 |  118.569363ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 796/8417 [08:38<1:24:08,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:10 | 200 |  179.341753ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 797/8417 [08:39<1:25:53,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:11 | 200 |  142.587198ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 798/8417 [08:39<1:26:15,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:11 | 200 |  149.409109ms |       127.0.0.1 | POST     "/api/chat"

  9%|▉         | 799/8417 [08:40<1:26:04,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:12 | 200 |  141.085157ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 800/8417 [08:41<1:25:26,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:13 | 200 |  115.227916ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 801/8417 [08:41<1:23:54,  1.51it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:13 | 200 |  116.065052ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 802/8417 [08:42<1:22:53,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:14 | 200 |  136.596459ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 803/8417 [08:42<1:22:56,  1.53it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:15 | 200 |  141.062654ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 804/8417 [08:43<1:23:22,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:15 | 200 |  141.024337ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 805/8417 [08:44<1:23:25,  1.52it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:16 | 200 |  170.133317ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 806/8417 [08:44<1:24:57,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:17 | 200 |   169.32099ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 807/8417 [08:45<1:26:27,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:17 | 200 |  150.262145ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 808/8417 [08:46<1:25:35,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:18 | 200 |  143.621164ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 809/8417 [08:47<1:25:19,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:19 | 200 |  127.280627ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 810/8417 [08:47<1:24:15,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:19 | 200 |  172.534722ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 811/8417 [08:48<1:25:17,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:20 | 200 |  183.641793ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 812/8417 [08:49<1:27:01,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:21 | 200 |  148.551576ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 813/8417 [08:49<1:27:02,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:21 | 200 |  147.359935ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 814/8417 [08:50<1:27:15,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:22 | 200 |  137.696217ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 815/8417 [08:51<1:26:16,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:23 | 200 |  138.302595ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 816/8417 [08:51<1:25:35,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:23 | 200 |   139.42523ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 817/8417 [08:52<1:24:31,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:24 | 200 |  156.352117ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 818/8417 [08:53<1:25:40,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:25 | 200 |  150.339421ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 819/8417 [08:53<1:25:22,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:25 | 200 |  140.321991ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 820/8417 [08:54<1:25:23,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:26 | 200 |  160.398257ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 821/8417 [08:55<1:25:37,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:27 | 200 |  148.574789ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 822/8417 [08:55<1:25:26,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:27 | 200 |  153.651285ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 823/8417 [08:56<1:25:30,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:28 | 200 |  146.075101ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 824/8417 [08:57<1:25:33,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:29 | 200 |  143.822057ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 825/8417 [08:57<1:25:08,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:29 | 200 |  127.277956ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 826/8417 [08:58<1:24:37,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:30 | 200 |   175.81858ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 827/8417 [08:59<1:25:44,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:31 | 200 |  194.793675ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 828/8417 [08:59<1:28:27,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:32 | 200 |   144.84789ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 829/8417 [09:00<1:27:05,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:32 | 200 |  147.753409ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 830/8417 [09:01<1:26:52,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:33 | 200 |  143.677445ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 831/8417 [09:01<1:26:12,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:34 | 200 |  139.636974ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 832/8417 [09:02<1:25:14,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:34 | 200 |   142.06511ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 833/8417 [09:03<1:24:39,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:35 | 200 |  148.280058ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 834/8417 [09:03<1:25:12,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:36 | 200 |  152.813866ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 835/8417 [09:04<1:25:37,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:36 | 200 |  140.868893ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 836/8417 [09:05<1:25:01,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:37 | 200 |  114.776648ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 837/8417 [09:05<1:24:23,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:38 | 200 |  140.999066ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 838/8417 [09:06<1:23:56,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:38 | 200 |  145.054377ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 839/8417 [09:07<1:24:21,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:39 | 200 |  141.253425ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 840/8417 [09:07<1:25:41,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:40 | 200 |  184.746137ms |       127.0.0.1 | POST     "/api/chat"

 10%|▉         | 841/8417 [09:08<1:27:19,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:40 | 200 |  132.427128ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 842/8417 [09:09<1:26:40,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:41 | 200 |  140.412715ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 843/8417 [09:10<1:26:06,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:42 | 200 |  178.408222ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 844/8417 [09:10<1:26:47,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:42 | 200 |  142.983352ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 845/8417 [09:11<1:25:38,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:43 | 200 |  147.135035ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 846/8417 [09:12<1:25:10,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:44 | 200 |  141.430377ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 847/8417 [09:12<1:24:53,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:44 | 200 |  140.649262ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 848/8417 [09:13<1:24:59,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:45 | 200 |   136.54796ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 849/8417 [09:14<1:24:51,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:46 | 200 |  158.471996ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 850/8417 [09:14<1:25:24,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:46 | 200 |  140.528725ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 851/8417 [09:15<1:24:36,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:47 | 200 |  142.956648ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 852/8417 [09:16<1:24:50,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:48 | 200 |  157.575775ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 853/8417 [09:16<1:25:20,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:48 | 200 |  118.057424ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 854/8417 [09:17<1:23:48,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:49 | 200 |  145.237868ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 855/8417 [09:18<1:23:59,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:50 | 200 |  164.328631ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 856/8417 [09:18<1:25:15,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:50 | 200 |  148.142018ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 857/8417 [09:19<1:25:53,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:51 | 200 |  137.882376ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 858/8417 [09:20<1:24:54,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:52 | 200 |  157.902862ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 859/8417 [09:20<1:25:05,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:52 | 200 |  180.372218ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 860/8417 [09:21<1:25:56,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:53 | 200 |  143.208027ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 861/8417 [09:22<1:25:28,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:54 | 200 |  142.141671ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 862/8417 [09:22<1:25:08,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:54 | 200 |  143.562832ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 863/8417 [09:23<1:24:59,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:55 | 200 |  158.128042ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 864/8417 [09:24<1:25:13,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:56 | 200 |  151.524976ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 865/8417 [09:24<1:25:37,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:57 | 200 |  140.595716ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 866/8417 [09:25<1:25:10,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:57 | 200 |  138.696129ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 867/8417 [09:26<1:24:18,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:58 | 200 |  136.865695ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 868/8417 [09:26<1:23:58,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:59 | 200 |  180.280836ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 869/8417 [09:27<1:25:00,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:33:59 | 200 |  142.601648ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 870/8417 [09:28<1:24:32,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:00 | 200 |  144.398174ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 871/8417 [09:28<1:24:29,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:01 | 200 |  142.172532ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 872/8417 [09:29<1:25:04,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:01 | 200 |  145.202126ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 873/8417 [09:30<1:25:05,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:02 | 200 |  182.017961ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 874/8417 [09:31<1:26:06,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:03 | 200 |  145.843052ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 875/8417 [09:31<1:25:26,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:03 | 200 |   145.81419ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 876/8417 [09:32<1:25:02,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:04 | 200 |  161.235683ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 877/8417 [09:33<1:25:34,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:05 | 200 |  140.377643ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 878/8417 [09:33<1:24:45,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:05 | 200 |  144.580608ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 879/8417 [09:34<1:24:08,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:06 | 200 |  159.978014ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 880/8417 [09:35<1:24:34,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:07 | 200 |  140.299199ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 881/8417 [09:35<1:24:12,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:07 | 200 |  146.998042ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 882/8417 [09:36<1:24:33,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:08 | 200 |    128.1963ms |       127.0.0.1 | POST     "/api/chat"

 10%|█         | 883/8417 [09:37<1:24:07,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:09 | 200 |  138.976135ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 884/8417 [09:37<1:24:00,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:09 | 200 |  144.382595ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 885/8417 [09:38<1:24:45,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:10 | 200 |  178.520463ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 886/8417 [09:39<1:26:29,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:11 | 200 |  169.964909ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 887/8417 [09:39<1:28:33,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:12 | 200 |  178.438096ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 888/8417 [09:40<1:28:37,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:12 | 200 |   144.88337ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 889/8417 [09:41<1:27:00,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:13 | 200 |    139.1441ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 890/8417 [09:41<1:25:25,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:14 | 200 |  142.523819ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 891/8417 [09:42<1:25:09,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:14 | 200 |  140.919829ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 892/8417 [09:43<1:24:00,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:15 | 200 |  145.543658ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 893/8417 [09:43<1:24:06,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:16 | 200 |  147.190759ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 894/8417 [09:44<1:24:17,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:16 | 200 |  140.291673ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 895/8417 [09:45<1:23:55,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:17 | 200 |   131.83434ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 896/8417 [09:45<1:23:32,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:18 | 200 |  177.526199ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 897/8417 [09:46<1:24:32,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:18 | 200 |  142.556911ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 898/8417 [09:47<1:24:03,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:19 | 200 |  175.878005ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 899/8417 [09:47<1:24:51,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:20 | 200 |  149.655109ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 900/8417 [09:48<1:25:20,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:20 | 200 |  141.555069ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 901/8417 [09:49<1:25:28,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:21 | 200 |   145.39328ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 902/8417 [09:49<1:25:39,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:22 | 200 |  136.279944ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 903/8417 [09:50<1:24:44,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:22 | 200 |  126.565296ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 904/8417 [09:51<1:24:09,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:23 | 200 |  175.742731ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 905/8417 [09:52<1:25:38,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:24 | 200 |  173.894745ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 906/8417 [09:52<1:26:42,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:24 | 200 |  143.752706ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 907/8417 [09:53<1:26:08,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:25 | 200 |  139.858953ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 908/8417 [09:54<1:26:06,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:26 | 200 |  137.327555ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 909/8417 [09:54<1:25:24,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:26 | 200 |  140.950812ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 910/8417 [09:55<1:24:25,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:27 | 200 |  156.587712ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 911/8417 [09:56<1:24:18,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:28 | 200 |  147.590805ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 912/8417 [09:56<1:24:29,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:28 | 200 |  120.710826ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 913/8417 [09:57<1:23:16,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:29 | 200 |  177.448928ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 914/8417 [09:58<1:24:30,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:30 | 200 |  146.285634ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 915/8417 [09:58<1:24:09,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:30 | 200 |  143.810985ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 916/8417 [09:59<1:26:00,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:31 | 200 |  142.406366ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 917/8417 [10:00<1:25:26,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:32 | 200 |  146.201084ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 918/8417 [10:00<1:24:59,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:32 | 200 |  147.231296ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 919/8417 [10:01<1:24:48,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:33 | 200 |  143.070967ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 920/8417 [10:02<1:24:41,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:34 | 200 |  143.735975ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 921/8417 [10:02<1:25:16,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:35 | 200 |  145.031315ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 922/8417 [10:03<1:25:25,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:35 | 200 |  149.159364ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 923/8417 [10:04<1:25:08,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:36 | 200 |  155.508255ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 924/8417 [10:04<1:25:32,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:37 | 200 |  135.999087ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 925/8417 [10:05<1:24:53,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:37 | 200 |  143.408666ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 926/8417 [10:06<1:24:47,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:38 | 200 |   158.40416ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 927/8417 [10:06<1:25:21,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:39 | 200 |  147.021806ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 928/8417 [10:07<1:25:09,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:39 | 200 |  146.285254ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 929/8417 [10:08<1:25:34,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:40 | 200 |  137.075863ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 930/8417 [10:09<1:25:06,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:41 | 200 |  117.311691ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 931/8417 [10:09<1:25:05,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:41 | 200 |  169.520175ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 932/8417 [10:10<1:25:43,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:42 | 200 |  129.713513ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 933/8417 [10:11<1:25:48,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:43 | 200 |  200.379658ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 934/8417 [10:11<1:28:36,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:44 | 200 |  178.145765ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 935/8417 [10:12<1:29:02,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:44 | 200 |    141.3222ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 936/8417 [10:13<1:27:16,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:45 | 200 |  121.738268ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 937/8417 [10:13<1:25:50,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:46 | 200 |  179.527033ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 938/8417 [10:14<1:27:05,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:46 | 200 |    129.5021ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 939/8417 [10:15<1:25:14,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:47 | 200 |  156.508903ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 940/8417 [10:15<1:24:59,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:48 | 200 |  144.734109ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 941/8417 [10:16<1:25:19,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:48 | 200 |  142.573275ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 942/8417 [10:17<1:24:22,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:49 | 200 |   161.95006ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 943/8417 [10:18<1:24:47,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:50 | 200 |  137.362046ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 944/8417 [10:18<1:24:28,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:50 | 200 |  147.103634ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 945/8417 [10:19<1:24:59,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:51 | 200 |  162.438922ms |       127.0.0.1 | POST     "/api/chat"

 11%|█         | 946/8417 [10:20<1:25:19,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:52 | 200 |  144.423094ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 947/8417 [10:20<1:24:43,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:52 | 200 |  179.441988ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 948/8417 [10:21<1:25:38,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:53 | 200 |  154.284963ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 949/8417 [10:22<1:25:11,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:54 | 200 |  155.911595ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 950/8417 [10:22<1:25:32,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:54 | 200 |  141.623822ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 951/8417 [10:23<1:25:17,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:55 | 200 |  141.187556ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 952/8417 [10:24<1:25:03,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:56 | 200 |  154.623896ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 953/8417 [10:24<1:26:02,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:57 | 200 |  159.516833ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 954/8417 [10:25<1:25:56,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:57 | 200 |  139.716787ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 955/8417 [10:26<1:25:11,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:58 | 200 |  138.535339ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 956/8417 [10:26<1:25:11,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:59 | 200 |  142.028575ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 957/8417 [10:27<1:24:42,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:34:59 | 200 |  155.618328ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 958/8417 [10:28<1:25:37,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:00 | 200 |  181.208454ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 959/8417 [10:29<1:26:24,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:01 | 200 |  118.771005ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 960/8417 [10:29<1:25:02,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:01 | 200 |  136.002341ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 961/8417 [10:30<1:24:09,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:02 | 200 |  167.342636ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 962/8417 [10:31<1:25:08,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:03 | 200 |  144.038936ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 963/8417 [10:31<1:24:27,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:03 | 200 |  141.797642ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 964/8417 [10:32<1:24:17,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:04 | 200 |  156.550597ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 965/8417 [10:33<1:24:32,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:05 | 200 |  144.380079ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 966/8417 [10:33<1:24:43,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:05 | 200 |  141.568789ms |       127.0.0.1 | POST     "/api/chat"

 11%|█▏        | 967/8417 [10:34<1:24:11,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:06 | 200 |  163.636868ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 968/8417 [10:35<1:24:52,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:07 | 200 |  179.006154ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 969/8417 [10:35<1:25:40,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:07 | 200 |  117.419685ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 970/8417 [10:36<1:23:58,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:08 | 200 |  120.657508ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 971/8417 [10:37<1:22:49,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:09 | 200 |  180.354983ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 972/8417 [10:37<1:24:35,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:09 | 200 |  146.886538ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 973/8417 [10:38<1:24:25,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:10 | 200 |  143.024406ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 974/8417 [10:39<1:24:40,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:11 | 200 |  173.217838ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 975/8417 [10:39<1:25:41,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:12 | 200 |    141.2306ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 976/8417 [10:40<1:25:02,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:12 | 200 |  147.400169ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 977/8417 [10:41<1:25:24,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:13 | 200 |  150.175381ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 978/8417 [10:41<1:25:09,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:14 | 200 |   137.51132ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 979/8417 [10:42<1:25:18,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:14 | 200 |  191.084145ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 980/8417 [10:43<1:27:16,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:15 | 200 |  181.669624ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 981/8417 [10:44<1:27:50,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:16 | 200 |  144.360414ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 982/8417 [10:44<1:26:28,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:16 | 200 |  147.002608ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 983/8417 [10:45<1:25:46,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:17 | 200 |  142.946813ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 984/8417 [10:46<1:24:42,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:18 | 200 |  145.028782ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 985/8417 [10:46<1:24:32,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:18 | 200 |   139.10696ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 986/8417 [10:47<1:23:35,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:19 | 200 |   126.76151ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 987/8417 [10:48<1:22:45,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:20 | 200 |  173.685403ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 988/8417 [10:48<1:23:58,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:20 | 200 |  180.489036ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 989/8417 [10:49<1:26:04,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:21 | 200 |  147.661953ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 990/8417 [10:50<1:25:45,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:22 | 200 |  143.164381ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 991/8417 [10:50<1:25:24,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:23 | 200 |   139.46112ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 992/8417 [10:51<1:24:31,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:23 | 200 |  138.564979ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 993/8417 [10:52<1:23:44,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:24 | 200 |   155.81421ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 994/8417 [10:52<1:24:57,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:25 | 200 |  143.536528ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 995/8417 [10:53<1:24:47,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:25 | 200 |  140.257415ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 996/8417 [10:54<1:24:14,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:26 | 200 |  140.919203ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 997/8417 [10:54<1:23:52,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:27 | 200 |  140.468987ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 998/8417 [10:55<1:23:56,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:27 | 200 |  162.163195ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 999/8417 [10:56<1:24:15,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:28 | 200 |  140.004188ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1000/8417 [10:57<1:23:57,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:29 | 200 |   144.27953ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1001/8417 [10:57<1:23:42,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:29 | 200 |  155.992485ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1002/8417 [10:58<1:24:30,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:30 | 200 |  185.143174ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1003/8417 [10:59<1:25:41,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:31 | 200 |  151.617884ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1004/8417 [10:59<1:25:22,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:31 | 200 |  143.356592ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1005/8417 [11:00<1:24:38,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:32 | 200 |  147.723798ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1006/8417 [11:01<1:24:39,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:33 | 200 |  117.183885ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1007/8417 [11:01<1:23:17,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:33 | 200 |  114.436379ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1008/8417 [11:02<1:22:11,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:34 | 200 |  150.159555ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1009/8417 [11:03<1:23:07,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:35 | 200 |  170.927026ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1010/8417 [11:03<1:24:07,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:36 | 200 |  174.025093ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1011/8417 [11:04<1:25:33,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:36 | 200 |  144.932995ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1012/8417 [11:05<1:25:19,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:37 | 200 |  148.371534ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1013/8417 [11:05<1:25:06,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:38 | 200 |  139.179985ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1014/8417 [11:06<1:24:31,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:38 | 200 |  142.564606ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1015/8417 [11:07<1:24:07,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:39 | 200 |  153.592186ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1016/8417 [11:07<1:24:32,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:40 | 200 |  139.693677ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1017/8417 [11:08<1:24:20,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:40 | 200 |  145.461163ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1018/8417 [11:09<1:25:09,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:41 | 200 |  159.167425ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1019/8417 [11:10<1:25:44,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:42 | 200 |  182.983936ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1020/8417 [11:10<1:27:47,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:42 | 200 |  146.247749ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1021/8417 [11:11<1:26:36,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:43 | 200 |  127.144119ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1022/8417 [11:12<1:24:39,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:44 | 200 |  143.053186ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1023/8417 [11:12<1:24:27,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:44 | 200 |  168.491271ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1024/8417 [11:13<1:25:03,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:45 | 200 |  146.758304ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1025/8417 [11:14<1:25:54,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:46 | 200 |  142.206463ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1026/8417 [11:14<1:25:56,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:47 | 200 |  157.277791ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1027/8417 [11:15<1:26:07,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:47 | 200 |  176.730749ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1028/8417 [11:16<1:26:36,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:48 | 200 |  143.139311ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1029/8417 [11:17<1:26:03,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:49 | 200 |  148.509994ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1030/8417 [11:17<1:25:23,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:49 | 200 |  141.950513ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1031/8417 [11:18<1:25:29,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:50 | 200 |  134.921672ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1032/8417 [11:19<1:24:03,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:51 | 200 |  137.740076ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1033/8417 [11:19<1:23:49,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:51 | 200 |  157.413213ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1034/8417 [11:20<1:23:52,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:52 | 200 |  112.406267ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1035/8417 [11:21<1:22:31,  1.49it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:53 | 200 |  118.748263ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1036/8417 [11:21<1:22:13,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:53 | 200 |  143.749103ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1037/8417 [11:22<1:22:15,  1.50it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:54 | 200 |  171.496237ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1038/8417 [11:23<1:23:38,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:55 | 200 |  172.705249ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1039/8417 [11:23<1:24:46,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:55 | 200 |  145.062464ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1040/8417 [11:24<1:25:09,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:56 | 200 |  144.777676ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1041/8417 [11:25<1:24:41,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:57 | 200 |  137.871257ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1042/8417 [11:25<1:24:20,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:58 | 200 |  143.434355ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1043/8417 [11:26<1:23:56,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:58 | 200 |  158.348194ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1044/8417 [11:27<1:24:26,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:35:59 | 200 |  132.226808ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1045/8417 [11:27<1:23:49,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:00 | 200 |  140.505424ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1046/8417 [11:28<1:23:16,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:00 | 200 |  163.812271ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1047/8417 [11:29<1:24:18,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:01 | 200 |  177.006257ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1048/8417 [11:30<1:25:11,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:02 | 200 |  151.780395ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1049/8417 [11:30<1:24:41,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:02 | 200 |  142.909794ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1050/8417 [11:31<1:24:01,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:03 | 200 |  145.568338ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1051/8417 [11:32<1:24:10,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:04 | 200 |  143.238757ms |       127.0.0.1 | POST     "/api/chat"

 12%|█▏        | 1052/8417 [11:32<1:24:17,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:04 | 200 |  140.584236ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1053/8417 [11:33<1:24:07,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:05 | 200 |  155.707932ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1054/8417 [11:34<1:24:34,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:06 | 200 |  183.108788ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1055/8417 [11:34<1:26:22,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:06 | 200 |   118.17556ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1056/8417 [11:35<1:24:56,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:07 | 200 |  143.062396ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1057/8417 [11:36<1:23:50,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:08 | 200 |  140.034735ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1058/8417 [11:36<1:23:25,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:08 | 200 |  141.503345ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1059/8417 [11:37<1:23:07,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:09 | 200 |  137.154374ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1060/8417 [11:38<1:22:47,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:10 | 200 |  155.776918ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1061/8417 [11:38<1:23:51,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:11 | 200 |  157.761527ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1062/8417 [11:39<1:25:09,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:11 | 200 |  138.987192ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1063/8417 [11:40<1:24:31,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:12 | 200 |  141.320743ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1064/8417 [11:41<1:24:07,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:13 | 200 |  115.752682ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1065/8417 [11:41<1:23:12,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:13 | 200 |  141.670588ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1066/8417 [11:42<1:23:05,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:14 | 200 |  176.225427ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1067/8417 [11:43<1:24:23,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:15 | 200 |  147.144979ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1068/8417 [11:43<1:24:28,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:15 | 200 |  140.177551ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1069/8417 [11:44<1:23:49,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:16 | 200 |  144.031909ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1070/8417 [11:45<1:24:17,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:17 | 200 |  168.985538ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1071/8417 [11:45<1:27:43,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:18 | 200 |  150.118011ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1072/8417 [11:46<1:27:36,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:18 | 200 |  139.701996ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1073/8417 [11:47<1:26:13,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:19 | 200 |   177.60079ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1074/8417 [11:48<1:26:23,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:20 | 200 |  135.612997ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1075/8417 [11:48<1:25:56,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:20 | 200 |  171.756278ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1076/8417 [11:49<1:27:27,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:21 | 200 |  182.629025ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1077/8417 [11:50<1:27:55,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:22 | 200 |  144.275237ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1078/8417 [11:50<1:26:25,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:22 | 200 |   152.63041ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1079/8417 [11:51<1:26:06,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:23 | 200 |  136.982539ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1080/8417 [11:52<1:24:38,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:24 | 200 |  142.276269ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1081/8417 [11:52<1:24:05,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:25 | 200 |  154.581581ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1082/8417 [11:53<1:24:15,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:25 | 200 |  114.342328ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1083/8417 [11:54<1:22:45,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:26 | 200 |  141.388115ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1084/8417 [11:54<1:23:20,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:27 | 200 |  157.965942ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1085/8417 [11:55<1:24:05,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:27 | 200 |  185.116523ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1086/8417 [11:56<1:25:07,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:28 | 200 |  117.010065ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1087/8417 [11:57<1:23:43,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:29 | 200 |  152.765678ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1088/8417 [11:57<1:24:23,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:29 | 200 |  139.652918ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1089/8417 [11:58<1:24:49,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:30 | 200 |  143.392009ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1090/8417 [11:59<1:24:35,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:31 | 200 |  140.298397ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1091/8417 [11:59<1:24:42,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:31 | 200 |  163.926239ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1092/8417 [12:00<1:25:06,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:32 | 200 |  152.235659ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1093/8417 [12:01<1:24:58,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:33 | 200 |  144.869408ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1094/8417 [12:01<1:24:53,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:34 | 200 |  140.408815ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1095/8417 [12:02<1:24:07,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:34 | 200 |  152.605653ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1096/8417 [12:03<1:23:57,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:35 | 200 |  179.433266ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1097/8417 [12:03<1:25:27,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:36 | 200 |  146.926639ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1098/8417 [12:04<1:26:04,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:36 | 200 |  145.603053ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1099/8417 [12:05<1:25:17,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:37 | 200 |  138.092491ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1100/8417 [12:06<1:24:07,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:38 | 200 |  143.362409ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1101/8417 [12:06<1:24:05,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:38 | 200 |   154.59948ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1102/8417 [12:07<1:24:42,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:39 | 200 |  145.646818ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1103/8417 [12:08<1:24:31,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:40 | 200 |  143.259253ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1104/8417 [12:08<1:24:03,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:40 | 200 |  143.001144ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1105/8417 [12:09<1:24:43,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:41 | 200 |  141.558748ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1106/8417 [12:10<1:24:08,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:42 | 200 |   142.81867ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1107/8417 [12:10<1:24:01,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:43 | 200 |  138.851889ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1108/8417 [12:11<1:24:24,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:43 | 200 |  158.235447ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1109/8417 [12:12<1:24:25,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:44 | 200 |  180.053579ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1110/8417 [12:13<1:25:41,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:45 | 200 |  121.255345ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1111/8417 [12:13<1:26:02,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:45 | 200 |   125.71535ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1112/8417 [12:14<1:24:09,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:46 | 200 |  143.637274ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1113/8417 [12:15<1:23:50,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:47 | 200 |   168.43702ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1114/8417 [12:15<1:24:43,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:47 | 200 |  149.882912ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1115/8417 [12:16<1:24:21,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:48 | 200 |  115.340754ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1116/8417 [12:17<1:22:30,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:49 | 200 |  182.518546ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1117/8417 [12:17<1:28:00,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:50 | 200 |  192.307453ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1118/8417 [12:18<1:29:34,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:50 | 200 |  152.101836ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1119/8417 [12:19<1:28:38,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:51 | 200 |  113.489212ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1120/8417 [12:20<1:25:57,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:52 | 200 |  142.679618ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1121/8417 [12:20<1:25:41,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:52 | 200 |  170.762749ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1122/8417 [12:21<1:25:45,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:53 | 200 |  143.276283ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1123/8417 [12:22<1:24:47,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:54 | 200 |  137.202117ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1124/8417 [12:22<1:24:03,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:54 | 200 |  161.181552ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1125/8417 [12:23<1:24:36,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:55 | 200 |  179.545005ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1126/8417 [12:24<1:25:54,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:56 | 200 |  146.176401ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1127/8417 [12:25<1:26:51,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:57 | 200 |  118.020855ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1128/8417 [12:25<1:25:41,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:57 | 200 |  144.315247ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1129/8417 [12:26<1:24:48,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:58 | 200 |  169.228559ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1130/8417 [12:27<1:25:13,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:59 | 200 |  152.073991ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1131/8417 [12:27<1:25:00,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:36:59 | 200 |  150.995448ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1132/8417 [12:28<1:25:49,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:00 | 200 |  143.785446ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1133/8417 [12:29<1:25:04,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:01 | 200 |  150.457666ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1134/8417 [12:29<1:25:34,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:02 | 200 |  140.155908ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1135/8417 [12:30<1:24:28,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:02 | 200 |  138.526832ms |       127.0.0.1 | POST     "/api/chat"

 13%|█▎        | 1136/8417 [12:31<1:23:26,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:03 | 200 |  161.841841ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1137/8417 [12:31<1:24:12,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:04 | 200 |  179.862572ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1138/8417 [12:32<1:25:15,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:04 | 200 |  136.200439ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1139/8417 [12:33<1:24:42,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:05 | 200 |  147.099207ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1140/8417 [12:34<1:24:17,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:06 | 200 |  141.392702ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1141/8417 [12:34<1:24:26,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:06 | 200 |   116.45939ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1142/8417 [12:35<1:24:11,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:07 | 200 |  118.482426ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1143/8417 [12:36<1:22:24,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:08 | 200 |  168.646834ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1144/8417 [12:36<1:23:15,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:08 | 200 |  177.263715ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1145/8417 [12:37<1:24:04,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:09 | 200 |  146.402306ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1146/8417 [12:38<1:23:54,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:10 | 200 |  140.071554ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1147/8417 [12:38<1:23:11,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:10 | 200 |  166.739954ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1148/8417 [12:39<1:24:34,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:11 | 200 |  143.911697ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1149/8417 [12:40<1:23:49,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:12 | 200 |  143.184694ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1150/8417 [12:40<1:23:23,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:13 | 200 |  145.699974ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1151/8417 [12:41<1:23:10,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:13 | 200 |  111.881523ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1152/8417 [12:42<1:21:44,  1.48it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:14 | 200 |  179.780468ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1153/8417 [12:42<1:23:17,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:15 | 200 |  154.862731ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1154/8417 [12:43<1:23:32,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:15 | 200 |  143.098869ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1155/8417 [12:44<1:23:00,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:16 | 200 |  141.853248ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1156/8417 [12:45<1:23:22,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:17 | 200 |  143.975832ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▎        | 1157/8417 [12:45<1:23:08,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:17 | 200 |  137.870577ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1158/8417 [12:46<1:23:05,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:18 | 200 |  141.855863ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1159/8417 [12:47<1:23:14,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:19 | 200 |   155.13224ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1160/8417 [12:47<1:23:30,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:19 | 200 |  187.203587ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1161/8417 [12:48<1:25:13,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:20 | 200 |  149.501502ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1162/8417 [12:49<1:26:24,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:21 | 200 |  147.868944ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1163/8417 [12:50<1:26:01,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:22 | 200 |  151.687991ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1164/8417 [12:50<1:25:42,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:22 | 200 |  134.390705ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1165/8417 [12:51<1:24:08,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:23 | 200 |  129.916949ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1166/8417 [12:52<1:23:09,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:24 | 200 |  180.871447ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1167/8417 [12:52<1:24:16,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:24 | 200 |  116.147452ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1168/8417 [12:53<1:23:52,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:25 | 200 |  143.317482ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1169/8417 [12:54<1:23:39,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:26 | 200 |  143.937377ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1170/8417 [12:54<1:23:44,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:26 | 200 |  137.990524ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1171/8417 [12:55<1:23:49,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:27 | 200 |  145.182489ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1172/8417 [12:56<1:23:24,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:28 | 200 |  124.505241ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1173/8417 [12:56<1:22:20,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:28 | 200 |  147.894728ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1174/8417 [12:57<1:22:16,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:29 | 200 |   174.46219ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1175/8417 [12:58<1:23:28,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:30 | 200 |  160.786055ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1176/8417 [12:58<1:23:30,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:31 | 200 |  141.847814ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1177/8417 [12:59<1:24:01,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:31 | 200 |  147.470996ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1178/8417 [13:00<1:23:42,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:32 | 200 |  143.652756ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1179/8417 [13:01<1:23:26,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:33 | 200 |  138.284324ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1180/8417 [13:01<1:23:39,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:33 | 200 |  141.436187ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1181/8417 [13:02<1:23:43,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:34 | 200 |  159.286293ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1182/8417 [13:03<1:24:10,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:35 | 200 |  175.555436ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1183/8417 [13:03<1:25:06,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:35 | 200 |  138.478335ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1184/8417 [13:04<1:24:29,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:36 | 200 |  118.060439ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1185/8417 [13:05<1:22:46,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:37 | 200 |  142.098021ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1186/8417 [13:05<1:22:27,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:37 | 200 |  139.590263ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1187/8417 [13:06<1:22:41,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:38 | 200 |  149.417206ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1188/8417 [13:07<1:22:23,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:39 | 200 |  173.086099ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1189/8417 [13:07<1:24:01,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:40 | 200 |   145.69256ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1190/8417 [13:08<1:23:41,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:40 | 200 |  145.941675ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1191/8417 [13:09<1:23:59,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:41 | 200 |  143.420519ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1192/8417 [13:10<1:23:32,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:42 | 200 |  141.521486ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1193/8417 [13:10<1:23:47,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:42 | 200 |  140.945882ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1194/8417 [13:11<1:23:03,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:43 | 200 |  144.832848ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1195/8417 [13:12<1:22:56,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:44 | 200 |   141.37484ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1196/8417 [13:12<1:23:07,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:44 | 200 |  153.019002ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1197/8417 [13:13<1:23:14,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:45 | 200 |  182.930627ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1198/8417 [13:14<1:25:19,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:46 | 200 |  144.517561ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1199/8417 [13:14<1:25:23,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:47 | 200 |  150.189438ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1200/8417 [13:15<1:24:45,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:47 | 200 |  137.774372ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1201/8417 [13:16<1:23:47,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:48 | 200 |  149.459616ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1202/8417 [13:17<1:24:00,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:49 | 200 |  158.648674ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1203/8417 [13:17<1:24:07,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:49 | 200 |  176.390858ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1204/8417 [13:18<1:25:01,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:50 | 200 |   147.52703ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1205/8417 [13:19<1:24:26,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:51 | 200 |  170.651594ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1206/8417 [13:19<1:25:06,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:51 | 200 |    135.0772ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1207/8417 [13:20<1:24:34,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:52 | 200 |  177.962058ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1208/8417 [13:21<1:26:17,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:53 | 200 |  136.394385ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1209/8417 [13:22<1:25:02,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:54 | 200 |  179.436256ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1210/8417 [13:22<1:25:31,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:54 | 200 |  157.504824ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1211/8417 [13:23<1:25:14,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:55 | 200 |  144.087551ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1212/8417 [13:24<1:24:19,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:56 | 200 |  149.824296ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1213/8417 [13:24<1:24:07,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:56 | 200 |   126.06609ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1214/8417 [13:25<1:23:14,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:57 | 200 |  173.283818ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1215/8417 [13:26<1:23:51,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:58 | 200 |  139.762424ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1216/8417 [13:26<1:23:57,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:59 | 200 |  173.630701ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1217/8417 [13:27<1:25:26,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:37:59 | 200 |   153.06208ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1218/8417 [13:28<1:26:06,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:00 | 200 |  146.102333ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1219/8417 [13:29<1:25:29,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:01 | 200 |  146.605779ms |       127.0.0.1 | POST     "/api/chat"

 14%|█▍        | 1220/8417 [13:29<1:26:12,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:01 | 200 |  139.187542ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1221/8417 [13:30<1:25:21,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:02 | 200 |  142.746508ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1222/8417 [13:31<1:23:59,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:03 | 200 |  143.531645ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1223/8417 [13:31<1:23:30,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:03 | 200 |  127.012218ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1224/8417 [13:32<1:22:36,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:04 | 200 |  171.741399ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1225/8417 [13:33<1:23:26,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:05 | 200 |  164.890118ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1226/8417 [13:33<1:23:59,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:06 | 200 |  146.639685ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1227/8417 [13:34<1:23:52,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:06 | 200 |  144.564468ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1228/8417 [13:35<1:24:14,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:07 | 200 |  140.994342ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1229/8417 [13:36<1:23:38,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:08 | 200 |  143.546197ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1230/8417 [13:36<1:22:58,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:08 | 200 |  155.417548ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1231/8417 [13:37<1:22:58,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:09 | 200 |  174.079487ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1232/8417 [13:38<1:23:46,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:10 | 200 |  148.640963ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1233/8417 [13:38<1:24:11,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:10 | 200 |   148.27039ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1234/8417 [13:39<1:24:42,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:11 | 200 |  119.205474ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1235/8417 [13:40<1:23:15,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:12 | 200 |  115.143412ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1236/8417 [13:40<1:22:02,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:13 | 200 |  147.978694ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1237/8417 [13:41<1:22:28,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:13 | 200 |  145.873407ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1238/8417 [13:42<1:22:30,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:14 | 200 |  179.357567ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1239/8417 [13:43<1:23:42,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:15 | 200 |  165.195258ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1240/8417 [13:43<1:25:06,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:15 | 200 |  145.899615ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1241/8417 [13:44<1:24:40,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:16 | 200 |  144.602979ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1242/8417 [13:45<1:25:31,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:17 | 200 |  139.639281ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1243/8417 [13:45<1:25:06,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:18 | 200 |  136.532395ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1244/8417 [13:46<1:23:51,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:18 | 200 |  156.666256ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1245/8417 [13:47<1:23:23,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:19 | 200 |  171.199462ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1246/8417 [13:47<1:23:50,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:20 | 200 |  151.963311ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1247/8417 [13:48<1:23:25,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:20 | 200 |   150.63317ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1248/8417 [13:49<1:23:45,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:21 | 200 |  142.999005ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1249/8417 [13:50<1:23:41,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:22 | 200 |  145.489859ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1250/8417 [13:50<1:23:29,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:22 | 200 |  156.928567ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1251/8417 [13:51<1:23:45,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:23 | 200 |  183.087919ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1252/8417 [13:52<1:26:23,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:24 | 200 |  170.023691ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1253/8417 [13:52<1:26:36,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:25 | 200 |   131.80698ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1254/8417 [13:53<1:25:00,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:25 | 200 |  143.797079ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1255/8417 [13:54<1:24:05,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:26 | 200 |  187.441287ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1256/8417 [13:55<1:25:27,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:27 | 200 |  175.434805ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1257/8417 [13:55<1:26:01,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:27 | 200 |  143.133571ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1258/8417 [13:56<1:24:47,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:28 | 200 |  149.923549ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1259/8417 [13:57<1:24:11,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:29 | 200 |  116.013022ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1260/8417 [13:57<1:22:53,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:29 | 200 |  114.157555ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1261/8417 [13:58<1:21:38,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:30 | 200 |  179.172914ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▍        | 1262/8417 [13:59<1:23:41,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:31 | 200 |  157.266489ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1263/8417 [13:59<1:24:03,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:32 | 200 |   142.60732ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1264/8417 [14:00<1:23:44,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:32 | 200 |  142.222753ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1265/8417 [14:01<1:23:49,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:33 | 200 |  160.228187ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1266/8417 [14:02<1:24:37,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:34 | 200 |  181.215793ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1267/8417 [14:02<1:25:36,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:34 | 200 |  145.676059ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1268/8417 [14:03<1:25:21,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:35 | 200 |  146.185569ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1269/8417 [14:04<1:24:46,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:36 | 200 |  138.353396ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1270/8417 [14:04<1:24:04,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:37 | 200 |  141.922144ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1271/8417 [14:05<1:23:30,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:37 | 200 |  156.768142ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1272/8417 [14:06<1:23:09,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:38 | 200 |  178.822377ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1273/8417 [14:07<1:24:14,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:39 | 200 |  140.662199ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1274/8417 [14:07<1:24:20,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:39 | 200 |  144.694103ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1275/8417 [14:08<1:24:24,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:40 | 200 |  144.232349ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1276/8417 [14:09<1:24:33,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:41 | 200 |  146.825528ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1277/8417 [14:09<1:25:00,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:42 | 200 |   180.60851ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1278/8417 [14:10<1:25:56,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:42 | 200 |  141.580702ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1279/8417 [14:11<1:24:32,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:43 | 200 |  120.525088ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1280/8417 [14:12<1:23:01,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:44 | 200 |  142.560179ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1281/8417 [14:12<1:23:05,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:44 | 200 |  178.512113ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1282/8417 [14:13<1:24:30,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:45 | 200 |   146.70354ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1283/8417 [14:14<1:24:15,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:46 | 200 |  146.883491ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1284/8417 [14:14<1:24:24,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:47 | 200 |  144.326502ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1285/8417 [14:15<1:24:20,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:47 | 200 |  140.488373ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1286/8417 [14:16<1:23:51,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:48 | 200 |  140.584173ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1287/8417 [14:16<1:23:23,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:49 | 200 |  113.238354ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1288/8417 [14:17<1:21:57,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:49 | 200 |  175.406595ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1289/8417 [14:18<1:23:53,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:50 | 200 |  185.927081ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1290/8417 [14:19<1:24:58,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:51 | 200 |  157.456367ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1291/8417 [14:19<1:25:08,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:51 | 200 |   146.84868ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1292/8417 [14:20<1:24:20,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:52 | 200 |  141.846787ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1293/8417 [14:21<1:23:27,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:53 | 200 |  125.069359ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1294/8417 [14:21<1:22:25,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:54 | 200 |   164.49221ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1295/8417 [14:22<1:23:08,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:54 | 200 |  182.260701ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1296/8417 [14:23<1:24:24,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:55 | 200 |  138.882509ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1297/8417 [14:24<1:25:28,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:56 | 200 |  143.747889ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1298/8417 [14:24<1:24:40,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:56 | 200 |   147.33285ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1299/8417 [14:25<1:23:51,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:57 | 200 |  144.906427ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1300/8417 [14:26<1:22:57,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:58 | 200 |  182.280378ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1301/8417 [14:26<1:24:58,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:59 | 200 |  150.499626ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1302/8417 [14:27<1:24:36,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:38:59 | 200 |  144.831626ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1303/8417 [14:28<1:24:06,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:00 | 200 |  157.089057ms |       127.0.0.1 | POST     "/api/chat"

 15%|█▌        | 1304/8417 [14:29<1:24:02,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:01 | 200 |  180.585412ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1305/8417 [14:29<1:24:45,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:01 | 200 |  136.131508ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1306/8417 [14:30<1:23:22,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:02 | 200 |     120.914ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1307/8417 [14:31<1:21:54,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:03 | 200 |  140.215803ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1308/8417 [14:31<1:21:42,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:03 | 200 |  179.422122ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1309/8417 [14:32<1:22:40,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:04 | 200 |  119.415102ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1310/8417 [14:33<1:21:04,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:05 | 200 |  143.234206ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1311/8417 [14:33<1:21:42,  1.45it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:05 | 200 |  166.794909ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1312/8417 [14:34<1:22:59,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:06 | 200 |  143.818637ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1313/8417 [14:35<1:22:52,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:07 | 200 |  141.501032ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1314/8417 [14:35<1:22:37,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:08 | 200 |  170.337745ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1315/8417 [14:36<1:23:48,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:08 | 200 |  148.556766ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1316/8417 [14:37<1:23:25,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:09 | 200 |  142.702933ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1317/8417 [14:38<1:23:19,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:10 | 200 |   141.53309ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1318/8417 [14:38<1:22:57,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:10 | 200 |   144.96876ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1319/8417 [14:39<1:24:01,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:11 | 200 |  158.577293ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1320/8417 [14:40<1:24:01,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:12 | 200 |   177.90617ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1321/8417 [14:40<1:24:53,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:13 | 200 |  143.749459ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1322/8417 [14:41<1:23:52,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:13 | 200 |  141.451735ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1323/8417 [14:42<1:23:26,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:14 | 200 |  113.277706ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1324/8417 [14:43<1:22:06,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:15 | 200 |  115.495483ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1325/8417 [14:43<1:20:29,  1.47it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:15 | 200 |  177.261463ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1326/8417 [14:44<1:22:16,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:16 | 200 |  146.773457ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1327/8417 [14:45<1:22:53,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:17 | 200 |  144.702418ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1328/8417 [14:45<1:22:50,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:17 | 200 |  144.205968ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1329/8417 [14:46<1:22:24,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:18 | 200 |  156.306055ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1330/8417 [14:47<1:22:22,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:19 | 200 |  144.363636ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1331/8417 [14:47<1:22:38,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:20 | 200 |  145.124408ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1332/8417 [14:48<1:23:13,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:20 | 200 |  166.653968ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1333/8417 [14:49<1:24:14,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:21 | 200 |  146.352981ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1334/8417 [14:50<1:23:26,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:22 | 200 |  115.141757ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1335/8417 [14:50<1:21:46,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:22 | 200 |  140.495924ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1336/8417 [14:51<1:21:44,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:23 | 200 |  168.339782ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1337/8417 [14:52<1:23:53,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:24 | 200 |  141.593336ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1338/8417 [14:52<1:23:38,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:24 | 200 |  146.831486ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1339/8417 [14:53<1:23:08,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:25 | 200 |  147.455153ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1340/8417 [14:54<1:24:19,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:26 | 200 |  117.550089ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1341/8417 [14:54<1:23:25,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:27 | 200 |  181.998695ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1342/8417 [14:55<1:25:57,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:27 | 200 |  142.108206ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1343/8417 [14:56<1:24:46,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:28 | 200 |  166.578958ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1344/8417 [14:57<1:24:46,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:29 | 200 |   153.56416ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1345/8417 [14:57<1:25:35,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:30 | 200 |  148.198436ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1346/8417 [14:58<1:24:50,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:30 | 200 |  147.102213ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1347/8417 [14:59<1:25:00,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:31 | 200 |  138.291817ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1348/8417 [15:00<1:23:58,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:32 | 200 |   139.24645ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1349/8417 [15:00<1:23:08,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:32 | 200 |  133.022114ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1350/8417 [15:01<1:22:04,  1.44it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:33 | 200 |  154.740277ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1351/8417 [15:02<1:22:15,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:34 | 200 |  173.346684ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1352/8417 [15:02<1:23:44,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:34 | 200 |  142.646991ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1353/8417 [15:03<1:23:23,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:35 | 200 |  146.172894ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1354/8417 [15:04<1:23:35,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:36 | 200 |  136.220648ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1355/8417 [15:04<1:23:55,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:37 | 200 |  138.595027ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1356/8417 [15:05<1:22:56,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:37 | 200 |  160.223373ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1357/8417 [15:06<1:22:44,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:38 | 200 |  147.914767ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1358/8417 [15:07<1:23:28,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:39 | 200 |  152.803491ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1359/8417 [15:07<1:23:21,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:39 | 200 |  141.760405ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1360/8417 [15:08<1:23:15,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:40 | 200 |  148.806629ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1361/8417 [15:09<1:23:30,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 16%|█▌        | 1362/8417 [15:09<1:23:11,  1.41it/s]

[GIN] 2025/06/26 - 23:39:41 | 200 |  126.207693ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:42 | 200 |  185.380289ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1363/8417 [15:10<1:24:14,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:42 | 200 |  147.550041ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1364/8417 [15:11<1:24:37,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:43 | 200 |  149.845529ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1365/8417 [15:12<1:24:20,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:44 | 200 |  141.243845ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1366/8417 [15:12<1:23:54,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:44 | 200 |  141.787954ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▌        | 1367/8417 [15:13<1:23:53,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:45 | 200 |  167.193604ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1368/8417 [15:14<1:24:08,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:46 | 200 |  118.431445ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1369/8417 [15:14<1:23:14,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:47 | 200 |  146.785609ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1370/8417 [15:15<1:23:17,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:47 | 200 |  143.703906ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1371/8417 [15:16<1:22:39,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:48 | 200 |  146.272225ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1372/8417 [15:17<1:22:45,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:49 | 200 |  157.870536ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1373/8417 [15:17<1:23:17,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:49 | 200 |  184.455364ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1374/8417 [15:18<1:24:31,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:50 | 200 |  143.083663ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1375/8417 [15:19<1:24:13,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:51 | 200 |  149.387311ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1376/8417 [15:19<1:24:54,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:52 | 200 |  150.873942ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1377/8417 [15:20<1:24:27,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:52 | 200 |  158.559893ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1378/8417 [15:21<1:23:57,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:53 | 200 |  181.047969ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1379/8417 [15:22<1:25:15,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:54 | 200 |  145.649965ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1380/8417 [15:22<1:24:45,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:54 | 200 |  141.121105ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1381/8417 [15:23<1:23:46,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:55 | 200 |  134.592043ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1382/8417 [15:24<1:22:45,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:56 | 200 |  143.935597ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1383/8417 [15:24<1:23:26,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:57 | 200 |  146.110381ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1384/8417 [15:25<1:23:05,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:57 | 200 |  139.685043ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1385/8417 [15:26<1:22:43,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:58 | 200 |  174.660165ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1386/8417 [15:27<1:25:57,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:39:59 | 200 |  156.737754ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1387/8417 [15:27<1:26:17,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:00 | 200 |  156.456429ms |       127.0.0.1 | POST     "/api/chat"

 16%|█▋        | 1388/8417 [15:28<1:26:36,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:00 | 200 |    150.5637ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1389/8417 [15:29<1:26:06,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:01 | 200 |  144.673508ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1390/8417 [15:30<1:24:23,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:02 | 200 |  136.576752ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1391/8417 [15:30<1:23:54,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:02 | 200 |  161.904697ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1392/8417 [15:31<1:23:55,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:03 | 200 |  146.468611ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1393/8417 [15:32<1:24:05,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:04 | 200 |  143.897269ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1394/8417 [15:32<1:23:22,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:05 | 200 |  141.080303ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1395/8417 [15:33<1:23:05,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:05 | 200 |  142.851173ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1396/8417 [15:34<1:22:20,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:06 | 200 |  157.668063ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1397/8417 [15:35<1:23:22,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:07 | 200 |  183.763381ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1398/8417 [15:35<1:24:16,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:07 | 200 |  149.547547ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1399/8417 [15:36<1:24:00,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:08 | 200 |  144.998921ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1400/8417 [15:37<1:24:07,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:09 | 200 |  143.795753ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1401/8417 [15:37<1:24:35,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:10 | 200 |  143.995757ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1402/8417 [15:38<1:24:10,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:10 | 200 |  118.951069ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1403/8417 [15:39<1:23:56,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:11 | 200 |  141.058668ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1404/8417 [15:40<1:23:37,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:12 | 200 |  146.100826ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1405/8417 [15:40<1:23:01,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:12 | 200 |  169.507637ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1406/8417 [15:41<1:23:33,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:13 | 200 |  160.785748ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1407/8417 [15:42<1:23:35,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:14 | 200 |  144.847837ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1408/8417 [15:42<1:23:03,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:15 | 200 |  143.318076ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1409/8417 [15:43<1:22:35,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:15 | 200 |  162.226424ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1410/8417 [15:44<1:23:09,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:16 | 200 |  145.778804ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1411/8417 [15:45<1:23:16,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:17 | 200 |  137.559353ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1412/8417 [15:45<1:22:55,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:17 | 200 |  159.891998ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1413/8417 [15:46<1:23:08,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:18 | 200 |  182.688262ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1414/8417 [15:47<1:23:57,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:19 | 200 |  143.578571ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1415/8417 [15:47<1:23:28,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:20 | 200 |  149.475109ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1416/8417 [15:48<1:23:49,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:20 | 200 |  145.598992ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1417/8417 [15:49<1:24:07,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:21 | 200 |   143.11562ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1418/8417 [15:50<1:24:02,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:22 | 200 |  178.634755ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1419/8417 [15:50<1:24:44,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:22 | 200 |  152.720022ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1420/8417 [15:51<1:24:16,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:23 | 200 |  146.012021ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1421/8417 [15:52<1:23:49,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:24 | 200 |  140.402778ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1422/8417 [15:52<1:23:19,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:25 | 200 |  118.929432ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1423/8417 [15:53<1:22:24,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:25 | 200 |   182.03544ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1424/8417 [15:54<1:24:01,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:26 | 200 |  146.944393ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1425/8417 [15:55<1:23:37,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:27 | 200 |  144.371933ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1426/8417 [15:55<1:24:22,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:27 | 200 |  145.150895ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1427/8417 [15:56<1:23:53,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:28 | 200 |  135.262003ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1428/8417 [15:57<1:23:17,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:29 | 200 |  162.953298ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1429/8417 [15:58<1:24:06,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:30 | 200 |  140.848743ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1430/8417 [15:58<1:24:52,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:30 | 200 |  156.682838ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1431/8417 [15:59<1:26:16,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:31 | 200 |  147.669356ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1432/8417 [16:00<1:26:20,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:32 | 200 |  139.902158ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1433/8417 [16:00<1:24:51,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:33 | 200 |  158.511201ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1434/8417 [16:01<1:24:47,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:33 | 200 |  140.299966ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1435/8417 [16:02<1:23:15,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:34 | 200 |  146.701317ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1436/8417 [16:03<1:22:47,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:35 | 200 |  117.826255ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1437/8417 [16:03<1:21:16,  1.43it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:35 | 200 |   115.81934ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1438/8417 [16:04<1:19:50,  1.46it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:36 | 200 |  181.147095ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1439/8417 [16:05<1:21:55,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:37 | 200 |  172.718942ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1440/8417 [16:05<1:22:56,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:37 | 200 |  116.487302ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1441/8417 [16:06<1:22:20,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:38 | 200 |  143.031067ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1442/8417 [16:07<1:21:52,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:39 | 200 |  141.518145ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1443/8417 [16:07<1:21:43,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:40 | 200 |  141.138551ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1444/8417 [16:08<1:21:39,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:40 | 200 |  142.917478ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1445/8417 [16:09<1:22:15,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:41 | 200 |   147.01036ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1446/8417 [16:10<1:21:57,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:42 | 200 |  159.550458ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1447/8417 [16:10<1:22:27,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:42 | 200 |  147.947791ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1448/8417 [16:11<1:22:09,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:43 | 200 |  144.957742ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1449/8417 [16:12<1:22:09,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:44 | 200 |  143.313352ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1450/8417 [16:12<1:22:09,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:45 | 200 |  160.702053ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1451/8417 [16:13<1:23:07,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:45 | 200 |  155.533593ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1452/8417 [16:14<1:23:20,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:46 | 200 |  146.182458ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1453/8417 [16:15<1:22:37,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:47 | 200 |  144.113448ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1454/8417 [16:15<1:22:26,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:47 | 200 |  136.248067ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1455/8417 [16:16<1:21:45,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:48 | 200 |  141.585264ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1456/8417 [16:17<1:22:07,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:49 | 200 |  136.634973ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1457/8417 [16:17<1:21:25,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:50 | 200 |  161.922905ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1458/8417 [16:18<1:23:18,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:50 | 200 |  153.002299ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1459/8417 [16:19<1:23:24,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:51 | 200 |  119.080697ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1460/8417 [16:20<1:21:54,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:52 | 200 |  138.998657ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1461/8417 [16:20<1:21:46,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:52 | 200 |  168.249199ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1462/8417 [16:21<1:22:35,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:53 | 200 |  146.660636ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1463/8417 [16:22<1:22:21,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:54 | 200 |  148.195079ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1464/8417 [16:22<1:22:31,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:55 | 200 |  143.469439ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1465/8417 [16:23<1:22:10,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:55 | 200 |  140.207839ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1466/8417 [16:24<1:21:58,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:56 | 200 |  154.593623ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1467/8417 [16:25<1:22:36,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:57 | 200 |  180.448289ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1468/8417 [16:25<1:23:48,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:57 | 200 |  145.738319ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1469/8417 [16:26<1:23:05,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:58 | 200 |  144.995366ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1470/8417 [16:27<1:22:29,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:40:59 | 200 |  171.151129ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1471/8417 [16:27<1:23:22,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:00 | 200 |  149.292262ms |       127.0.0.1 | POST     "/api/chat"

 17%|█▋        | 1472/8417 [16:28<1:23:43,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:00 | 200 |  142.355687ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1473/8417 [16:29<1:23:37,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:01 | 200 |  139.366044ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1474/8417 [16:30<1:24:52,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 18%|█▊        | 1475/8417 [16:30<1:24:51,  1.36it/s]

[GIN] 2025/06/26 - 23:41:02 | 200 |  154.825966ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:03 | 200 |  176.908199ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1476/8417 [16:31<1:24:51,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:03 | 200 |  140.542413ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1477/8417 [16:32<1:24:09,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:04 | 200 |  146.226589ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1478/8417 [16:33<1:24:03,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:05 | 200 |  180.082521ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1479/8417 [16:33<1:24:36,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:05 | 200 |  119.298321ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1480/8417 [16:34<1:22:33,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:06 | 200 |  147.806196ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1481/8417 [16:35<1:22:51,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:07 | 200 |  137.870139ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1482/8417 [16:35<1:22:51,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:08 | 200 |  143.575649ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1483/8417 [16:36<1:23:15,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:08 | 200 |  169.565671ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1484/8417 [16:37<1:23:14,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:09 | 200 |  144.341386ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1485/8417 [16:38<1:22:27,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:10 | 200 |  146.264664ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1486/8417 [16:38<1:22:17,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:10 | 200 |  145.440972ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1487/8417 [16:39<1:23:10,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:11 | 200 |  118.325019ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1488/8417 [16:40<1:21:14,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:12 | 200 |  181.308512ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1489/8417 [16:40<1:23:24,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:13 | 200 |  170.298124ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1490/8417 [16:41<1:23:51,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:13 | 200 |  162.531752ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1491/8417 [16:42<1:24:03,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:14 | 200 |  146.100109ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1492/8417 [16:43<1:23:34,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:15 | 200 |  122.203031ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1493/8417 [16:43<1:21:46,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:15 | 200 |  141.206475ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1494/8417 [16:44<1:21:27,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:16 | 200 |    178.2693ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1495/8417 [16:45<1:22:47,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:17 | 200 |  141.746197ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1496/8417 [16:45<1:22:06,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:18 | 200 |  146.734865ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1497/8417 [16:46<1:22:51,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:18 | 200 |  162.102309ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1498/8417 [16:47<1:23:07,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:19 | 200 |  147.884193ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1499/8417 [16:48<1:22:28,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:20 | 200 |  142.204882ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1500/8417 [16:48<1:21:58,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:20 | 200 |  143.105069ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1501/8417 [16:49<1:22:42,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:21 | 200 |  145.229602ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1502/8417 [16:50<1:22:21,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:22 | 200 |  142.070589ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1503/8417 [16:50<1:21:46,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:23 | 200 |  141.209693ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1504/8417 [16:51<1:21:23,  1.42it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:23 | 200 |  143.901912ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1505/8417 [16:52<1:22:11,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:24 | 200 |  143.201773ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1506/8417 [16:53<1:21:55,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:25 | 200 |  157.598544ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1507/8417 [16:53<1:21:47,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:25 | 200 |   148.32026ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1508/8417 [16:54<1:21:35,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:26 | 200 |  141.915226ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1509/8417 [16:55<1:22:15,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:27 | 200 |  141.329582ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1510/8417 [16:55<1:21:50,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:28 | 200 |  176.607068ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1511/8417 [16:56<1:22:28,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:28 | 200 |  144.158974ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1512/8417 [16:57<1:23:09,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:29 | 200 |  151.740221ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1513/8417 [16:58<1:23:12,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:30 | 200 |  134.623293ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1514/8417 [16:58<1:22:24,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:30 | 200 |  141.039218ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1515/8417 [16:59<1:23:56,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:31 | 200 |  179.169989ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1516/8417 [17:00<1:24:54,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:32 | 200 |  153.264486ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1517/8417 [17:01<1:23:41,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:33 | 200 |  146.235754ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1518/8417 [17:01<1:23:53,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:33 | 200 |  154.649157ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1519/8417 [17:02<1:23:36,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:34 | 200 |  146.541884ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1520/8417 [17:03<1:23:02,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:35 | 200 |  138.110922ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1521/8417 [17:03<1:22:27,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:35 | 200 |  137.117831ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1522/8417 [17:04<1:22:08,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:36 | 200 |  118.501284ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1523/8417 [17:05<1:21:18,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:37 | 200 |  142.058725ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1524/8417 [17:06<1:24:21,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:38 | 200 |  137.186214ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1525/8417 [17:06<1:23:24,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:38 | 200 |  173.595014ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1526/8417 [17:07<1:24:00,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 18%|█▊        | 1527/8417 [17:08<1:23:33,  1.37it/s]

[GIN] 2025/06/26 - 23:41:39 | 200 |  155.656557ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:40 | 200 |  157.432343ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1528/8417 [17:08<1:23:38,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:41 | 200 |  148.230416ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1529/8417 [17:09<1:24:32,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:41 | 200 |  142.620578ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1530/8417 [17:10<1:23:29,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:42 | 200 |  140.867718ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1531/8417 [17:11<1:22:45,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:43 | 200 |  140.340336ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1532/8417 [17:11<1:22:09,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:43 | 200 |  144.882214ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1533/8417 [17:12<1:22:30,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:44 | 200 |  178.589012ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1534/8417 [17:13<1:23:37,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:45 | 200 |  114.565906ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1535/8417 [17:14<1:22:28,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:46 | 200 |   143.11238ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1536/8417 [17:14<1:22:51,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:46 | 200 |  166.524705ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1537/8417 [17:15<1:23:55,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:47 | 200 |  141.349057ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1538/8417 [17:16<1:23:25,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:48 | 200 |  115.578461ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1539/8417 [17:16<1:21:57,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:49 | 200 |  146.389835ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1540/8417 [17:17<1:22:55,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:49 | 200 |  155.802428ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1541/8417 [17:18<1:23:05,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:50 | 200 |  143.695287ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1542/8417 [17:19<1:22:28,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:51 | 200 |  181.643463ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1543/8417 [17:19<1:23:56,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:52 | 200 |  178.020511ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1544/8417 [17:20<1:24:29,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:52 | 200 |  175.111871ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1545/8417 [17:21<1:24:31,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:53 | 200 |  144.059683ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1546/8417 [17:22<1:23:38,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:54 | 200 |  157.649133ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1547/8417 [17:22<1:23:36,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:54 | 200 |  169.898314ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1548/8417 [17:23<1:23:53,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:55 | 200 |  150.095358ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1549/8417 [17:24<1:24:03,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:56 | 200 |  147.517316ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1550/8417 [17:24<1:23:59,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:57 | 200 |  165.207869ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1551/8417 [17:25<1:24:17,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:57 | 200 |  152.231839ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1552/8417 [17:26<1:23:49,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:58 | 200 |  156.293585ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1553/8417 [17:27<1:23:42,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:41:59 | 200 |  138.154613ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1554/8417 [17:27<1:22:55,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:00 | 200 |  140.487372ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1555/8417 [17:28<1:22:30,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:00 | 200 |   177.75366ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1556/8417 [17:29<1:24:11,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:01 | 200 |  144.447141ms |       127.0.0.1 | POST     "/api/chat"

 18%|█▊        | 1557/8417 [17:30<1:23:21,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:02 | 200 |  148.608651ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1558/8417 [17:30<1:23:00,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:02 | 200 |  141.953417ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1559/8417 [17:31<1:22:31,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:03 | 200 |  162.158805ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1560/8417 [17:32<1:23:01,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:04 | 200 |  177.235188ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1561/8417 [17:33<1:24:29,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:05 | 200 |  172.319125ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1562/8417 [17:33<1:24:53,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:05 | 200 |  139.313797ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1563/8417 [17:34<1:23:46,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:06 | 200 |  145.276835ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1564/8417 [17:35<1:23:42,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:07 | 200 |  170.911965ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1565/8417 [17:35<1:23:31,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:08 | 200 |  141.935433ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1566/8417 [17:36<1:23:03,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:08 | 200 |  144.445814ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1567/8417 [17:37<1:23:34,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:09 | 200 |  116.841861ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1568/8417 [17:38<1:22:04,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:10 | 200 |  140.968227ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1569/8417 [17:38<1:21:33,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:10 | 200 |  159.608018ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1570/8417 [17:39<1:23:18,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:11 | 200 |  147.359601ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1571/8417 [17:40<1:22:15,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:12 | 200 |  121.536761ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1572/8417 [17:40<1:20:48,  1.41it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:13 | 200 |  177.439063ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1573/8417 [17:41<1:22:02,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:13 | 200 |  177.036444ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1574/8417 [17:42<1:22:56,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:14 | 200 |  154.339284ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1575/8417 [17:43<1:22:44,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:15 | 200 |   144.42211ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1576/8417 [17:43<1:22:07,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:15 | 200 |  140.977508ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1577/8417 [17:44<1:21:49,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:16 | 200 |  155.356942ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▊        | 1578/8417 [17:45<1:22:04,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:17 | 200 |  177.202595ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1579/8417 [17:46<1:22:49,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:18 | 200 |  150.445702ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1580/8417 [17:46<1:22:57,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:18 | 200 |  118.319189ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1581/8417 [17:47<1:21:53,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:19 | 200 |  145.885921ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1582/8417 [17:48<1:21:35,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:20 | 200 |  158.069159ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1583/8417 [17:48<1:21:50,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:21 | 200 |  168.657697ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1584/8417 [17:49<1:23:29,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:21 | 200 |  149.967561ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1585/8417 [17:50<1:22:51,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:22 | 200 |  139.592133ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1586/8417 [17:51<1:21:53,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:23 | 200 |  141.387315ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1587/8417 [17:51<1:21:23,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:23 | 200 |  158.254165ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1588/8417 [17:52<1:21:50,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:24 | 200 |  179.908351ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1589/8417 [17:53<1:22:33,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:25 | 200 |  138.827123ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1590/8417 [17:53<1:21:27,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:26 | 200 |  141.177778ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1591/8417 [17:54<1:21:36,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:26 | 200 |  140.276777ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1592/8417 [17:55<1:21:00,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:27 | 200 |  141.934166ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1593/8417 [17:56<1:21:56,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:28 | 200 |  180.523144ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1594/8417 [17:56<1:23:12,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:29 | 200 |  143.564549ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1595/8417 [17:57<1:22:58,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:29 | 200 |  147.302598ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1596/8417 [17:58<1:22:22,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:30 | 200 |  179.208113ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1597/8417 [17:59<1:23:26,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:31 | 200 |  149.377293ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1598/8417 [17:59<1:23:00,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:31 | 200 |  144.296195ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1599/8417 [18:00<1:22:30,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:32 | 200 |  115.739593ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1600/8417 [18:01<1:20:52,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:33 | 200 |  171.068549ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1601/8417 [18:01<1:21:38,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:34 | 200 |  169.742952ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1602/8417 [18:02<1:23:09,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:34 | 200 |  144.466162ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1603/8417 [18:03<1:23:20,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:35 | 200 |  145.421476ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1604/8417 [18:04<1:23:15,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:36 | 200 |  145.815513ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1605/8417 [18:04<1:25:11,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:37 | 200 |  179.036187ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1606/8417 [18:05<1:25:24,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:37 | 200 |  152.386589ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1607/8417 [18:06<1:24:37,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:38 | 200 |  140.612591ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1608/8417 [18:07<1:23:47,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:39 | 200 |  147.342276ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1609/8417 [18:07<1:23:01,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:40 | 200 |  165.661451ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1610/8417 [18:08<1:23:34,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:40 | 200 |  180.523581ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1611/8417 [18:09<1:26:52,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:41 | 200 |  154.965043ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1612/8417 [18:10<1:25:05,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:42 | 200 |  156.624907ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1613/8417 [18:10<1:24:42,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:43 | 200 |  144.992955ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1614/8417 [18:11<1:23:25,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:43 | 200 |  137.059654ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1615/8417 [18:12<1:22:32,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:44 | 200 |  160.281319ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1616/8417 [18:13<1:22:24,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:45 | 200 |   143.12361ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1617/8417 [18:13<1:21:50,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:45 | 200 |  147.595009ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1618/8417 [18:14<1:21:47,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:46 | 200 |  145.757857ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1619/8417 [18:15<1:22:21,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:47 | 200 |  141.281524ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1620/8417 [18:15<1:22:01,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:48 | 200 |  138.239679ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1621/8417 [18:16<1:22:08,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:48 | 200 |  134.752118ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1622/8417 [18:17<1:22:23,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:49 | 200 |  184.010981ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1623/8417 [18:18<1:23:11,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:50 | 200 |  117.685227ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1624/8417 [18:18<1:21:43,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:50 | 200 |  142.984196ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1625/8417 [18:19<1:23:07,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:51 | 200 |  166.425304ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1626/8417 [18:20<1:23:22,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:52 | 200 |  133.923485ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1627/8417 [18:21<1:21:59,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:53 | 200 |  145.736007ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1628/8417 [18:21<1:21:21,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:53 | 200 |  139.510144ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1629/8417 [18:22<1:20:51,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:54 | 200 |  137.552602ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1630/8417 [18:23<1:20:48,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:55 | 200 |  159.429572ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1631/8417 [18:23<1:21:19,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:56 | 200 |  139.443437ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1632/8417 [18:24<1:22:00,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:56 | 200 |  146.561762ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1633/8417 [18:25<1:21:39,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:57 | 200 |  146.100691ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1634/8417 [18:26<1:21:34,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:58 | 200 |  141.724677ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1635/8417 [18:26<1:21:43,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:58 | 200 |  162.053056ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1636/8417 [18:27<1:21:37,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:42:59 | 200 |   144.39428ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1637/8417 [18:28<1:21:36,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:00 | 200 |  145.572543ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1638/8417 [18:28<1:22:03,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:01 | 200 |  138.842751ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1639/8417 [18:29<1:21:57,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:01 | 200 |  140.183848ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1640/8417 [18:30<1:21:44,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:02 | 200 |  175.452003ms |       127.0.0.1 | POST     "/api/chat"

 19%|█▉        | 1641/8417 [18:31<1:22:30,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:03 | 200 |  141.860505ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1642/8417 [18:31<1:21:46,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:04 | 200 |  151.783901ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1643/8417 [18:32<1:21:44,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:04 | 200 |  142.722208ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1644/8417 [18:33<1:21:41,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:05 | 200 |   115.75027ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1645/8417 [18:34<1:20:28,  1.40it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:06 | 200 |  181.595604ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1646/8417 [18:34<1:21:42,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:06 | 200 |  143.292103ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1647/8417 [18:35<1:21:06,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:07 | 200 |  148.918524ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1648/8417 [18:36<1:21:49,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:08 | 200 |  146.252373ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1649/8417 [18:36<1:22:59,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:09 | 200 |  145.316004ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1650/8417 [18:37<1:23:28,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:09 | 200 |  154.711545ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1651/8417 [18:38<1:23:54,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:10 | 200 |  174.378375ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1652/8417 [18:39<1:25:31,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:11 | 200 |  151.619429ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1653/8417 [18:39<1:24:26,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:12 | 200 |  141.560825ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1654/8417 [18:40<1:23:47,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:12 | 200 |  146.569343ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1655/8417 [18:41<1:22:55,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:13 | 200 |  141.991072ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1656/8417 [18:42<1:22:12,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:14 | 200 |  137.700485ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1657/8417 [18:42<1:21:16,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:14 | 200 |  169.370812ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1658/8417 [18:43<1:21:33,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:15 | 200 |  144.579509ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1659/8417 [18:44<1:21:24,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:16 | 200 |  148.124945ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1660/8417 [18:45<1:22:18,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:17 | 200 |  138.490218ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1661/8417 [18:45<1:21:40,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:17 | 200 |  136.643772ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1662/8417 [18:46<1:21:02,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:18 | 200 |  165.547049ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1663/8417 [18:47<1:21:45,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:19 | 200 |  144.264317ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1664/8417 [18:47<1:21:25,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:20 | 200 |  142.960349ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1665/8417 [18:48<1:21:07,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:20 | 200 |  140.904328ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1666/8417 [18:49<1:21:10,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:21 | 200 |  140.447713ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1667/8417 [18:50<1:22:30,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:22 | 200 |  181.699518ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1668/8417 [18:50<1:23:33,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:23 | 200 |  146.111494ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1669/8417 [18:51<1:23:13,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:23 | 200 |  141.160703ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1670/8417 [18:52<1:22:12,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:24 | 200 |  122.227503ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1671/8417 [18:53<1:20:51,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:25 | 200 |  179.273209ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1672/8417 [18:53<1:25:42,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:26 | 200 |  144.998909ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1673/8417 [18:54<1:24:51,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:26 | 200 |  149.007144ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1674/8417 [18:55<1:24:26,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:27 | 200 |  176.411374ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1675/8417 [18:56<1:24:34,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:28 | 200 |  166.205926ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1676/8417 [18:56<1:24:10,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:28 | 200 |   143.50166ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1677/8417 [18:57<1:23:03,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:29 | 200 |  141.977968ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1678/8417 [18:58<1:22:47,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:30 | 200 |  166.090468ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1679/8417 [18:59<1:23:08,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:31 | 200 |  149.439788ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1680/8417 [18:59<1:22:33,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:32 | 200 |   142.12125ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1681/8417 [19:00<1:26:56,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:32 | 200 |   142.28757ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1682/8417 [19:01<1:26:45,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:33 | 200 |  155.606408ms |       127.0.0.1 | POST     "/api/chat"

 20%|█▉        | 1683/8417 [19:02<1:25:20,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:34 | 200 |  166.142101ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1684/8417 [19:02<1:24:42,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:35 | 200 |  150.218354ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1685/8417 [19:03<1:23:44,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:35 | 200 |  142.097549ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1686/8417 [19:04<1:22:26,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:36 | 200 |  145.127823ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1687/8417 [19:05<1:21:56,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:37 | 200 |  159.656872ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1688/8417 [19:05<1:22:12,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:37 | 200 |  173.190541ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1689/8417 [19:06<1:22:47,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:38 | 200 |  150.166194ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1690/8417 [19:07<1:22:51,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:39 | 200 |  146.185911ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1691/8417 [19:08<1:23:38,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:40 | 200 |  157.321416ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1692/8417 [19:08<1:24:02,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:40 | 200 |  202.765599ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1693/8417 [19:09<1:26:26,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:41 | 200 |  180.753184ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1694/8417 [19:10<1:25:44,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:42 | 200 |  177.198035ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1695/8417 [19:11<1:25:31,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:43 | 200 |   142.29742ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1696/8417 [19:11<1:24:01,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:43 | 200 |   141.75082ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1697/8417 [19:12<1:23:15,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:44 | 200 |   176.43393ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1698/8417 [19:13<1:24:01,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:45 | 200 |  145.173357ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1699/8417 [19:14<1:23:04,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:46 | 200 |  147.125927ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1700/8417 [19:14<1:23:50,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:46 | 200 |  163.365207ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1701/8417 [19:15<1:23:21,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:47 | 200 |  150.550969ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1702/8417 [19:16<1:24:20,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:48 | 200 |  121.723922ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1703/8417 [19:17<1:23:34,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:49 | 200 |   142.32731ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1704/8417 [19:17<1:23:09,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:49 | 200 |  181.031362ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1705/8417 [19:18<1:24:05,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:50 | 200 |  150.051582ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1706/8417 [19:19<1:25:20,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:51 | 200 |  139.406745ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1707/8417 [19:20<1:25:26,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:52 | 200 |  143.891888ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1708/8417 [19:20<1:24:11,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:52 | 200 |  154.228843ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1709/8417 [19:21<1:23:11,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:53 | 200 |    146.9416ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1710/8417 [19:22<1:22:08,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:54 | 200 |  144.461466ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1711/8417 [19:23<1:21:16,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:55 | 200 |  141.552138ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1712/8417 [19:23<1:21:13,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:55 | 200 |  159.155165ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1713/8417 [19:24<1:21:30,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:56 | 200 |  176.179194ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1714/8417 [19:25<1:22:17,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:57 | 200 |  164.485877ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1715/8417 [19:25<1:22:18,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:58 | 200 |  144.536332ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1716/8417 [19:26<1:23:10,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:58 | 200 |  138.326554ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1717/8417 [19:27<1:21:53,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:43:59 | 200 |   147.42673ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1718/8417 [19:28<1:21:46,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:00 | 200 |    169.2345ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1719/8417 [19:28<1:23:13,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:01 | 200 |  150.110304ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1720/8417 [19:29<1:23:45,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:01 | 200 |  146.033361ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1721/8417 [19:30<1:23:43,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:02 | 200 |  181.591252ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1722/8417 [19:31<1:23:41,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:03 | 200 |  143.061399ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1723/8417 [19:31<1:22:23,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:04 | 200 |  116.550228ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1724/8417 [19:32<1:21:27,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:04 | 200 |   143.10996ms |       127.0.0.1 | POST     "/api/chat"

 20%|██        | 1725/8417 [19:33<1:21:12,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:05 | 200 |  142.725309ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1726/8417 [19:34<1:21:08,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:06 | 200 |  180.872171ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1727/8417 [19:34<1:22:15,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:06 | 200 |   142.17982ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1728/8417 [19:35<1:21:06,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:07 | 200 |  141.326803ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1729/8417 [19:36<1:20:38,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:08 | 200 |  166.698606ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1730/8417 [19:37<1:21:21,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:09 | 200 |  147.180206ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1731/8417 [19:37<1:21:12,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:09 | 200 |  142.804338ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1732/8417 [19:38<1:21:44,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:10 | 200 |  168.173937ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1733/8417 [19:39<1:22:28,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:11 | 200 |  143.994091ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1734/8417 [19:39<1:23:06,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:12 | 200 |  130.557855ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1735/8417 [19:40<1:21:35,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:12 | 200 |  141.198325ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1736/8417 [19:41<1:21:17,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:13 | 200 |  168.467323ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1737/8417 [19:42<1:21:58,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:14 | 200 |  154.652714ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1738/8417 [19:42<1:21:38,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:15 | 200 |  156.313892ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1739/8417 [19:43<1:21:19,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:15 | 200 |  136.565666ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1740/8417 [19:44<1:20:38,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:16 | 200 |  145.965473ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1741/8417 [19:45<1:20:57,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:17 | 200 |  141.870348ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1742/8417 [19:45<1:21:11,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:17 | 200 |  145.503483ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1743/8417 [19:46<1:21:11,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:18 | 200 |  180.737766ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1744/8417 [19:47<1:22:09,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:19 | 200 |  147.868646ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1745/8417 [19:48<1:22:06,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:20 | 200 |  142.344674ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1746/8417 [19:48<1:21:39,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:20 | 200 |  139.170363ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1747/8417 [19:49<1:21:42,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:21 | 200 |  139.038725ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1748/8417 [19:50<1:21:19,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:22 | 200 |  143.855458ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1749/8417 [19:50<1:21:45,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:23 | 200 |  152.076001ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1750/8417 [19:51<1:22:28,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:23 | 200 |  176.358229ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1751/8417 [19:52<1:22:46,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:24 | 200 |  148.817356ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1752/8417 [19:53<1:22:27,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:25 | 200 |  133.173887ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1753/8417 [19:53<1:21:20,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:26 | 200 |  144.616366ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1754/8417 [19:54<1:21:13,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:26 | 200 |  157.136149ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1755/8417 [19:55<1:21:29,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:27 | 200 |  175.473096ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1756/8417 [19:56<1:22:00,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:28 | 200 |  148.299096ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1757/8417 [19:56<1:21:38,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:28 | 200 |  146.018475ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1758/8417 [19:57<1:21:47,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:29 | 200 |  137.387257ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1759/8417 [19:58<1:25:00,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:30 | 200 |  133.983721ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1760/8417 [19:59<1:23:33,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:31 | 200 |   190.47618ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1761/8417 [19:59<1:24:39,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:32 | 200 |  159.697292ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1762/8417 [20:00<1:24:10,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:32 | 200 |  142.792421ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1763/8417 [20:01<1:23:01,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:33 | 200 |  120.071414ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1764/8417 [20:02<1:21:03,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:34 | 200 |  178.551663ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1765/8417 [20:02<1:22:23,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:34 | 200 |  150.923699ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1766/8417 [20:03<1:21:49,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:35 | 200 |  118.831199ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1767/8417 [20:04<1:20:40,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:36 | 200 |  178.159636ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1768/8417 [20:05<1:21:54,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:37 | 200 |  144.164677ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1769/8417 [20:05<1:21:12,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:37 | 200 |  145.658321ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1770/8417 [20:06<1:20:52,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:38 | 200 |  142.825748ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1771/8417 [20:07<1:20:46,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:39 | 200 |  141.593662ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1772/8417 [20:07<1:21:34,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:40 | 200 |  178.789456ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1773/8417 [20:08<1:22:53,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:40 | 200 |  140.559923ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1774/8417 [20:09<1:23:55,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:41 | 200 |  142.281344ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1775/8417 [20:10<1:22:36,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:42 | 200 |  136.545748ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1776/8417 [20:11<1:22:12,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:43 | 200 |  187.419168ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1777/8417 [20:11<1:23:32,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:43 | 200 |  143.465735ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1778/8417 [20:12<1:22:45,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:44 | 200 |  139.919554ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1779/8417 [20:13<1:22:21,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:45 | 200 |   171.81674ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1780/8417 [20:14<1:22:45,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:46 | 200 |  162.900197ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1781/8417 [20:14<1:22:30,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:46 | 200 |  139.519651ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1782/8417 [20:15<1:22:06,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:47 | 200 |  145.017176ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1783/8417 [20:16<1:21:56,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:48 | 200 |   177.06058ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1784/8417 [20:17<1:23:29,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:49 | 200 |  153.448354ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1785/8417 [20:17<1:22:34,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:49 | 200 |  116.390283ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1786/8417 [20:18<1:20:54,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:50 | 200 |  144.159525ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1787/8417 [20:19<1:20:34,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:51 | 200 |  160.096818ms |       127.0.0.1 | POST     "/api/chat"

 21%|██        | 1788/8417 [20:19<1:21:18,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:52 | 200 |  144.305123ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1789/8417 [20:20<1:21:22,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:52 | 200 |  174.263113ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1790/8417 [20:21<1:21:58,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:53 | 200 |  142.840634ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1791/8417 [20:22<1:21:08,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:54 | 200 |  140.726933ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1792/8417 [20:22<1:21:16,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:55 | 200 |  178.642145ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1793/8417 [20:23<1:22:20,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:55 | 200 |  118.167924ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1794/8417 [20:24<1:21:25,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:56 | 200 |  148.824034ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1795/8417 [20:25<1:21:43,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:57 | 200 |  167.869288ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1796/8417 [20:25<1:22:12,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:57 | 200 |  168.146016ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1797/8417 [20:26<1:22:15,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:58 | 200 |  144.669316ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1798/8417 [20:27<1:21:31,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:44:59 | 200 |  145.642928ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1799/8417 [20:28<1:21:34,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:00 | 200 |   168.15132ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1800/8417 [20:28<1:22:16,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:00 | 200 |  140.851044ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1801/8417 [20:29<1:22:14,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:01 | 200 |  139.545594ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1802/8417 [20:30<1:21:35,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:02 | 200 |  186.823953ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1803/8417 [20:31<1:23:21,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:03 | 200 |  178.484023ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1804/8417 [20:31<1:23:48,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:03 | 200 |  155.767615ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1805/8417 [20:32<1:23:14,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:04 | 200 |  147.292312ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1806/8417 [20:33<1:22:41,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:05 | 200 |  145.244378ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1807/8417 [20:34<1:21:54,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:06 | 200 |  173.155424ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1808/8417 [20:34<1:23:08,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:06 | 200 |  139.509325ms |       127.0.0.1 | POST     "/api/chat"

 21%|██▏       | 1809/8417 [20:35<1:22:18,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:07 | 200 |  148.338716ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1810/8417 [20:36<1:22:25,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:08 | 200 |  159.239632ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1811/8417 [20:37<1:22:13,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:09 | 200 |  153.884818ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1812/8417 [20:37<1:21:49,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:09 | 200 |   145.42482ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1813/8417 [20:38<1:22:14,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:10 | 200 |  139.288015ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1814/8417 [20:39<1:24:14,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:11 | 200 |  142.197846ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1815/8417 [20:40<1:23:26,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:12 | 200 |   174.72575ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1816/8417 [20:40<1:23:49,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:13 | 200 |  151.163194ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1817/8417 [20:41<1:22:35,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:13 | 200 |  146.607125ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1818/8417 [20:42<1:22:32,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:14 | 200 |  163.807659ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1819/8417 [20:43<1:24:05,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:15 | 200 |  178.728484ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1820/8417 [20:43<1:24:01,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:16 | 200 |  159.310925ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1821/8417 [20:44<1:23:15,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:16 | 200 |  146.870855ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1822/8417 [20:45<1:22:12,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:17 | 200 |  135.235092ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1823/8417 [20:46<1:20:53,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:18 | 200 |  146.883161ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1824/8417 [20:46<1:23:04,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:19 | 200 |   141.13305ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1825/8417 [20:47<1:21:59,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:19 | 200 |  114.593501ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1826/8417 [20:48<1:20:07,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:20 | 200 |  178.742424ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1827/8417 [20:49<1:20:59,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:21 | 200 |  120.611271ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1828/8417 [20:49<1:19:45,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:21 | 200 |  145.998272ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1829/8417 [20:50<1:19:55,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:22 | 200 |  136.213311ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1830/8417 [20:51<1:19:26,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:23 | 200 |  142.289406ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1831/8417 [20:51<1:19:56,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:24 | 200 |  174.627854ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1832/8417 [20:52<1:20:59,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:24 | 200 |  146.661285ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1833/8417 [20:53<1:20:37,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:25 | 200 |  142.808743ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1834/8417 [20:54<1:20:17,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:26 | 200 |  176.964845ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1835/8417 [20:54<1:21:22,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:27 | 200 |  141.340073ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1836/8417 [20:55<1:20:37,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:27 | 200 |  144.395691ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1837/8417 [20:56<1:20:31,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:28 | 200 |  177.968717ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1838/8417 [20:57<1:21:42,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:29 | 200 |  161.974525ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1839/8417 [20:57<1:22:04,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:30 | 200 |  144.350703ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1840/8417 [20:58<1:21:19,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:30 | 200 |  137.935116ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1841/8417 [20:59<1:21:44,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:31 | 200 |  183.572718ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1842/8417 [21:00<1:22:06,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:32 | 200 |  122.020645ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1843/8417 [21:00<1:20:33,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:32 | 200 |   147.83192ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1844/8417 [21:01<1:20:30,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:33 | 200 |  176.543577ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1845/8417 [21:02<1:21:33,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:34 | 200 |  113.581898ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1846/8417 [21:03<1:19:47,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:35 | 200 |  143.123492ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1847/8417 [21:03<1:19:37,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:35 | 200 |  165.382351ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1848/8417 [21:04<1:19:59,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:36 | 200 |  146.346367ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1849/8417 [21:05<1:19:46,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:37 | 200 |  147.274819ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1850/8417 [21:05<1:19:37,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:38 | 200 |  143.207747ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1851/8417 [21:06<1:19:46,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:38 | 200 |  140.752419ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1852/8417 [21:07<1:20:32,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:39 | 200 |  164.198357ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1853/8417 [21:08<1:20:51,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:40 | 200 |  156.933704ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1854/8417 [21:08<1:22:12,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:41 | 200 |  147.575321ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1855/8417 [21:09<1:22:12,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:41 | 200 |  140.877974ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1856/8417 [21:10<1:22:11,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:42 | 200 |  160.076519ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1857/8417 [21:11<1:22:22,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:43 | 200 |  178.360867ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1858/8417 [21:12<1:24:39,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:44 | 200 |  179.345447ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1859/8417 [21:12<1:25:23,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:45 | 200 |  177.274154ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1860/8417 [21:13<1:25:10,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:45 | 200 |  171.349139ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1861/8417 [21:14<1:25:36,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:46 | 200 |  168.863732ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1862/8417 [21:15<1:24:53,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:47 | 200 |  146.917498ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1863/8417 [21:15<1:23:50,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:48 | 200 |  137.884644ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1864/8417 [21:16<1:22:40,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:48 | 200 |  176.258594ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1865/8417 [21:17<1:22:30,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:49 | 200 |  149.003205ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1866/8417 [21:18<1:21:50,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:50 | 200 |  139.962263ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1867/8417 [21:18<1:20:54,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:50 | 200 |  142.666734ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1868/8417 [21:19<1:21:26,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:51 | 200 |  139.362598ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1869/8417 [21:20<1:21:08,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:52 | 200 |  140.123475ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1870/8417 [21:21<1:20:32,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:53 | 200 |  127.840594ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1871/8417 [21:21<1:20:03,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:53 | 200 |  179.937131ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1872/8417 [21:22<1:21:43,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:54 | 200 |  146.904928ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1873/8417 [21:23<1:21:42,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:55 | 200 |  144.988028ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1874/8417 [21:24<1:21:18,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:56 | 200 |  142.823606ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1875/8417 [21:24<1:22:34,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:57 | 200 |  177.504614ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1876/8417 [21:25<1:22:32,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:57 | 200 |  141.278296ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1877/8417 [21:26<1:21:15,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:58 | 200 |  143.542985ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1878/8417 [21:27<1:20:52,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:59 | 200 |   180.61506ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1879/8417 [21:27<1:21:29,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:45:59 | 200 |  141.355028ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1880/8417 [21:28<1:20:37,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:00 | 200 |  143.712397ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1881/8417 [21:29<1:21:28,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:01 | 200 |  173.458628ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1882/8417 [21:30<1:21:58,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:02 | 200 |  173.592686ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1883/8417 [21:30<1:23:12,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:03 | 200 |  156.646884ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1884/8417 [21:31<1:22:37,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:03 | 200 |  156.456072ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1885/8417 [21:32<1:22:24,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:04 | 200 |  152.564763ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1886/8417 [21:33<1:22:05,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:05 | 200 |  143.479144ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1887/8417 [21:33<1:23:21,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:06 | 200 |   173.92116ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1888/8417 [21:34<1:23:15,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:06 | 200 |  152.758148ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1889/8417 [21:35<1:22:35,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:07 | 200 |  148.176161ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1890/8417 [21:36<1:21:37,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:08 | 200 |  142.716609ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1891/8417 [21:36<1:21:03,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:09 | 200 |  140.256007ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1892/8417 [21:37<1:21:06,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:09 | 200 |  137.081958ms |       127.0.0.1 | POST     "/api/chat"

 22%|██▏       | 1893/8417 [21:38<1:20:19,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:10 | 200 |  111.963533ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1894/8417 [21:39<1:19:12,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:11 | 200 |  183.965691ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1895/8417 [21:39<1:20:38,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:11 | 200 |  146.759936ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1896/8417 [21:40<1:20:09,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:12 | 200 |  142.843289ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1897/8417 [21:41<1:19:38,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:13 | 200 |  139.569456ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1898/8417 [21:42<1:19:33,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:14 | 200 |   111.45907ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1899/8417 [21:42<1:18:16,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:14 | 200 |  139.776482ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1900/8417 [21:43<1:19:10,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:15 | 200 |  137.754511ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1901/8417 [21:44<1:19:23,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:16 | 200 |    175.7246ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1902/8417 [21:44<1:20:39,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:17 | 200 |  175.671855ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1903/8417 [21:45<1:22:01,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 23%|██▎       | 1904/8417 [21:46<1:22:28,  1.32it/s]

[GIN] 2025/06/26 - 23:46:17 | 200 |  162.137592ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:18 | 200 |  153.221824ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1905/8417 [21:47<1:21:53,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:19 | 200 |  146.485861ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1906/8417 [21:48<1:21:30,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:20 | 200 |  146.180135ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1907/8417 [21:48<1:21:24,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:20 | 200 |  142.944979ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1908/8417 [21:49<1:21:50,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:21 | 200 |  141.941822ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1909/8417 [21:50<1:21:46,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:22 | 200 |  144.376984ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1910/8417 [21:51<1:20:41,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:23 | 200 |  130.425224ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1911/8417 [21:51<1:19:42,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:23 | 200 |  141.119193ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1912/8417 [21:52<1:19:36,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:24 | 200 |  143.511298ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1913/8417 [21:53<1:19:19,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:25 | 200 |  141.427409ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1914/8417 [21:53<1:19:05,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:26 | 200 |  175.519178ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1915/8417 [21:54<1:20:52,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:26 | 200 |  144.651466ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1916/8417 [21:55<1:20:37,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:27 | 200 |  140.908312ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1917/8417 [21:56<1:19:51,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:28 | 200 |  140.347861ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1918/8417 [21:56<1:19:30,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:28 | 200 |  138.943114ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1919/8417 [21:57<1:18:53,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:29 | 200 |  177.633638ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1920/8417 [21:58<1:20:24,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:30 | 200 |  144.123874ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1921/8417 [21:59<1:20:34,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:31 | 200 |  147.129149ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1922/8417 [21:59<1:20:29,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:31 | 200 |  145.385302ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1923/8417 [22:00<1:20:25,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:32 | 200 |  185.215283ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1924/8417 [22:01<1:21:18,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:33 | 200 |  144.692334ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1925/8417 [22:02<1:21:50,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:34 | 200 |  137.212051ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1926/8417 [22:02<1:20:46,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:34 | 200 |  137.901265ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1927/8417 [22:03<1:20:04,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:35 | 200 |  164.800098ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1928/8417 [22:04<1:20:46,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:36 | 200 |  147.633041ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1929/8417 [22:05<1:20:54,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:37 | 200 |  144.647769ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1930/8417 [22:05<1:20:10,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:37 | 200 |  138.197115ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1931/8417 [22:06<1:19:57,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:38 | 200 |  115.755385ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1932/8417 [22:07<1:18:21,  1.38it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:39 | 200 |  115.486213ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1933/8417 [22:07<1:17:48,  1.39it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:40 | 200 |   182.34125ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1934/8417 [22:08<1:20:26,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:40 | 200 |  146.291182ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1935/8417 [22:09<1:21:10,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:41 | 200 |  140.170935ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1936/8417 [22:10<1:20:53,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:42 | 200 |  143.115521ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1937/8417 [22:11<1:20:29,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:43 | 200 |  117.432325ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1938/8417 [22:11<1:19:10,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:43 | 200 |   142.57699ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1939/8417 [22:12<1:18:59,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:44 | 200 |  182.005681ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1940/8417 [22:13<1:20:06,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:45 | 200 |  142.472882ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1941/8417 [22:13<1:19:39,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:46 | 200 |  148.172365ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1942/8417 [22:14<1:20:11,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:46 | 200 |  164.274677ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1943/8417 [22:15<1:20:30,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:47 | 200 |  166.747356ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1944/8417 [22:16<1:21:26,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:48 | 200 |  139.511707ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1945/8417 [22:16<1:20:38,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:49 | 200 |  143.846455ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1946/8417 [22:17<1:22:20,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:49 | 200 |  162.465212ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1947/8417 [22:18<1:22:34,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:50 | 200 |  175.745961ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1948/8417 [22:19<1:23:22,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:51 | 200 |  181.432796ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1949/8417 [22:20<1:23:47,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:52 | 200 |  175.941248ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1950/8417 [22:20<1:23:29,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:52 | 200 |  163.650935ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1951/8417 [22:21<1:22:37,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:53 | 200 |  150.029651ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1952/8417 [22:22<1:22:03,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:54 | 200 |  140.918343ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1953/8417 [22:23<1:21:17,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:55 | 200 |  144.419542ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1954/8417 [22:23<1:20:33,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:55 | 200 |  140.057359ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1955/8417 [22:24<1:20:00,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:56 | 200 |  135.519673ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1956/8417 [22:25<1:19:23,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:57 | 200 |  184.145657ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1957/8417 [22:26<1:20:30,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:58 | 200 |  148.640876ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1958/8417 [22:26<1:20:35,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:58 | 200 |  144.207753ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1959/8417 [22:27<1:20:22,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:46:59 | 200 |  143.859696ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1960/8417 [22:28<1:20:01,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:00 | 200 |  142.338464ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1961/8417 [22:29<1:19:53,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:01 | 200 |  173.728144ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1962/8417 [22:29<1:20:36,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:01 | 200 |  150.401661ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1963/8417 [22:30<1:21:06,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:02 | 200 |  142.683209ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1964/8417 [22:31<1:20:11,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:03 | 200 |  143.710481ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1965/8417 [22:32<1:19:48,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:04 | 200 |   168.65076ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1966/8417 [22:32<1:21:00,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:04 | 200 |  140.473402ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1967/8417 [22:33<1:21:35,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:05 | 200 |  146.734786ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1968/8417 [22:34<1:21:26,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:06 | 200 |  180.385078ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1969/8417 [22:35<1:22:02,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:07 | 200 |   149.72564ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1970/8417 [22:35<1:21:48,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:08 | 200 |  138.386526ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1971/8417 [22:36<1:23:40,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:08 | 200 |  138.240486ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1972/8417 [22:37<1:24:08,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:09 | 200 |  139.572999ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1973/8417 [22:38<1:22:49,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:10 | 200 |  163.589581ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1974/8417 [22:38<1:22:39,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:11 | 200 |  187.559197ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1975/8417 [22:39<1:23:34,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:11 | 200 |  170.463985ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1976/8417 [22:40<1:23:17,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:12 | 200 |  181.901581ms |       127.0.0.1 | POST     "/api/chat"

 23%|██▎       | 1977/8417 [22:41<1:22:51,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:13 | 200 |   119.11077ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1978/8417 [22:42<1:20:46,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:14 | 200 |   119.48401ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1979/8417 [22:42<1:19:05,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:14 | 200 |  143.685854ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1980/8417 [22:43<1:19:09,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:15 | 200 |  141.330887ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1981/8417 [22:44<1:18:32,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:16 | 200 |  139.031396ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1982/8417 [22:44<1:18:21,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:17 | 200 |  175.091904ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1983/8417 [22:45<1:19:30,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:17 | 200 |  144.699614ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1984/8417 [22:46<1:19:11,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:18 | 200 |  120.040197ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1985/8417 [22:47<1:18:16,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:19 | 200 |  165.486637ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1986/8417 [22:47<1:19:07,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:19 | 200 |  151.885017ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1987/8417 [22:48<1:19:01,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:20 | 200 |  172.049722ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1988/8417 [22:49<1:21:37,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:21 | 200 |  182.666744ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1989/8417 [22:50<1:22:03,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:22 | 200 |  151.156202ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1990/8417 [22:50<1:21:06,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:23 | 200 |   139.30496ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1991/8417 [22:51<1:19:56,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:23 | 200 |  137.374381ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1992/8417 [22:52<1:18:56,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:24 | 200 |  146.569115ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1993/8417 [22:53<1:18:47,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:25 | 200 |  142.118665ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1994/8417 [22:53<1:18:53,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:25 | 200 |  170.315842ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1995/8417 [22:54<1:19:47,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:26 | 200 |  173.046569ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1996/8417 [22:55<1:20:03,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:27 | 200 |  125.111646ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1997/8417 [22:56<1:18:54,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:28 | 200 |  148.760892ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1998/8417 [22:56<1:19:17,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:28 | 200 |    172.7483ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▎       | 1999/8417 [22:57<1:20:05,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:29 | 200 |  155.176424ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2000/8417 [22:58<1:20:16,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:30 | 200 |  138.867502ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2001/8417 [22:59<1:19:52,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:31 | 200 |  143.544372ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2002/8417 [22:59<1:19:49,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:31 | 200 |  176.076769ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2003/8417 [23:00<1:20:39,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:32 | 200 |  131.865331ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2004/8417 [23:01<1:19:41,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:33 | 200 |  171.624436ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2005/8417 [23:02<1:20:19,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:34 | 200 |  141.092401ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2006/8417 [23:02<1:19:43,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:34 | 200 |  147.816589ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2007/8417 [23:03<1:19:54,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:35 | 200 |   140.08653ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2008/8417 [23:04<1:19:52,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:36 | 200 |  136.130247ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2009/8417 [23:05<1:19:18,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:37 | 200 |   172.25496ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2010/8417 [23:05<1:19:49,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:37 | 200 |  159.897781ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2011/8417 [23:06<1:20:06,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:38 | 200 |  140.669762ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2012/8417 [23:07<1:19:49,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:39 | 200 |  111.405086ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2013/8417 [23:08<1:18:09,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:40 | 200 |  141.958445ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2014/8417 [23:08<1:18:18,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:40 | 200 |  153.125805ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2015/8417 [23:09<1:20:24,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:41 | 200 |  178.209349ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2016/8417 [23:10<1:21:17,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:42 | 200 |   144.43489ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2017/8417 [23:11<1:20:27,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:43 | 200 |  147.460433ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2018/8417 [23:11<1:20:35,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:43 | 200 |   140.99298ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2019/8417 [23:12<1:20:36,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:44 | 200 |  143.051912ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2020/8417 [23:13<1:20:41,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:45 | 200 |  147.798561ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2021/8417 [23:14<1:20:24,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:46 | 200 |  169.717223ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2022/8417 [23:14<1:20:57,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:46 | 200 |  162.674471ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2023/8417 [23:15<1:20:46,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:47 | 200 |  147.281393ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2024/8417 [23:16<1:19:49,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:48 | 200 |  137.289088ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2025/8417 [23:17<1:20:03,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:49 | 200 |  136.970362ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2026/8417 [23:17<1:19:31,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:50 | 200 |  170.233655ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2027/8417 [23:18<1:21:16,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:50 | 200 |  115.304289ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2028/8417 [23:19<1:20:49,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:51 | 200 |   144.54076ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2029/8417 [23:20<1:20:25,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:52 | 200 |  163.541978ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2030/8417 [23:20<1:21:27,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:53 | 200 |  199.007503ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2031/8417 [23:21<1:23:18,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:53 | 200 |  174.882791ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2032/8417 [23:22<1:23:36,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:54 | 200 |  181.391139ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2033/8417 [23:23<1:23:49,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:55 | 200 |  182.154222ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2034/8417 [23:24<1:23:29,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:56 | 200 |  178.048566ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2035/8417 [23:24<1:23:10,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:57 | 200 |  147.985693ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2036/8417 [23:25<1:21:31,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:57 | 200 |  118.374585ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2037/8417 [23:26<1:19:28,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:58 | 200 |  122.897556ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2038/8417 [23:27<1:18:20,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:59 | 200 |  138.918762ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2039/8417 [23:27<1:18:22,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:47:59 | 200 |  180.852972ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2040/8417 [23:28<1:19:18,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:00 | 200 |  179.232243ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2041/8417 [23:29<1:20:29,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:01 | 200 |  155.376867ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2042/8417 [23:30<1:20:02,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:02 | 200 |  143.052263ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2043/8417 [23:30<1:19:43,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:02 | 200 |  139.825564ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2044/8417 [23:31<1:19:22,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:03 | 200 |   176.36789ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2045/8417 [23:32<1:20:30,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:04 | 200 |  162.891111ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2046/8417 [23:33<1:20:34,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:05 | 200 |  134.631826ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2047/8417 [23:33<1:20:47,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:05 | 200 |  139.284213ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2048/8417 [23:34<1:20:09,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:06 | 200 |  159.281502ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2049/8417 [23:35<1:20:23,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:07 | 200 |  174.435379ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2050/8417 [23:36<1:20:36,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:08 | 200 |   157.55227ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2051/8417 [23:36<1:20:11,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:08 | 200 |  118.872386ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2052/8417 [23:37<1:19:01,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:09 | 200 |  142.489326ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2053/8417 [23:38<1:18:39,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:10 | 200 |  165.127607ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2054/8417 [23:39<1:19:11,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:11 | 200 |  122.571147ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2055/8417 [23:39<1:18:47,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:11 | 200 |  148.347246ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2056/8417 [23:40<1:18:41,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:12 | 200 |  180.788449ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2057/8417 [23:41<1:19:54,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:13 | 200 |   148.35729ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2058/8417 [23:42<1:19:39,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:14 | 200 |   137.52999ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2059/8417 [23:42<1:18:57,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:14 | 200 |  143.245179ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2060/8417 [23:43<1:20:34,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:15 | 200 |    162.1101ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2061/8417 [23:44<1:20:43,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:16 | 200 |  176.636868ms |       127.0.0.1 | POST     "/api/chat"

 24%|██▍       | 2062/8417 [23:45<1:21:16,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:17 | 200 |  150.853851ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2063/8417 [23:45<1:20:55,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:18 | 200 |  141.874674ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2064/8417 [23:46<1:19:58,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:18 | 200 |  140.608355ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2065/8417 [23:47<1:19:18,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:19 | 200 |  177.350288ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2066/8417 [23:48<1:20:10,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:20 | 200 |  152.147637ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2067/8417 [23:48<1:20:06,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:21 | 200 |  136.929675ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2068/8417 [23:49<1:20:18,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:21 | 200 |  140.652527ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2069/8417 [23:50<1:20:10,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:22 | 200 |  153.162079ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2070/8417 [23:51<1:19:32,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:23 | 200 |   177.57048ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2071/8417 [23:51<1:21:38,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:24 | 200 |  131.041418ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2072/8417 [23:52<1:20:23,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:24 | 200 |  142.188802ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2073/8417 [23:53<1:20:34,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:25 | 200 |  193.466662ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2074/8417 [23:54<1:22:20,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:26 | 200 |  148.580785ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2075/8417 [23:55<1:23:06,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:27 | 200 |   143.45195ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2076/8417 [23:55<1:21:40,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:27 | 200 |  140.974644ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2077/8417 [23:56<1:20:23,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:28 | 200 |  145.209689ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2078/8417 [23:57<1:19:33,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:29 | 200 |  135.637487ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2079/8417 [23:58<1:18:55,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:30 | 200 |   172.60826ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2080/8417 [23:58<1:19:57,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:30 | 200 |  182.664456ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2081/8417 [23:59<1:21:53,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:31 | 200 |  162.397421ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2082/8417 [24:00<1:21:26,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:32 | 200 |  157.570709ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2083/8417 [24:01<1:21:27,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:33 | 200 |  141.566312ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2084/8417 [24:01<1:20:49,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:34 | 200 |  137.921542ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2085/8417 [24:02<1:19:40,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:34 | 200 |  168.656444ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2086/8417 [24:03<1:20:11,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:35 | 200 |  160.384947ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2087/8417 [24:04<1:20:38,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:36 | 200 |  142.128561ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2088/8417 [24:04<1:20:10,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:37 | 200 |  141.200364ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2089/8417 [24:05<1:19:17,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:37 | 200 |  162.337588ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2090/8417 [24:06<1:19:30,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:38 | 200 |  140.677086ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2091/8417 [24:07<1:18:48,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:39 | 200 |  169.438958ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2092/8417 [24:07<1:19:31,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:40 | 200 |  146.827554ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2093/8417 [24:08<1:19:16,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:40 | 200 |  150.177981ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2094/8417 [24:09<1:20:25,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:41 | 200 |  174.694091ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2095/8417 [24:10<1:20:56,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:42 | 200 |  174.317064ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2096/8417 [24:11<1:21:16,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:43 | 200 |  127.982499ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2097/8417 [24:11<1:20:05,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:43 | 200 |  156.620567ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2098/8417 [24:12<1:20:10,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:44 | 200 |  143.163076ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2099/8417 [24:13<1:19:40,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:45 | 200 |  146.924791ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2100/8417 [24:14<1:19:13,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:46 | 200 |  140.117744ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2101/8417 [24:14<1:19:02,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:46 | 200 |  142.268308ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2102/8417 [24:15<1:18:55,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:47 | 200 |  153.304593ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2103/8417 [24:16<1:19:18,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:48 | 200 |   181.70321ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▍       | 2104/8417 [24:17<1:20:25,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:49 | 200 |  165.724081ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2105/8417 [24:17<1:21:08,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:50 | 200 |  147.325198ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2106/8417 [24:18<1:20:31,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:50 | 200 |  141.493038ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2107/8417 [24:19<1:20:18,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:51 | 200 |  135.121149ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2108/8417 [24:20<1:19:53,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:52 | 200 |  169.470642ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2109/8417 [24:20<1:20:26,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:53 | 200 |  176.776447ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2110/8417 [24:21<1:20:42,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:53 | 200 |   153.29884ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2111/8417 [24:22<1:20:07,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:54 | 200 |  142.491144ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2112/8417 [24:23<1:19:37,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:55 | 200 |  144.665698ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2113/8417 [24:23<1:20:29,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:56 | 200 |  191.029625ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2114/8417 [24:24<1:21:52,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:56 | 200 |   177.48226ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2115/8417 [24:25<1:22:32,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:57 | 200 |  157.745322ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2116/8417 [24:26<1:22:08,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:58 | 200 |   161.11791ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2117/8417 [24:27<1:22:38,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:48:59 | 200 |  175.457712ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2118/8417 [24:27<1:21:57,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:00 | 200 |   137.48638ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2119/8417 [24:28<1:23:00,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:00 | 200 |  136.644056ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2120/8417 [24:29<1:23:12,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:01 | 200 |  175.662755ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2121/8417 [24:30<1:22:45,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:02 | 200 |  159.523848ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2122/8417 [24:31<1:21:53,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:03 | 200 |  146.276392ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2123/8417 [24:31<1:21:05,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:03 | 200 |  137.645307ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2124/8417 [24:32<1:21:10,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:04 | 200 |  173.303772ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2125/8417 [24:33<1:22:04,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:05 | 200 |  125.581544ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2126/8417 [24:34<1:21:29,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:06 | 200 |  151.708029ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2127/8417 [24:34<1:21:22,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:07 | 200 |  175.971906ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2128/8417 [24:35<1:21:31,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:07 | 200 |  153.466658ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2129/8417 [24:36<1:20:35,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:08 | 200 |  145.048769ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2130/8417 [24:37<1:19:33,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:09 | 200 |   137.49371ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2131/8417 [24:37<1:18:50,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:10 | 200 |  178.631886ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2132/8417 [24:38<1:19:47,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:10 | 200 |  115.694977ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2133/8417 [24:39<1:19:29,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:11 | 200 |  118.713306ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2134/8417 [24:40<1:17:59,  1.34it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:12 | 200 |  180.765215ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2135/8417 [24:40<1:19:30,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:13 | 200 |  177.824261ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2136/8417 [24:41<1:20:50,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:13 | 200 |  172.550025ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2137/8417 [24:42<1:21:25,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:14 | 200 |  165.999381ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2138/8417 [24:43<1:24:06,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:15 | 200 |  152.946895ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2139/8417 [24:44<1:23:09,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:16 | 200 |  160.201444ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2140/8417 [24:45<1:23:50,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:17 | 200 |  154.299367ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2141/8417 [24:45<1:23:09,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:17 | 200 |  154.121386ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2142/8417 [24:46<1:22:31,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:18 | 200 |  181.048515ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2143/8417 [24:47<1:22:44,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:19 | 200 |  172.454669ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2144/8417 [24:48<1:21:57,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:20 | 200 |  146.927631ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2145/8417 [24:48<1:20:54,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:20 | 200 |  116.047318ms |       127.0.0.1 | POST     "/api/chat"

 25%|██▌       | 2146/8417 [24:49<1:20:04,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:21 | 200 |  119.205041ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2147/8417 [24:50<1:18:17,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:22 | 200 |  167.932312ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2148/8417 [24:51<1:18:42,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:23 | 200 |  149.390945ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2149/8417 [24:51<1:18:30,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:23 | 200 |  118.866463ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2150/8417 [24:52<1:17:15,  1.35it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:24 | 200 |  115.390603ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2151/8417 [24:53<1:16:18,  1.37it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:25 | 200 |  138.335315ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2152/8417 [24:54<1:16:37,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:26 | 200 |  145.708997ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2153/8417 [24:54<1:17:01,  1.36it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:26 | 200 |  141.117902ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2154/8417 [24:55<1:18:32,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:27 | 200 |  164.471106ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2155/8417 [24:56<1:18:53,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:28 | 200 |  146.060076ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2156/8417 [24:57<1:18:22,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:29 | 200 |  172.483023ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2157/8417 [24:57<1:19:03,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:30 | 200 |  181.298599ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2158/8417 [24:58<1:19:30,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:30 | 200 |  133.064989ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2159/8417 [24:59<1:18:55,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:31 | 200 |  141.679666ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2160/8417 [25:00<1:18:44,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:32 | 200 |  144.953441ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2161/8417 [25:00<1:18:25,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:33 | 200 |   171.04677ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2162/8417 [25:01<1:18:40,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:33 | 200 |  177.540393ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2163/8417 [25:02<1:19:31,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:34 | 200 |   142.51039ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2164/8417 [25:03<1:18:50,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:35 | 200 |  145.201039ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2165/8417 [25:03<1:18:35,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:36 | 200 |  164.197581ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2166/8417 [25:04<1:19:19,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:36 | 200 |  178.589742ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2167/8417 [25:05<1:19:43,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:37 | 200 |  175.315403ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2168/8417 [25:06<1:20:24,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:38 | 200 |  164.431917ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2169/8417 [25:07<1:20:27,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:39 | 200 |  140.298931ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2170/8417 [25:07<1:19:58,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:39 | 200 |   141.98071ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2171/8417 [25:08<1:19:12,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:40 | 200 |   117.79292ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2172/8417 [25:09<1:18:54,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:41 | 200 |  143.758609ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2173/8417 [25:10<1:19:09,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:42 | 200 |  139.257846ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2174/8417 [25:10<1:18:55,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:42 | 200 |  168.777507ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2175/8417 [25:11<1:19:48,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:43 | 200 |  159.198376ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2176/8417 [25:12<1:20:05,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:44 | 200 |  147.382403ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2177/8417 [25:13<1:19:26,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:45 | 200 |  140.557284ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2178/8417 [25:13<1:20:04,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:46 | 200 |  170.900048ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2179/8417 [25:14<1:20:56,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:46 | 200 |  157.333528ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2180/8417 [25:15<1:20:58,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:47 | 200 |  153.320988ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2181/8417 [25:16<1:20:17,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:48 | 200 |  138.734449ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2182/8417 [25:16<1:19:26,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:49 | 200 |  134.316548ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2183/8417 [25:17<1:18:27,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:49 | 200 |  173.459039ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2184/8417 [25:18<1:19:29,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:50 | 200 |  156.427658ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2185/8417 [25:19<1:19:43,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:51 | 200 |  142.036721ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2186/8417 [25:20<1:19:20,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:52 | 200 |   141.03291ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2187/8417 [25:20<1:19:31,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:52 | 200 |  163.461992ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2188/8417 [25:21<1:20:03,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:53 | 200 |  146.287733ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2189/8417 [25:22<1:19:54,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:54 | 200 |   147.09572ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2190/8417 [25:23<1:19:50,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:55 | 200 |  179.610681ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2191/8417 [25:23<1:20:34,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:56 | 200 |  147.240867ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2192/8417 [25:24<1:20:12,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:56 | 200 |  139.236809ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2193/8417 [25:25<1:19:36,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:57 | 200 |    141.3793ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2194/8417 [25:26<1:19:44,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:58 | 200 |  165.674026ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2195/8417 [25:27<1:21:28,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:59 | 200 |  192.519035ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2196/8417 [25:27<1:22:45,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:49:59 | 200 |  147.192201ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2197/8417 [25:28<1:21:44,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:00 | 200 |  147.228026ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2198/8417 [25:29<1:21:34,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:01 | 200 |  143.560176ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2199/8417 [25:30<1:20:40,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:02 | 200 |   179.21269ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2200/8417 [25:30<1:21:11,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 26%|██▌       | 2201/8417 [25:31<1:20:50,  1.28it/s]

[GIN] 2025/06/26 - 23:50:03 | 200 |  160.573194ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:03 | 200 |  145.974388ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2202/8417 [25:32<1:20:11,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:04 | 200 |  144.512568ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2203/8417 [25:33<1:19:13,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:05 | 200 |  144.937971ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2204/8417 [25:33<1:19:21,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:06 | 200 |  174.126549ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2205/8417 [25:34<1:20:05,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:06 | 200 |   139.32276ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2206/8417 [25:35<1:19:35,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:07 | 200 |  143.198606ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2207/8417 [25:36<1:18:48,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:08 | 200 |  173.566632ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2208/8417 [25:37<1:19:48,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:09 | 200 |  146.884832ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▌       | 2209/8417 [25:37<1:19:20,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:09 | 200 |  148.728527ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2210/8417 [25:38<1:19:44,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:10 | 200 |  143.829931ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2211/8417 [25:39<1:19:52,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:11 | 200 |   140.49525ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2212/8417 [25:40<1:19:03,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:12 | 200 |  174.683836ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2213/8417 [25:40<1:20:04,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:13 | 200 |  125.611557ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2214/8417 [25:41<1:19:18,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:13 | 200 |  143.714661ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2215/8417 [25:42<1:18:41,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:14 | 200 |  158.792388ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2216/8417 [25:43<1:19:21,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:15 | 200 |  184.203685ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2217/8417 [25:44<1:20:25,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:16 | 200 |  176.455028ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2218/8417 [25:44<1:21:40,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:16 | 200 |  177.595186ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2219/8417 [25:45<1:21:29,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:17 | 200 |  179.052544ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2220/8417 [25:46<1:21:10,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:18 | 200 |  175.949097ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2221/8417 [25:47<1:20:33,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:19 | 200 |   156.81262ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2222/8417 [25:47<1:20:00,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:20 | 200 |  145.570007ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2223/8417 [25:48<1:19:48,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:20 | 200 |  141.631326ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2224/8417 [25:49<1:20:26,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:21 | 200 |  168.363084ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2225/8417 [25:50<1:21:16,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:22 | 200 |   149.01401ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2226/8417 [25:51<1:20:50,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:23 | 200 |  142.180979ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2227/8417 [25:51<1:19:34,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:23 | 200 |   143.58104ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2228/8417 [25:52<1:18:58,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:24 | 200 |  143.321743ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2229/8417 [25:53<1:18:54,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:25 | 200 |   136.66275ms |       127.0.0.1 | POST     "/api/chat"

 26%|██▋       | 2230/8417 [25:54<1:18:38,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:26 | 200 |  123.787893ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2231/8417 [25:54<1:17:41,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:26 | 200 |  142.524168ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2232/8417 [25:55<1:17:42,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:27 | 200 |   178.19466ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2233/8417 [25:56<1:18:41,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:28 | 200 |  147.152233ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2234/8417 [25:57<1:18:21,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:29 | 200 |  143.186951ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2235/8417 [25:57<1:18:00,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:29 | 200 |  138.771694ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2236/8417 [25:58<1:19:10,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:30 | 200 |  201.167413ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2237/8417 [25:59<1:22:44,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:31 | 200 |  162.017076ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2238/8417 [26:00<1:22:01,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:32 | 200 |  154.562223ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2239/8417 [26:01<1:21:06,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:33 | 200 |  119.696882ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2240/8417 [26:01<1:19:02,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:33 | 200 |   178.53899ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2241/8417 [26:02<1:19:36,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:34 | 200 |  142.117866ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2242/8417 [26:03<1:18:48,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:35 | 200 |  144.401721ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2243/8417 [26:04<1:18:37,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:36 | 200 |  153.756435ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2244/8417 [26:04<1:19:07,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:37 | 200 |  179.539193ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2245/8417 [26:05<1:19:34,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:37 | 200 |  175.601291ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2246/8417 [26:06<1:19:54,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:38 | 200 |  167.328998ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2247/8417 [26:07<1:20:22,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:39 | 200 |  155.171114ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2248/8417 [26:08<1:20:14,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:40 | 200 |  139.605467ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2249/8417 [26:08<1:19:09,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:40 | 200 |  118.085961ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2250/8417 [26:09<1:18:52,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:41 | 200 |  147.348176ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2251/8417 [26:10<1:18:21,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:42 | 200 |  177.259623ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2252/8417 [26:11<1:19:08,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:43 | 200 |  159.558844ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2253/8417 [26:11<1:19:02,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:43 | 200 |  143.643817ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2254/8417 [26:12<1:18:41,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:44 | 200 |  141.661109ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2255/8417 [26:13<1:19:12,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:45 | 200 |  144.821996ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2256/8417 [26:14<1:18:55,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:46 | 200 |  159.017482ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2257/8417 [26:14<1:19:13,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:47 | 200 |  146.534227ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2258/8417 [26:15<1:18:57,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:47 | 200 |  136.127054ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2259/8417 [26:16<1:18:16,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:48 | 200 |  140.622384ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2260/8417 [26:17<1:18:37,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:49 | 200 |  137.540056ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2261/8417 [26:17<1:17:36,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:50 | 200 |  165.513271ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2262/8417 [26:18<1:18:02,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:50 | 200 |  178.760646ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2263/8417 [26:19<1:19:43,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:51 | 200 |  156.616898ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2264/8417 [26:20<1:19:06,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:52 | 200 |  151.984982ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2265/8417 [26:21<1:18:55,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:53 | 200 |  139.360699ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2266/8417 [26:21<1:19:46,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:53 | 200 |  140.930368ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2267/8417 [26:22<1:19:25,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:54 | 200 |  160.310303ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2268/8417 [26:23<1:20:00,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:55 | 200 |  145.222391ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2269/8417 [26:24<1:19:31,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:56 | 200 |   148.18872ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2270/8417 [26:24<1:19:35,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:57 | 200 |  172.959474ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2271/8417 [26:25<1:19:55,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:57 | 200 |  173.519666ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2272/8417 [26:26<1:20:17,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:58 | 200 |  172.913455ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2273/8417 [26:27<1:20:23,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:50:59 | 200 |  158.478586ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2274/8417 [26:28<1:19:47,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:00 | 200 |  142.332588ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2275/8417 [26:28<1:19:50,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:01 | 200 |  145.540232ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2276/8417 [26:29<1:20:00,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:01 | 200 |   166.82912ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2277/8417 [26:30<1:20:47,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:02 | 200 |   139.35335ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2278/8417 [26:31<1:19:37,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:03 | 200 |   137.00413ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2279/8417 [26:31<1:18:29,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:04 | 200 |  177.848262ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2280/8417 [26:32<1:20:00,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:04 | 200 |  178.964061ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2281/8417 [26:33<1:21:26,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:05 | 200 |  179.842215ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2282/8417 [26:34<1:22:58,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:06 | 200 |  145.293358ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2283/8417 [26:35<1:21:48,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:07 | 200 |  144.665814ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2284/8417 [26:36<1:20:57,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:08 | 200 |  148.132701ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2285/8417 [26:36<1:20:18,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:08 | 200 |  183.752909ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2286/8417 [26:37<1:21:53,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:09 | 200 |  179.048151ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2287/8417 [26:38<1:21:37,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:10 | 200 |  188.298483ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2288/8417 [26:39<1:21:58,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:11 | 200 |  146.811558ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2289/8417 [26:39<1:20:51,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:12 | 200 |  177.309688ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2290/8417 [26:40<1:20:36,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:12 | 200 |   151.24715ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2291/8417 [26:41<1:19:50,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:13 | 200 |  148.560631ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2292/8417 [26:42<1:18:43,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:14 | 200 |  134.342029ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2293/8417 [26:43<1:17:37,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:15 | 200 |  181.572705ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2294/8417 [26:43<1:19:00,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:15 | 200 |  143.557303ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2295/8417 [26:44<1:18:27,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:16 | 200 |  179.018197ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2296/8417 [26:45<1:18:52,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:17 | 200 |  144.951831ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2297/8417 [26:46<1:18:20,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:18 | 200 |  143.565526ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2298/8417 [26:46<1:17:54,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:18 | 200 |  160.807447ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2299/8417 [26:47<1:18:07,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:19 | 200 |  181.954789ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2300/8417 [26:48<1:18:52,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:20 | 200 |  177.846286ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2301/8417 [26:49<1:19:33,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:21 | 200 |  170.946529ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2302/8417 [26:50<1:20:25,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:22 | 200 |  173.996023ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2303/8417 [26:50<1:20:07,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:22 | 200 |  170.528305ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2304/8417 [26:51<1:20:12,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:23 | 200 |   149.78975ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2305/8417 [26:52<1:19:42,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:24 | 200 |  141.824471ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2306/8417 [26:53<1:18:37,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:25 | 200 |  138.944748ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2307/8417 [26:53<1:18:34,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:26 | 200 |  155.532057ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2308/8417 [26:54<1:18:28,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:26 | 200 |  179.084885ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2309/8417 [26:55<1:19:02,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:27 | 200 |  176.361492ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2310/8417 [26:56<1:19:18,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:28 | 200 |  169.296048ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2311/8417 [26:57<1:19:01,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:29 | 200 |  121.009719ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2312/8417 [26:57<1:17:41,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:29 | 200 |  145.569122ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2313/8417 [26:58<1:17:29,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:30 | 200 |  132.035973ms |       127.0.0.1 | POST     "/api/chat"

 27%|██▋       | 2314/8417 [26:59<1:17:35,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:31 | 200 |  145.007392ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2315/8417 [27:00<1:17:42,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:32 | 200 |  140.877109ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2316/8417 [27:00<1:17:13,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:32 | 200 |  134.822399ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2317/8417 [27:01<1:18:05,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:33 | 200 |  184.968649ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2318/8417 [27:02<1:19:06,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:34 | 200 |  158.687678ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2319/8417 [27:03<1:19:09,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:35 | 200 |  142.291849ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2320/8417 [27:03<1:18:24,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:36 | 200 |  141.130655ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2321/8417 [27:04<1:18:08,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:36 | 200 |  177.941413ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2322/8417 [27:05<1:19:20,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:37 | 200 |  162.453539ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2323/8417 [27:06<1:19:01,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:38 | 200 |  114.442418ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2324/8417 [27:06<1:17:17,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:39 | 200 |  141.410071ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2325/8417 [27:07<1:16:34,  1.33it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:39 | 200 |  167.927603ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2326/8417 [27:08<1:17:55,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:40 | 200 |  143.498911ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2327/8417 [27:09<1:18:36,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:41 | 200 |  175.429479ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2328/8417 [27:10<1:19:24,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:42 | 200 |  178.583305ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2329/8417 [27:10<1:19:39,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:43 | 200 |  163.931571ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2330/8417 [27:11<1:19:33,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:43 | 200 |  152.061235ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2331/8417 [27:12<1:19:04,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:44 | 200 |  139.420849ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2332/8417 [27:13<1:17:50,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:45 | 200 |  139.034799ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2333/8417 [27:13<1:17:28,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:46 | 200 |  169.938233ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2334/8417 [27:14<1:18:24,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:46 | 200 |  182.125358ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2335/8417 [27:15<1:19:01,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:47 | 200 |  186.367638ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2336/8417 [27:16<1:19:41,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:48 | 200 |  178.574176ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2337/8417 [27:17<1:20:16,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:49 | 200 |  181.316145ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2338/8417 [27:17<1:20:30,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:50 | 200 |  184.509027ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2339/8417 [27:18<1:21:08,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:50 | 200 |  179.733137ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2340/8417 [27:19<1:22:28,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:51 | 200 |  177.656121ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2341/8417 [27:20<1:21:52,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:52 | 200 |  161.705219ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2342/8417 [27:21<1:21:05,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:53 | 200 |  124.033199ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2343/8417 [27:21<1:20:08,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:54 | 200 |  184.274293ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2344/8417 [27:22<1:20:53,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:54 | 200 |  181.871108ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2345/8417 [27:23<1:21:06,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:55 | 200 |  174.658811ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2346/8417 [27:24<1:20:50,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:56 | 200 |  141.778749ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2347/8417 [27:25<1:19:38,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:57 | 200 |  176.028769ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2348/8417 [27:25<1:19:55,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:58 | 200 |  148.257194ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2349/8417 [27:26<1:18:43,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:58 | 200 |  146.875943ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2350/8417 [27:27<1:17:51,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:51:59 | 200 |  146.914679ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2351/8417 [27:28<1:18:02,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:00 | 200 |  142.054162ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2352/8417 [27:28<1:18:34,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:01 | 200 |  162.796357ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2353/8417 [27:29<1:19:01,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:01 | 200 |   178.17843ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2354/8417 [27:30<1:19:34,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:02 | 200 |  178.398604ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2355/8417 [27:31<1:19:51,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:03 | 200 |   176.28246ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2356/8417 [27:32<1:21:01,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:04 | 200 |  179.934218ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2357/8417 [27:33<1:22:18,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:05 | 200 |  184.027189ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2358/8417 [27:33<1:22:36,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:06 | 200 |  158.210804ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2359/8417 [27:34<1:21:56,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:06 | 200 |   145.91213ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2360/8417 [27:35<1:21:00,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:07 | 200 |  146.740444ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2361/8417 [27:36<1:19:42,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:08 | 200 |  164.225873ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2362/8417 [27:36<1:18:57,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:09 | 200 |   180.36354ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2363/8417 [27:37<1:19:56,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:09 | 200 |  135.673812ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2364/8417 [27:38<1:19:02,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:10 | 200 |  170.740807ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2365/8417 [27:39<1:20:01,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:11 | 200 |  143.225629ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2366/8417 [27:40<1:19:38,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:12 | 200 |   140.53633ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2367/8417 [27:40<1:19:19,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:13 | 200 |  137.659782ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2368/8417 [27:41<1:18:16,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:13 | 200 |  165.596616ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2369/8417 [27:42<1:18:26,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:14 | 200 |  145.193656ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2370/8417 [27:43<1:18:26,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:15 | 200 |  117.063357ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2371/8417 [27:44<1:17:57,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:16 | 200 |  136.857013ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2372/8417 [27:44<1:18:06,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:16 | 200 |  182.622342ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2373/8417 [27:45<1:18:47,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:17 | 200 |  148.083725ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2374/8417 [27:46<1:17:58,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:18 | 200 |  133.331919ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2375/8417 [27:47<1:17:16,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:19 | 200 |  115.806818ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2376/8417 [27:47<1:16:32,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:19 | 200 |  174.812104ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2377/8417 [27:48<1:17:10,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:20 | 200 |  165.988986ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2378/8417 [27:49<1:17:58,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:21 | 200 |  144.495715ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2379/8417 [27:50<1:18:23,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:22 | 200 |  137.666442ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2380/8417 [27:50<1:17:34,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:23 | 200 |  142.306278ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2381/8417 [27:51<1:17:11,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:23 | 200 |  163.034327ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2382/8417 [27:52<1:17:53,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:24 | 200 |   150.91903ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2383/8417 [27:53<1:18:18,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:25 | 200 |  154.474495ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2384/8417 [27:54<1:18:27,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:26 | 200 |  179.677077ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2385/8417 [27:54<1:19:27,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:27 | 200 |  180.427954ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2386/8417 [27:55<1:19:32,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:27 | 200 |  181.970751ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2387/8417 [27:56<1:19:58,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:28 | 200 |  173.537604ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2388/8417 [27:57<1:19:50,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:29 | 200 |  178.308657ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2389/8417 [27:58<1:20:27,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:30 | 200 |  182.955421ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2390/8417 [27:58<1:20:42,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:31 | 200 |  174.568309ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2391/8417 [27:59<1:20:47,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:31 | 200 |  175.062589ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2392/8417 [28:00<1:20:10,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:32 | 200 |  169.959538ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2393/8417 [28:01<1:20:06,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:33 | 200 |  183.886257ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2394/8417 [28:02<1:20:35,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:34 | 200 |   175.11036ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2395/8417 [28:02<1:20:27,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:35 | 200 |  180.157391ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2396/8417 [28:03<1:20:25,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:35 | 200 |  176.849855ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2397/8417 [28:04<1:20:49,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:36 | 200 |  193.847568ms |       127.0.0.1 | POST     "/api/chat"

 28%|██▊       | 2398/8417 [28:05<1:20:58,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:37 | 200 |  138.363941ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2399/8417 [28:06<1:19:06,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:38 | 200 |  171.305896ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2400/8417 [28:06<1:19:51,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:39 | 200 |  172.088605ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2401/8417 [28:07<1:19:30,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:39 | 200 |   171.10068ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2402/8417 [28:08<1:19:29,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:40 | 200 |  149.699923ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2403/8417 [28:09<1:19:05,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:41 | 200 |  149.661719ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2404/8417 [28:10<1:18:52,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:42 | 200 |  138.219974ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2405/8417 [28:10<1:18:26,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:42 | 200 |  114.075325ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2406/8417 [28:11<1:16:53,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:43 | 200 |  119.717172ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2407/8417 [28:12<1:16:38,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:44 | 200 |  178.286072ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2408/8417 [28:13<1:18:27,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:45 | 200 |  178.725035ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2409/8417 [28:13<1:18:51,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:46 | 200 |  177.254186ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2410/8417 [28:14<1:21:37,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:46 | 200 |  153.068095ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2411/8417 [28:15<1:20:26,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:47 | 200 |  144.593853ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2412/8417 [28:16<1:19:43,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:48 | 200 |  143.020018ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2413/8417 [28:17<1:19:32,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:49 | 200 |  176.239556ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2414/8417 [28:17<1:20:16,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:50 | 200 |  178.044414ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2415/8417 [28:18<1:20:14,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:50 | 200 |  145.565444ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2416/8417 [28:19<1:20:33,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:51 | 200 |  174.456719ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2417/8417 [28:20<1:20:22,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:52 | 200 |  165.552916ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2418/8417 [28:21<1:20:08,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:53 | 200 |  163.783924ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▊       | 2419/8417 [28:21<1:19:40,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:54 | 200 |  182.834334ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2420/8417 [28:22<1:20:06,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:54 | 200 |  139.663793ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2421/8417 [28:23<1:19:37,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:55 | 200 |  170.093049ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2422/8417 [28:24<1:20:32,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:56 | 200 |  177.456883ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2423/8417 [28:25<1:20:48,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:57 | 200 |  163.812195ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2424/8417 [28:25<1:19:57,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:58 | 200 |   129.24023ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2425/8417 [28:26<1:18:09,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:58 | 200 |  144.541534ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2426/8417 [28:27<1:17:15,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:52:59 | 200 |  165.476101ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2427/8417 [28:28<1:17:28,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:00 | 200 |  119.314556ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2428/8417 [28:29<1:16:20,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:01 | 200 |  120.312995ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2429/8417 [28:29<1:16:06,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:01 | 200 |  177.675526ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2430/8417 [28:30<1:16:41,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:02 | 200 |  129.709227ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2431/8417 [28:31<1:15:48,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:03 | 200 |  152.636863ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2432/8417 [28:32<1:15:40,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:04 | 200 |  150.481276ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2433/8417 [28:32<1:15:54,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:04 | 200 |  125.443496ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2434/8417 [28:33<1:15:38,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:05 | 200 |  176.409628ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2435/8417 [28:34<1:16:58,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:06 | 200 |  156.192073ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2436/8417 [28:35<1:17:05,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:07 | 200 |  135.899185ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2437/8417 [28:35<1:16:45,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:08 | 200 |  157.466233ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2438/8417 [28:36<1:17:34,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:08 | 200 |  151.907525ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2439/8417 [28:37<1:17:22,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:09 | 200 |  164.353051ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2440/8417 [28:38<1:17:59,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:10 | 200 |  146.817181ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2441/8417 [28:39<1:17:57,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:11 | 200 |  148.366058ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2442/8417 [28:39<1:17:58,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:11 | 200 |  143.645586ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2443/8417 [28:40<1:17:20,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:12 | 200 |  181.687012ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2444/8417 [28:41<1:18:23,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:13 | 200 |  173.838674ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2445/8417 [28:42<1:18:22,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:14 | 200 |  169.769963ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2446/8417 [28:42<1:18:26,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:15 | 200 |  143.470778ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2447/8417 [28:43<1:17:36,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:15 | 200 |  137.709196ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2448/8417 [28:44<1:16:48,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:16 | 200 |  140.687009ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2449/8417 [28:45<1:16:33,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:17 | 200 |  162.113715ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2450/8417 [28:46<1:17:27,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:18 | 200 |  179.631718ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2451/8417 [28:46<1:18:26,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:19 | 200 |  168.071883ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2452/8417 [28:47<1:18:15,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:19 | 200 |  168.664349ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2453/8417 [28:48<1:18:30,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:20 | 200 |   179.19584ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2454/8417 [28:49<1:19:22,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:21 | 200 |  178.591986ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2455/8417 [28:50<1:19:59,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:22 | 200 |   126.80135ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2456/8417 [28:50<1:18:44,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:23 | 200 |  173.974117ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2457/8417 [28:51<1:18:50,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:23 | 200 |  175.829036ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2458/8417 [28:52<1:18:53,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:24 | 200 |  181.508954ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2459/8417 [28:53<1:19:02,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:25 | 200 |  181.774371ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2460/8417 [28:54<1:20:22,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:26 | 200 |  176.871202ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2461/8417 [28:54<1:20:14,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:27 | 200 |  178.100087ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2462/8417 [28:55<1:19:40,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:27 | 200 |  181.451562ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2463/8417 [28:56<1:19:35,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:28 | 200 |  142.120339ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2464/8417 [28:57<1:18:33,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:29 | 200 |  175.036798ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2465/8417 [28:58<1:18:45,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:30 | 200 |  131.542845ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2466/8417 [28:58<1:17:19,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:30 | 200 |  169.456705ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2467/8417 [28:59<1:18:46,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:31 | 200 |  139.614982ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2468/8417 [29:00<1:17:59,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:32 | 200 |  138.972821ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2469/8417 [29:01<1:16:47,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:33 | 200 |  138.967378ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2470/8417 [29:01<1:16:26,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:34 | 200 |  162.578175ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2471/8417 [29:02<1:17:03,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:34 | 200 |  173.906508ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2472/8417 [29:03<1:18:13,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:35 | 200 |   174.34424ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2473/8417 [29:04<1:19:09,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:36 | 200 |  160.129909ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2474/8417 [29:05<1:19:12,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:37 | 200 |  162.145971ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2475/8417 [29:05<1:18:38,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:38 | 200 |  178.484776ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2476/8417 [29:06<1:18:24,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:38 | 200 |  141.277393ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2477/8417 [29:07<1:17:40,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:39 | 200 |  141.303775ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2478/8417 [29:08<1:17:36,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:40 | 200 |  140.900542ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2479/8417 [29:09<1:17:28,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:41 | 200 |  142.552077ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2480/8417 [29:09<1:17:12,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:41 | 200 |  173.361188ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2481/8417 [29:10<1:18:17,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:42 | 200 |  145.312053ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2482/8417 [29:11<1:17:35,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:43 | 200 |  142.958997ms |       127.0.0.1 | POST     "/api/chat"

 29%|██▉       | 2483/8417 [29:12<1:18:00,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:44 | 200 |  141.175016ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2484/8417 [29:12<1:17:17,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:45 | 200 |  164.094578ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2485/8417 [29:13<1:17:56,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:45 | 200 |  153.786358ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2486/8417 [29:14<1:17:52,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:46 | 200 |  148.208636ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2487/8417 [29:15<1:17:53,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:47 | 200 |  142.719588ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2488/8417 [29:16<1:16:40,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:48 | 200 |  178.492345ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2489/8417 [29:16<1:17:29,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:49 | 200 |   152.25859ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2490/8417 [29:17<1:17:48,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:49 | 200 |  117.156659ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2491/8417 [29:18<1:17:15,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:50 | 200 |  137.620643ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2492/8417 [29:19<1:16:51,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:51 | 200 |  165.579177ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2493/8417 [29:20<1:17:14,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:52 | 200 |   148.19803ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2494/8417 [29:20<1:17:19,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:52 | 200 |  142.860167ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2495/8417 [29:21<1:17:01,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:53 | 200 |  142.790731ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2496/8417 [29:22<1:16:49,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:54 | 200 |  181.811195ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2497/8417 [29:23<1:17:18,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:55 | 200 |  174.730354ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2498/8417 [29:23<1:17:45,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:56 | 200 |  164.154667ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2499/8417 [29:24<1:18:01,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:56 | 200 |  159.766765ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2500/8417 [29:25<1:19:53,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:57 | 200 |  164.738522ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2501/8417 [29:26<1:18:59,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:58 | 200 |  178.787339ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2502/8417 [29:27<1:19:14,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:53:59 | 200 |  175.989411ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2503/8417 [29:28<1:19:30,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:00 | 200 |  175.023142ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2504/8417 [29:28<1:19:29,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:00 | 200 |   181.02704ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2505/8417 [29:29<1:19:56,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:01 | 200 |  176.048909ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2506/8417 [29:30<1:20:05,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:02 | 200 |  153.407817ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2507/8417 [29:31<1:19:55,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:03 | 200 |  140.083438ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2508/8417 [29:32<1:18:39,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:04 | 200 |  138.946283ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2509/8417 [29:32<1:18:42,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:04 | 200 |  128.949516ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2510/8417 [29:33<1:17:13,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:05 | 200 |  181.903684ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2511/8417 [29:34<1:17:46,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:06 | 200 |   167.73167ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2512/8417 [29:35<1:18:19,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:07 | 200 |  165.502362ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2513/8417 [29:35<1:18:05,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:08 | 200 |  161.090984ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2514/8417 [29:36<1:17:48,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:08 | 200 |  145.540998ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2515/8417 [29:37<1:17:04,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:09 | 200 |  137.162827ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2516/8417 [29:38<1:16:41,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:10 | 200 |  137.743551ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2517/8417 [29:39<1:16:26,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:11 | 200 |  169.499932ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2518/8417 [29:39<1:17:49,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:12 | 200 |  150.409349ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2519/8417 [29:40<1:17:33,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:12 | 200 |  143.229928ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2520/8417 [29:41<1:16:48,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:13 | 200 |  144.104763ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2521/8417 [29:42<1:16:28,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:14 | 200 |  181.389895ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2522/8417 [29:43<1:17:07,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:15 | 200 |  174.055812ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2523/8417 [29:43<1:19:14,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:16 | 200 |  164.284184ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2524/8417 [29:44<1:18:38,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:16 | 200 |  162.129092ms |       127.0.0.1 | POST     "/api/chat"

 30%|██▉       | 2525/8417 [29:45<1:18:30,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:17 | 200 |  176.042625ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2526/8417 [29:46<1:18:15,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:18 | 200 |  175.366903ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2527/8417 [29:47<1:18:00,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:19 | 200 |  140.411928ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2528/8417 [29:47<1:17:06,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:19 | 200 |  176.365234ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2529/8417 [29:48<1:17:54,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:20 | 200 |  146.358982ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2530/8417 [29:49<1:17:56,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:21 | 200 |  144.095687ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2531/8417 [29:50<1:17:38,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:22 | 200 |  113.578176ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2532/8417 [29:50<1:16:10,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:23 | 200 |  142.878759ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2533/8417 [29:51<1:16:17,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:23 | 200 |  177.563154ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2534/8417 [29:52<1:17:31,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:24 | 200 |  146.947912ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2535/8417 [29:53<1:17:22,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:25 | 200 |  148.562942ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2536/8417 [29:54<1:17:07,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:26 | 200 |  141.881376ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2537/8417 [29:54<1:17:35,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:27 | 200 |  168.694086ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2538/8417 [29:55<1:18:16,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:27 | 200 |  161.285438ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2539/8417 [29:56<1:18:49,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:28 | 200 |  146.169752ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2540/8417 [29:57<1:18:04,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:29 | 200 |  141.461358ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2541/8417 [29:58<1:17:35,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:30 | 200 |  143.551656ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2542/8417 [29:58<1:17:10,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:31 | 200 |  142.059376ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2543/8417 [29:59<1:17:45,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:31 | 200 |  179.988024ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2544/8417 [30:00<1:18:45,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:32 | 200 |  177.515086ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2545/8417 [30:01<1:18:47,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:33 | 200 |  179.127512ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2546/8417 [30:02<1:18:51,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:34 | 200 |  176.546368ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2547/8417 [30:02<1:18:52,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:35 | 200 |  140.494342ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2548/8417 [30:03<1:17:41,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:35 | 200 |  170.222406ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2549/8417 [30:04<1:17:54,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:36 | 200 |  188.468614ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2550/8417 [30:05<1:18:45,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:37 | 200 |  177.466614ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2551/8417 [30:06<1:20:19,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:38 | 200 |  145.093513ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2552/8417 [30:07<1:19:58,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:39 | 200 |  143.382678ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2553/8417 [30:07<1:19:19,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:39 | 200 |   149.49693ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2554/8417 [30:08<1:19:07,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:40 | 200 |   165.02336ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2555/8417 [30:09<1:19:52,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:41 | 200 |  125.827361ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2556/8417 [30:10<1:18:41,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:42 | 200 |  143.773127ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2557/8417 [30:11<1:19:47,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:43 | 200 |   184.12965ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2558/8417 [30:11<1:20:01,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:44 | 200 |  146.062138ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2559/8417 [30:12<1:19:11,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:44 | 200 |  140.598249ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2560/8417 [30:13<1:18:42,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:45 | 200 |  146.913263ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2561/8417 [30:14<1:17:56,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:46 | 200 |  158.772915ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2562/8417 [30:15<1:17:42,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:47 | 200 |   142.36282ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2563/8417 [30:15<1:16:54,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:47 | 200 |  117.443112ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2564/8417 [30:16<1:15:15,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 30%|███       | 2565/8417 [30:17<1:14:02,  1.32it/s]

[GIN] 2025/06/26 - 23:54:48 | 200 |  114.510025ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:49 | 200 |  142.203656ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2566/8417 [30:18<1:14:02,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:50 | 200 |  139.876514ms |       127.0.0.1 | POST     "/api/chat"

 30%|███       | 2567/8417 [30:18<1:13:59,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:50 | 200 |  148.538758ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2568/8417 [30:19<1:15:04,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:51 | 200 |  147.453972ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2569/8417 [30:20<1:15:00,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:52 | 200 |  143.409032ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2570/8417 [30:21<1:14:59,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:53 | 200 |  138.053608ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2571/8417 [30:21<1:14:51,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:54 | 200 |  143.289962ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2572/8417 [30:22<1:14:22,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:54 | 200 |  140.057074ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2573/8417 [30:23<1:14:22,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:55 | 200 |  139.528477ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2574/8417 [30:24<1:14:17,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:56 | 200 |  139.737551ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2575/8417 [30:24<1:14:08,  1.31it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:57 | 200 |  174.233618ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2576/8417 [30:25<1:15:06,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:57 | 200 |  146.948631ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2577/8417 [30:26<1:15:07,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:58 | 200 |  131.818825ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2578/8417 [30:27<1:14:46,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:54:59 | 200 |  112.552798ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2579/8417 [30:28<1:13:53,  1.32it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:00 | 200 |  177.348534ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2580/8417 [30:28<1:15:21,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:00 | 200 |  182.864571ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2581/8417 [30:29<1:17:09,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:01 | 200 |  178.429041ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2582/8417 [30:30<1:17:18,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:02 | 200 |  160.289999ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2583/8417 [30:31<1:16:54,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:03 | 200 |  165.552622ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2584/8417 [30:32<1:16:48,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:04 | 200 |  183.765952ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2585/8417 [30:32<1:17:34,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:04 | 200 |  183.168497ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2586/8417 [30:33<1:17:51,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:05 | 200 |  142.709073ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2587/8417 [30:34<1:16:35,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:06 | 200 |  145.300744ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2588/8417 [30:35<1:16:02,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:07 | 200 |  175.532611ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2589/8417 [30:35<1:16:52,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:08 | 200 |   148.21846ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2590/8417 [30:36<1:16:20,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:08 | 200 |   115.28976ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2591/8417 [30:37<1:14:44,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:09 | 200 |  139.733508ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2592/8417 [30:38<1:14:55,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:10 | 200 |  137.223394ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2593/8417 [30:39<1:15:11,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:11 | 200 |  145.727966ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2594/8417 [30:39<1:15:52,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:11 | 200 |   180.82366ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2595/8417 [30:40<1:16:49,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:12 | 200 |  188.935934ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2596/8417 [30:41<1:17:53,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:13 | 200 |  177.941266ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2597/8417 [30:42<1:18:45,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:14 | 200 |  173.729442ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2598/8417 [30:43<1:18:50,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:15 | 200 |  135.814652ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2599/8417 [30:43<1:17:48,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:16 | 200 |  144.195179ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2600/8417 [30:44<1:17:35,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:16 | 200 |  163.960196ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2601/8417 [30:45<1:17:58,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:17 | 200 |  149.817098ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2602/8417 [30:46<1:17:43,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:18 | 200 |  140.228982ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2603/8417 [30:47<1:16:39,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:19 | 200 |   139.65242ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2604/8417 [30:47<1:16:17,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:20 | 200 |  176.441532ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2605/8417 [30:48<1:16:54,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:20 | 200 |  180.024219ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2606/8417 [30:49<1:18:50,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:21 | 200 |  186.675459ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2607/8417 [30:50<1:19:47,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:22 | 200 |  146.500022ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2608/8417 [30:51<1:18:35,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:23 | 200 |  147.179341ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2609/8417 [30:51<1:18:23,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:24 | 200 |  147.818496ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2610/8417 [30:52<1:17:39,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:24 | 200 |  157.826509ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2611/8417 [30:53<1:17:43,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:25 | 200 |  147.674449ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2612/8417 [30:54<1:17:08,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:26 | 200 |  151.076828ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2613/8417 [30:55<1:16:51,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:27 | 200 |  142.968782ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2614/8417 [30:55<1:16:07,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:28 | 200 |  177.247527ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2615/8417 [30:56<1:16:22,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:28 | 200 |  181.144403ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2616/8417 [30:57<1:17:14,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:29 | 200 |  177.823932ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2617/8417 [30:58<1:18:10,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:30 | 200 |  168.068161ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2618/8417 [30:59<1:18:05,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:31 | 200 |  178.820047ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2619/8417 [30:59<1:18:37,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:32 | 200 |  147.832429ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2620/8417 [31:00<1:17:35,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:32 | 200 |  142.806942ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2621/8417 [31:01<1:16:20,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:33 | 200 |  119.524249ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2622/8417 [31:02<1:15:04,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:34 | 200 |  176.810274ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2623/8417 [31:03<1:15:51,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:35 | 200 |  152.635044ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2624/8417 [31:03<1:16:30,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:35 | 200 |  144.285473ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2625/8417 [31:04<1:16:19,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:36 | 200 |  137.957672ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2626/8417 [31:05<1:15:40,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:37 | 200 |  138.862119ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2627/8417 [31:06<1:16:32,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:38 | 200 |  162.782997ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2628/8417 [31:07<1:16:30,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:39 | 200 |  143.486332ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2629/8417 [31:07<1:15:40,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:39 | 200 |  114.730987ms |       127.0.0.1 | POST     "/api/chat"

 31%|███       | 2630/8417 [31:08<1:14:27,  1.30it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:40 | 200 |  143.598174ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2631/8417 [31:09<1:15:06,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:41 | 200 |  178.296728ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2632/8417 [31:10<1:16:14,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:42 | 200 |  180.198466ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2633/8417 [31:10<1:16:53,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:43 | 200 |  176.522521ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2634/8417 [31:11<1:18:00,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:43 | 200 |  155.708047ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2635/8417 [31:12<1:17:55,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:44 | 200 |  152.035038ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2636/8417 [31:13<1:17:35,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:45 | 200 |  140.363907ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2637/8417 [31:14<1:19:09,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:46 | 200 |  143.747365ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2638/8417 [31:15<1:18:09,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:47 | 200 |  118.238585ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2639/8417 [31:15<1:16:29,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:47 | 200 |  139.629022ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2640/8417 [31:16<1:16:19,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:48 | 200 |  135.889236ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2641/8417 [31:17<1:15:58,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:49 | 200 |  175.810908ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2642/8417 [31:18<1:16:41,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:50 | 200 |  167.580643ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2643/8417 [31:18<1:16:28,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:51 | 200 |   173.30044ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2644/8417 [31:19<1:17:11,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:51 | 200 |  179.927377ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2645/8417 [31:20<1:17:28,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:52 | 200 |  135.181969ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2646/8417 [31:21<1:16:37,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:53 | 200 |  167.544905ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2647/8417 [31:22<1:16:52,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:54 | 200 |  178.304327ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2648/8417 [31:23<1:18:21,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:55 | 200 |   148.32836ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2649/8417 [31:23<1:17:52,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:55 | 200 |  141.868117ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2650/8417 [31:24<1:16:49,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:56 | 200 |  143.629229ms |       127.0.0.1 | POST     "/api/chat"

 31%|███▏      | 2651/8417 [31:25<1:15:50,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:57 | 200 |   174.90213ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2652/8417 [31:26<1:16:08,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:58 | 200 |  178.260683ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2653/8417 [31:27<1:16:59,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:59 | 200 |  179.136113ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2654/8417 [31:27<1:17:24,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:55:59 | 200 |  170.068745ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2655/8417 [31:28<1:18:04,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:00 | 200 |  153.415312ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2656/8417 [31:29<1:17:47,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:01 | 200 |  145.400183ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2657/8417 [31:30<1:16:54,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:02 | 200 |  146.470731ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2658/8417 [31:31<1:17:00,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:03 | 200 |  161.909326ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2659/8417 [31:31<1:16:40,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:03 | 200 |  179.086798ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2660/8417 [31:32<1:16:51,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:04 | 200 |  140.087158ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2661/8417 [31:33<1:16:09,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:05 | 200 |  134.655663ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2662/8417 [31:34<1:15:36,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:06 | 200 |  147.488548ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2663/8417 [31:35<1:16:32,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:07 | 200 |  180.978277ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2664/8417 [31:35<1:16:53,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:07 | 200 |  141.801742ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2665/8417 [31:36<1:16:10,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:08 | 200 |   142.05649ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2666/8417 [31:37<1:15:22,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:09 | 200 |  141.454704ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2667/8417 [31:38<1:14:37,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:10 | 200 |  170.398028ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2668/8417 [31:38<1:15:21,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:11 | 200 |  157.735596ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2669/8417 [31:39<1:16:05,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:11 | 200 |  135.963408ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2670/8417 [31:40<1:15:20,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:12 | 200 |  145.936939ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2671/8417 [31:41<1:14:59,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:13 | 200 |   165.06338ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2672/8417 [31:42<1:15:35,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:14 | 200 |  151.589936ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2673/8417 [31:42<1:15:52,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:15 | 200 |  141.044232ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2674/8417 [31:43<1:15:06,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:15 | 200 |  144.801947ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2675/8417 [31:44<1:14:59,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:16 | 200 |  180.603981ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2676/8417 [31:45<1:16:34,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:17 | 200 |  163.407911ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2677/8417 [31:46<1:17:50,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:18 | 200 |   192.34239ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2678/8417 [31:46<1:19:09,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:19 | 200 |  150.449115ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2679/8417 [31:47<1:18:35,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:19 | 200 |  139.877409ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2680/8417 [31:48<1:17:25,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:20 | 200 |   138.39606ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2681/8417 [31:49<1:17:06,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:21 | 200 |  166.483387ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2682/8417 [31:50<1:17:07,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:22 | 200 |  147.159811ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2683/8417 [31:50<1:16:17,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:23 | 200 |  143.281351ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2684/8417 [31:51<1:17:56,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:23 | 200 |  141.738246ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2685/8417 [31:52<1:16:48,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:24 | 200 |  147.940861ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2686/8417 [31:53<1:17:22,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:25 | 200 |  159.901261ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2687/8417 [31:54<1:17:03,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:26 | 200 |  139.491436ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2688/8417 [31:55<1:16:45,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:27 | 200 |   136.82219ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2689/8417 [31:55<1:15:54,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:27 | 200 |  140.684201ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2690/8417 [31:56<1:15:30,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:28 | 200 |  166.922498ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2691/8417 [31:57<1:15:51,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:29 | 200 |  147.145895ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2692/8417 [31:58<1:15:36,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:30 | 200 |  143.966901ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2693/8417 [31:58<1:15:47,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:31 | 200 |  134.194249ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2694/8417 [31:59<1:17:10,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:31 | 200 |  174.941032ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2695/8417 [32:00<1:17:35,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:32 | 200 |  140.979585ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2696/8417 [32:01<1:16:26,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:33 | 200 |  141.461604ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2697/8417 [32:02<1:15:27,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:34 | 200 |  144.527199ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2698/8417 [32:02<1:15:23,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:35 | 200 |   162.71095ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2699/8417 [32:03<1:15:38,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:35 | 200 |  152.251225ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2700/8417 [32:04<1:16:58,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:36 | 200 |  145.016841ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2701/8417 [32:05<1:16:53,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:37 | 200 |  153.263638ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2702/8417 [32:06<1:16:20,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:38 | 200 |   134.49447ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2703/8417 [32:06<1:15:22,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:39 | 200 |  177.654886ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2704/8417 [32:07<1:15:46,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:39 | 200 |  134.751221ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2705/8417 [32:08<1:14:58,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:40 | 200 |  132.387229ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2706/8417 [32:09<1:14:40,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:41 | 200 |  187.407384ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2707/8417 [32:10<1:16:26,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:42 | 200 |  184.965642ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2708/8417 [32:11<1:17:16,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:43 | 200 |  132.512901ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2709/8417 [32:11<1:16:11,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:43 | 200 |  161.889522ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2710/8417 [32:12<1:16:26,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:44 | 200 |  180.801753ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2711/8417 [32:13<1:17:13,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:45 | 200 |  154.470744ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2712/8417 [32:14<1:17:01,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:46 | 200 |  119.790859ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2713/8417 [32:14<1:15:45,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:47 | 200 |  146.654095ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2714/8417 [32:15<1:15:37,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:47 | 200 |    178.3621ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2715/8417 [32:16<1:16:12,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:48 | 200 |   187.85453ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2716/8417 [32:17<1:18:06,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:49 | 200 |  150.506558ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2717/8417 [32:18<1:17:58,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:50 | 200 |  156.494104ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2718/8417 [32:19<1:17:31,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:51 | 200 |  148.008831ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2719/8417 [32:19<1:17:28,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:52 | 200 |  140.563259ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2720/8417 [32:20<1:16:46,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:52 | 200 |  147.255127ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2721/8417 [32:21<1:16:22,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:53 | 200 |  163.800996ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2722/8417 [32:22<1:16:27,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:54 | 200 |  141.141134ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2723/8417 [32:23<1:15:30,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:55 | 200 |  149.843256ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2724/8417 [32:23<1:15:15,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:55 | 200 |  142.692879ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2725/8417 [32:24<1:14:44,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:56 | 200 |  132.811331ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2726/8417 [32:25<1:14:09,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:57 | 200 |  139.478908ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2727/8417 [32:26<1:13:37,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:58 | 200 |  181.313842ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2728/8417 [32:27<1:15:40,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:56:59 | 200 |  145.422214ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2729/8417 [32:27<1:16:10,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:00 | 200 |  180.674061ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2730/8417 [32:28<1:17:49,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:00 | 200 |  123.893514ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2731/8417 [32:29<1:17:21,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:01 | 200 |  142.418102ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2732/8417 [32:30<1:16:29,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:02 | 200 |   143.72916ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2733/8417 [32:31<1:16:00,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:03 | 200 |  139.450025ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2734/8417 [32:31<1:15:34,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:04 | 200 |  172.777094ms |       127.0.0.1 | POST     "/api/chat"

 32%|███▏      | 2735/8417 [32:32<1:16:16,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:04 | 200 |  146.751829ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2736/8417 [32:33<1:16:48,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:05 | 200 |  150.579114ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2737/8417 [32:34<1:16:15,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:06 | 200 |   145.51013ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2738/8417 [32:35<1:15:43,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:07 | 200 |  169.080933ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2739/8417 [32:35<1:15:51,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:08 | 200 |  143.045074ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2740/8417 [32:36<1:15:02,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:08 | 200 |  139.216115ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2741/8417 [32:37<1:14:17,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:09 | 200 |  141.791551ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2742/8417 [32:38<1:13:55,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:10 | 200 |   138.14593ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2743/8417 [32:38<1:13:47,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:11 | 200 |  152.830732ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2744/8417 [32:39<1:14:24,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:11 | 200 |  139.081405ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2745/8417 [32:40<1:13:44,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:12 | 200 |  142.195067ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2746/8417 [32:41<1:13:50,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:13 | 200 |  168.185574ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2747/8417 [32:42<1:14:47,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:14 | 200 |  151.212315ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2748/8417 [32:42<1:15:10,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:15 | 200 |  146.960034ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2749/8417 [32:43<1:15:04,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:15 | 200 |  142.026247ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2750/8417 [32:44<1:14:58,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:16 | 200 |  154.855365ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2751/8417 [32:45<1:15:22,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:17 | 200 |  166.452518ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2752/8417 [32:46<1:16:47,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:18 | 200 |  141.504134ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2753/8417 [32:47<1:16:21,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:19 | 200 |  143.395267ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2754/8417 [32:47<1:16:47,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:19 | 200 |  134.296181ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2755/8417 [32:48<1:17:01,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:20 | 200 |  181.316585ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2756/8417 [32:49<1:18:43,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:21 | 200 |  189.627647ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2757/8417 [32:50<1:18:41,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:22 | 200 |  151.056714ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2758/8417 [32:51<1:17:24,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:23 | 200 |  146.390731ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2759/8417 [32:51<1:16:32,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:24 | 200 |  140.609134ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2760/8417 [32:52<1:15:56,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:24 | 200 |  133.441498ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2761/8417 [32:53<1:15:27,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:25 | 200 |  180.147149ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2762/8417 [32:54<1:15:33,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:26 | 200 |  142.869929ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2763/8417 [32:55<1:15:01,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:27 | 200 |  145.599181ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2764/8417 [32:55<1:14:46,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:28 | 200 |  144.753412ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2765/8417 [32:56<1:14:26,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:28 | 200 |  179.481602ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2766/8417 [32:57<1:15:05,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:29 | 200 |   161.73179ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2767/8417 [32:58<1:15:03,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:30 | 200 |  124.992071ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2768/8417 [32:59<1:14:09,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:31 | 200 |   124.80697ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2769/8417 [32:59<1:13:43,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:31 | 200 |  179.106882ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2770/8417 [33:00<1:14:21,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:32 | 200 |  120.555223ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2771/8417 [33:01<1:13:01,  1.29it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:33 | 200 |  146.920266ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2772/8417 [33:02<1:13:57,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:34 | 200 |  140.682818ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2773/8417 [33:02<1:13:44,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:35 | 200 |  145.220956ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2774/8417 [33:03<1:13:37,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:35 | 200 |  178.759947ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2775/8417 [33:04<1:14:27,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:36 | 200 |  142.077063ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2776/8417 [33:05<1:14:00,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:37 | 200 |  176.742315ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2777/8417 [33:06<1:15:00,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:38 | 200 |  142.006246ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2778/8417 [33:06<1:14:27,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:39 | 200 |  174.386231ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2779/8417 [33:07<1:15:11,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:39 | 200 |  174.590047ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2780/8417 [33:08<1:15:59,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:40 | 200 |   172.05923ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2781/8417 [33:09<1:16:37,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:41 | 200 |  166.601865ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2782/8417 [33:10<1:16:37,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:42 | 200 |  152.544973ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2783/8417 [33:11<1:15:42,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:43 | 200 |   141.54939ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2784/8417 [33:11<1:15:09,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:43 | 200 |  146.939645ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2785/8417 [33:12<1:14:59,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:44 | 200 |  171.441496ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2786/8417 [33:13<1:16:03,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:45 | 200 |  153.016545ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2787/8417 [33:14<1:15:21,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:46 | 200 |  149.664416ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2788/8417 [33:15<1:15:18,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:47 | 200 |  140.695776ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2789/8417 [33:15<1:15:01,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:47 | 200 |  169.309194ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2790/8417 [33:16<1:15:06,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:48 | 200 |  147.634488ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2791/8417 [33:17<1:14:31,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:49 | 200 |  157.510494ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2792/8417 [33:18<1:14:51,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:50 | 200 |  177.419037ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2793/8417 [33:19<1:15:46,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:51 | 200 |  173.805259ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2794/8417 [33:19<1:16:29,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:51 | 200 |  152.875512ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2795/8417 [33:20<1:17:33,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:52 | 200 |  159.191735ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2796/8417 [33:21<1:17:34,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:53 | 200 |  143.670496ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2797/8417 [33:22<1:16:29,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:54 | 200 |   143.24268ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2798/8417 [33:23<1:15:46,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:55 | 200 |  156.430671ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2799/8417 [33:23<1:15:38,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:56 | 200 |  140.914651ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2800/8417 [33:24<1:15:08,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:56 | 200 |  115.973501ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2801/8417 [33:25<1:13:50,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:57 | 200 |   137.75031ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2802/8417 [33:26<1:13:31,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:58 | 200 |  134.191303ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2803/8417 [33:27<1:13:07,  1.28it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:57:59 | 200 |  178.105716ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2804/8417 [33:27<1:14:07,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:00 | 200 |   181.18513ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2805/8417 [33:28<1:15:34,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:00 | 200 |  146.464284ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2806/8417 [33:29<1:15:52,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:01 | 200 |  145.206179ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2807/8417 [33:30<1:15:25,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:02 | 200 |  144.233176ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2808/8417 [33:31<1:14:55,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:03 | 200 |  167.055899ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2809/8417 [33:31<1:15:27,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:04 | 200 |  144.869793ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2810/8417 [33:32<1:15:22,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:04 | 200 |  144.060371ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2811/8417 [33:33<1:14:41,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:05 | 200 |  139.531915ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2812/8417 [33:34<1:15:14,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:06 | 200 |  167.048797ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2813/8417 [33:35<1:15:33,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:07 | 200 |   155.30162ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2814/8417 [33:36<1:16:52,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:08 | 200 |  147.563302ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2815/8417 [33:36<1:15:55,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:08 | 200 |  137.540573ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2816/8417 [33:37<1:14:43,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:09 | 200 |  140.887071ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2817/8417 [33:38<1:14:16,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:10 | 200 |  158.598889ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2818/8417 [33:39<1:14:47,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:11 | 200 |  162.751148ms |       127.0.0.1 | POST     "/api/chat"

 33%|███▎      | 2819/8417 [33:39<1:15:33,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:12 | 200 |  143.479975ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2820/8417 [33:40<1:15:19,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:12 | 200 |  137.642992ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2821/8417 [33:41<1:14:47,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:13 | 200 |  140.056249ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2822/8417 [33:42<1:14:45,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:14 | 200 |  161.309219ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2823/8417 [33:43<1:15:22,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:15 | 200 |  143.668195ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2824/8417 [33:44<1:14:47,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:16 | 200 |  132.166515ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2825/8417 [33:44<1:14:32,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:16 | 200 |  142.021068ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2826/8417 [33:45<1:14:18,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:17 | 200 |  164.793975ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2827/8417 [33:46<1:14:23,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:18 | 200 |  136.895929ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2828/8417 [33:47<1:13:46,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:19 | 200 |  146.107065ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2829/8417 [33:47<1:13:45,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:20 | 200 |  140.967738ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2830/8417 [33:48<1:13:56,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:20 | 200 |  140.191199ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2831/8417 [33:49<1:14:33,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:21 | 200 |  161.084083ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2832/8417 [33:50<1:15:00,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:22 | 200 |  143.015553ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2833/8417 [33:51<1:14:16,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:23 | 200 |  139.511115ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2834/8417 [33:52<1:15:19,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:24 | 200 |  165.059849ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2835/8417 [33:52<1:15:59,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:24 | 200 |  175.098203ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2836/8417 [33:53<1:16:02,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:25 | 200 |  143.748059ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2837/8417 [33:54<1:15:24,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:26 | 200 |  138.978066ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2838/8417 [33:55<1:14:49,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:27 | 200 |   113.78876ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2839/8417 [33:56<1:13:34,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:28 | 200 |  150.204784ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▎      | 2840/8417 [33:56<1:13:39,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:28 | 200 |   179.68336ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2841/8417 [33:57<1:15:07,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:29 | 200 |  142.806968ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2842/8417 [33:58<1:15:00,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:30 | 200 |  145.356178ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2843/8417 [33:59<1:14:57,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:31 | 200 |  139.530188ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2844/8417 [34:00<1:14:32,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:32 | 200 |   126.80887ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2845/8417 [34:00<1:14:21,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:33 | 200 |  175.355385ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2846/8417 [34:01<1:15:57,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:33 | 200 |  148.294729ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2847/8417 [34:02<1:15:20,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:34 | 200 |  148.323401ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2848/8417 [34:03<1:14:48,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:35 | 200 |  144.314721ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2849/8417 [34:04<1:14:25,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:36 | 200 |  141.000079ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2850/8417 [34:04<1:14:06,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:37 | 200 |  161.139527ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2851/8417 [34:05<1:14:16,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:37 | 200 |   142.88298ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2852/8417 [34:06<1:13:58,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:38 | 200 |  139.003881ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2853/8417 [34:07<1:13:53,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:39 | 200 |  137.210448ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2854/8417 [34:08<1:13:41,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:40 | 200 |   138.44991ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2855/8417 [34:08<1:13:25,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:40 | 200 |  128.194681ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2856/8417 [34:09<1:13:46,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:41 | 200 |   181.76474ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2857/8417 [34:10<1:14:39,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:42 | 200 |   150.02962ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2858/8417 [34:11<1:14:09,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:43 | 200 |  143.067648ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2859/8417 [34:12<1:13:43,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:44 | 200 |  142.281458ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2860/8417 [34:12<1:13:23,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:44 | 200 |  158.959269ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2861/8417 [34:13<1:13:30,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:45 | 200 |  144.644203ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2862/8417 [34:14<1:14:25,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:46 | 200 |  123.341619ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2863/8417 [34:15<1:13:19,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:47 | 200 |  141.353712ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2864/8417 [34:16<1:13:51,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:48 | 200 |  180.844732ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2865/8417 [34:16<1:14:56,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:49 | 200 |  146.499253ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2866/8417 [34:17<1:15:15,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:49 | 200 |  142.075363ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2867/8417 [34:18<1:14:41,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:50 | 200 |  145.606529ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2868/8417 [34:19<1:14:32,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:51 | 200 |  142.737923ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2869/8417 [34:20<1:14:23,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:52 | 200 |   133.11727ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2870/8417 [34:20<1:14:12,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:53 | 200 |  175.082656ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2871/8417 [34:21<1:14:36,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:53 | 200 |  121.865408ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2872/8417 [34:22<1:13:25,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 34%|███▍      | 2873/8417 [34:23<1:12:59,  1.27it/s]

[GIN] 2025/06/26 - 23:58:54 | 200 |  127.528296ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:55 | 200 |  193.032671ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2874/8417 [34:24<1:15:35,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:56 | 200 |  173.118631ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2875/8417 [34:24<1:16:08,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:57 | 200 |  138.366221ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2876/8417 [34:25<1:15:10,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:57 | 200 |  147.731575ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2877/8417 [34:26<1:14:31,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:58 | 200 |  141.562442ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2878/8417 [34:27<1:14:16,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:58:59 | 200 |  137.361528ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2879/8417 [34:28<1:14:00,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:00 | 200 |  142.552635ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2880/8417 [34:28<1:14:02,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:01 | 200 |  165.107979ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2881/8417 [34:29<1:14:46,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:01 | 200 |  141.648904ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2882/8417 [34:30<1:14:24,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:02 | 200 |   141.43639ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2883/8417 [34:31<1:13:50,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:03 | 200 |    139.3191ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2884/8417 [34:32<1:13:49,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:04 | 200 |  141.709365ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2885/8417 [34:32<1:14:10,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:05 | 200 |  143.266405ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2886/8417 [34:33<1:13:41,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:05 | 200 |  135.802092ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2887/8417 [34:34<1:13:52,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:06 | 200 |  158.903007ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2888/8417 [34:35<1:13:49,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:07 | 200 |  149.660028ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2889/8417 [34:36<1:13:34,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:08 | 200 |  143.785208ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2890/8417 [34:36<1:13:39,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:09 | 200 |  141.510461ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2891/8417 [34:37<1:14:55,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:09 | 200 |  141.126714ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2892/8417 [34:38<1:15:00,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:10 | 200 |  140.205806ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2893/8417 [34:39<1:15:25,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:11 | 200 |  156.633638ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2894/8417 [34:40<1:15:08,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:12 | 200 |  180.893649ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2895/8417 [34:41<1:16:26,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:13 | 200 |   176.08309ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2896/8417 [34:41<1:16:55,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:14 | 200 |  149.740392ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2897/8417 [34:42<1:15:54,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:14 | 200 |   141.69445ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2898/8417 [34:43<1:14:37,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:15 | 200 |  143.920512ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2899/8417 [34:44<1:14:54,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:16 | 200 |  165.447264ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2900/8417 [34:45<1:15:15,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:17 | 200 |  145.835654ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2901/8417 [34:46<1:14:58,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:18 | 200 |  144.719415ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2902/8417 [34:46<1:14:13,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:18 | 200 |  111.713734ms |       127.0.0.1 | POST     "/api/chat"

 34%|███▍      | 2903/8417 [34:47<1:12:40,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:19 | 200 |  183.056426ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2904/8417 [34:48<1:13:33,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:20 | 200 |  148.867342ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2905/8417 [34:49<1:13:41,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:21 | 200 |  155.061848ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2906/8417 [34:50<1:13:57,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:22 | 200 |  134.738142ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2907/8417 [34:50<1:13:24,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:22 | 200 |  171.910484ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2908/8417 [34:51<1:13:48,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:23 | 200 |  146.261418ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2909/8417 [34:52<1:13:52,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:24 | 200 |  141.650083ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2910/8417 [34:53<1:13:31,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:25 | 200 |  141.675453ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2911/8417 [34:54<1:13:31,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:26 | 200 |  161.860879ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2912/8417 [34:54<1:14:06,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:26 | 200 |  177.402746ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2913/8417 [34:55<1:15:14,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:27 | 200 |  147.931358ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2914/8417 [34:56<1:14:38,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:28 | 200 |  138.172789ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2915/8417 [34:57<1:13:35,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:29 | 200 |   145.24776ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2916/8417 [34:58<1:13:20,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:30 | 200 |  163.861013ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2917/8417 [34:58<1:13:54,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:30 | 200 |  144.190637ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2918/8417 [34:59<1:14:26,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:31 | 200 |   141.16299ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2919/8417 [35:00<1:13:45,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:32 | 200 |  138.036868ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2920/8417 [35:01<1:14:05,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:33 | 200 |  143.189653ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2921/8417 [35:02<1:13:49,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:34 | 200 |  133.321247ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2922/8417 [35:02<1:12:58,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:34 | 200 |  131.020125ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2923/8417 [35:03<1:13:06,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:35 | 200 |  171.683051ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2924/8417 [35:04<1:13:54,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:36 | 200 |  145.937601ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2925/8417 [35:05<1:13:21,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:37 | 200 |  138.915553ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2926/8417 [35:06<1:13:02,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:38 | 200 |  135.221518ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2927/8417 [35:06<1:12:37,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:39 | 200 |  164.141762ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2928/8417 [35:07<1:13:19,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:39 | 200 |  144.868754ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2929/8417 [35:08<1:13:43,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:40 | 200 |  138.817507ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2930/8417 [35:09<1:14:09,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:41 | 200 |  141.317182ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2931/8417 [35:10<1:13:48,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:42 | 200 |  146.302811ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2932/8417 [35:10<1:13:17,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:43 | 200 |  138.345983ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2933/8417 [35:11<1:12:38,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:43 | 200 |  139.814059ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2934/8417 [35:12<1:12:59,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:44 | 200 |  164.707948ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2935/8417 [35:13<1:14:39,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:45 | 200 |  141.967787ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2936/8417 [35:14<1:14:22,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:46 | 200 |   140.74471ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2937/8417 [35:14<1:14:07,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:47 | 200 |  134.500526ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2938/8417 [35:15<1:13:34,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 35%|███▍      | 2939/8417 [35:16<1:13:18,  1.25it/s]

[GIN] 2025/06/26 - 23:59:47 | 200 |  156.427133ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:48 | 200 |  119.317391ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2940/8417 [35:17<1:12:06,  1.27it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:49 | 200 |  140.399106ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2941/8417 [35:18<1:12:48,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:50 | 200 |  139.429262ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2942/8417 [35:18<1:12:56,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:51 | 200 |  142.823791ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2943/8417 [35:19<1:13:32,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:51 | 200 |  160.675664ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2944/8417 [35:20<1:13:59,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:52 | 200 |  142.209403ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▍      | 2945/8417 [35:21<1:13:15,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:53 | 200 |  138.045818ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2946/8417 [35:22<1:12:52,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:54 | 200 |  118.162682ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2947/8417 [35:22<1:12:07,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:55 | 200 |  178.840066ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2948/8417 [35:23<1:13:12,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:55 | 200 |  145.901793ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2949/8417 [35:24<1:13:19,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:56 | 200 |   135.10258ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2950/8417 [35:25<1:12:40,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:57 | 200 |  138.649495ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2951/8417 [35:26<1:12:23,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:58 | 200 |  163.040964ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2952/8417 [35:27<1:14:15,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:59 | 200 |  159.484376ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2953/8417 [35:27<1:14:41,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/26 - 23:59:59 | 200 |  142.706882ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2954/8417 [35:28<1:13:58,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:00 | 200 |  168.869881ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2955/8417 [35:29<1:14:31,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:01 | 200 |  162.942848ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2956/8417 [35:30<1:14:27,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:02 | 200 |  165.410665ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2957/8417 [35:31<1:14:36,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:03 | 200 |  180.837546ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2958/8417 [35:31<1:14:56,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:04 | 200 |  157.655833ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2959/8417 [35:32<1:14:53,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:04 | 200 |  118.241631ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2960/8417 [35:33<1:13:33,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:05 | 200 |  139.647518ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2961/8417 [35:34<1:13:03,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:06 | 200 |  169.224676ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2962/8417 [35:35<1:13:43,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:07 | 200 |  147.319788ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2963/8417 [35:35<1:13:12,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:08 | 200 |  142.141124ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2964/8417 [35:36<1:13:07,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:08 | 200 |  144.494255ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2965/8417 [35:37<1:13:04,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:09 | 200 |  165.424423ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2966/8417 [35:38<1:13:33,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:10 | 200 |  147.808389ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2967/8417 [35:39<1:13:35,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:11 | 200 |  163.209852ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2968/8417 [35:40<1:14:04,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:12 | 200 |  143.789413ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2969/8417 [35:40<1:13:36,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:12 | 200 |  141.318557ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2970/8417 [35:41<1:13:09,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:13 | 200 |  137.969598ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2971/8417 [35:42<1:13:14,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:14 | 200 |  161.040634ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2972/8417 [35:43<1:13:34,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:15 | 200 |  138.275577ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2973/8417 [35:44<1:13:52,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:16 | 200 |  144.679664ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2974/8417 [35:44<1:14:19,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:17 | 200 |  170.247576ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2975/8417 [35:45<1:15:45,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:17 | 200 |  176.757896ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2976/8417 [35:46<1:15:49,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:18 | 200 |  146.260288ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2977/8417 [35:47<1:14:53,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:19 | 200 |  143.721279ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2978/8417 [35:48<1:13:53,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:20 | 200 |  146.359748ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2979/8417 [35:48<1:13:30,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:21 | 200 |  115.420652ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2980/8417 [35:49<1:12:58,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:21 | 200 |  183.930732ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2981/8417 [35:50<1:13:22,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:22 | 200 |  141.222971ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2982/8417 [35:51<1:12:40,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:23 | 200 |  116.870712ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2983/8417 [35:52<1:11:38,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:24 | 200 |   119.07697ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2984/8417 [35:52<1:11:37,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:25 | 200 |  147.219551ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2985/8417 [35:53<1:12:20,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:25 | 200 |  178.980122ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2986/8417 [35:54<1:13:22,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:26 | 200 |  166.807904ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2987/8417 [35:55<1:13:40,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:27 | 200 |  148.546919ms |       127.0.0.1 | POST     "/api/chat"

 35%|███▌      | 2988/8417 [35:56<1:14:34,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:28 | 200 |   138.58343ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 2989/8417 [35:57<1:13:59,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:29 | 200 |  140.856788ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 2990/8417 [35:57<1:13:34,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 36%|███▌      | 2991/8417 [35:58<1:15:11,  1.20it/s]

[GIN] 2025/06/27 - 00:00:30 | 200 |  142.113755ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:30 | 200 |  141.271579ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 2992/8417 [35:59<1:15:50,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:31 | 200 |   180.96801ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 2993/8417 [36:00<1:15:39,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:32 | 200 |  146.252784ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 2994/8417 [36:01<1:14:58,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:33 | 200 |  137.805946ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 2995/8417 [36:02<1:14:05,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:34 | 200 |  156.792638ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 2996/8417 [36:02<1:15:03,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:35 | 200 |  168.688631ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 2997/8417 [36:03<1:15:06,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:35 | 200 |  139.546267ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 2998/8417 [36:04<1:14:05,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:36 | 200 |  141.750842ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 2999/8417 [36:05<1:13:19,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:37 | 200 |  139.268222ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3000/8417 [36:06<1:14:23,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:38 | 200 |  183.562973ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3001/8417 [36:07<1:16:53,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:39 | 200 |  147.991949ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3002/8417 [36:07<1:16:15,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:40 | 200 |  146.319628ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3003/8417 [36:08<1:15:13,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:40 | 200 |   115.03508ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3004/8417 [36:09<1:14:42,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:41 | 200 |  177.216876ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3005/8417 [36:10<1:14:53,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:42 | 200 |  156.454172ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3006/8417 [36:11<1:14:14,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:43 | 200 |  159.069432ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3007/8417 [36:12<1:14:32,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:44 | 200 |  174.483678ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3008/8417 [36:12<1:14:55,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:45 | 200 |  174.312246ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3009/8417 [36:13<1:14:50,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:45 | 200 |  120.324944ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3010/8417 [36:14<1:13:37,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:46 | 200 |  145.835379ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3011/8417 [36:15<1:14:08,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:47 | 200 |   143.30971ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3012/8417 [36:16<1:14:01,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:48 | 200 |  138.563842ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3013/8417 [36:16<1:13:25,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:49 | 200 |  139.112538ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3014/8417 [36:17<1:12:45,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:49 | 200 |  160.763936ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3015/8417 [36:18<1:13:11,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:50 | 200 |  145.790365ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3016/8417 [36:19<1:13:26,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:51 | 200 |  137.682404ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3017/8417 [36:20<1:13:24,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:52 | 200 |  133.789927ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3018/8417 [36:20<1:12:46,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:53 | 200 |  116.870307ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3019/8417 [36:21<1:12:11,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:53 | 200 |  177.282515ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3020/8417 [36:22<1:14:21,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:54 | 200 |  170.082071ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3021/8417 [36:23<1:14:47,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:55 | 200 |  142.867093ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3022/8417 [36:24<1:14:57,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:56 | 200 |  180.413558ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3023/8417 [36:25<1:15:21,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:57 | 200 |  153.958725ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3024/8417 [36:25<1:14:34,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:58 | 200 |  139.329173ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3025/8417 [36:26<1:13:59,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:58 | 200 |  118.331427ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3026/8417 [36:27<1:13:02,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:00:59 | 200 |  140.689899ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3027/8417 [36:28<1:14:15,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:00 | 200 |  183.697537ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3028/8417 [36:29<1:15:22,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:01 | 200 |  177.621664ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3029/8417 [36:30<1:16:35,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:02 | 200 |  148.058035ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3030/8417 [36:31<1:17:40,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:03 | 200 |  148.607445ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3031/8417 [36:31<1:15:57,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:04 | 200 |  180.965042ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3032/8417 [36:32<1:15:27,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:04 | 200 |  168.067226ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3033/8417 [36:33<1:14:55,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:05 | 200 |  142.102965ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3034/8417 [36:34<1:13:33,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:06 | 200 |  118.345872ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3035/8417 [36:35<1:12:12,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:07 | 200 |  113.072139ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3036/8417 [36:35<1:11:17,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:07 | 200 |  138.838792ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3037/8417 [36:36<1:11:10,  1.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:08 | 200 |  181.740236ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3038/8417 [36:37<1:12:22,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:09 | 200 |  180.666967ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3039/8417 [36:38<1:13:16,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:10 | 200 |  174.824646ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3040/8417 [36:39<1:13:41,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:11 | 200 |  143.195826ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3041/8417 [36:39<1:13:10,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:12 | 200 |  147.436853ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3042/8417 [36:40<1:12:37,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:12 | 200 |  134.451933ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3043/8417 [36:41<1:12:24,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:13 | 200 |   154.09665ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3044/8417 [36:42<1:12:45,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:14 | 200 |   166.20109ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3045/8417 [36:43<1:12:48,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:15 | 200 |  145.767919ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3046/8417 [36:44<1:12:48,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:16 | 200 |   147.38663ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3047/8417 [36:44<1:12:45,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:16 | 200 |  139.545621ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3048/8417 [36:45<1:12:26,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:17 | 200 |  136.018238ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3049/8417 [36:46<1:12:24,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:18 | 200 |  170.362122ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3050/8417 [36:47<1:16:31,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:19 | 200 |  145.616741ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▌      | 3051/8417 [36:48<1:14:53,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:20 | 200 |  142.436343ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3052/8417 [36:49<1:14:30,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:21 | 200 |  116.897833ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3053/8417 [36:49<1:13:11,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:21 | 200 |  180.089111ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3054/8417 [36:50<1:13:37,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:22 | 200 |   144.06474ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3055/8417 [36:51<1:13:27,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:23 | 200 |  117.482113ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3056/8417 [36:52<1:12:55,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:24 | 200 |  143.798151ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3057/8417 [36:53<1:12:45,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:25 | 200 |  161.150373ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3058/8417 [36:53<1:12:52,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:26 | 200 |  144.982842ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3059/8417 [36:54<1:12:45,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:26 | 200 |  139.777885ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3060/8417 [36:55<1:12:19,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:27 | 200 |  115.472723ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3061/8417 [36:56<1:11:21,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:28 | 200 |   169.78463ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3062/8417 [36:57<1:12:27,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:29 | 200 |  154.744572ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3063/8417 [36:57<1:12:30,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:30 | 200 |   142.26164ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3064/8417 [36:58<1:12:24,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:30 | 200 |  175.644851ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3065/8417 [36:59<1:14:27,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:31 | 200 |   172.27624ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3066/8417 [37:00<1:14:49,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:32 | 200 |  151.122957ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3067/8417 [37:01<1:14:50,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:33 | 200 |  147.214671ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3068/8417 [37:02<1:14:24,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:34 | 200 |  156.507134ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3069/8417 [37:02<1:14:02,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:35 | 200 |  182.428753ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3070/8417 [37:03<1:14:25,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:35 | 200 |  168.325518ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3071/8417 [37:04<1:14:49,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:36 | 200 |  123.746213ms |       127.0.0.1 | POST     "/api/chat"

 36%|███▋      | 3072/8417 [37:05<1:13:17,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:37 | 200 |  152.344366ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3073/8417 [37:06<1:12:42,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:38 | 200 |  115.253979ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3074/8417 [37:07<1:12:33,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:39 | 200 |  145.147813ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3075/8417 [37:07<1:12:14,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:39 | 200 |  139.068261ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3076/8417 [37:08<1:12:00,  1.24it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:40 | 200 |  116.480348ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3077/8417 [37:09<1:12:45,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:41 | 200 |  168.369908ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3078/8417 [37:10<1:13:09,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:42 | 200 |  144.967682ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3079/8417 [37:11<1:12:45,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:43 | 200 |  140.096991ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3080/8417 [37:11<1:12:26,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:44 | 200 |  141.670105ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3081/8417 [37:12<1:12:27,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:44 | 200 |   129.13775ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3082/8417 [37:13<1:12:13,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:45 | 200 |  181.494338ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3083/8417 [37:14<1:13:15,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:46 | 200 |   147.99148ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3084/8417 [37:15<1:12:53,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:47 | 200 |   179.18383ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3085/8417 [37:16<1:13:34,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:48 | 200 |    158.7549ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3086/8417 [37:16<1:14:02,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:49 | 200 |  141.546427ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3087/8417 [37:17<1:13:20,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:49 | 200 |  132.297023ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3088/8417 [37:18<1:12:50,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:50 | 200 |  143.657668ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3089/8417 [37:19<1:12:42,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:51 | 200 |  137.533038ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3090/8417 [37:20<1:12:40,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:52 | 200 |  139.248765ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3091/8417 [37:21<1:12:50,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:53 | 200 |  160.114156ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3092/8417 [37:21<1:13:47,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:54 | 200 |  184.864211ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3093/8417 [37:22<1:14:07,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:54 | 200 |  126.150319ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3094/8417 [37:23<1:13:40,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:55 | 200 |  127.893174ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3095/8417 [37:24<1:12:24,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:56 | 200 |  185.354218ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3096/8417 [37:25<1:13:25,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:57 | 200 |   120.34994ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3097/8417 [37:25<1:12:23,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:58 | 200 |  144.147735ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3098/8417 [37:26<1:11:58,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:58 | 200 |  120.476849ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3099/8417 [37:27<1:10:50,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:01:59 | 200 |  136.076054ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3100/8417 [37:28<1:11:01,  1.25it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:00 | 200 |  170.039079ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3101/8417 [37:29<1:12:04,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:01 | 200 |  163.967064ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3102/8417 [37:30<1:12:14,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:02 | 200 |   144.42925ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3103/8417 [37:30<1:12:37,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:02 | 200 |  137.801636ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3104/8417 [37:31<1:12:16,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:03 | 200 |   137.50175ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3105/8417 [37:32<1:12:11,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:04 | 200 |  158.350842ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3106/8417 [37:33<1:13:28,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:05 | 200 |  187.931807ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3107/8417 [37:34<1:14:54,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:06 | 200 |  146.259122ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3108/8417 [37:35<1:14:14,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:07 | 200 |  140.849832ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3109/8417 [37:35<1:14:14,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:07 | 200 |   142.47048ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3110/8417 [37:36<1:13:45,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:08 | 200 |  184.395533ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3111/8417 [37:37<1:14:57,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:09 | 200 |  162.509003ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3112/8417 [37:38<1:14:39,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:10 | 200 |  147.082906ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3113/8417 [37:39<1:14:12,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:11 | 200 |  143.342835ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3114/8417 [37:40<1:14:09,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:12 | 200 |  135.952326ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3115/8417 [37:40<1:12:51,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:12 | 200 |  143.499016ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3116/8417 [37:41<1:11:57,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:13 | 200 |  159.424267ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3117/8417 [37:42<1:12:43,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:14 | 200 |  146.101254ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3118/8417 [37:43<1:12:27,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:15 | 200 |  149.006088ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3119/8417 [37:44<1:12:19,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:16 | 200 |  171.235795ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3120/8417 [37:44<1:12:42,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:17 | 200 |  176.868617ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3121/8417 [37:45<1:13:11,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:17 | 200 |  156.962676ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3122/8417 [37:46<1:13:05,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:18 | 200 |  144.626875ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3123/8417 [37:47<1:13:08,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:19 | 200 |  137.204127ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3124/8417 [37:48<1:12:48,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:20 | 200 |  140.504612ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3125/8417 [37:49<1:12:28,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:21 | 200 |  142.659817ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3126/8417 [37:49<1:12:18,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:22 | 200 |  139.444762ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3127/8417 [37:50<1:11:58,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:22 | 200 |  163.688442ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3128/8417 [37:51<1:12:34,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:23 | 200 |  177.719282ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3129/8417 [37:52<1:15:43,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:24 | 200 |    147.5797ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3130/8417 [37:53<1:15:19,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:25 | 200 |   147.07196ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3131/8417 [37:54<1:14:19,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:26 | 200 |  179.776283ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3132/8417 [37:55<1:15:05,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:27 | 200 |  164.914121ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3133/8417 [37:55<1:14:56,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:27 | 200 |  152.257924ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3134/8417 [37:56<1:14:00,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:28 | 200 |  144.432933ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3135/8417 [37:57<1:14:10,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:29 | 200 |   137.22346ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3136/8417 [37:58<1:13:11,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:30 | 200 |  166.776928ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3137/8417 [37:59<1:13:06,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:31 | 200 |  207.484019ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3138/8417 [38:00<1:14:25,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:32 | 200 |  157.694299ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3139/8417 [38:00<1:14:11,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:33 | 200 |  144.113082ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3140/8417 [38:01<1:13:18,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:33 | 200 |  137.356782ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3141/8417 [38:02<1:12:20,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:34 | 200 |  142.528397ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3142/8417 [38:03<1:11:50,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:35 | 200 |  151.364809ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3143/8417 [38:04<1:11:37,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:36 | 200 |  182.594901ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3144/8417 [38:05<1:13:38,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:37 | 200 |  146.121966ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3145/8417 [38:05<1:12:58,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:37 | 200 |  183.257412ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3146/8417 [38:06<1:13:59,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:38 | 200 |  120.842621ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3147/8417 [38:07<1:12:20,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:39 | 200 |  152.409943ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3148/8417 [38:08<1:12:00,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:40 | 200 |  143.623101ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3149/8417 [38:09<1:11:40,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:41 | 200 |   157.83502ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3150/8417 [38:09<1:12:26,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:42 | 200 |  165.414986ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3151/8417 [38:10<1:13:05,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:42 | 200 |  140.608328ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3152/8417 [38:11<1:11:57,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:43 | 200 |  140.845958ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3153/8417 [38:12<1:11:55,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:44 | 200 |  140.987393ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3154/8417 [38:13<1:11:19,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:45 | 200 |  173.451367ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3155/8417 [38:14<1:12:05,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:46 | 200 |  184.436117ms |       127.0.0.1 | POST     "/api/chat"

 37%|███▋      | 3156/8417 [38:14<1:13:06,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:47 | 200 |  166.922291ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3157/8417 [38:15<1:14:14,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:47 | 200 |  143.470649ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3158/8417 [38:16<1:13:24,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:48 | 200 |  113.224546ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3159/8417 [38:17<1:12:14,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:49 | 200 |  118.254619ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3160/8417 [38:18<1:12:23,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:50 | 200 |  145.126136ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3161/8417 [38:19<1:12:14,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:51 | 200 |  186.116069ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3162/8417 [38:19<1:13:30,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:52 | 200 |   183.06184ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3163/8417 [38:20<1:13:38,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:52 | 200 |  145.382756ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3164/8417 [38:21<1:12:52,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:53 | 200 |  146.389033ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3165/8417 [38:22<1:13:21,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:54 | 200 |  139.597232ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3166/8417 [38:23<1:13:40,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:55 | 200 |  144.070363ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3167/8417 [38:24<1:13:12,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:56 | 200 |  177.938352ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3168/8417 [38:24<1:13:59,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:57 | 200 |  149.670786ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3169/8417 [38:25<1:13:35,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:57 | 200 |  149.835379ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3170/8417 [38:26<1:12:43,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:58 | 200 |  140.440605ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3171/8417 [38:27<1:12:02,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:02:59 | 200 |   136.96831ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3172/8417 [38:28<1:13:12,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:00 | 200 |  184.949514ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3173/8417 [38:29<1:14:03,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:01 | 200 |  174.091086ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3174/8417 [38:30<1:14:51,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:02 | 200 |  153.711082ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3175/8417 [38:30<1:14:26,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:03 | 200 |  145.910495ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3176/8417 [38:31<1:14:53,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:03 | 200 |  143.737228ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3177/8417 [38:32<1:13:58,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:04 | 200 |  146.110723ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3178/8417 [38:33<1:13:09,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:05 | 200 |  146.687104ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3179/8417 [38:34<1:12:33,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:06 | 200 |  164.586201ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3180/8417 [38:35<1:13:47,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:07 | 200 |  120.758065ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3181/8417 [38:35<1:12:46,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:07 | 200 |  148.862352ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3182/8417 [38:36<1:12:44,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:08 | 200 |  187.585235ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3183/8417 [38:37<1:13:35,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:09 | 200 |   155.71472ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3184/8417 [38:38<1:13:01,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:10 | 200 |  151.343985ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3185/8417 [38:39<1:12:42,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:11 | 200 |  143.295367ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3186/8417 [38:40<1:12:31,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:12 | 200 |  140.368833ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3187/8417 [38:40<1:11:40,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:12 | 200 |  138.475971ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3188/8417 [38:41<1:11:24,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:13 | 200 |  137.351463ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3189/8417 [38:42<1:11:07,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:14 | 200 |  138.106932ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3190/8417 [38:43<1:10:49,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:15 | 200 |  157.527795ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3191/8417 [38:44<1:11:04,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:16 | 200 |  149.305834ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3192/8417 [38:44<1:11:34,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:17 | 200 |  133.232388ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3193/8417 [38:45<1:10:54,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:17 | 200 |  178.890264ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3194/8417 [38:46<1:11:24,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:18 | 200 |   139.88328ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3195/8417 [38:47<1:11:29,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:19 | 200 |  183.782596ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3196/8417 [38:48<1:12:27,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:20 | 200 |  114.534968ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3197/8417 [38:49<1:11:43,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:21 | 200 |  150.006728ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3198/8417 [38:49<1:11:54,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:22 | 200 |   140.69141ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3199/8417 [38:50<1:11:49,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:22 | 200 |  139.952396ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3200/8417 [38:51<1:11:50,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:23 | 200 |  116.667042ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3201/8417 [38:52<1:10:35,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:24 | 200 |  168.492071ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3202/8417 [38:53<1:11:38,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:25 | 200 |  181.097367ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3203/8417 [38:54<1:12:19,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:26 | 200 |  174.102312ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3204/8417 [38:54<1:12:54,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:26 | 200 |  114.894024ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3205/8417 [38:55<1:11:26,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:27 | 200 |  150.501193ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3206/8417 [38:56<1:11:15,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:28 | 200 |  142.997948ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3207/8417 [38:57<1:11:18,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:29 | 200 |  143.667298ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3208/8417 [38:58<1:11:42,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:30 | 200 |  141.487674ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3209/8417 [38:58<1:11:56,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:31 | 200 |  142.337568ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3210/8417 [38:59<1:12:27,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:31 | 200 |  177.226608ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3211/8417 [39:00<1:12:38,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:32 | 200 |  127.645033ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3212/8417 [39:01<1:11:23,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:33 | 200 |  156.476272ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3213/8417 [39:02<1:11:40,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:34 | 200 |  141.974976ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3214/8417 [39:03<1:11:16,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:35 | 200 |  146.990791ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3215/8417 [39:03<1:11:39,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:36 | 200 |  139.599102ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3216/8417 [39:04<1:11:29,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:36 | 200 |  135.060572ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3217/8417 [39:05<1:11:04,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:37 | 200 |  142.104763ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3218/8417 [39:06<1:10:34,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:38 | 200 |  159.032941ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3219/8417 [39:07<1:10:47,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:39 | 200 |  152.793573ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3220/8417 [39:08<1:12:08,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:40 | 200 |  150.486866ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3221/8417 [39:08<1:12:38,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:41 | 200 |  133.823925ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3222/8417 [39:09<1:12:23,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:41 | 200 |  142.186523ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3223/8417 [39:10<1:11:56,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:42 | 200 |  140.167144ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3224/8417 [39:11<1:11:27,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:43 | 200 |  139.183082ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3225/8417 [39:12<1:10:52,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:44 | 200 |  149.451265ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3226/8417 [39:12<1:10:53,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:45 | 200 |  141.280558ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3227/8417 [39:13<1:10:47,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:45 | 200 |  159.494677ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3228/8417 [39:14<1:11:06,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:46 | 200 |  173.236253ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3229/8417 [39:15<1:11:27,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:47 | 200 |   175.44783ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3230/8417 [39:16<1:11:39,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:48 | 200 |  147.882758ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3231/8417 [39:17<1:11:34,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:49 | 200 |  145.095628ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3232/8417 [39:17<1:11:27,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:50 | 200 |  136.606194ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3233/8417 [39:18<1:11:42,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:50 | 200 |  148.597418ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3234/8417 [39:19<1:12:42,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:51 | 200 |  175.149526ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3235/8417 [39:20<1:12:41,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:52 | 200 |    155.5239ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3236/8417 [39:21<1:12:06,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:53 | 200 |  146.885507ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3237/8417 [39:22<1:11:52,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:54 | 200 |  150.550957ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3238/8417 [39:22<1:11:37,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:55 | 200 |  119.183102ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3239/8417 [39:23<1:10:46,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:55 | 200 |  136.731787ms |       127.0.0.1 | POST     "/api/chat"

 38%|███▊      | 3240/8417 [39:24<1:10:37,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:56 | 200 |  166.182117ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3241/8417 [39:25<1:11:34,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:57 | 200 |  133.186829ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3242/8417 [39:26<1:11:00,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:58 | 200 |  143.097678ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3243/8417 [39:27<1:11:06,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:03:59 | 200 |  180.675536ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3244/8417 [39:27<1:11:45,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:00 | 200 |  136.618633ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3245/8417 [39:28<1:11:18,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:00 | 200 |   171.61135ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3246/8417 [39:29<1:12:54,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:01 | 200 |  120.191402ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3247/8417 [39:30<1:11:55,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:02 | 200 |  149.056544ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3248/8417 [39:31<1:11:33,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:03 | 200 |  183.947605ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3249/8417 [39:32<1:12:10,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:04 | 200 |   168.18883ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3250/8417 [39:32<1:12:26,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:05 | 200 |   123.49434ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3251/8417 [39:33<1:11:04,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:05 | 200 |  157.301926ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3252/8417 [39:34<1:11:42,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:06 | 200 |  142.353417ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3253/8417 [39:35<1:11:28,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:07 | 200 |  139.972782ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3254/8417 [39:36<1:11:21,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:08 | 200 |  139.075948ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3255/8417 [39:37<1:10:42,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:09 | 200 |  137.016069ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3256/8417 [39:37<1:10:52,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:10 | 200 |   132.71669ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3257/8417 [39:38<1:10:52,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:10 | 200 |  186.775692ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3258/8417 [39:39<1:14:06,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:11 | 200 |  178.261197ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3259/8417 [39:40<1:14:03,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:12 | 200 |  163.347514ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3260/8417 [39:41<1:13:31,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:13 | 200 |  180.206037ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▊      | 3261/8417 [39:42<1:13:57,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:14 | 200 |   147.44816ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3262/8417 [39:43<1:13:17,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:15 | 200 |  136.917282ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3263/8417 [39:43<1:12:35,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:16 | 200 |  135.666451ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3264/8417 [39:44<1:12:09,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:16 | 200 |  178.397271ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3265/8417 [39:45<1:12:29,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:17 | 200 |  176.041601ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3266/8417 [39:46<1:12:37,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:18 | 200 |  148.052866ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3267/8417 [39:47<1:11:37,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:19 | 200 |  148.929889ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3268/8417 [39:48<1:11:42,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:20 | 200 |  139.812123ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3269/8417 [39:48<1:11:38,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:21 | 200 |  146.615687ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3270/8417 [39:49<1:13:25,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:21 | 200 |  136.167081ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3271/8417 [39:50<1:12:18,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:22 | 200 |  162.815356ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3272/8417 [39:51<1:11:52,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:23 | 200 |  141.601874ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3273/8417 [39:52<1:10:56,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:24 | 200 |  146.375733ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3274/8417 [39:53<1:11:25,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:25 | 200 |  144.072613ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3275/8417 [39:53<1:11:19,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:26 | 200 |  137.340618ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3276/8417 [39:54<1:10:41,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:26 | 200 |  115.573246ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3277/8417 [39:55<1:09:48,  1.23it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:27 | 200 |  175.380314ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3278/8417 [39:56<1:11:22,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:28 | 200 |  175.242638ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3279/8417 [39:57<1:11:59,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:29 | 200 |  148.996944ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3280/8417 [39:58<1:12:18,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:30 | 200 |  143.288451ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3281/8417 [39:58<1:11:45,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:31 | 200 |  140.964483ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3282/8417 [39:59<1:11:38,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:31 | 200 |  171.749853ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3283/8417 [40:00<1:11:46,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:32 | 200 |  139.397594ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3284/8417 [40:01<1:10:38,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:33 | 200 |  179.801863ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3285/8417 [40:02<1:11:08,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:34 | 200 |  151.507928ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3286/8417 [40:03<1:11:33,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:35 | 200 |  144.396345ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3287/8417 [40:03<1:11:20,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:36 | 200 |  139.759423ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3288/8417 [40:04<1:11:25,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:36 | 200 |  152.387933ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3289/8417 [40:05<1:12:26,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:37 | 200 |  186.389718ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3290/8417 [40:06<1:12:44,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:38 | 200 |  119.217506ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3291/8417 [40:07<1:10:44,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:39 | 200 |  148.087282ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3292/8417 [40:08<1:10:28,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:40 | 200 |  118.351768ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3293/8417 [40:08<1:10:05,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:41 | 200 |  149.482946ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3294/8417 [40:09<1:10:56,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:41 | 200 |  140.489601ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3295/8417 [40:10<1:11:58,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:42 | 200 |  156.005193ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3296/8417 [40:11<1:12:12,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:43 | 200 |  164.720116ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3297/8417 [40:12<1:12:00,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:44 | 200 |  148.020068ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3298/8417 [40:13<1:11:36,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:45 | 200 |  140.648284ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3299/8417 [40:14<1:11:30,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:46 | 200 |  133.905206ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3300/8417 [40:14<1:11:33,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:47 | 200 |   181.56718ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3301/8417 [40:15<1:12:24,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:47 | 200 |  156.041732ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3302/8417 [40:16<1:11:51,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:48 | 200 |  147.633907ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3303/8417 [40:17<1:11:50,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:49 | 200 |   141.06865ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3304/8417 [40:18<1:11:16,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:50 | 200 |  139.041297ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3305/8417 [40:19<1:11:26,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:51 | 200 |  179.553002ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3306/8417 [40:19<1:12:05,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:52 | 200 |  142.275926ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3307/8417 [40:20<1:11:12,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:52 | 200 |  177.498339ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3308/8417 [40:21<1:11:56,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:53 | 200 |  141.391033ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3309/8417 [40:22<1:12:12,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:54 | 200 |  145.448414ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3310/8417 [40:23<1:12:21,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:55 | 200 |  181.235528ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3311/8417 [40:24<1:12:59,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:56 | 200 |  142.639751ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3312/8417 [40:25<1:12:21,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:57 | 200 |   141.69281ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3313/8417 [40:25<1:11:54,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:57 | 200 |  146.085891ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3314/8417 [40:26<1:12:08,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:58 | 200 |  139.689089ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3315/8417 [40:27<1:11:03,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:04:59 | 200 |  188.408571ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3316/8417 [40:28<1:11:35,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:00 | 200 |  151.514113ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3317/8417 [40:29<1:11:24,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:01 | 200 |  147.356512ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3318/8417 [40:30<1:11:53,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:02 | 200 |  137.182166ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3319/8417 [40:30<1:11:21,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:03 | 200 |  142.017321ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3320/8417 [40:31<1:11:34,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:03 | 200 |  181.565255ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3321/8417 [40:32<1:13:06,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:04 | 200 |  125.761614ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3322/8417 [40:33<1:11:52,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:05 | 200 |  143.828838ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3323/8417 [40:34<1:11:16,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:06 | 200 |  139.506664ms |       127.0.0.1 | POST     "/api/chat"

 39%|███▉      | 3324/8417 [40:35<1:10:50,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:07 | 200 |  113.728741ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3325/8417 [40:35<1:09:42,  1.22it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:08 | 200 |  175.513868ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3326/8417 [40:36<1:11:28,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:08 | 200 |  156.491315ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3327/8417 [40:37<1:11:48,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:09 | 200 |  139.079325ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3328/8417 [40:38<1:11:00,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:10 | 200 |  138.147447ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3329/8417 [40:39<1:11:05,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:11 | 200 |  140.372122ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3330/8417 [40:40<1:10:43,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:12 | 200 |  177.698844ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3331/8417 [40:40<1:11:27,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:13 | 200 |    139.5357ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3332/8417 [40:41<1:11:26,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:14 | 200 |  183.871369ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3333/8417 [40:42<1:13:16,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:14 | 200 |  144.358204ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3334/8417 [40:43<1:13:02,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:15 | 200 |  143.132951ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3335/8417 [40:44<1:11:53,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:16 | 200 |  165.597108ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3336/8417 [40:45<1:12:00,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:17 | 200 |  149.997336ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3337/8417 [40:46<1:12:09,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:18 | 200 |  142.599698ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3338/8417 [40:46<1:11:51,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:19 | 200 |  178.682516ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3339/8417 [40:47<1:12:16,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:19 | 200 |   160.28035ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3340/8417 [40:48<1:11:44,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:20 | 200 |  145.651671ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3341/8417 [40:49<1:11:29,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:21 | 200 |  112.993705ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3342/8417 [40:50<1:09:50,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:22 | 200 |  132.005033ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3343/8417 [40:51<1:13:52,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:23 | 200 |  170.043433ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3344/8417 [40:52<1:13:32,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:24 | 200 |  145.542722ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3345/8417 [40:53<1:13:35,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:25 | 200 |  134.166093ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3346/8417 [40:53<1:12:39,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:25 | 200 |  167.183403ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3347/8417 [40:54<1:12:11,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:26 | 200 |  145.498307ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3348/8417 [40:55<1:12:14,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:27 | 200 |   143.86984ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3349/8417 [40:56<1:12:49,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:28 | 200 |  139.305075ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3350/8417 [40:57<1:12:10,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:29 | 200 |   161.00563ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3351/8417 [40:58<1:12:06,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:30 | 200 |  148.655576ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3352/8417 [40:58<1:11:53,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:31 | 200 |   148.44491ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3353/8417 [40:59<1:11:23,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:31 | 200 |  113.866932ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3354/8417 [41:00<1:09:56,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:32 | 200 |  180.526861ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3355/8417 [41:01<1:10:09,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:33 | 200 |  169.163714ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3356/8417 [41:02<1:10:16,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:34 | 200 |  181.707974ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3357/8417 [41:03<1:11:15,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:35 | 200 |  146.511996ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3358/8417 [41:03<1:10:54,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:36 | 200 |  135.510524ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3359/8417 [41:04<1:10:33,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:36 | 200 |  138.651787ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3360/8417 [41:05<1:09:55,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:37 | 200 |  159.377606ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3361/8417 [41:06<1:10:08,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:38 | 200 |   178.74482ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3362/8417 [41:07<1:10:36,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:39 | 200 |  171.272947ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3363/8417 [41:08<1:10:59,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:40 | 200 |  144.185992ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3364/8417 [41:08<1:10:28,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 40%|███▉      | 3365/8417 [41:09<1:10:20,  1.20it/s]

[GIN] 2025/06/27 - 00:05:41 | 200 |  146.838361ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:41 | 200 |  139.387933ms |       127.0.0.1 | POST     "/api/chat"

 40%|███▉      | 3366/8417 [41:10<1:09:50,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:42 | 200 |  146.651941ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3367/8417 [41:11<1:10:18,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:43 | 200 |  182.218324ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3368/8417 [41:12<1:11:05,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:44 | 200 |   158.36501ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3369/8417 [41:13<1:12:09,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:45 | 200 |  144.675914ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3370/8417 [41:14<1:13:13,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:46 | 200 |  148.115972ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3371/8417 [41:14<1:12:41,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:47 | 200 |   172.38215ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3372/8417 [41:15<1:12:31,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:47 | 200 |  137.402477ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3373/8417 [41:16<1:11:28,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:48 | 200 |  115.245776ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3374/8417 [41:17<1:10:02,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:49 | 200 |  181.843311ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3375/8417 [41:18<1:10:42,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:50 | 200 |  179.761259ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3376/8417 [41:19<1:11:21,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:51 | 200 |  164.869447ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3377/8417 [41:20<1:11:43,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:52 | 200 |  140.228139ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3378/8417 [41:20<1:10:53,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:52 | 200 |  140.432694ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3379/8417 [41:21<1:10:57,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:53 | 200 |  143.625858ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3380/8417 [41:22<1:10:42,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:54 | 200 |  176.302401ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3381/8417 [41:23<1:11:02,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:55 | 200 |  147.576908ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3382/8417 [41:24<1:11:17,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:56 | 200 |   138.61814ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3383/8417 [41:25<1:10:26,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:57 | 200 |  140.071363ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3384/8417 [41:25<1:10:12,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:58 | 200 |  173.139009ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3385/8417 [41:26<1:11:21,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:58 | 200 |   157.71051ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3386/8417 [41:27<1:10:59,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:05:59 | 200 |  144.872356ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3387/8417 [41:28<1:10:42,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:00 | 200 |  143.056466ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3388/8417 [41:29<1:10:41,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:01 | 200 |  142.723226ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3389/8417 [41:30<1:10:09,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:02 | 200 |   179.95669ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3390/8417 [41:30<1:10:51,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:03 | 200 |  161.834648ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3391/8417 [41:31<1:10:51,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:03 | 200 |  139.535131ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3392/8417 [41:32<1:10:10,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:04 | 200 |  141.698961ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3393/8417 [41:33<1:09:53,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:05 | 200 |  141.816304ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3394/8417 [41:34<1:09:44,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:06 | 200 |  140.238567ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3395/8417 [41:35<1:10:02,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:07 | 200 |  177.491462ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3396/8417 [41:36<1:10:39,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:08 | 200 |  143.168494ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3397/8417 [41:36<1:11:03,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:09 | 200 |  138.467646ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3398/8417 [41:37<1:11:23,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:09 | 200 |  117.201056ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3399/8417 [41:38<1:10:54,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:10 | 200 |  140.579279ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3400/8417 [41:39<1:11:26,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:11 | 200 |  142.821691ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3401/8417 [41:40<1:10:38,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:12 | 200 |  169.880634ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3402/8417 [41:41<1:10:59,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:13 | 200 |  145.945319ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3403/8417 [41:41<1:10:37,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:14 | 200 |  147.303543ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3404/8417 [41:42<1:10:50,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:14 | 200 |  141.629282ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3405/8417 [41:43<1:10:06,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:15 | 200 |  138.510543ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3406/8417 [41:44<1:09:47,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:16 | 200 |  130.088213ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3407/8417 [41:45<1:10:13,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:17 | 200 |  186.132648ms |       127.0.0.1 | POST     "/api/chat"

 40%|████      | 3408/8417 [41:46<1:11:45,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:18 | 200 |  184.555857ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3409/8417 [41:47<1:12:07,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:19 | 200 |  146.855255ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3410/8417 [41:47<1:11:03,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:20 | 200 |  137.749233ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3411/8417 [41:48<1:10:11,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:20 | 200 |  142.249279ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3412/8417 [41:49<1:10:29,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:21 | 200 |  179.812391ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3413/8417 [41:50<1:11:15,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:22 | 200 |  142.380621ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3414/8417 [41:51<1:10:48,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:23 | 200 |  147.020871ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3415/8417 [41:52<1:10:23,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:24 | 200 |  153.407774ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3416/8417 [41:53<1:11:05,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:25 | 200 |  143.010275ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3417/8417 [41:53<1:10:13,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:25 | 200 |   177.95479ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3418/8417 [41:54<1:11:22,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:26 | 200 |  149.613025ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3419/8417 [41:55<1:10:49,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:27 | 200 |  137.927234ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3420/8417 [41:56<1:10:03,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:28 | 200 |  141.432361ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3421/8417 [41:57<1:09:52,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:29 | 200 |  167.530778ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3422/8417 [41:58<1:10:30,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:30 | 200 |  178.951302ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3423/8417 [41:58<1:11:05,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:31 | 200 |  154.410857ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3424/8417 [41:59<1:11:29,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:31 | 200 |  141.642402ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3425/8417 [42:00<1:10:28,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:32 | 200 |  144.643081ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3426/8417 [42:01<1:09:44,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:33 | 200 |   185.21686ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3427/8417 [42:02<1:10:23,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:34 | 200 |  144.247552ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3428/8417 [42:03<1:10:05,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:35 | 200 |  142.258376ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3429/8417 [42:03<1:10:16,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:36 | 200 |  136.441561ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3430/8417 [42:04<1:09:50,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:36 | 200 |  136.982185ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3431/8417 [42:05<1:09:37,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:37 | 200 |  143.225966ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3432/8417 [42:06<1:11:54,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:38 | 200 |  172.174235ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3433/8417 [42:07<1:11:29,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:39 | 200 |  160.004146ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3434/8417 [42:08<1:10:40,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:40 | 200 |  131.103456ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3435/8417 [42:09<1:10:04,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:41 | 200 |  175.428578ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3436/8417 [42:09<1:10:39,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:42 | 200 |  144.513026ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3437/8417 [42:10<1:10:06,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:42 | 200 |  117.537635ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3438/8417 [42:11<1:09:17,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:43 | 200 |  144.234479ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3439/8417 [42:12<1:08:56,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:44 | 200 |  157.549876ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3440/8417 [42:13<1:08:54,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:45 | 200 |  174.500606ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3441/8417 [42:14<1:09:44,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:46 | 200 |   179.55692ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3442/8417 [42:15<1:10:50,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:47 | 200 |  149.096265ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3443/8417 [42:15<1:10:34,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:47 | 200 |  146.217355ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3444/8417 [42:16<1:10:45,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:48 | 200 |  193.446622ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3445/8417 [42:17<1:12:19,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:49 | 200 |  165.574466ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3446/8417 [42:18<1:11:55,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:50 | 200 |  147.419678ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3447/8417 [42:19<1:11:41,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:51 | 200 |  171.012109ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3448/8417 [42:20<1:12:02,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:52 | 200 |  116.181474ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3449/8417 [42:21<1:10:54,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:53 | 200 |  144.498737ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3450/8417 [42:21<1:10:05,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:54 | 200 |   180.05988ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3451/8417 [42:22<1:10:23,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:54 | 200 |  178.552046ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3452/8417 [42:23<1:10:58,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:55 | 200 |  143.727593ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3453/8417 [42:24<1:11:08,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:56 | 200 |  137.101228ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3454/8417 [42:25<1:10:43,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:57 | 200 |  138.621195ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3455/8417 [42:26<1:10:10,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:58 | 200 |    178.5782ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3456/8417 [42:27<1:11:10,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:59 | 200 |   147.62732ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3457/8417 [42:27<1:10:30,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:06:59 | 200 |  141.863387ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3458/8417 [42:28<1:09:48,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:00 | 200 |  143.461757ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3459/8417 [42:29<1:09:52,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:01 | 200 |  171.590057ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3460/8417 [42:30<1:10:27,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:02 | 200 |  153.753519ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3461/8417 [42:31<1:10:03,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:03 | 200 |  141.045136ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3462/8417 [42:32<1:09:42,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:04 | 200 |  139.591926ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3463/8417 [42:32<1:09:50,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:05 | 200 |  179.665047ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3464/8417 [42:33<1:10:39,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:05 | 200 |   156.96819ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3465/8417 [42:34<1:10:31,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:06 | 200 |  114.565715ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3466/8417 [42:35<1:08:57,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:07 | 200 |  136.268727ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3467/8417 [42:36<1:08:31,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:08 | 200 |  143.104411ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3468/8417 [42:37<1:08:41,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:09 | 200 |  139.683245ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3469/8417 [42:37<1:08:54,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:10 | 200 |  143.468484ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3470/8417 [42:38<1:08:56,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:10 | 200 |  171.327589ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3471/8417 [42:39<1:10:19,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:11 | 200 |  143.391813ms |       127.0.0.1 | POST     "/api/chat"

 41%|████      | 3472/8417 [42:40<1:09:36,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:12 | 200 |  139.681297ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3473/8417 [42:41<1:08:56,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:13 | 200 |  138.823881ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3474/8417 [42:42<1:10:27,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:14 | 200 |  135.245782ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3475/8417 [42:43<1:09:47,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:15 | 200 |  131.563284ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3476/8417 [42:43<1:10:35,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:16 | 200 |  139.626329ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3477/8417 [42:44<1:10:04,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:16 | 200 |  169.480598ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3478/8417 [42:45<1:10:56,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:17 | 200 |  151.719344ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3479/8417 [42:46<1:10:12,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:18 | 200 |  143.780085ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3480/8417 [42:47<1:10:15,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:19 | 200 |  121.140115ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3481/8417 [42:48<1:09:22,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:20 | 200 |  156.795447ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3482/8417 [42:49<1:10:33,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:21 | 200 |  182.441816ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3483/8417 [42:49<1:11:02,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:22 | 200 |  146.527631ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3484/8417 [42:50<1:09:56,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:22 | 200 |  139.890111ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3485/8417 [42:51<1:09:25,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:23 | 200 |  144.268624ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3486/8417 [42:52<1:09:43,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:24 | 200 |  175.543456ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3487/8417 [42:53<1:09:57,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:25 | 200 |   148.10694ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3488/8417 [42:54<1:10:00,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:26 | 200 |  116.024853ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3489/8417 [42:54<1:09:07,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:27 | 200 |  140.648991ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3490/8417 [42:55<1:08:50,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:27 | 200 |  186.718889ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3491/8417 [42:56<1:09:36,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:28 | 200 |  162.341056ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3492/8417 [42:57<1:09:39,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:29 | 200 |  149.304578ms |       127.0.0.1 | POST     "/api/chat"

 41%|████▏     | 3493/8417 [42:58<1:09:11,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:30 | 200 |  146.003435ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3494/8417 [42:59<1:09:28,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:31 | 200 |  140.371545ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3495/8417 [43:00<1:09:51,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:32 | 200 |  135.094444ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3496/8417 [43:00<1:09:33,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:33 | 200 |  178.539014ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3497/8417 [43:01<1:09:41,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:33 | 200 |  145.131154ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3498/8417 [43:02<1:09:10,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:34 | 200 |   142.02765ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3499/8417 [43:03<1:09:06,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:35 | 200 |  142.586325ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3500/8417 [43:04<1:10:02,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:36 | 200 |   166.05407ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3501/8417 [43:05<1:10:15,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:37 | 200 |  142.467022ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3502/8417 [43:06<1:09:49,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:38 | 200 |  148.414312ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3503/8417 [43:06<1:09:57,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:38 | 200 |  130.466186ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3504/8417 [43:07<1:09:05,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:39 | 200 |  134.517456ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3505/8417 [43:08<1:08:46,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:40 | 200 |   170.09371ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3506/8417 [43:09<1:10:14,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:41 | 200 |  146.381825ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3507/8417 [43:10<1:10:34,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:42 | 200 |   136.94884ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3508/8417 [43:11<1:09:43,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:43 | 200 |  145.343533ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3509/8417 [43:11<1:09:18,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:44 | 200 |  141.245609ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3510/8417 [43:12<1:08:47,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:44 | 200 |  139.029304ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3511/8417 [43:13<1:09:12,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:45 | 200 |  133.528674ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3512/8417 [43:14<1:09:48,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:46 | 200 |  170.787779ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3513/8417 [43:15<1:09:59,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:47 | 200 |  146.330916ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3514/8417 [43:16<1:10:21,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:48 | 200 |  139.552374ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3515/8417 [43:17<1:09:44,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:49 | 200 |  144.925807ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3516/8417 [43:17<1:09:36,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:50 | 200 |  162.512007ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3517/8417 [43:18<1:09:55,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:50 | 200 |  148.637485ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3518/8417 [43:19<1:10:14,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:51 | 200 |  136.271232ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3519/8417 [43:20<1:10:00,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:52 | 200 |  143.598863ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3520/8417 [43:21<1:09:40,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:53 | 200 |   161.12056ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3521/8417 [43:22<1:09:37,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:54 | 200 |  118.176918ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3522/8417 [43:23<1:08:23,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:55 | 200 |  150.010071ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3523/8417 [43:23<1:08:30,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:55 | 200 |  142.750374ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3524/8417 [43:24<1:08:25,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:56 | 200 |  140.400467ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3525/8417 [43:25<1:09:05,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:57 | 200 |  167.405297ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3526/8417 [43:26<1:09:45,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:58 | 200 |  141.375874ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3527/8417 [43:27<1:09:20,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:07:59 | 200 |  143.140543ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3528/8417 [43:28<1:09:45,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:00 | 200 |  170.967203ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3529/8417 [43:29<1:09:56,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:01 | 200 |  148.073082ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3530/8417 [43:29<1:09:46,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:01 | 200 |  141.289809ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3531/8417 [43:30<1:09:06,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:02 | 200 |  143.041746ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3532/8417 [43:31<1:09:47,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:03 | 200 |  162.141441ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3533/8417 [43:32<1:09:27,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:04 | 200 |  149.398998ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3534/8417 [43:33<1:09:11,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:05 | 200 |  141.762463ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3535/8417 [43:34<1:08:26,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:06 | 200 |  141.069056ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3536/8417 [43:34<1:08:05,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:07 | 200 |  140.507288ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3537/8417 [43:35<1:07:53,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:07 | 200 |  134.367715ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3538/8417 [43:36<1:07:08,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:08 | 200 |  185.585915ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3539/8417 [43:37<1:08:09,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:09 | 200 |  149.091083ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3540/8417 [43:38<1:07:59,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:10 | 200 |   152.29768ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3541/8417 [43:39<1:08:08,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:11 | 200 |   138.58539ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3542/8417 [43:39<1:07:44,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:12 | 200 |  135.308824ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3543/8417 [43:40<1:07:19,  1.21it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:12 | 200 |  154.994051ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3544/8417 [43:41<1:07:45,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:13 | 200 |  180.097675ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3545/8417 [43:42<1:08:22,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:14 | 200 |  148.074279ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3546/8417 [43:43<1:08:13,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:15 | 200 |  119.680781ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3547/8417 [43:44<1:07:33,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:16 | 200 |  146.479272ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3548/8417 [43:44<1:07:49,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:17 | 200 |  139.588421ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3549/8417 [43:45<1:07:37,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:17 | 200 |  145.261292ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3550/8417 [43:46<1:07:21,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:18 | 200 |  177.548412ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3551/8417 [43:47<1:07:49,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:19 | 200 |    162.2566ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3552/8417 [43:48<1:08:25,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:20 | 200 |  145.676736ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3553/8417 [43:49<1:08:16,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:21 | 200 |  139.587325ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3554/8417 [43:49<1:08:13,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:22 | 200 |   140.97754ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3555/8417 [43:50<1:08:00,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:22 | 200 |  180.494194ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3556/8417 [43:51<1:10:18,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:23 | 200 |  156.893079ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3557/8417 [43:52<1:10:06,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:24 | 200 |  144.612313ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3558/8417 [43:53<1:10:01,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:25 | 200 |  148.191097ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3559/8417 [43:54<1:09:12,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:26 | 200 |  142.986069ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3560/8417 [43:55<1:08:49,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:27 | 200 |  140.050283ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3561/8417 [43:55<1:08:35,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:28 | 200 |  141.250522ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3562/8417 [43:56<1:08:36,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:29 | 200 |  177.568925ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3563/8417 [43:57<1:09:29,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:29 | 200 |  146.831018ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3564/8417 [43:58<1:09:08,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:30 | 200 |  136.059631ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3565/8417 [43:59<1:08:57,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:31 | 200 |  140.130427ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3566/8417 [44:00<1:08:55,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:32 | 200 |  176.578379ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3567/8417 [44:01<1:09:27,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:33 | 200 |  146.781157ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3568/8417 [44:01<1:09:10,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:34 | 200 |  111.541805ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3569/8417 [44:02<1:07:31,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:34 | 200 |   144.22973ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3570/8417 [44:03<1:07:23,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:35 | 200 |  139.870112ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3571/8417 [44:04<1:07:37,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:36 | 200 |  143.353509ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3572/8417 [44:05<1:07:23,  1.20it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:37 | 200 |  181.483864ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3573/8417 [44:06<1:08:16,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:38 | 200 |  151.260335ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3574/8417 [44:07<1:08:26,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:39 | 200 |   141.26081ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3575/8417 [44:07<1:07:59,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:39 | 200 |  141.213506ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3576/8417 [44:08<1:08:51,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:40 | 200 |  181.727129ms |       127.0.0.1 | POST     "/api/chat"

 42%|████▏     | 3577/8417 [44:09<1:10:23,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:41 | 200 |  148.422371ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3578/8417 [44:10<1:09:55,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:42 | 200 |  115.498419ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3579/8417 [44:11<1:08:50,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:43 | 200 |  181.548401ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3580/8417 [44:12<1:09:01,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:44 | 200 |  148.015344ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3581/8417 [44:13<1:09:05,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:45 | 200 |   137.69683ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3582/8417 [44:13<1:08:57,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:46 | 200 |  141.222541ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3583/8417 [44:14<1:09:03,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:46 | 200 |  167.671647ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3584/8417 [44:15<1:09:12,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:47 | 200 |   145.31954ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3585/8417 [44:16<1:08:22,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:48 | 200 |  138.027221ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3586/8417 [44:17<1:07:34,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:49 | 200 |  148.161798ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3587/8417 [44:18<1:07:48,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:50 | 200 |   178.03251ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3588/8417 [44:18<1:08:56,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:51 | 200 |  157.402253ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3589/8417 [44:19<1:09:18,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:51 | 200 |  142.339537ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3590/8417 [44:20<1:09:20,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:52 | 200 |  149.524268ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3591/8417 [44:21<1:08:47,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:53 | 200 |  166.923602ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3592/8417 [44:22<1:09:23,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:54 | 200 |  145.651646ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3593/8417 [44:23<1:09:42,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:55 | 200 |  148.109258ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3594/8417 [44:24<1:09:35,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:56 | 200 |  137.647726ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3595/8417 [44:25<1:08:57,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:57 | 200 |  163.049617ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3596/8417 [44:25<1:08:45,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:57 | 200 |  139.601625ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3597/8417 [44:26<1:08:06,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:58 | 200 |  146.404867ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3598/8417 [44:27<1:07:44,  1.19it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:08:59 | 200 |  173.812102ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3599/8417 [44:28<1:08:52,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:00 | 200 |  148.648311ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3600/8417 [44:29<1:08:56,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:01 | 200 |  143.875099ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3601/8417 [44:30<1:08:41,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:02 | 200 |  139.787484ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3602/8417 [44:30<1:08:40,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:03 | 200 |   175.24759ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3603/8417 [44:31<1:08:52,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:03 | 200 |  140.724273ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3604/8417 [44:32<1:08:56,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:04 | 200 |  140.335672ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3605/8417 [44:33<1:09:07,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:05 | 200 |  137.282751ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3606/8417 [44:34<1:09:11,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:06 | 200 |  162.352483ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3607/8417 [44:35<1:09:39,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:07 | 200 |  146.271761ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3608/8417 [44:36<1:09:31,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:08 | 200 |  152.056134ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3609/8417 [44:37<1:09:43,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:09 | 200 |  166.560752ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3610/8417 [44:37<1:09:30,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:10 | 200 |  138.351528ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3611/8417 [44:38<1:08:36,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:10 | 200 |  120.145004ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3612/8417 [44:39<1:09:01,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:11 | 200 |  180.294413ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3613/8417 [44:40<1:09:46,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:12 | 200 |  141.046603ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3614/8417 [44:41<1:08:47,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:13 | 200 |  136.115807ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3615/8417 [44:42<1:08:00,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:14 | 200 |  179.688978ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3616/8417 [44:43<1:08:32,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:15 | 200 |  144.513764ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3617/8417 [44:43<1:09:32,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:16 | 200 |  139.494307ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3618/8417 [44:44<1:08:52,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:16 | 200 |  139.438169ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3619/8417 [44:45<1:09:46,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:17 | 200 |  161.451931ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3620/8417 [44:46<1:09:12,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:18 | 200 |  139.509096ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3621/8417 [44:47<1:08:39,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:19 | 200 |  141.011117ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3622/8417 [44:48<1:08:45,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:20 | 200 |  190.768831ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3623/8417 [44:49<1:10:55,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:21 | 200 |  144.993202ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3624/8417 [44:50<1:10:38,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:22 | 200 |  140.225658ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3625/8417 [44:50<1:09:16,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:23 | 200 |  162.629527ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3626/8417 [44:51<1:09:14,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:23 | 200 |  139.710502ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3627/8417 [44:52<1:08:11,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:24 | 200 |  149.214115ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3628/8417 [44:53<1:08:50,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:25 | 200 |  172.604598ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3629/8417 [44:54<1:09:43,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:26 | 200 |  155.152616ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3630/8417 [44:55<1:10:20,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:27 | 200 |  149.807624ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3631/8417 [44:56<1:09:17,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:28 | 200 |  163.232426ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3632/8417 [44:57<1:09:55,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:29 | 200 |  123.312512ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3633/8417 [44:57<1:09:01,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:30 | 200 |  154.468422ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3634/8417 [44:58<1:09:11,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:30 | 200 |  142.355742ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3635/8417 [44:59<1:09:16,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:31 | 200 |  139.962296ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3636/8417 [45:00<1:08:11,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:32 | 200 |  141.013841ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3637/8417 [45:01<1:08:05,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:33 | 200 |  166.191247ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3638/8417 [45:02<1:08:26,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:34 | 200 |  153.659498ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3639/8417 [45:03<1:08:15,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:35 | 200 |  143.155093ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3640/8417 [45:03<1:08:20,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:35 | 200 |   140.38902ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3641/8417 [45:04<1:08:06,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:36 | 200 |  166.682523ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3642/8417 [45:05<1:09:07,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:37 | 200 |  147.546992ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3643/8417 [45:06<1:08:05,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:38 | 200 |  134.568376ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3644/8417 [45:07<1:07:28,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:39 | 200 |  178.274153ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3645/8417 [45:08<1:07:54,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:40 | 200 |  161.546138ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3646/8417 [45:09<1:08:17,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:41 | 200 |  136.319484ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3647/8417 [45:09<1:08:06,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:41 | 200 |  152.182264ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3648/8417 [45:10<1:07:38,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:42 | 200 |  179.368459ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3649/8417 [45:11<1:08:26,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:43 | 200 |    149.8564ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3650/8417 [45:12<1:08:30,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:44 | 200 |  142.539563ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3651/8417 [45:13<1:08:07,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:45 | 200 |  148.712855ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3652/8417 [45:14<1:07:57,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:46 | 200 |  167.198102ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3653/8417 [45:15<1:08:25,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:47 | 200 |  144.554528ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3654/8417 [45:15<1:08:20,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:47 | 200 |  135.940268ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3655/8417 [45:16<1:07:14,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:48 | 200 |  180.990349ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3656/8417 [45:17<1:08:18,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:49 | 200 |  153.435152ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3657/8417 [45:18<1:08:43,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:50 | 200 |  139.759048ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3658/8417 [45:19<1:08:38,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:51 | 200 |  140.161679ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3659/8417 [45:20<1:08:03,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:52 | 200 |   176.03942ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3660/8417 [45:21<1:08:17,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:53 | 200 |  118.081784ms |       127.0.0.1 | POST     "/api/chat"

 43%|████▎     | 3661/8417 [45:21<1:06:55,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:54 | 200 |  146.494536ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3662/8417 [45:22<1:07:39,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:54 | 200 |  179.601142ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3663/8417 [45:23<1:08:45,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:55 | 200 |  147.351055ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3664/8417 [45:24<1:08:15,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:56 | 200 |  142.447103ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3665/8417 [45:25<1:08:01,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:57 | 200 |  138.507196ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3666/8417 [45:26<1:08:35,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:58 | 200 |  219.290012ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3667/8417 [45:27<1:10:54,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:09:59 | 200 |  181.783111ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3668/8417 [45:28<1:10:58,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:00 | 200 |  146.911336ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3669/8417 [45:28<1:10:12,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:01 | 200 |  151.886519ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3670/8417 [45:29<1:10:24,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:01 | 200 |  177.832517ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3671/8417 [45:30<1:10:27,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:02 | 200 |   140.38543ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3672/8417 [45:31<1:09:30,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:03 | 200 |  143.647493ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3673/8417 [45:32<1:08:56,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:04 | 200 |  165.249612ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3674/8417 [45:33<1:09:00,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:05 | 200 |  143.250337ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3675/8417 [45:34<1:08:16,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:06 | 200 |   151.65577ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3676/8417 [45:35<1:08:06,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:07 | 200 |  142.134766ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3677/8417 [45:35<1:07:29,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:07 | 200 |  152.822045ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3678/8417 [45:36<1:07:25,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:08 | 200 |  151.284806ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3679/8417 [45:37<1:07:43,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:09 | 200 |  141.285102ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3680/8417 [45:38<1:07:41,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:10 | 200 |  147.261408ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3681/8417 [45:39<1:08:48,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:11 | 200 |  162.040771ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▎     | 3682/8417 [45:40<1:08:44,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:12 | 200 |  175.774653ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3683/8417 [45:41<1:08:58,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:13 | 200 |  155.856959ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3684/8417 [45:41<1:08:57,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:14 | 200 |   141.83528ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3685/8417 [45:42<1:08:27,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:14 | 200 |  142.965714ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3686/8417 [45:43<1:08:54,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:15 | 200 |  149.527213ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3687/8417 [45:44<1:09:23,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:16 | 200 |  147.462427ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3688/8417 [45:45<1:08:39,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:17 | 200 |  149.655044ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3689/8417 [45:46<1:08:36,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:18 | 200 |  141.572766ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3690/8417 [45:47<1:08:14,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:19 | 200 |  138.418828ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3691/8417 [45:48<1:07:48,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:20 | 200 |  112.653623ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3692/8417 [45:48<1:07:11,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:21 | 200 |  179.073142ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3693/8417 [45:49<1:08:40,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:21 | 200 |  149.019117ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3694/8417 [45:50<1:09:27,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:22 | 200 |  144.299269ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3695/8417 [45:51<1:08:45,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:23 | 200 |  141.331121ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3696/8417 [45:52<1:08:44,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:24 | 200 |  139.145871ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3697/8417 [45:53<1:08:41,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:25 | 200 |  142.270334ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3698/8417 [45:54<1:08:02,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:26 | 200 |   132.47541ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3699/8417 [45:54<1:07:57,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:27 | 200 |  182.544804ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3700/8417 [45:55<1:09:20,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:28 | 200 |  179.003131ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3701/8417 [45:56<1:10:08,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:28 | 200 |  138.206921ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3702/8417 [45:57<1:09:01,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:29 | 200 |  148.290393ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3703/8417 [45:58<1:08:53,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:30 | 200 |  151.341252ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3704/8417 [45:59<1:09:32,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:31 | 200 |  172.899379ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3705/8417 [46:00<1:10:55,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:32 | 200 |  148.012255ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3706/8417 [46:01<1:09:29,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:33 | 200 |  141.681003ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3707/8417 [46:02<1:08:51,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:34 | 200 |   136.97613ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3708/8417 [46:02<1:07:53,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:35 | 200 |  170.747276ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3709/8417 [46:03<1:08:07,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:35 | 200 |  150.741339ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3710/8417 [46:04<1:07:51,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:36 | 200 |   139.13298ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3711/8417 [46:05<1:06:58,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:37 | 200 |  141.143724ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3712/8417 [46:06<1:06:58,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:38 | 200 |  178.910779ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3713/8417 [46:07<1:07:19,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:39 | 200 |  148.463367ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3714/8417 [46:08<1:08:14,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:40 | 200 |  147.632516ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3715/8417 [46:08<1:08:06,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:41 | 200 |  143.857718ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3716/8417 [46:09<1:08:23,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:41 | 200 |  140.801834ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3717/8417 [46:10<1:07:30,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:42 | 200 |  139.992854ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3718/8417 [46:11<1:07:22,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:43 | 200 |  181.751783ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3719/8417 [46:12<1:08:00,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:44 | 200 |  144.104446ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3720/8417 [46:13<1:07:30,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:45 | 200 |  113.560067ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3721/8417 [46:14<1:06:52,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:46 | 200 |   139.28699ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3722/8417 [46:14<1:06:52,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:47 | 200 |  176.587246ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3723/8417 [46:15<1:07:22,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:47 | 200 |  137.699103ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3724/8417 [46:16<1:07:18,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:48 | 200 |   143.25971ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3725/8417 [46:17<1:06:55,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:49 | 200 |  168.178058ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3726/8417 [46:18<1:07:44,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:50 | 200 |  159.178587ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3727/8417 [46:19<1:08:17,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:51 | 200 |  137.694653ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3728/8417 [46:20<1:07:47,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:52 | 200 |  142.090596ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3729/8417 [46:21<1:07:30,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:53 | 200 |  159.047319ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3730/8417 [46:21<1:07:39,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:54 | 200 |  144.757101ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3731/8417 [46:22<1:07:06,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:54 | 200 |  139.747399ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3732/8417 [46:23<1:07:25,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:55 | 200 |  177.657224ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3733/8417 [46:24<1:07:52,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:56 | 200 |  116.228696ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3734/8417 [46:25<1:07:05,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:57 | 200 |  143.092247ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3735/8417 [46:26<1:06:31,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:58 | 200 |  183.092292ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3736/8417 [46:27<1:07:04,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:10:59 | 200 |   149.02411ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3737/8417 [46:27<1:07:00,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:00 | 200 |  136.091773ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3738/8417 [46:28<1:06:43,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:00 | 200 |  151.626752ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3739/8417 [46:29<1:08:41,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:01 | 200 |  175.102628ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3740/8417 [46:30<1:08:45,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:02 | 200 |  181.254567ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3741/8417 [46:31<1:09:07,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:03 | 200 |  141.162937ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3742/8417 [46:32<1:08:17,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:04 | 200 |  145.652186ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3743/8417 [46:33<1:07:15,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:05 | 200 |  143.624483ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3744/8417 [46:34<1:06:48,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:06 | 200 |  176.123716ms |       127.0.0.1 | POST     "/api/chat"

 44%|████▍     | 3745/8417 [46:34<1:07:48,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:07 | 200 |  146.788391ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3746/8417 [46:35<1:07:32,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:07 | 200 |  146.254544ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3747/8417 [46:36<1:06:50,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:08 | 200 |  177.289811ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3748/8417 [46:37<1:07:25,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:09 | 200 |  147.475343ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3749/8417 [46:38<1:07:22,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:10 | 200 |  139.281998ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3750/8417 [46:39<1:07:40,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:11 | 200 |  137.952064ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3751/8417 [46:40<1:06:58,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:12 | 200 |  160.001839ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3752/8417 [46:40<1:07:18,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:13 | 200 |  145.345189ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3753/8417 [46:41<1:06:37,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:13 | 200 |  139.857014ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3754/8417 [46:42<1:06:27,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:14 | 200 |  181.230317ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3755/8417 [46:43<1:07:32,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:15 | 200 |  136.384569ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3756/8417 [46:44<1:06:58,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:16 | 200 |  148.444505ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3757/8417 [46:45<1:06:36,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:17 | 200 |  175.647173ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3758/8417 [46:46<1:07:13,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:18 | 200 |  146.352912ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3759/8417 [46:47<1:07:18,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:19 | 200 |  139.511242ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3760/8417 [46:47<1:07:22,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:19 | 200 |  116.901871ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3761/8417 [46:48<1:06:43,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:20 | 200 |  140.288905ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3762/8417 [46:49<1:06:41,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:21 | 200 |  142.009553ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3763/8417 [46:50<1:06:26,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:22 | 200 |  174.961384ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3764/8417 [46:51<1:06:53,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:23 | 200 |  174.508453ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3765/8417 [46:52<1:07:35,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:24 | 200 |  146.046816ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3766/8417 [46:53<1:07:07,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:25 | 200 |  145.956794ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3767/8417 [46:53<1:07:10,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:26 | 200 |   140.70195ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3768/8417 [46:54<1:06:47,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:26 | 200 |  142.627836ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3769/8417 [46:55<1:06:35,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:27 | 200 |  175.775799ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3770/8417 [46:56<1:06:53,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:28 | 200 |   170.46545ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3771/8417 [46:57<1:07:32,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 45%|████▍     | 3772/8417 [46:58<1:06:53,  1.16it/s]

[GIN] 2025/06/27 - 00:11:29 | 200 |  150.463619ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:30 | 200 |  129.667015ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3773/8417 [46:59<1:06:05,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:31 | 200 |  139.940349ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3774/8417 [46:59<1:05:38,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:32 | 200 |  171.742322ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3775/8417 [47:00<1:06:55,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:32 | 200 |   168.02384ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3776/8417 [47:01<1:07:42,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:33 | 200 |  147.908211ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3777/8417 [47:02<1:07:13,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:34 | 200 |   152.07241ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3778/8417 [47:03<1:06:50,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:35 | 200 |  144.566197ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3779/8417 [47:04<1:06:28,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:36 | 200 |  137.680527ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3780/8417 [47:05<1:06:13,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:37 | 200 |  148.403701ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3781/8417 [47:05<1:06:25,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:38 | 200 |   158.27212ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3782/8417 [47:06<1:07:05,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:38 | 200 |  140.943736ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3783/8417 [47:07<1:06:40,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:39 | 200 |   139.67353ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3784/8417 [47:08<1:06:28,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:40 | 200 |  177.958801ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3785/8417 [47:09<1:07:43,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:41 | 200 |   145.60634ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3786/8417 [47:10<1:07:23,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:42 | 200 |  142.256134ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▍     | 3787/8417 [47:11<1:06:36,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:43 | 200 |  155.518853ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3788/8417 [47:12<1:06:35,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:44 | 200 |  145.048524ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3789/8417 [47:12<1:06:30,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:45 | 200 |   178.92662ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3790/8417 [47:13<1:07:57,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:45 | 200 |  145.706934ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3791/8417 [47:14<1:07:35,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:46 | 200 |  139.734303ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3792/8417 [47:15<1:06:55,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:47 | 200 |  138.872961ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3793/8417 [47:16<1:06:00,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:48 | 200 |  157.365335ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3794/8417 [47:17<1:06:00,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:49 | 200 |  151.790672ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3795/8417 [47:18<1:06:30,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:50 | 200 |   145.06351ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3796/8417 [47:18<1:06:12,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:51 | 200 |  154.614958ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3797/8417 [47:19<1:06:30,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:51 | 200 |   141.92151ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3798/8417 [47:20<1:06:17,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:52 | 200 |  118.428279ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3799/8417 [47:21<1:05:40,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:53 | 200 |  135.596782ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3800/8417 [47:22<1:05:05,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:54 | 200 |  180.380438ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3801/8417 [47:23<1:06:08,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:55 | 200 |  150.204436ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3802/8417 [47:24<1:06:34,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:56 | 200 |  141.855335ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3803/8417 [47:24<1:06:31,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:57 | 200 |  141.577675ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3804/8417 [47:25<1:05:59,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:57 | 200 |  163.581006ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3805/8417 [47:26<1:06:41,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:58 | 200 |  142.873704ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3806/8417 [47:27<1:06:21,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:11:59 | 200 |  143.644615ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3807/8417 [47:28<1:06:48,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:00 | 200 |  165.099428ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3808/8417 [47:29<1:07:04,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:01 | 200 |  144.131314ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3809/8417 [47:30<1:06:33,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:02 | 200 |   142.93197ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3810/8417 [47:31<1:06:30,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:03 | 200 |  144.429867ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3811/8417 [47:31<1:05:56,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:04 | 200 |  140.682956ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3812/8417 [47:32<1:07:45,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:04 | 200 |  146.030232ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3813/8417 [47:33<1:07:08,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:05 | 200 |  163.859631ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3814/8417 [47:34<1:07:22,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:06 | 200 |  142.618167ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3815/8417 [47:35<1:06:46,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:07 | 200 |  152.472512ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3816/8417 [47:36<1:06:46,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:08 | 200 |  161.229341ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3817/8417 [47:37<1:07:01,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:09 | 200 |  148.253368ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3818/8417 [47:38<1:06:28,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:10 | 200 |  137.616761ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3819/8417 [47:38<1:06:00,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:11 | 200 |  173.994756ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3820/8417 [47:39<1:07:03,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:11 | 200 |  111.296579ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3821/8417 [47:40<1:05:46,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:12 | 200 |  140.728774ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3822/8417 [47:41<1:06:20,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:13 | 200 |  166.554533ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3823/8417 [47:42<1:06:53,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:14 | 200 |  140.661855ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3824/8417 [47:43<1:06:12,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:15 | 200 |  144.794065ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3825/8417 [47:44<1:06:13,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:16 | 200 |   161.66064ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3826/8417 [47:44<1:06:28,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:17 | 200 |  144.931653ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3827/8417 [47:45<1:06:29,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:17 | 200 |  140.935689ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3828/8417 [47:46<1:05:45,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:18 | 200 |  164.997749ms |       127.0.0.1 | POST     "/api/chat"

 45%|████▌     | 3829/8417 [47:47<1:05:52,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:19 | 200 |  150.723414ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3830/8417 [47:48<1:06:34,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:20 | 200 |   117.54669ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3831/8417 [47:49<1:06:13,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:21 | 200 |  183.340126ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3832/8417 [47:50<1:07:08,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:22 | 200 |  133.934019ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3833/8417 [47:51<1:05:57,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:23 | 200 |  147.252951ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3834/8417 [47:51<1:05:54,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:24 | 200 |  167.565498ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3835/8417 [47:52<1:07:07,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:24 | 200 |  154.526825ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3836/8417 [47:53<1:07:15,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:25 | 200 |  147.523902ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3837/8417 [47:54<1:07:17,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:26 | 200 |  148.887626ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3838/8417 [47:55<1:06:56,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:27 | 200 |  133.975559ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3839/8417 [47:56<1:06:14,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:28 | 200 |  183.771384ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3840/8417 [47:57<1:06:54,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:29 | 200 |  144.859767ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3841/8417 [47:58<1:06:51,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:30 | 200 |  147.760455ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3842/8417 [47:58<1:06:50,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:31 | 200 |  167.683745ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3843/8417 [47:59<1:07:56,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:32 | 200 |  117.625325ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3844/8417 [48:00<1:07:06,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:32 | 200 |  137.863242ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3845/8417 [48:01<1:06:44,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:33 | 200 |  169.440754ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3846/8417 [48:02<1:06:54,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:34 | 200 |  143.615925ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3847/8417 [48:03<1:06:34,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:35 | 200 |  138.140471ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3848/8417 [48:04<1:07:30,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:36 | 200 |  175.063274ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3849/8417 [48:05<1:07:44,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:37 | 200 |  179.878534ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3850/8417 [48:06<1:07:43,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:38 | 200 |  149.372799ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3851/8417 [48:06<1:06:42,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:38 | 200 |  118.637141ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3852/8417 [48:07<1:05:11,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:39 | 200 |  145.412443ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3853/8417 [48:08<1:04:53,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:40 | 200 |   140.57691ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3854/8417 [48:09<1:04:56,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:41 | 200 |  178.692684ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3855/8417 [48:10<1:05:30,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:42 | 200 |  141.969704ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3856/8417 [48:11<1:05:31,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:43 | 200 |  154.038621ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3857/8417 [48:12<1:06:19,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:44 | 200 |  140.508091ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3858/8417 [48:12<1:06:00,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:45 | 200 |  146.317431ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3859/8417 [48:13<1:05:35,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:45 | 200 |  139.737217ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3860/8417 [48:14<1:05:18,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:46 | 200 |  133.335173ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3861/8417 [48:15<1:04:29,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:47 | 200 |  140.020597ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3862/8417 [48:16<1:04:13,  1.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:48 | 200 |  170.097526ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3863/8417 [48:17<1:04:51,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:49 | 200 |   160.98194ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3864/8417 [48:18<1:05:11,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:50 | 200 |  146.985521ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3865/8417 [48:18<1:05:11,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:50 | 200 |  156.369193ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3866/8417 [48:19<1:06:08,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:51 | 200 |  140.431824ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3867/8417 [48:20<1:05:52,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:52 | 200 |  144.476595ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3868/8417 [48:21<1:05:46,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:53 | 200 |  135.061659ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3869/8417 [48:22<1:05:07,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:54 | 200 |  147.213285ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3870/8417 [48:23<1:05:10,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:55 | 200 |  176.479638ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3871/8417 [48:24<1:06:29,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:56 | 200 |  141.826946ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3872/8417 [48:24<1:06:14,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:57 | 200 |  143.852403ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3873/8417 [48:25<1:06:21,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:57 | 200 |  142.934633ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3874/8417 [48:26<1:05:49,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:58 | 200 |  138.952656ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3875/8417 [48:27<1:05:36,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:12:59 | 200 |   141.75634ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3876/8417 [48:28<1:05:44,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:00 | 200 |  164.671224ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3877/8417 [48:29<1:05:59,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:01 | 200 |  143.507483ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3878/8417 [48:30<1:05:20,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:02 | 200 |  141.027703ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3879/8417 [48:31<1:05:26,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:03 | 200 |  179.642609ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3880/8417 [48:31<1:06:18,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:04 | 200 |  147.050439ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3881/8417 [48:32<1:06:06,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:04 | 200 |  143.083081ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3882/8417 [48:33<1:05:32,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:05 | 200 |  172.128926ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3883/8417 [48:34<1:06:46,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:06 | 200 |  144.875957ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3884/8417 [48:35<1:11:46,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:07 | 200 |  195.008252ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3885/8417 [48:36<1:11:13,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:08 | 200 |  142.494878ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3886/8417 [48:37<1:09:40,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:09 | 200 |  151.343758ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3887/8417 [48:38<1:08:22,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:10 | 200 |  140.507831ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3888/8417 [48:39<1:07:21,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:11 | 200 |  140.806346ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3889/8417 [48:40<1:06:43,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:12 | 200 |  162.895073ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3890/8417 [48:40<1:06:40,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:13 | 200 |  144.518236ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3891/8417 [48:41<1:06:35,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:14 | 200 |   147.51147ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▌     | 3892/8417 [48:42<1:06:37,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:14 | 200 |  147.593183ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3893/8417 [48:43<1:06:07,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:15 | 200 |  140.657686ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3894/8417 [48:44<1:05:54,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:16 | 200 |  141.503769ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3895/8417 [48:45<1:05:40,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:17 | 200 |  172.345577ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3896/8417 [48:46<1:05:53,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:18 | 200 |  140.635363ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3897/8417 [48:47<1:05:17,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:19 | 200 |  140.660131ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3898/8417 [48:47<1:04:52,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:20 | 200 |  160.894518ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3899/8417 [48:48<1:05:09,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:20 | 200 |  150.035374ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3900/8417 [48:49<1:05:52,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:21 | 200 |  150.418449ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3901/8417 [48:50<1:05:24,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:22 | 200 |   144.42783ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3902/8417 [48:51<1:04:53,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:23 | 200 |   145.54814ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3903/8417 [48:52<1:04:23,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:24 | 200 |    139.8565ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3904/8417 [48:53<1:04:26,  1.17it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:25 | 200 |  134.517331ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3905/8417 [48:53<1:04:38,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:26 | 200 |  166.708093ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3906/8417 [48:54<1:05:58,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:26 | 200 |  140.561847ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3907/8417 [48:55<1:05:32,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:27 | 200 |  136.928845ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3908/8417 [48:56<1:05:48,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:28 | 200 |  160.579007ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3909/8417 [48:57<1:06:05,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:29 | 200 |  180.664759ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3910/8417 [48:58<1:07:16,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:30 | 200 |  146.267278ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3911/8417 [48:59<1:07:12,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:31 | 200 |  145.619551ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3912/8417 [49:00<1:06:55,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:32 | 200 |  150.007769ms |       127.0.0.1 | POST     "/api/chat"

 46%|████▋     | 3913/8417 [49:01<1:06:08,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:33 | 200 |  139.142113ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3914/8417 [49:01<1:05:16,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:34 | 200 |  136.160923ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3915/8417 [49:02<1:05:12,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:34 | 200 |  163.893304ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3916/8417 [49:03<1:05:51,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:35 | 200 |  145.416894ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3917/8417 [49:04<1:05:38,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:36 | 200 |  139.201391ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3918/8417 [49:05<1:05:46,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:37 | 200 |  167.871077ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3919/8417 [49:06<1:05:47,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:38 | 200 |  145.934045ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3920/8417 [49:07<1:05:44,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:39 | 200 |  178.220145ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3921/8417 [49:08<1:06:20,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:40 | 200 |  147.892016ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3922/8417 [49:08<1:06:06,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:41 | 200 |  126.537461ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3923/8417 [49:09<1:05:37,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:41 | 200 |  181.686533ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3924/8417 [49:10<1:05:48,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:42 | 200 |  146.016781ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3925/8417 [49:11<1:06:14,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:43 | 200 |  156.250731ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3926/8417 [49:12<1:06:29,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:44 | 200 |  145.006578ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3927/8417 [49:13<1:05:49,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:45 | 200 |  137.404401ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3928/8417 [49:14<1:05:39,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:46 | 200 |  167.884081ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3929/8417 [49:15<1:06:36,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:47 | 200 |  123.850902ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3930/8417 [49:16<1:05:57,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:48 | 200 |  155.784466ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3931/8417 [49:16<1:05:38,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:49 | 200 |  145.048423ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3932/8417 [49:17<1:04:58,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:49 | 200 |  113.910294ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3933/8417 [49:18<1:04:21,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:50 | 200 |  143.926521ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3934/8417 [49:19<1:04:45,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:51 | 200 |  159.681551ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3935/8417 [49:20<1:05:16,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:52 | 200 |    149.1565ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3936/8417 [49:21<1:05:04,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:53 | 200 |  127.707626ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3937/8417 [49:22<1:04:18,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:54 | 200 |  182.757868ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3938/8417 [49:22<1:04:53,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:55 | 200 |  145.511715ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3939/8417 [49:23<1:05:19,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:55 | 200 |  145.838612ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3940/8417 [49:24<1:05:25,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:56 | 200 |  144.941469ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3941/8417 [49:25<1:05:15,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:57 | 200 |  144.685198ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3942/8417 [49:26<1:04:45,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:58 | 200 |  176.209174ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3943/8417 [49:27<1:05:16,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:13:59 | 200 |  145.578895ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3944/8417 [49:28<1:04:43,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:00 | 200 |  144.877935ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3945/8417 [49:29<1:05:34,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:01 | 200 |  144.028845ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3946/8417 [49:29<1:05:14,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:02 | 200 |  134.926766ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3947/8417 [49:30<1:05:17,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:02 | 200 |  113.025256ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3948/8417 [49:31<1:04:03,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:03 | 200 |  181.733026ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3949/8417 [49:32<1:05:31,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:04 | 200 |  155.839437ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3950/8417 [49:33<1:05:29,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:05 | 200 |  142.136926ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3951/8417 [49:34<1:04:55,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:06 | 200 |  146.193218ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3952/8417 [49:35<1:05:06,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:07 | 200 |  143.356002ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3953/8417 [49:36<1:04:54,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:08 | 200 |  141.215866ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3954/8417 [49:36<1:05:17,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:09 | 200 |  161.165704ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3955/8417 [49:37<1:05:20,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:09 | 200 |  142.266031ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3956/8417 [49:38<1:05:48,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:10 | 200 |  181.538576ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3957/8417 [49:39<1:07:32,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:11 | 200 |  165.915062ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3958/8417 [49:40<1:07:01,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:12 | 200 |  149.723584ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3959/8417 [49:41<1:06:27,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:13 | 200 |   142.80918ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3960/8417 [49:42<1:06:03,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:14 | 200 |  170.503636ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3961/8417 [49:43<1:06:52,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:15 | 200 |    166.3635ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3962/8417 [49:44<1:06:44,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:16 | 200 |  143.409858ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3963/8417 [49:45<1:05:55,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:17 | 200 |  141.752623ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3964/8417 [49:45<1:05:14,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:17 | 200 |   139.90134ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3965/8417 [49:46<1:04:30,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:18 | 200 |  159.573022ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3966/8417 [49:47<1:04:33,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:19 | 200 |  143.837501ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3967/8417 [49:48<1:04:36,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:20 | 200 |  147.891765ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3968/8417 [49:49<1:05:09,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:21 | 200 |  165.346409ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3969/8417 [49:50<1:05:16,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:22 | 200 |  142.721584ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3970/8417 [49:51<1:05:01,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:23 | 200 |   140.46233ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3971/8417 [49:51<1:04:53,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:24 | 200 |  160.029335ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3972/8417 [49:52<1:05:33,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:25 | 200 |  179.676735ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3973/8417 [49:53<1:06:11,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:25 | 200 |   144.60099ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3974/8417 [49:54<1:05:18,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:26 | 200 |  140.399376ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3975/8417 [49:55<1:04:37,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:27 | 200 |  134.965238ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3976/8417 [49:56<1:04:01,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:28 | 200 |  164.802431ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3977/8417 [49:57<1:04:18,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:29 | 200 |  120.511885ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3978/8417 [49:58<1:03:49,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:30 | 200 |  144.180051ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3979/8417 [49:58<1:03:51,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:31 | 200 |  170.860938ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3980/8417 [49:59<1:04:49,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:32 | 200 |  143.135051ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3981/8417 [50:00<1:05:00,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:32 | 200 |  144.074661ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3982/8417 [50:01<1:04:41,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:33 | 200 |  130.840062ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3983/8417 [50:02<1:04:09,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:34 | 200 |   178.55072ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3984/8417 [50:03<1:04:45,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:35 | 200 |  181.491248ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3985/8417 [50:04<1:05:27,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:36 | 200 |  145.710999ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3986/8417 [50:05<1:05:17,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:37 | 200 |  154.801636ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3987/8417 [50:06<1:05:37,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:38 | 200 |   139.17288ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3988/8417 [50:06<1:04:53,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:39 | 200 |  141.788463ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3989/8417 [50:07<1:04:50,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:39 | 200 |  139.571427ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3990/8417 [50:08<1:05:05,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:40 | 200 |  136.250551ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3991/8417 [50:09<1:05:40,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:41 | 200 |  140.247364ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3992/8417 [50:10<1:05:49,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:42 | 200 |  177.576899ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3993/8417 [50:11<1:07:08,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:43 | 200 |  159.855152ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3994/8417 [50:12<1:06:48,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:44 | 200 |  135.517708ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3995/8417 [50:13<1:05:25,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:45 | 200 |  142.131966ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3996/8417 [50:14<1:05:17,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:46 | 200 |  164.693137ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3997/8417 [50:14<1:06:05,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:47 | 200 |  174.867184ms |       127.0.0.1 | POST     "/api/chat"

 47%|████▋     | 3998/8417 [50:15<1:06:19,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:47 | 200 |  116.610472ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 3999/8417 [50:16<1:04:41,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:48 | 200 |  143.131317ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4000/8417 [50:17<1:04:28,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:49 | 200 |  185.079313ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4001/8417 [50:18<1:05:28,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:50 | 200 |   148.96101ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4002/8417 [50:19<1:05:21,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:51 | 200 |  144.851091ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4003/8417 [50:20<1:05:10,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:52 | 200 |  147.879297ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4004/8417 [50:21<1:05:08,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:53 | 200 |    141.5542ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4005/8417 [50:22<1:04:56,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:54 | 200 |  141.409119ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4006/8417 [50:22<1:04:39,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:55 | 200 |  162.375858ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4007/8417 [50:23<1:05:19,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:55 | 200 |  177.621955ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4008/8417 [50:24<1:06:07,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:56 | 200 |  122.491839ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4009/8417 [50:25<1:04:55,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:57 | 200 |  146.147013ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4010/8417 [50:26<1:05:31,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:58 | 200 |  135.263733ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4011/8417 [50:27<1:04:37,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:14:59 | 200 |  144.215739ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4012/8417 [50:28<1:04:18,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:00 | 200 |  176.673806ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4013/8417 [50:29<1:05:48,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:01 | 200 |  152.740543ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4014/8417 [50:30<1:06:12,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:02 | 200 |  144.367649ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4015/8417 [50:30<1:05:39,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:03 | 200 |  136.339873ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4016/8417 [50:31<1:04:56,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:03 | 200 |  142.616445ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4017/8417 [50:32<1:05:47,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:04 | 200 |  157.019352ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4018/8417 [50:33<1:05:36,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:05 | 200 |   187.94739ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4019/8417 [50:34<1:06:05,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:06 | 200 |  142.522395ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4020/8417 [50:35<1:05:48,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:07 | 200 |  148.398671ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4021/8417 [50:36<1:05:34,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:08 | 200 |  143.573597ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4022/8417 [50:37<1:05:13,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:09 | 200 |  141.254289ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4023/8417 [50:38<1:04:59,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:10 | 200 |  136.462462ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4024/8417 [50:38<1:04:49,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:11 | 200 |  137.307749ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4025/8417 [50:39<1:06:09,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:12 | 200 |   174.96953ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4026/8417 [50:40<1:06:39,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:13 | 200 |  149.697694ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4027/8417 [50:41<1:07:11,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 48%|████▊     | 4028/8417 [50:42<1:06:40,  1.10it/s]

[GIN] 2025/06/27 - 00:15:13 | 200 |  162.372662ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:14 | 200 |  135.166694ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4029/8417 [50:43<1:05:23,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:15 | 200 |  141.503447ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4030/8417 [50:44<1:04:31,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:16 | 200 |  174.937488ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4031/8417 [50:45<1:04:36,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:17 | 200 |  166.319322ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4032/8417 [50:46<1:04:40,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:18 | 200 |  148.344763ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4033/8417 [50:47<1:04:03,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:19 | 200 |  137.100821ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4034/8417 [50:47<1:03:24,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:19 | 200 |  135.493136ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4035/8417 [50:48<1:02:53,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:20 | 200 |  181.609866ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4036/8417 [50:49<1:04:23,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:21 | 200 |  144.084946ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4037/8417 [50:50<1:04:18,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:22 | 200 |  149.412732ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4038/8417 [50:51<1:03:41,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:23 | 200 |  144.983862ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4039/8417 [50:52<1:03:07,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:24 | 200 |  117.049844ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4040/8417 [50:53<1:02:39,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:25 | 200 |  150.344124ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4041/8417 [50:53<1:03:27,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:26 | 200 |  138.817706ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4042/8417 [50:54<1:03:25,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:26 | 200 |  175.642802ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4043/8417 [50:55<1:04:33,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:27 | 200 |  170.719046ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4044/8417 [50:56<1:04:19,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:28 | 200 |  145.696457ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4045/8417 [50:57<1:03:37,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:29 | 200 |  149.863619ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4046/8417 [50:58<1:03:36,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:30 | 200 |  139.652372ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4047/8417 [50:59<1:04:21,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:31 | 200 |  144.100925ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4048/8417 [51:00<1:03:58,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:32 | 200 |  139.060332ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4049/8417 [51:00<1:03:29,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:33 | 200 |  134.219034ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4050/8417 [51:01<1:03:21,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:34 | 200 |  182.692305ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4051/8417 [51:02<1:03:59,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:34 | 200 |  178.863638ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4052/8417 [51:03<1:04:53,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:35 | 200 |  146.561027ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4053/8417 [51:04<1:04:20,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:36 | 200 |  147.177444ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4054/8417 [51:05<1:03:54,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:37 | 200 |  140.371432ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4055/8417 [51:06<1:03:47,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:38 | 200 |  139.029387ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4056/8417 [51:07<1:03:22,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:39 | 200 |  138.999772ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4057/8417 [51:08<1:03:12,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:40 | 200 |   166.68007ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4058/8417 [51:08<1:03:23,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:41 | 200 |  145.103555ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4059/8417 [51:09<1:03:50,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:41 | 200 |  146.419908ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4060/8417 [51:10<1:03:59,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:42 | 200 |  145.959897ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4061/8417 [51:11<1:03:54,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:43 | 200 |  140.979168ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4062/8417 [51:12<1:03:49,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:44 | 200 |  162.612278ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4063/8417 [51:13<1:04:01,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:45 | 200 |  156.994148ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4064/8417 [51:14<1:04:42,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:46 | 200 |  155.673206ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4065/8417 [51:15<1:04:45,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:47 | 200 |  143.493939ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4066/8417 [51:16<1:04:53,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:48 | 200 |  136.570898ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4067/8417 [51:16<1:04:29,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:49 | 200 |  161.637606ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4068/8417 [51:17<1:04:28,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:49 | 200 |  176.636964ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4069/8417 [51:18<1:04:31,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:50 | 200 |  156.863416ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4070/8417 [51:19<1:04:51,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:51 | 200 |  139.964108ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4071/8417 [51:20<1:04:44,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:52 | 200 |  139.896723ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4072/8417 [51:21<1:04:29,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:53 | 200 |  171.029408ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4073/8417 [51:22<1:04:24,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:54 | 200 |  162.714161ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4074/8417 [51:23<1:04:35,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:55 | 200 |  145.128133ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4075/8417 [51:24<1:04:04,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:56 | 200 |  144.895043ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4076/8417 [51:24<1:04:19,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:57 | 200 |  162.509034ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4077/8417 [51:25<1:04:16,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:57 | 200 |  150.405274ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4078/8417 [51:26<1:03:36,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:58 | 200 |  146.202218ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4079/8417 [51:27<1:03:15,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:15:59 | 200 |  142.922791ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4080/8417 [51:28<1:04:13,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:00 | 200 |  138.890478ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4081/8417 [51:29<1:04:16,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:01 | 200 |    171.6428ms |       127.0.0.1 | POST     "/api/chat"

 48%|████▊     | 4082/8417 [51:30<1:04:30,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:02 | 200 |  181.747838ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4083/8417 [51:31<1:05:21,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:03 | 200 |   147.54878ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4084/8417 [51:32<1:04:38,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:04 | 200 |  118.120247ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4085/8417 [51:32<1:03:27,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:05 | 200 |  138.188365ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4086/8417 [51:33<1:03:33,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:05 | 200 |  177.003797ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4087/8417 [51:34<1:04:29,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:06 | 200 |  171.940605ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4088/8417 [51:35<1:05:19,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:07 | 200 |  138.704988ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4089/8417 [51:36<1:04:22,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:08 | 200 |   148.48012ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4090/8417 [51:37<1:03:59,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:09 | 200 |  163.774255ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4091/8417 [51:38<1:04:00,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:10 | 200 |  162.782197ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4092/8417 [51:39<1:04:20,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:11 | 200 |  158.953469ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4093/8417 [51:40<1:04:17,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:12 | 200 |  135.639875ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4094/8417 [51:40<1:03:34,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:12 | 200 |  115.017374ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4095/8417 [51:41<1:02:18,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:13 | 200 |  141.691272ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4096/8417 [51:42<1:02:14,  1.16it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:14 | 200 |  178.088705ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4097/8417 [51:43<1:03:10,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:15 | 200 |  176.883834ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4098/8417 [51:44<1:04:04,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:16 | 200 |  136.489889ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4099/8417 [51:45<1:04:38,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:17 | 200 |  158.120244ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4100/8417 [51:46<1:05:33,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:18 | 200 |  141.742986ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4101/8417 [51:47<1:04:44,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:19 | 200 |  144.879456ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4102/8417 [51:48<1:04:09,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:20 | 200 |  138.569905ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▊     | 4103/8417 [51:48<1:04:10,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:21 | 200 |  139.856753ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4104/8417 [51:49<1:04:44,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:21 | 200 |  172.438281ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4105/8417 [51:50<1:04:21,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:22 | 200 |  185.029067ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4106/8417 [51:51<1:04:32,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:23 | 200 |  145.611532ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4107/8417 [51:52<1:04:03,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:24 | 200 |  146.403067ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4108/8417 [51:53<1:04:28,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:25 | 200 |  142.842982ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4109/8417 [51:54<1:03:44,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:26 | 200 |  141.874737ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4110/8417 [51:55<1:03:17,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:27 | 200 |  135.573555ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4111/8417 [51:56<1:03:47,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:28 | 200 |  162.374279ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4112/8417 [51:56<1:03:21,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:29 | 200 |  175.091525ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4113/8417 [51:57<1:03:21,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:29 | 200 |  148.576922ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4114/8417 [51:58<1:03:06,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:30 | 200 |  141.715209ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4115/8417 [51:59<1:03:13,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:31 | 200 |  142.375191ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4116/8417 [52:00<1:03:35,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:32 | 200 |  138.461172ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4117/8417 [52:01<1:03:11,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:33 | 200 |   136.70179ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4118/8417 [52:02<1:03:17,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:34 | 200 |  165.554013ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4119/8417 [52:03<1:03:53,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:35 | 200 |  146.667021ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4120/8417 [52:04<1:04:40,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:36 | 200 |  140.365235ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4121/8417 [52:04<1:04:07,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:37 | 200 |  145.805764ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4122/8417 [52:05<1:03:47,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:37 | 200 |  140.942748ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4123/8417 [52:06<1:02:54,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:38 | 200 |  136.346741ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4124/8417 [52:07<1:02:45,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:39 | 200 |  139.667855ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4125/8417 [52:08<1:02:45,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:40 | 200 |  170.222653ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4126/8417 [52:09<1:03:13,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:41 | 200 |  144.718181ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4127/8417 [52:10<1:02:44,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:42 | 200 |  139.826112ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4128/8417 [52:11<1:02:17,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:43 | 200 |  132.867087ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4129/8417 [52:11<1:01:55,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:44 | 200 |  179.380811ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4130/8417 [52:12<1:02:39,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:44 | 200 |  145.727927ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4131/8417 [52:13<1:02:39,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:45 | 200 |  169.315882ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4132/8417 [52:14<1:03:32,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:46 | 200 |  155.996171ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4133/8417 [52:15<1:04:34,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:47 | 200 |  141.561131ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4134/8417 [52:16<1:04:16,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:48 | 200 |  157.722253ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4135/8417 [52:17<1:05:03,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:49 | 200 |  157.284757ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4136/8417 [52:18<1:04:15,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:50 | 200 |  134.834234ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4137/8417 [52:19<1:04:33,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:51 | 200 |  195.141543ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4138/8417 [52:20<1:05:01,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:52 | 200 |  157.378958ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4139/8417 [52:20<1:04:48,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:53 | 200 |  141.586902ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4140/8417 [52:21<1:04:30,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:54 | 200 |  143.451431ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4141/8417 [52:22<1:03:53,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:54 | 200 |  144.378792ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4142/8417 [52:23<1:04:11,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:55 | 200 |  137.193735ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4143/8417 [52:24<1:03:23,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:56 | 200 |  162.921013ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4144/8417 [52:25<1:03:41,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:57 | 200 |  157.975348ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4145/8417 [52:26<1:03:32,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:58 | 200 |  146.264791ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4146/8417 [52:27<1:03:10,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:16:59 | 200 |  145.041396ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4147/8417 [52:28<1:03:11,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:00 | 200 |  145.074578ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4148/8417 [52:28<1:03:01,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:01 | 200 |   124.55754ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4149/8417 [52:29<1:02:43,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:01 | 200 |  136.024699ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4150/8417 [52:30<1:02:26,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:02 | 200 |  161.391548ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4151/8417 [52:31<1:03:14,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:03 | 200 |  140.116053ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4152/8417 [52:32<1:03:30,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:04 | 200 |  142.595649ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4153/8417 [52:33<1:03:19,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:05 | 200 |  141.121002ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4154/8417 [52:34<1:03:01,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:06 | 200 |  145.461821ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4155/8417 [52:35<1:03:07,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:07 | 200 |  171.749551ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4156/8417 [52:36<1:04:17,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:08 | 200 |  179.058732ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4157/8417 [52:37<1:04:33,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:09 | 200 |  146.870612ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4158/8417 [52:37<1:04:16,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:10 | 200 |  143.628885ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4159/8417 [52:38<1:03:36,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:10 | 200 |  137.214168ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4160/8417 [52:39<1:03:26,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:11 | 200 |  138.948226ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4161/8417 [52:40<1:02:46,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:12 | 200 |  162.558734ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4162/8417 [52:41<1:03:14,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:13 | 200 |  180.364109ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4163/8417 [52:42<1:04:08,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:14 | 200 |  144.454218ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4164/8417 [52:43<1:03:46,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:15 | 200 |  143.000103ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4165/8417 [52:44<1:03:07,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:16 | 200 |  145.932801ms |       127.0.0.1 | POST     "/api/chat"

 49%|████▉     | 4166/8417 [52:45<1:02:51,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:17 | 200 |  142.346082ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4167/8417 [52:45<1:02:42,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:18 | 200 |  135.840827ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4168/8417 [52:46<1:02:35,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:18 | 200 |  165.763404ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4169/8417 [52:47<1:02:59,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:19 | 200 |  177.898313ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4170/8417 [52:48<1:04:40,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:20 | 200 |  150.189183ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4171/8417 [52:49<1:05:19,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:21 | 200 |  143.731986ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4172/8417 [52:50<1:04:14,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:22 | 200 |  138.797497ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4173/8417 [52:51<1:03:29,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:23 | 200 |  170.677448ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4174/8417 [52:52<1:03:44,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:24 | 200 |  115.843797ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4175/8417 [52:53<1:02:48,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:25 | 200 |  114.384431ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4176/8417 [52:54<1:02:12,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:26 | 200 |  176.562979ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4177/8417 [52:54<1:03:07,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:27 | 200 |  151.520712ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4178/8417 [52:55<1:03:12,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:27 | 200 |  140.582385ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4179/8417 [52:56<1:02:52,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:28 | 200 |  116.466887ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4180/8417 [52:57<1:02:14,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:29 | 200 |  114.565393ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4181/8417 [52:58<1:01:09,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:30 | 200 |  179.156861ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4182/8417 [52:59<1:01:55,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:31 | 200 |  144.423218ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4183/8417 [53:00<1:02:05,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:32 | 200 |  120.547512ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4184/8417 [53:01<1:01:22,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:33 | 200 |  178.869634ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4185/8417 [53:01<1:02:37,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:34 | 200 |  168.390409ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4186/8417 [53:02<1:03:39,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:35 | 200 |  145.550373ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4187/8417 [53:03<1:03:28,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:35 | 200 |  143.855683ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4188/8417 [53:04<1:03:04,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:36 | 200 |  140.581473ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4189/8417 [53:05<1:02:52,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:37 | 200 |  142.933899ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4190/8417 [53:06<1:03:07,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:38 | 200 |  131.200493ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4191/8417 [53:07<1:02:53,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:39 | 200 |  168.623187ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4192/8417 [53:08<1:03:24,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:40 | 200 |  153.900776ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4193/8417 [53:09<1:03:31,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:41 | 200 |   132.73006ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4194/8417 [53:10<1:03:31,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:42 | 200 |  163.005734ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4195/8417 [53:11<1:04:13,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:43 | 200 |  176.607662ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4196/8417 [53:11<1:04:13,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:44 | 200 |  151.414785ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4197/8417 [53:12<1:05:54,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:45 | 200 |  140.574196ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4198/8417 [53:13<1:04:48,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:45 | 200 |  143.856758ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4199/8417 [53:14<1:04:19,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:46 | 200 |  163.811606ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4200/8417 [53:15<1:04:47,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:47 | 200 |  179.399803ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4201/8417 [53:16<1:04:39,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:48 | 200 |   144.80682ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4202/8417 [53:17<1:03:39,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:49 | 200 |  122.481091ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4203/8417 [53:18<1:02:28,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:50 | 200 |  178.324463ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4204/8417 [53:19<1:03:01,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:51 | 200 |   151.70093ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4205/8417 [53:20<1:03:58,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:52 | 200 |  170.983471ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4206/8417 [53:21<1:03:50,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:53 | 200 |  182.551084ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4207/8417 [53:21<1:03:56,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:54 | 200 |   146.63373ms |       127.0.0.1 | POST     "/api/chat"

 50%|████▉     | 4208/8417 [53:22<1:03:09,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:54 | 200 |  142.888135ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4209/8417 [53:23<1:02:37,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:55 | 200 |  136.366266ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4210/8417 [53:24<1:02:07,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:56 | 200 |  141.197837ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4211/8417 [53:25<1:01:58,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:57 | 200 |  183.172311ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4212/8417 [53:26<1:02:56,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:58 | 200 |  143.306855ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4213/8417 [53:27<1:02:14,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:17:59 | 200 |  145.758894ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4214/8417 [53:28<1:01:54,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:00 | 200 |  152.249472ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4215/8417 [53:29<1:02:07,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:01 | 200 |  145.109617ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4216/8417 [53:29<1:01:59,  1.13it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:02 | 200 |  116.975558ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4217/8417 [53:30<1:01:29,  1.14it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:02 | 200 |  139.354053ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4218/8417 [53:31<1:01:02,  1.15it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:03 | 200 |  183.174574ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4219/8417 [53:32<1:02:28,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:04 | 200 |  149.206228ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4220/8417 [53:33<1:02:37,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:05 | 200 |  161.823776ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4221/8417 [53:34<1:03:03,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:06 | 200 |  147.529664ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4222/8417 [53:35<1:02:47,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:07 | 200 |  144.175728ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4223/8417 [53:36<1:02:34,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:08 | 200 |  162.226085ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4224/8417 [53:37<1:02:44,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:09 | 200 |  158.777022ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4225/8417 [53:37<1:02:51,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:10 | 200 |  148.025924ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4226/8417 [53:38<1:03:00,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:11 | 200 |  145.618606ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4227/8417 [53:39<1:03:19,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:11 | 200 |  145.190362ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4228/8417 [53:40<1:02:44,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:12 | 200 |  144.513851ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4229/8417 [53:41<1:02:39,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:13 | 200 |  160.191571ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4230/8417 [53:42<1:02:38,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:14 | 200 |  146.219559ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4231/8417 [53:43<1:02:41,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:15 | 200 |  137.161751ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4232/8417 [53:44<1:02:43,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:16 | 200 |  133.098843ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4233/8417 [53:45<1:02:34,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:17 | 200 |  177.339701ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4234/8417 [53:46<1:03:02,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:18 | 200 |  143.638964ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4235/8417 [53:46<1:02:58,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:19 | 200 |  148.743245ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4236/8417 [53:47<1:03:25,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:20 | 200 |  180.188375ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4237/8417 [53:48<1:04:09,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:20 | 200 |  145.831554ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4238/8417 [53:49<1:04:00,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:21 | 200 |  153.567683ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4239/8417 [53:50<1:03:30,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:22 | 200 |  139.509894ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4240/8417 [53:51<1:03:48,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:23 | 200 |  147.892212ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4241/8417 [53:52<1:03:11,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:24 | 200 |   167.04925ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4242/8417 [53:53<1:03:42,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:25 | 200 |   159.11489ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4243/8417 [53:54<1:03:25,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:26 | 200 |  140.292414ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4244/8417 [53:55<1:03:03,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:27 | 200 |  143.695008ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4245/8417 [53:56<1:02:53,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:28 | 200 |  144.074042ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4246/8417 [53:57<1:02:59,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:29 | 200 |  139.399961ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4247/8417 [53:57<1:02:48,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:30 | 200 |  171.531291ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4248/8417 [53:58<1:03:32,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:31 | 200 |  145.491658ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4249/8417 [53:59<1:03:52,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:31 | 200 |   142.72208ms |       127.0.0.1 | POST     "/api/chat"

 50%|█████     | 4250/8417 [54:00<1:03:06,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:32 | 200 |  136.772727ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4251/8417 [54:01<1:02:42,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:33 | 200 |  147.733012ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4252/8417 [54:02<1:02:30,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:34 | 200 |  164.406148ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4253/8417 [54:03<1:02:54,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:35 | 200 |  177.258798ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4254/8417 [54:04<1:03:27,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:36 | 200 |  120.592615ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4255/8417 [54:05<1:02:50,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:37 | 200 |  148.543301ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4256/8417 [54:06<1:02:48,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:38 | 200 |  147.221974ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4257/8417 [54:06<1:02:26,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:39 | 200 |  139.115107ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4258/8417 [54:07<1:02:13,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:40 | 200 |  161.616613ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4259/8417 [54:08<1:02:19,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:40 | 200 |  167.782118ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4260/8417 [54:09<1:03:15,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:41 | 200 |  143.187503ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4261/8417 [54:10<1:03:31,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:42 | 200 |  143.676401ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4262/8417 [54:11<1:03:17,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:43 | 200 |  141.477876ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4263/8417 [54:12<1:03:12,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:44 | 200 |  143.730241ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4264/8417 [54:13<1:02:54,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:45 | 200 |  169.685123ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4265/8417 [54:14<1:03:36,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:46 | 200 |  145.353427ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4266/8417 [54:15<1:03:03,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:47 | 200 |  144.917718ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4267/8417 [54:16<1:03:06,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:48 | 200 |  144.945193ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4268/8417 [54:17<1:03:03,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:49 | 200 |  145.319748ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4269/8417 [54:17<1:03:02,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:50 | 200 |  135.821698ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4270/8417 [54:18<1:02:56,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:50 | 200 |   141.80867ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4271/8417 [54:19<1:03:10,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:51 | 200 |  168.336219ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4272/8417 [54:20<1:03:49,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:52 | 200 |  151.849175ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4273/8417 [54:21<1:03:39,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:53 | 200 |  140.351347ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4274/8417 [54:22<1:04:02,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:54 | 200 |  146.122496ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4275/8417 [54:23<1:04:13,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:55 | 200 |  149.322262ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4276/8417 [54:24<1:03:57,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:56 | 200 |  172.165429ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4277/8417 [54:25<1:04:11,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:57 | 200 |   119.91549ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4278/8417 [54:26<1:02:40,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:58 | 200 |  141.590045ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4279/8417 [54:27<1:02:24,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:18:59 | 200 |  147.766421ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4280/8417 [54:28<1:02:39,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:00 | 200 |  140.101477ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4281/8417 [54:28<1:02:27,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:01 | 200 |  171.466017ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4282/8417 [54:29<1:03:13,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:02 | 200 |  176.755317ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4283/8417 [54:30<1:03:29,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:02 | 200 |  141.819764ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4284/8417 [54:31<1:03:07,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:03 | 200 |  146.871637ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4285/8417 [54:32<1:03:31,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:04 | 200 |  179.617581ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4286/8417 [54:33<1:04:02,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:05 | 200 |  146.310025ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4287/8417 [54:34<1:03:39,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:06 | 200 |  147.174734ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4288/8417 [54:35<1:02:55,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:07 | 200 |  139.594868ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4289/8417 [54:36<1:02:49,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:08 | 200 |  140.807091ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4290/8417 [54:37<1:02:43,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:09 | 200 |   139.88742ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4291/8417 [54:38<1:02:38,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:10 | 200 |  143.501274ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4292/8417 [54:39<1:02:25,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:11 | 200 |  130.691394ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4293/8417 [54:39<1:02:25,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:12 | 200 |  118.239911ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4294/8417 [54:40<1:01:52,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:12 | 200 |  177.221383ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4295/8417 [54:41<1:02:14,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:13 | 200 |  176.028417ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4296/8417 [54:42<1:02:38,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:14 | 200 |  141.105039ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4297/8417 [54:43<1:02:19,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:15 | 200 |  143.422768ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4298/8417 [54:44<1:02:26,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:16 | 200 |  140.188724ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4299/8417 [54:45<1:02:39,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:17 | 200 |  143.071922ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4300/8417 [54:46<1:02:23,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:18 | 200 |   184.44591ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4301/8417 [54:47<1:02:46,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:19 | 200 |  146.933475ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4302/8417 [54:48<1:02:20,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:20 | 200 |  152.839645ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4303/8417 [54:49<1:02:43,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:21 | 200 |  150.758172ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4304/8417 [54:50<1:03:26,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:22 | 200 |  142.884996ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4305/8417 [54:50<1:03:03,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:23 | 200 |  171.526973ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4306/8417 [54:51<1:03:24,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:24 | 200 |  150.529929ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4307/8417 [54:52<1:03:37,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:24 | 200 |   147.90833ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4308/8417 [54:53<1:03:17,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:25 | 200 |  145.402032ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4309/8417 [54:54<1:03:20,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:26 | 200 |  166.326271ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4310/8417 [54:55<1:03:36,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:27 | 200 |  181.521233ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4311/8417 [54:56<1:03:52,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:28 | 200 |   150.75655ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4312/8417 [54:57<1:03:20,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:29 | 200 |  144.202909ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████     | 4313/8417 [54:58<1:03:10,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:30 | 200 |  140.851568ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4314/8417 [54:59<1:03:07,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:31 | 200 |   169.37609ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4315/8417 [55:00<1:03:39,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:32 | 200 |  183.195841ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4316/8417 [55:01<1:04:27,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:33 | 200 |  179.436451ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4317/8417 [55:02<1:04:35,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:34 | 200 |  141.789996ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4318/8417 [55:03<1:03:33,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:35 | 200 |  140.190376ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4319/8417 [55:03<1:03:00,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:36 | 200 |  139.460656ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4320/8417 [55:04<1:02:33,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:36 | 200 |  137.217436ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4321/8417 [55:05<1:02:03,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:37 | 200 |  138.695393ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4322/8417 [55:06<1:02:06,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:38 | 200 |  137.466338ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4323/8417 [55:07<1:01:57,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:39 | 200 |  165.808213ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4324/8417 [55:08<1:02:29,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:40 | 200 |  144.827567ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4325/8417 [55:09<1:02:47,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:41 | 200 |  152.885292ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4326/8417 [55:10<1:02:30,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:42 | 200 |  142.385332ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4327/8417 [55:11<1:01:58,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:43 | 200 |  143.653877ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4328/8417 [55:12<1:01:29,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:44 | 200 |  146.364844ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4329/8417 [55:13<1:01:52,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:45 | 200 |  176.419911ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4330/8417 [55:13<1:02:30,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:46 | 200 |  145.006942ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4331/8417 [55:14<1:02:19,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:47 | 200 |  146.555361ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4332/8417 [55:15<1:02:09,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:47 | 200 |  140.285477ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4333/8417 [55:16<1:01:44,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:48 | 200 |  135.431929ms |       127.0.0.1 | POST     "/api/chat"

 51%|█████▏    | 4334/8417 [55:17<1:01:14,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:49 | 200 |   166.61928ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4335/8417 [55:18<1:01:52,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:50 | 200 |  176.674319ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4336/8417 [55:19<1:02:49,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:51 | 200 |  151.747872ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4337/8417 [55:20<1:02:38,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:52 | 200 |  141.350759ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4338/8417 [55:21<1:02:39,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:53 | 200 |  143.318949ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4339/8417 [55:22<1:02:34,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:54 | 200 |  134.619181ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4340/8417 [55:23<1:01:50,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:55 | 200 |  136.336562ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4341/8417 [55:24<1:01:58,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:56 | 200 |  165.978655ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4342/8417 [55:24<1:02:39,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:57 | 200 |  147.780625ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4343/8417 [55:25<1:02:57,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:58 | 200 |   148.20536ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4344/8417 [55:26<1:02:43,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:58 | 200 |  156.244522ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4345/8417 [55:27<1:01:58,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:19:59 | 200 |   141.22567ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4346/8417 [55:28<1:02:21,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:00 | 200 |  138.245247ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4347/8417 [55:29<1:03:02,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:01 | 200 |  156.932034ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4348/8417 [55:30<1:03:14,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:02 | 200 |  177.378934ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4349/8417 [55:31<1:03:10,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:03 | 200 |  144.565084ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4350/8417 [55:32<1:03:04,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:04 | 200 |  140.438713ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4351/8417 [55:33<1:02:07,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:05 | 200 |   141.66081ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4352/8417 [55:34<1:02:29,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:06 | 200 |   160.58784ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4353/8417 [55:35<1:02:35,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:07 | 200 |  180.121557ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4354/8417 [55:36<1:03:22,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:08 | 200 |   165.46074ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4355/8417 [55:37<1:02:51,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:09 | 200 |  146.263391ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4356/8417 [55:37<1:01:55,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:09 | 200 |  118.744777ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4357/8417 [55:38<1:00:54,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:10 | 200 |  141.737198ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4358/8417 [55:39<1:01:12,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:11 | 200 |  177.983945ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4359/8417 [55:40<1:01:40,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:12 | 200 |  146.408121ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4360/8417 [55:41<1:01:08,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:13 | 200 |  137.584155ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4361/8417 [55:42<1:01:09,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:14 | 200 |  144.865592ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4362/8417 [55:43<1:01:33,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:15 | 200 |   175.18444ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4363/8417 [55:44<1:01:31,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:16 | 200 |  124.294892ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4364/8417 [55:45<1:01:18,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:17 | 200 |  146.196998ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4365/8417 [55:46<1:01:30,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:18 | 200 |  143.976352ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4366/8417 [55:46<1:01:03,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:19 | 200 |  141.970387ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4367/8417 [55:47<1:01:11,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:20 | 200 |  171.416034ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4368/8417 [55:48<1:01:44,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:20 | 200 |  180.374121ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4369/8417 [55:49<1:02:46,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:21 | 200 |  149.016101ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4370/8417 [55:50<1:02:20,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:22 | 200 |  143.754134ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4371/8417 [55:51<1:01:25,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:23 | 200 |  141.472584ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4372/8417 [55:52<1:00:39,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:24 | 200 |  164.312607ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4373/8417 [55:53<1:01:14,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:25 | 200 |  140.660592ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4374/8417 [55:54<1:00:56,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:26 | 200 |  147.217333ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4375/8417 [55:55<1:00:36,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:27 | 200 |  141.356687ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4376/8417 [55:56<1:00:41,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:28 | 200 |  141.999186ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4377/8417 [55:56<1:00:45,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:29 | 200 |  166.030451ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4378/8417 [55:57<1:02:22,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:30 | 200 |  146.178411ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4379/8417 [55:58<1:02:05,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:30 | 200 |  144.751638ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4380/8417 [55:59<1:01:47,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:31 | 200 |  142.591036ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4381/8417 [56:00<1:01:06,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:32 | 200 |   135.55725ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4382/8417 [56:01<1:01:11,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:33 | 200 |  167.411483ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4383/8417 [56:02<1:01:22,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:34 | 200 |  156.692608ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4384/8417 [56:03<1:01:49,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:35 | 200 |  161.878974ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4385/8417 [56:04<1:01:48,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:36 | 200 |   143.77946ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4386/8417 [56:05<1:01:41,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:37 | 200 |  143.788062ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4387/8417 [56:06<1:01:28,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:38 | 200 |  141.845954ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4388/8417 [56:07<1:01:15,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:39 | 200 |  143.507956ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4389/8417 [56:07<1:00:53,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:40 | 200 |  162.970855ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4390/8417 [56:08<1:01:27,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:41 | 200 |  186.218525ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4391/8417 [56:09<1:02:51,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:42 | 200 |  174.097927ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4392/8417 [56:10<1:02:57,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:42 | 200 |   122.70161ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4393/8417 [56:11<1:01:52,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:43 | 200 |  117.634932ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4394/8417 [56:12<1:01:01,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:44 | 200 |  181.065197ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4395/8417 [56:13<1:01:27,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:45 | 200 |  164.397444ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4396/8417 [56:14<1:01:39,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:46 | 200 |  157.513747ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4397/8417 [56:15<1:01:17,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:47 | 200 |  143.720745ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4398/8417 [56:16<1:01:42,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:48 | 200 |  118.758301ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4399/8417 [56:17<1:00:59,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:49 | 200 |  177.039865ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4400/8417 [56:18<1:02:00,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:50 | 200 |  173.578649ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4401/8417 [56:19<1:02:24,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:51 | 200 |  166.594806ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4402/8417 [56:20<1:02:40,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:52 | 200 |  144.143652ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4403/8417 [56:20<1:01:56,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:53 | 200 |   143.85232ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4404/8417 [56:21<1:01:31,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:53 | 200 |  139.968718ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4405/8417 [56:22<1:01:12,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:54 | 200 |  144.367605ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4406/8417 [56:23<1:00:40,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:55 | 200 |  158.542687ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4407/8417 [56:24<1:00:39,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:56 | 200 |  144.472105ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4408/8417 [56:25<1:00:35,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:57 | 200 |  176.019779ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4409/8417 [56:26<1:01:07,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:58 | 200 |  144.550982ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4410/8417 [56:27<1:00:56,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:20:59 | 200 |  120.793001ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4411/8417 [56:28<1:00:38,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:00 | 200 |  180.254422ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4412/8417 [56:29<1:02:43,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:01 | 200 |  177.384222ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4413/8417 [56:30<1:04:08,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:02 | 200 |  153.107667ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4414/8417 [56:31<1:03:02,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:03 | 200 |  147.395996ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4415/8417 [56:32<1:02:22,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:04 | 200 |  148.608967ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4416/8417 [56:32<1:01:53,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:05 | 200 |  146.670169ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4417/8417 [56:33<1:01:49,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:05 | 200 |  141.738943ms |       127.0.0.1 | POST     "/api/chat"

 52%|█████▏    | 4418/8417 [56:34<1:01:50,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:06 | 200 |  143.784828ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4419/8417 [56:35<1:01:43,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:07 | 200 |  177.322187ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4420/8417 [56:36<1:02:14,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:08 | 200 |  143.822727ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4421/8417 [56:37<1:02:04,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:09 | 200 |   149.97978ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4422/8417 [56:38<1:01:50,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:10 | 200 |  143.551289ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4423/8417 [56:39<1:01:46,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:11 | 200 |  163.779187ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4424/8417 [56:40<1:02:06,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:12 | 200 |  181.871383ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4425/8417 [56:41<1:02:09,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:13 | 200 |  149.472629ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4426/8417 [56:42<1:01:26,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:14 | 200 |   146.40242ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4427/8417 [56:43<1:01:56,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:15 | 200 |  145.771506ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4428/8417 [56:44<1:01:42,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:16 | 200 |  145.524012ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4429/8417 [56:45<1:02:06,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:17 | 200 |  146.069101ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4430/8417 [56:45<1:01:58,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:18 | 200 |  143.652989ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4431/8417 [56:46<1:01:25,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:19 | 200 |  177.735551ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4432/8417 [56:47<1:01:34,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:19 | 200 |  178.985693ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4433/8417 [56:48<1:01:36,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:20 | 200 |  146.045857ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4434/8417 [56:49<1:02:09,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:21 | 200 |   155.65696ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4435/8417 [56:50<1:01:53,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:22 | 200 |  179.309392ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4436/8417 [56:51<1:02:11,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:23 | 200 |   146.75861ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4437/8417 [56:52<1:01:04,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:24 | 200 |  144.138318ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4438/8417 [56:53<1:00:38,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:25 | 200 |  139.354348ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4439/8417 [56:54<1:00:09,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:26 | 200 |  141.770905ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4440/8417 [56:55<1:00:04,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:27 | 200 |  169.239046ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4441/8417 [56:56<1:00:36,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:28 | 200 |  159.049657ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4442/8417 [56:56<1:00:49,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:29 | 200 |  154.017305ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4443/8417 [56:57<1:01:59,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:30 | 200 |  118.996209ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4444/8417 [56:58<1:02:00,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:31 | 200 |  154.565163ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4445/8417 [56:59<1:03:24,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:32 | 200 |  179.818237ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4446/8417 [57:00<1:04:15,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:33 | 200 |  183.376052ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4447/8417 [57:01<1:03:50,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:33 | 200 |   173.99467ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4448/8417 [57:02<1:03:08,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:34 | 200 |  117.707936ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4449/8417 [57:03<1:01:24,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:35 | 200 |  139.873112ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4450/8417 [57:04<1:00:33,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:36 | 200 |  138.307199ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4451/8417 [57:05<1:00:38,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:37 | 200 |  137.285337ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4452/8417 [57:06<1:00:04,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:38 | 200 |  142.049372ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4453/8417 [57:07<1:00:07,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:39 | 200 |  137.593335ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4454/8417 [57:08<59:32,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:40 | 200 |  165.578918ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4455/8417 [57:09<1:00:08,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:41 | 200 |  181.496087ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4456/8417 [57:10<1:00:45,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:42 | 200 |  151.390052ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4457/8417 [57:10<1:00:38,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:43 | 200 |  142.594316ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4458/8417 [57:11<1:00:05,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:43 | 200 |  149.516208ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4459/8417 [57:12<1:00:38,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:44 | 200 |  174.968236ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4460/8417 [57:13<1:00:57,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:45 | 200 |  175.864718ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4461/8417 [57:14<1:01:04,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:46 | 200 |  147.642775ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4462/8417 [57:15<1:00:43,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:47 | 200 |  146.466995ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4463/8417 [57:16<1:00:29,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:48 | 200 |  144.418857ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4464/8417 [57:17<1:00:22,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:49 | 200 |   169.75999ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4465/8417 [57:18<1:01:01,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:50 | 200 |  177.982688ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4466/8417 [57:19<1:01:31,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:51 | 200 |  155.534771ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4467/8417 [57:20<1:01:12,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:52 | 200 |  143.060677ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4468/8417 [57:21<1:00:57,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:53 | 200 |  139.173812ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4469/8417 [57:22<1:00:49,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:54 | 200 |  134.521666ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4470/8417 [57:22<1:00:14,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:55 | 200 |  177.630287ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4471/8417 [57:23<1:01:04,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:56 | 200 |  149.446419ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4472/8417 [57:24<1:00:56,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:56 | 200 |  146.457762ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4473/8417 [57:25<1:00:29,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:57 | 200 |  142.427708ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4474/8417 [57:26<1:00:06,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:58 | 200 |  114.642057ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4475/8417 [57:27<59:00,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:21:59 | 200 |   142.00511ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4476/8417 [57:28<59:10,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:00 | 200 |  164.536767ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4477/8417 [57:29<59:55,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:01 | 200 |  157.922351ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4478/8417 [57:30<1:00:02,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:02 | 200 |  155.400551ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4479/8417 [57:31<1:00:21,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:03 | 200 |  140.991511ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4480/8417 [57:32<1:01:19,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:04 | 200 |  146.947729ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4481/8417 [57:33<1:01:04,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:05 | 200 |  184.796668ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4482/8417 [57:34<1:01:58,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:06 | 200 |  119.488626ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4483/8417 [57:34<1:00:53,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:07 | 200 |  148.196187ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4484/8417 [57:35<1:00:44,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:07 | 200 |  111.375343ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4485/8417 [57:36<59:39,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:08 | 200 |  114.265969ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4486/8417 [57:37<58:57,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:09 | 200 |  183.845342ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4487/8417 [57:38<1:00:35,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:10 | 200 |  170.638128ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4488/8417 [57:39<1:01:49,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:11 | 200 |  122.836712ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4489/8417 [57:40<1:00:42,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:12 | 200 |  131.786068ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4490/8417 [57:41<59:51,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:13 | 200 |   178.40922ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4491/8417 [57:42<1:00:09,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:14 | 200 |  146.326109ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4492/8417 [57:43<59:54,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:15 | 200 |  146.886094ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4493/8417 [57:44<59:56,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:16 | 200 |   136.89798ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4494/8417 [57:45<59:57,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:17 | 200 |  140.868277ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4495/8417 [57:45<59:48,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:18 | 200 |  171.878435ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4496/8417 [57:46<1:00:17,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:18 | 200 |  147.224059ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4497/8417 [57:47<59:59,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:19 | 200 |  150.069094ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4498/8417 [57:48<1:00:51,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:20 | 200 |  141.726812ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4499/8417 [57:49<1:00:59,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:21 | 200 |  151.490297ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4500/8417 [57:50<1:00:45,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:22 | 200 |  179.156384ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4501/8417 [57:51<1:01:17,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:23 | 200 |  150.892559ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4502/8417 [57:52<1:00:53,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:24 | 200 |  147.197218ms |       127.0.0.1 | POST     "/api/chat"

 53%|█████▎    | 4503/8417 [57:53<1:01:41,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:25 | 200 |  156.784963ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4504/8417 [57:54<1:02:12,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:26 | 200 |  142.757204ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4505/8417 [57:55<1:01:16,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:27 | 200 |  169.022628ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4506/8417 [57:56<1:01:42,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:28 | 200 |  144.925978ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4507/8417 [57:57<1:01:11,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:29 | 200 |  118.861924ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4508/8417 [57:58<1:00:07,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:30 | 200 |  188.452933ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4509/8417 [57:59<1:01:27,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:31 | 200 |  140.065478ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4510/8417 [57:59<1:00:24,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:32 | 200 |  148.960707ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4511/8417 [58:00<59:50,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:32 | 200 |  115.817162ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4512/8417 [58:01<58:45,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:33 | 200 |   146.70387ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4513/8417 [58:02<58:32,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:34 | 200 |  142.470809ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4514/8417 [58:03<59:27,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:35 | 200 |  201.407233ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4515/8417 [58:04<1:01:05,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:36 | 200 |  158.743874ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4516/8417 [58:05<1:00:40,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:37 | 200 |  146.373297ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4517/8417 [58:06<1:00:12,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:38 | 200 |  142.248668ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4518/8417 [58:07<59:53,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:39 | 200 |  163.285294ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4519/8417 [58:08<59:47,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:40 | 200 |  186.812104ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4520/8417 [58:09<1:00:53,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:41 | 200 |  141.497642ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4521/8417 [58:10<1:00:38,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:42 | 200 |  158.466291ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4522/8417 [58:11<1:00:26,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:43 | 200 |  176.948256ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4523/8417 [58:12<1:00:24,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:44 | 200 |  141.923151ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▎    | 4524/8417 [58:12<1:00:11,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:45 | 200 |  139.280439ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4525/8417 [58:13<59:44,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:45 | 200 |  114.472618ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4526/8417 [58:14<58:55,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:46 | 200 |  135.443415ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4527/8417 [58:15<58:31,  1.11it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:47 | 200 |  169.089693ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4528/8417 [58:16<59:06,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:48 | 200 |  147.200237ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4529/8417 [58:17<58:48,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:49 | 200 |  146.494535ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4530/8417 [58:18<59:11,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:50 | 200 |  138.393362ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4531/8417 [58:19<59:24,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:51 | 200 |  178.293299ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4532/8417 [58:20<59:51,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:52 | 200 |  143.404165ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4533/8417 [58:21<59:55,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:53 | 200 |  140.553288ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4534/8417 [58:22<59:33,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:54 | 200 |  134.172121ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4535/8417 [58:22<59:32,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:55 | 200 |  145.055738ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4536/8417 [58:23<59:23,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:56 | 200 |  178.248851ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4537/8417 [58:24<59:47,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:56 | 200 |  145.153663ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4538/8417 [58:25<59:12,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:57 | 200 |  140.295769ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4539/8417 [58:26<59:02,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:58 | 200 |  149.327194ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4540/8417 [58:27<59:00,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:22:59 | 200 |  145.920546ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4541/8417 [58:28<59:01,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:00 | 200 |  137.928148ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4542/8417 [58:29<58:40,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:01 | 200 |  138.546038ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4543/8417 [58:30<58:36,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:02 | 200 |   167.69096ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4544/8417 [58:31<59:08,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:03 | 200 |  148.840057ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4545/8417 [58:32<59:23,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:04 | 200 |  144.047892ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4546/8417 [58:33<59:24,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:05 | 200 |  140.239006ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4547/8417 [58:33<59:20,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:06 | 200 |  141.016755ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4548/8417 [58:34<59:36,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:07 | 200 |  167.820175ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4549/8417 [58:35<1:00:35,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:08 | 200 |  163.335271ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4550/8417 [58:36<1:01:08,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:08 | 200 |  140.905863ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4551/8417 [58:37<1:00:22,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:09 | 200 |  143.154838ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4552/8417 [58:38<59:59,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:10 | 200 |  138.038032ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4553/8417 [58:39<1:00:03,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:11 | 200 |  138.767336ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4554/8417 [58:40<59:16,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:12 | 200 |  174.615097ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4555/8417 [58:41<59:26,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:13 | 200 |  146.361341ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4556/8417 [58:42<59:17,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:14 | 200 |  117.019041ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4557/8417 [58:43<58:41,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:15 | 200 |  178.004131ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4558/8417 [58:44<59:23,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:16 | 200 |  177.913125ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4559/8417 [58:45<59:58,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:17 | 200 |  147.565012ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4560/8417 [58:46<59:46,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:18 | 200 |  145.291317ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4561/8417 [58:46<59:34,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:19 | 200 |   140.95979ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4562/8417 [58:47<58:58,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:20 | 200 |   139.31071ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4563/8417 [58:48<59:03,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:20 | 200 |    138.1496ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4564/8417 [58:49<59:36,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:21 | 200 |  176.096315ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4565/8417 [58:50<59:39,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:22 | 200 |  144.759402ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4566/8417 [58:51<59:53,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:23 | 200 |  149.524501ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4567/8417 [58:52<59:38,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:24 | 200 |  139.733135ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4568/8417 [58:53<59:49,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:25 | 200 |  124.767486ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4569/8417 [58:54<59:00,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:26 | 200 |  178.792776ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4570/8417 [58:55<59:24,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:27 | 200 |  150.439075ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4571/8417 [58:56<59:41,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:28 | 200 |  143.033127ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4572/8417 [58:57<59:36,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:29 | 200 |  144.767357ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4573/8417 [58:58<59:22,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:30 | 200 |  162.286758ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4574/8417 [58:59<1:00:10,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:31 | 200 |  187.314953ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4575/8417 [59:00<1:00:58,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:32 | 200 |  175.713634ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4576/8417 [59:01<1:00:54,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:33 | 200 |  164.571381ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4577/8417 [59:01<1:00:36,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:34 | 200 |  144.551354ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4578/8417 [59:02<1:00:45,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:35 | 200 |  141.058957ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4579/8417 [59:03<1:01:04,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:36 | 200 |  144.554107ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4580/8417 [59:04<1:00:31,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:36 | 200 |  173.427075ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4581/8417 [59:05<1:00:26,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:37 | 200 |  118.322388ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4582/8417 [59:06<59:03,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:38 | 200 |  128.909332ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4583/8417 [59:07<59:34,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:39 | 200 |  179.776466ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4584/8417 [59:08<1:01:19,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:40 | 200 |  145.828905ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4585/8417 [59:09<1:00:50,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:41 | 200 |  168.936743ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4586/8417 [59:10<1:01:22,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:42 | 200 |  153.932388ms |       127.0.0.1 | POST     "/api/chat"

 54%|█████▍    | 4587/8417 [59:11<1:00:41,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:43 | 200 |  154.508122ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4588/8417 [59:12<59:50,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:44 | 200 |  116.722985ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4589/8417 [59:13<58:59,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:45 | 200 |  143.074839ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4590/8417 [59:14<58:55,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:46 | 200 |  164.684597ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4591/8417 [59:15<59:15,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:47 | 200 |  179.199417ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4592/8417 [59:16<59:42,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:48 | 200 |  163.766722ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4593/8417 [59:17<59:44,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:49 | 200 |  142.298093ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4594/8417 [59:17<59:20,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:50 | 200 |  145.217085ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4595/8417 [59:18<59:26,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:51 | 200 |  177.636268ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4596/8417 [59:19<1:00:17,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:51 | 200 |  145.067264ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4597/8417 [59:20<1:00:00,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:52 | 200 |    145.0944ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4598/8417 [59:21<59:34,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:53 | 200 |  142.445804ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4599/8417 [59:22<59:21,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:54 | 200 |  140.032727ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4600/8417 [59:23<59:23,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:55 | 200 |  143.306596ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4601/8417 [59:24<58:49,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:56 | 200 |  167.949822ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4602/8417 [59:25<59:13,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:57 | 200 |   147.04864ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4603/8417 [59:26<59:02,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:58 | 200 |  140.514022ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4604/8417 [59:27<58:42,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:23:59 | 200 |  142.169503ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4605/8417 [59:28<58:24,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:00 | 200 |  122.523034ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4606/8417 [59:29<57:46,  1.10it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:01 | 200 |  180.467397ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4607/8417 [59:29<58:32,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:02 | 200 |  172.293855ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4608/8417 [59:30<58:44,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:03 | 200 |  163.465609ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4609/8417 [59:31<58:59,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:03 | 200 |  144.858396ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4610/8417 [59:32<59:05,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:04 | 200 |  135.799456ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4611/8417 [59:33<58:44,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:05 | 200 |   176.16045ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4612/8417 [59:34<59:11,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:06 | 200 |  146.400609ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4613/8417 [59:35<58:47,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:07 | 200 |  143.848997ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4614/8417 [59:36<58:11,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:08 | 200 |  147.497542ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4615/8417 [59:37<58:03,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:09 | 200 |  135.730597ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4616/8417 [59:38<57:59,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:10 | 200 |  188.568373ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4617/8417 [59:39<1:00:02,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:11 | 200 |  149.681275ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4618/8417 [59:40<59:45,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:12 | 200 |  142.667395ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4619/8417 [59:41<59:29,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:13 | 200 |   143.12938ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4620/8417 [59:42<58:54,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:14 | 200 |   140.01225ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4621/8417 [59:43<59:14,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:15 | 200 |  145.440846ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4622/8417 [59:43<59:01,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:16 | 200 |  144.838269ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4623/8417 [59:44<59:03,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:17 | 200 |  177.595621ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4624/8417 [59:45<59:37,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:17 | 200 |  147.449584ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4625/8417 [59:46<59:09,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:18 | 200 |  142.213714ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4626/8417 [59:47<59:01,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:19 | 200 |  147.298628ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4627/8417 [59:48<58:39,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:20 | 200 |  139.260765ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4628/8417 [59:49<58:48,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:21 | 200 |  112.801777ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▍    | 4629/8417 [59:50<57:43,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:22 | 200 |  139.535929ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4630/8417 [59:51<57:48,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:23 | 200 |  168.982194ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4631/8417 [59:52<58:18,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:24 | 200 |   140.29256ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4632/8417 [59:53<57:57,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:25 | 200 |  146.989234ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4633/8417 [59:54<58:10,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:26 | 200 |  137.898909ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4634/8417 [59:55<58:13,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:27 | 200 |  139.814882ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4635/8417 [59:55<58:13,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:28 | 200 |  176.745194ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4636/8417 [59:56<58:56,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:29 | 200 |  141.576015ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4637/8417 [59:57<58:42,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:30 | 200 |  153.971732ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4638/8417 [59:58<59:19,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:30 | 200 |   176.58583ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4639/8417 [59:59<59:51,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:31 | 200 |  149.176751ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4640/8417 [1:00:00<59:20,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:32 | 200 |  144.355709ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4641/8417 [1:00:01<58:32,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:33 | 200 |  139.269189ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4642/8417 [1:00:02<58:39,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:34 | 200 |  143.746293ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4643/8417 [1:00:03<58:15,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:35 | 200 |  136.125357ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4644/8417 [1:00:04<58:03,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:36 | 200 |   174.04348ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4645/8417 [1:00:05<58:19,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:37 | 200 |  120.799526ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4646/8417 [1:00:06<57:56,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:38 | 200 |  140.516436ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4647/8417 [1:00:07<57:43,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:39 | 200 |  174.209845ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4648/8417 [1:00:08<58:28,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:40 | 200 |  143.592873ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4649/8417 [1:00:09<58:12,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:41 | 200 |  116.202873ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4650/8417 [1:00:09<58:11,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:42 | 200 |  197.594382ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4651/8417 [1:00:10<59:24,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:43 | 200 |  154.134349ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4652/8417 [1:00:11<59:15,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:44 | 200 |  145.875861ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4653/8417 [1:00:12<58:57,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:44 | 200 |  142.892667ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4654/8417 [1:00:13<58:28,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:45 | 200 |  142.167511ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4655/8417 [1:00:14<58:23,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:46 | 200 |  176.708915ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4656/8417 [1:00:15<59:21,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:47 | 200 |  175.484414ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4657/8417 [1:00:16<59:19,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:48 | 200 |  143.704602ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4658/8417 [1:00:17<58:56,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:49 | 200 |  152.022787ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4659/8417 [1:00:18<59:26,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:50 | 200 |  141.351895ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4660/8417 [1:00:19<59:06,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:51 | 200 |  146.510226ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4661/8417 [1:00:20<59:38,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:52 | 200 |  157.899311ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4662/8417 [1:00:21<59:04,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:53 | 200 |  145.796835ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4663/8417 [1:00:22<58:31,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:54 | 200 |  171.555188ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4664/8417 [1:00:23<1:00:23,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:55 | 200 |  145.664577ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4665/8417 [1:00:24<1:00:14,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:56 | 200 |  132.838402ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4666/8417 [1:00:25<1:01:02,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:57 | 200 |  167.656444ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4667/8417 [1:00:26<1:00:14,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:58 | 200 |  153.923397ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4668/8417 [1:00:27<59:22,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:24:59 | 200 |  157.689454ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4669/8417 [1:00:28<59:02,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:00 | 200 |  143.426566ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4670/8417 [1:00:28<58:25,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:01 | 200 |  144.498286ms |       127.0.0.1 | POST     "/api/chat"

 55%|█████▌    | 4671/8417 [1:00:29<58:19,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:01 | 200 |  144.853941ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4672/8417 [1:00:30<58:01,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:02 | 200 |  141.960235ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4673/8417 [1:00:31<57:38,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:03 | 200 |  167.362555ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4674/8417 [1:00:32<58:06,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:04 | 200 |  145.485991ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4675/8417 [1:00:33<57:36,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:05 | 200 |  140.244988ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4676/8417 [1:00:34<57:56,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:06 | 200 |  140.154866ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4677/8417 [1:00:35<58:01,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:07 | 200 |  142.403838ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4678/8417 [1:00:36<57:37,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:08 | 200 |  184.360011ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4679/8417 [1:00:37<58:34,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:09 | 200 |  141.232412ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4680/8417 [1:00:38<57:48,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:10 | 200 |  148.832579ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4681/8417 [1:00:39<58:14,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:11 | 200 |  194.468135ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4682/8417 [1:00:40<59:07,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:12 | 200 |  158.417846ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4683/8417 [1:00:41<58:55,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:13 | 200 |   144.96867ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4684/8417 [1:00:42<59:41,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:14 | 200 |  158.394702ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4685/8417 [1:00:43<59:29,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:15 | 200 |  166.918705ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4686/8417 [1:00:44<59:48,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:16 | 200 |  173.652825ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4687/8417 [1:00:44<59:43,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:17 | 200 |  151.271673ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4688/8417 [1:00:45<58:51,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:18 | 200 |  146.996922ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4689/8417 [1:00:46<58:31,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:18 | 200 |  142.433926ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4690/8417 [1:00:47<58:16,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:19 | 200 |  145.548855ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4691/8417 [1:00:48<57:34,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:20 | 200 |  145.342443ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4692/8417 [1:00:49<57:53,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:21 | 200 |  143.378679ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4693/8417 [1:00:50<57:32,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:22 | 200 |  166.585234ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4694/8417 [1:00:51<57:52,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:23 | 200 |  163.850606ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4695/8417 [1:00:52<58:17,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:24 | 200 |  158.767207ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4696/8417 [1:00:53<59:00,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:25 | 200 |  117.285625ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4697/8417 [1:00:54<58:25,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:26 | 200 |  175.056618ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4698/8417 [1:00:55<58:49,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:27 | 200 |  164.309086ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4699/8417 [1:00:56<58:38,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:28 | 200 |   161.26958ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4700/8417 [1:00:57<58:26,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:29 | 200 |  142.613236ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4701/8417 [1:00:58<57:34,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:30 | 200 |  145.852354ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4702/8417 [1:00:58<57:33,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:31 | 200 |  141.660141ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4703/8417 [1:00:59<57:47,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:32 | 200 |  148.152715ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4704/8417 [1:01:00<57:24,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:33 | 200 |  178.544647ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4705/8417 [1:01:01<58:12,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:33 | 200 |  141.827206ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4706/8417 [1:01:02<57:34,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:34 | 200 |  149.379478ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4707/8417 [1:01:03<57:35,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:35 | 200 |  177.741075ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4708/8417 [1:01:04<58:27,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:36 | 200 |  145.043836ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4709/8417 [1:01:05<57:43,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:37 | 200 |  140.517281ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4710/8417 [1:01:06<57:02,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:38 | 200 |  143.294296ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4711/8417 [1:01:07<56:49,  1.09it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:39 | 200 |  170.906557ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4712/8417 [1:01:08<57:57,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:40 | 200 |  157.568605ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4713/8417 [1:01:09<58:28,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:41 | 200 |  154.324935ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4714/8417 [1:01:10<58:16,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:42 | 200 |   142.73819ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4715/8417 [1:01:11<57:50,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:43 | 200 |  146.761818ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4716/8417 [1:01:12<57:46,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:44 | 200 |  178.447272ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4717/8417 [1:01:13<58:40,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:45 | 200 |  172.313581ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4718/8417 [1:01:14<59:30,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:46 | 200 |  151.322214ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4719/8417 [1:01:15<59:24,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:47 | 200 |  175.532267ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4720/8417 [1:01:15<58:53,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:48 | 200 |  142.599378ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4721/8417 [1:01:16<58:03,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:49 | 200 |  123.134235ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4722/8417 [1:01:17<58:00,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:49 | 200 |  140.929032ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4723/8417 [1:01:18<57:19,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:50 | 200 |  183.063319ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4724/8417 [1:01:19<58:53,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:51 | 200 |  174.968961ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4725/8417 [1:01:20<59:29,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:52 | 200 |  177.452753ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4726/8417 [1:01:21<59:38,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:53 | 200 |  138.772925ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4727/8417 [1:01:22<59:12,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:54 | 200 |  171.990778ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4728/8417 [1:01:23<59:46,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:55 | 200 |  149.070843ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4729/8417 [1:01:24<59:38,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:56 | 200 |  146.134597ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4730/8417 [1:01:25<58:52,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:57 | 200 |  138.790637ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4731/8417 [1:01:26<58:07,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:58 | 200 |  143.816265ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4732/8417 [1:01:27<57:57,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:25:59 | 200 |  117.188346ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4733/8417 [1:01:28<57:03,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:00 | 200 |  178.448446ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▌    | 4734/8417 [1:01:29<58:22,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:01 | 200 |  143.572397ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4735/8417 [1:01:30<57:57,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:02 | 200 |  127.604561ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4736/8417 [1:01:31<57:19,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:03 | 200 |  173.642488ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4737/8417 [1:01:32<58:14,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:04 | 200 |  164.053662ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4738/8417 [1:01:33<58:20,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:05 | 200 |  146.052487ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4739/8417 [1:01:33<57:48,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:06 | 200 |  143.554783ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4740/8417 [1:01:34<57:48,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:07 | 200 |   178.35043ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4741/8417 [1:01:35<58:07,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:08 | 200 |  142.612483ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4742/8417 [1:01:36<57:50,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:08 | 200 |  162.120356ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4743/8417 [1:01:37<57:48,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:09 | 200 |  171.232704ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4744/8417 [1:01:38<58:28,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:10 | 200 |  174.216434ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4745/8417 [1:01:39<59:21,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:11 | 200 |  152.653916ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4746/8417 [1:01:40<58:25,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:12 | 200 |   136.31541ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4747/8417 [1:01:41<57:27,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:13 | 200 |  140.778341ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4748/8417 [1:01:42<57:23,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:14 | 200 |  141.934608ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4749/8417 [1:01:43<57:29,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:15 | 200 |  155.828977ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4750/8417 [1:01:44<57:38,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:16 | 200 |  189.042231ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4751/8417 [1:01:45<58:58,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:17 | 200 |  190.862268ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4752/8417 [1:01:46<59:09,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:18 | 200 |  173.479322ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4753/8417 [1:01:47<59:04,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:19 | 200 |  166.908287ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4754/8417 [1:01:48<59:00,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:20 | 200 |  137.781734ms |       127.0.0.1 | POST     "/api/chat"

 56%|█████▋    | 4755/8417 [1:01:49<58:22,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:21 | 200 |  161.905491ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4756/8417 [1:01:50<58:11,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:22 | 200 |  175.161202ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4757/8417 [1:01:51<58:27,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:23 | 200 |  161.060959ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4758/8417 [1:01:52<58:06,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:24 | 200 |  153.394195ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4759/8417 [1:01:53<57:42,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:25 | 200 |  146.488134ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4760/8417 [1:01:54<57:46,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:26 | 200 |  147.349875ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4761/8417 [1:01:54<57:52,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:27 | 200 |  139.345203ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4762/8417 [1:01:55<57:59,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:28 | 200 |   165.26059ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4763/8417 [1:01:56<58:09,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:29 | 200 |   160.73439ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4764/8417 [1:01:57<58:29,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:29 | 200 |  127.472981ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4765/8417 [1:01:58<57:40,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:30 | 200 |  172.798747ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4766/8417 [1:01:59<58:19,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:31 | 200 |  127.991305ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4767/8417 [1:02:00<57:48,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:32 | 200 |  170.037282ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4768/8417 [1:02:01<58:23,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:33 | 200 |  178.148644ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4769/8417 [1:02:02<58:21,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:34 | 200 |  168.085182ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4770/8417 [1:02:03<58:23,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:35 | 200 |  139.594361ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4771/8417 [1:02:04<57:51,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:36 | 200 |   155.91327ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4772/8417 [1:02:05<57:10,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:37 | 200 |  175.245598ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4773/8417 [1:02:06<57:48,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:38 | 200 |  148.714331ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4774/8417 [1:02:07<57:32,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:39 | 200 |  144.125494ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4775/8417 [1:02:08<56:56,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:40 | 200 |  146.954612ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4776/8417 [1:02:09<56:56,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:41 | 200 |  140.237881ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4777/8417 [1:02:10<57:26,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:42 | 200 |  175.969674ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4778/8417 [1:02:11<57:50,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:43 | 200 |  122.092042ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4779/8417 [1:02:12<57:37,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:44 | 200 |  144.600812ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4780/8417 [1:02:13<57:19,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:45 | 200 |  122.420042ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4781/8417 [1:02:13<56:44,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:46 | 200 |   140.94513ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4782/8417 [1:02:14<56:31,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:47 | 200 |  179.598505ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4783/8417 [1:02:15<57:11,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:47 | 200 |  143.764974ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4784/8417 [1:02:16<57:57,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:49 | 200 |  193.340648ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4785/8417 [1:02:17<59:13,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:49 | 200 |  145.530515ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4786/8417 [1:02:18<58:30,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:50 | 200 |  143.980454ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4787/8417 [1:02:19<58:19,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:51 | 200 |  142.009807ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4788/8417 [1:02:20<57:43,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:52 | 200 |   178.10759ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4789/8417 [1:02:21<57:53,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:53 | 200 |  149.264867ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4790/8417 [1:02:22<57:36,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:54 | 200 |  167.891471ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4791/8417 [1:02:23<57:57,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:55 | 200 |  184.576464ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4792/8417 [1:02:24<58:20,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:56 | 200 |  179.506641ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4793/8417 [1:02:25<58:19,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:57 | 200 |  160.465464ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4794/8417 [1:02:26<57:30,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:58 | 200 |  152.291404ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4795/8417 [1:02:27<57:20,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:26:59 | 200 |  147.357491ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4796/8417 [1:02:28<57:09,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:00 | 200 |  142.421991ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4797/8417 [1:02:29<57:42,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:01 | 200 |  122.490545ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4798/8417 [1:02:30<57:29,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:02 | 200 |  175.812771ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4799/8417 [1:02:31<57:38,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:03 | 200 |  122.597283ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4800/8417 [1:02:32<56:55,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:04 | 200 |  145.350427ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4801/8417 [1:02:33<56:51,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:05 | 200 |  146.485167ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4802/8417 [1:02:34<56:49,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:06 | 200 |   166.56125ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4803/8417 [1:02:34<57:22,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:07 | 200 |  178.416456ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4804/8417 [1:02:35<57:44,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:08 | 200 |   176.81704ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4805/8417 [1:02:36<57:41,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:09 | 200 |  143.123112ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4806/8417 [1:02:37<57:37,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:09 | 200 |  141.337528ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4807/8417 [1:02:38<57:15,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:10 | 200 |  144.778855ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4808/8417 [1:02:39<57:18,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:11 | 200 |  174.902234ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4809/8417 [1:02:40<57:16,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:12 | 200 |  144.054831ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4810/8417 [1:02:41<57:51,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:13 | 200 |  136.019374ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4811/8417 [1:02:42<57:36,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:14 | 200 |  167.988071ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4812/8417 [1:02:43<57:57,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:15 | 200 |  162.558751ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4813/8417 [1:02:44<57:53,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:16 | 200 |  167.324813ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4814/8417 [1:02:45<57:25,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:17 | 200 |  138.948527ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4815/8417 [1:02:46<56:30,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:18 | 200 |  140.550709ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4816/8417 [1:02:47<55:49,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:19 | 200 |  140.026506ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4817/8417 [1:02:48<56:35,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:20 | 200 |  197.288806ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4818/8417 [1:02:49<58:15,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:21 | 200 |  143.257711ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4819/8417 [1:02:50<57:15,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:22 | 200 |  142.949503ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4820/8417 [1:02:51<56:36,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:23 | 200 |   145.21184ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4821/8417 [1:02:52<56:34,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:24 | 200 |  138.133378ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4822/8417 [1:02:53<56:09,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:25 | 200 |  144.460796ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4823/8417 [1:02:53<55:55,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:26 | 200 |  136.011332ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4824/8417 [1:02:54<56:00,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:27 | 200 |  168.970728ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4825/8417 [1:02:55<56:47,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:28 | 200 |  152.318473ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4826/8417 [1:02:56<56:51,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:28 | 200 |  154.049169ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4827/8417 [1:02:57<56:41,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:29 | 200 |  145.583889ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4828/8417 [1:02:58<56:36,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:30 | 200 |  142.325603ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4829/8417 [1:02:59<56:58,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:31 | 200 |  145.516133ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4830/8417 [1:03:00<56:17,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:32 | 200 |  179.034627ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4831/8417 [1:03:01<56:40,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:33 | 200 |  154.831868ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4832/8417 [1:03:02<56:36,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:34 | 200 |  144.906178ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4833/8417 [1:03:03<56:29,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:35 | 200 |  145.157067ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4834/8417 [1:03:04<55:57,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:36 | 200 |  114.934578ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4835/8417 [1:03:05<55:12,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:37 | 200 |  144.219517ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4836/8417 [1:03:06<55:51,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:38 | 200 |  167.868742ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4837/8417 [1:03:07<56:24,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:39 | 200 |  140.760794ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4838/8417 [1:03:08<56:31,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:40 | 200 |  136.421308ms |       127.0.0.1 | POST     "/api/chat"

 57%|█████▋    | 4839/8417 [1:03:09<56:33,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:41 | 200 |  154.433838ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4840/8417 [1:03:10<56:23,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:42 | 200 |  178.441365ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4841/8417 [1:03:11<56:35,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:43 | 200 |  147.558336ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4842/8417 [1:03:11<56:30,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:44 | 200 |    147.5893ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4843/8417 [1:03:12<56:36,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:45 | 200 |  141.953046ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4844/8417 [1:03:13<56:36,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:45 | 200 |   173.33478ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4845/8417 [1:03:14<56:41,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:46 | 200 |  146.139798ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4846/8417 [1:03:15<56:31,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:47 | 200 |  141.061217ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4847/8417 [1:03:16<55:43,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:48 | 200 |    140.8408ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4848/8417 [1:03:17<56:26,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:49 | 200 |  139.831393ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4849/8417 [1:03:18<56:06,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:50 | 200 |  159.706016ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4850/8417 [1:03:19<57:05,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:51 | 200 |  199.961415ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4851/8417 [1:03:20<57:34,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:52 | 200 |  164.034096ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4852/8417 [1:03:21<57:14,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:53 | 200 |  160.539378ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4853/8417 [1:03:22<56:59,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:54 | 200 |  143.055402ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4854/8417 [1:03:23<56:31,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:55 | 200 |  170.072097ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4855/8417 [1:03:24<56:35,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 58%|█████▊    | 4856/8417 [1:03:25<56:13,  1.06it/s]

[GIN] 2025/06/27 - 00:27:56 | 200 |   166.25685ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:57 | 200 |  151.398059ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4857/8417 [1:03:26<56:00,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:58 | 200 |  144.163647ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4858/8417 [1:03:27<55:50,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:27:59 | 200 |  149.794807ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4859/8417 [1:03:28<55:55,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:00 | 200 |  176.548859ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4860/8417 [1:03:29<56:27,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:01 | 200 |  148.623727ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4861/8417 [1:03:30<56:06,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:02 | 200 |  141.017833ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4862/8417 [1:03:30<55:53,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:03 | 200 |  140.770844ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4863/8417 [1:03:31<55:31,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:03 | 200 |  123.867134ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4864/8417 [1:03:32<55:11,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:04 | 200 |  141.879063ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4865/8417 [1:03:33<55:04,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:05 | 200 |  170.478806ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4866/8417 [1:03:34<55:42,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:06 | 200 |  146.419283ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4867/8417 [1:03:35<55:45,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:07 | 200 |  142.729166ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4868/8417 [1:03:36<55:18,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:08 | 200 |  146.854271ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4869/8417 [1:03:37<55:00,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:09 | 200 |  139.611996ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4870/8417 [1:03:38<54:40,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:10 | 200 |  140.397251ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4871/8417 [1:03:39<54:44,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:11 | 200 |  164.892949ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4872/8417 [1:03:40<54:56,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:12 | 200 |  144.349761ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4873/8417 [1:03:41<54:43,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:13 | 200 |  145.124731ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4874/8417 [1:03:42<54:35,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:14 | 200 |  141.488232ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4875/8417 [1:03:43<54:37,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:15 | 200 |  141.061228ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4876/8417 [1:03:43<54:58,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:16 | 200 |  144.510579ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4877/8417 [1:03:44<54:46,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:17 | 200 |  177.577029ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4878/8417 [1:03:45<55:30,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:18 | 200 |   169.24715ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4879/8417 [1:03:46<55:59,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:18 | 200 |   165.20978ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4880/8417 [1:03:47<56:06,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:19 | 200 |  172.028032ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4881/8417 [1:03:48<56:48,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:20 | 200 |  149.673932ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4882/8417 [1:03:49<56:53,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:21 | 200 |  137.886788ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4883/8417 [1:03:50<56:15,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:22 | 200 |  145.860823ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4884/8417 [1:03:51<56:53,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:23 | 200 |  143.492787ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4885/8417 [1:03:52<56:44,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:24 | 200 |  182.742294ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4886/8417 [1:03:53<57:02,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:25 | 200 |  170.375276ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4887/8417 [1:03:54<56:55,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:26 | 200 |  144.099933ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4888/8417 [1:03:55<56:52,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:27 | 200 |  135.008773ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4889/8417 [1:03:56<56:12,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:28 | 200 |    138.5705ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4890/8417 [1:03:57<55:37,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:29 | 200 |  173.939784ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4891/8417 [1:03:58<55:43,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:30 | 200 |  146.177256ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4892/8417 [1:03:59<55:48,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:31 | 200 |  162.917158ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4893/8417 [1:04:00<56:24,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:32 | 200 |  183.810017ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4894/8417 [1:04:01<56:53,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:33 | 200 |  169.917858ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4895/8417 [1:04:02<57:02,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:34 | 200 |  177.952125ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4896/8417 [1:04:03<56:55,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:35 | 200 |  148.782655ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4897/8417 [1:04:04<57:06,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:36 | 200 |   141.68647ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4898/8417 [1:04:05<56:27,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:37 | 200 |  146.522535ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4899/8417 [1:04:06<55:35,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:38 | 200 |  177.226714ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4900/8417 [1:04:07<55:49,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:39 | 200 |  140.059561ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4901/8417 [1:04:07<55:20,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:40 | 200 |  173.185234ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4902/8417 [1:04:08<56:24,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:41 | 200 |  158.337388ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4903/8417 [1:04:09<57:01,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:42 | 200 |  169.691314ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4904/8417 [1:04:10<57:04,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:43 | 200 |  174.128655ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4905/8417 [1:04:11<56:35,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:43 | 200 |  168.195698ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4906/8417 [1:04:12<56:16,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:44 | 200 |  148.992813ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4907/8417 [1:04:13<55:57,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:45 | 200 |  143.605544ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4908/8417 [1:04:14<55:52,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:46 | 200 |  145.541692ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4909/8417 [1:04:15<55:44,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:47 | 200 |  137.616396ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4910/8417 [1:04:16<55:25,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:48 | 200 |  173.509505ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4911/8417 [1:04:17<55:48,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:49 | 200 |  147.699925ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4912/8417 [1:04:18<55:34,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:50 | 200 |  155.168704ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4913/8417 [1:04:19<55:51,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:51 | 200 |  141.471908ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4914/8417 [1:04:20<56:11,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:52 | 200 |  171.432007ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4915/8417 [1:04:21<56:33,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:53 | 200 |  142.279801ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4916/8417 [1:04:22<56:17,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:54 | 200 |  171.744256ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4917/8417 [1:04:23<57:13,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:55 | 200 |    172.6009ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4918/8417 [1:04:24<56:57,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:56 | 200 |  158.186241ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4919/8417 [1:04:25<56:48,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:57 | 200 |  161.270797ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4920/8417 [1:04:26<56:04,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:58 | 200 |  139.529721ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4921/8417 [1:04:27<55:39,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:28:59 | 200 |  172.898386ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4922/8417 [1:04:28<55:46,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:00 | 200 |  162.818674ms |       127.0.0.1 | POST     "/api/chat"

 58%|█████▊    | 4923/8417 [1:04:29<55:55,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:01 | 200 |  193.207573ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4924/8417 [1:04:30<56:22,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:02 | 200 |  168.212117ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4925/8417 [1:04:31<56:01,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:03 | 200 |  150.224275ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4926/8417 [1:04:32<55:25,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:04 | 200 |  141.781883ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4927/8417 [1:04:32<54:55,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:05 | 200 |  137.469473ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4928/8417 [1:04:33<54:49,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:05 | 200 |  142.606192ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4929/8417 [1:04:34<54:30,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:06 | 200 |  167.425085ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4930/8417 [1:04:35<55:34,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:07 | 200 |  165.700914ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4931/8417 [1:04:36<55:29,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:08 | 200 |  131.652221ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4932/8417 [1:04:37<54:51,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:09 | 200 |  175.724774ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4933/8417 [1:04:38<55:24,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:10 | 200 |  145.692786ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4934/8417 [1:04:39<56:02,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:11 | 200 |  161.025682ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4935/8417 [1:04:40<55:55,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:12 | 200 |  181.820868ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4936/8417 [1:04:41<56:30,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:13 | 200 |  140.510361ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4937/8417 [1:04:42<55:45,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:14 | 200 |  175.731375ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4938/8417 [1:04:43<56:13,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:15 | 200 |   144.12288ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4939/8417 [1:04:44<56:01,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:16 | 200 |  143.346895ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4940/8417 [1:04:45<55:54,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:17 | 200 |  152.345141ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4941/8417 [1:04:46<55:32,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:18 | 200 |  177.750043ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4942/8417 [1:04:47<55:51,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:19 | 200 |  146.038425ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4943/8417 [1:04:48<55:06,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:20 | 200 |  139.280107ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▊    | 4944/8417 [1:04:49<55:06,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:21 | 200 |  166.996937ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4945/8417 [1:04:50<55:55,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:22 | 200 |  174.687097ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4946/8417 [1:04:51<55:55,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:23 | 200 |  174.965278ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4947/8417 [1:04:52<55:41,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:24 | 200 |  141.066037ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4948/8417 [1:04:53<55:23,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:25 | 200 |  177.469052ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4949/8417 [1:04:54<56:47,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:26 | 200 |  155.581992ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4950/8417 [1:04:55<56:42,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:27 | 200 |  148.823754ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4951/8417 [1:04:56<56:09,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:28 | 200 |  131.585934ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4952/8417 [1:04:57<56:09,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:29 | 200 |   180.68437ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4953/8417 [1:04:58<56:27,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:30 | 200 |  172.094305ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4954/8417 [1:04:59<56:28,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:31 | 200 |  162.854168ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4955/8417 [1:04:59<56:29,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:32 | 200 |  146.083677ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4956/8417 [1:05:00<56:21,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:33 | 200 |  140.809901ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4957/8417 [1:05:01<56:17,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:34 | 200 |   138.19531ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4958/8417 [1:05:02<55:38,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:35 | 200 |  147.605338ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4959/8417 [1:05:03<55:31,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:36 | 200 |  172.858913ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4960/8417 [1:05:04<56:11,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:37 | 200 |  165.506358ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4961/8417 [1:05:05<56:19,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:37 | 200 |  147.958451ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4962/8417 [1:05:06<55:19,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:38 | 200 |  147.793679ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4963/8417 [1:05:07<54:41,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:39 | 200 |  140.020466ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4964/8417 [1:05:08<54:08,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:40 | 200 |   179.31234ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4965/8417 [1:05:09<55:21,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:41 | 200 |  142.820834ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4966/8417 [1:05:10<55:26,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:42 | 200 |  141.898705ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4967/8417 [1:05:11<55:00,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:43 | 200 |  155.166426ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4968/8417 [1:05:12<55:10,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:44 | 200 |  181.252514ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4969/8417 [1:05:13<55:57,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:45 | 200 |    178.4953ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4970/8417 [1:05:14<56:25,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:46 | 200 |  174.413241ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4971/8417 [1:05:15<56:15,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:47 | 200 |  163.963005ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4972/8417 [1:05:16<56:09,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:48 | 200 |  135.954856ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4973/8417 [1:05:17<55:19,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:49 | 200 |  161.349844ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4974/8417 [1:05:18<54:58,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:50 | 200 |  174.054265ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4975/8417 [1:05:19<55:11,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:51 | 200 |  163.117772ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4976/8417 [1:05:20<55:23,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:52 | 200 |  141.765001ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4977/8417 [1:05:21<54:48,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:53 | 200 |  144.138493ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4978/8417 [1:05:22<54:50,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:54 | 200 |   150.99636ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4979/8417 [1:05:23<54:42,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:55 | 200 |  177.170008ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4980/8417 [1:05:24<55:17,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:56 | 200 |  156.289663ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4981/8417 [1:05:25<55:26,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:57 | 200 |  136.512712ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4982/8417 [1:05:26<55:37,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:58 | 200 |  188.540309ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4983/8417 [1:05:27<56:06,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:29:59 | 200 |  145.638112ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4984/8417 [1:05:28<55:55,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:00 | 200 |    146.2636ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4985/8417 [1:05:28<55:20,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:01 | 200 |  145.951702ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4986/8417 [1:05:29<55:01,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:02 | 200 |  139.142745ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4987/8417 [1:05:30<54:29,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:02 | 200 |  159.047352ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4988/8417 [1:05:31<54:30,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:03 | 200 |  166.452402ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4989/8417 [1:05:32<54:41,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:04 | 200 |  133.570507ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4990/8417 [1:05:33<54:00,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:05 | 200 |  180.230904ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4991/8417 [1:05:34<54:25,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:06 | 200 |  148.555324ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4992/8417 [1:05:35<53:58,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:07 | 200 |  120.800642ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4993/8417 [1:05:36<53:00,  1.08it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:08 | 200 |  181.238135ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4994/8417 [1:05:37<53:54,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:09 | 200 |  148.305431ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4995/8417 [1:05:38<53:42,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:10 | 200 |  150.319524ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4996/8417 [1:05:39<54:00,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:11 | 200 |  140.584487ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4997/8417 [1:05:40<53:41,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:12 | 200 |  178.746778ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4998/8417 [1:05:41<54:07,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:13 | 200 |  144.307967ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 4999/8417 [1:05:42<53:44,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:14 | 200 |   144.90271ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 5000/8417 [1:05:43<53:50,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:15 | 200 |  144.108644ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 5001/8417 [1:05:44<54:17,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:16 | 200 |  180.584825ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 5002/8417 [1:05:45<55:11,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:17 | 200 |  148.103333ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 5003/8417 [1:05:46<55:25,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:18 | 200 |   147.93026ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 5004/8417 [1:05:47<54:50,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:19 | 200 |  147.888939ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 5005/8417 [1:05:47<54:30,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:20 | 200 |  178.210804ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 5006/8417 [1:05:48<54:44,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:21 | 200 |  146.601686ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 5007/8417 [1:05:49<54:26,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:22 | 200 |  174.633626ms |       127.0.0.1 | POST     "/api/chat"

 59%|█████▉    | 5008/8417 [1:05:50<54:39,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:23 | 200 |   156.04736ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5009/8417 [1:05:51<54:42,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:23 | 200 |  122.888948ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5010/8417 [1:05:52<54:15,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:24 | 200 |  180.818065ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5011/8417 [1:05:53<54:47,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:25 | 200 |  140.240467ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5012/8417 [1:05:54<54:29,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:26 | 200 |  176.378086ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5013/8417 [1:05:55<54:49,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:27 | 200 |  158.458607ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5014/8417 [1:05:56<54:54,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:28 | 200 |  126.031464ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5015/8417 [1:05:57<55:08,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:29 | 200 |  188.810234ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5016/8417 [1:05:58<55:37,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:30 | 200 |  173.625687ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5017/8417 [1:05:59<56:02,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:31 | 200 |  162.742356ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5018/8417 [1:06:00<55:26,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:32 | 200 |  155.914232ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5019/8417 [1:06:01<55:16,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:33 | 200 |  143.593938ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5020/8417 [1:06:02<54:19,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:34 | 200 |  149.593565ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5021/8417 [1:06:03<54:13,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:35 | 200 |  173.413652ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5022/8417 [1:06:04<54:57,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:36 | 200 |   174.21397ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5023/8417 [1:06:05<54:51,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:37 | 200 |  146.101266ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5024/8417 [1:06:06<54:08,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:38 | 200 |  142.582904ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5025/8417 [1:06:07<53:54,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:39 | 200 |  160.041556ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5026/8417 [1:06:08<54:16,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:40 | 200 |  177.872659ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5027/8417 [1:06:09<55:25,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:41 | 200 |  182.525442ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5028/8417 [1:06:10<55:31,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:42 | 200 |  171.789915ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5029/8417 [1:06:11<55:11,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:43 | 200 |  156.752391ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5030/8417 [1:06:12<54:56,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:44 | 200 |  111.535468ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5031/8417 [1:06:13<54:16,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:45 | 200 |   157.04324ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5032/8417 [1:06:14<54:46,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:46 | 200 |   178.82771ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5033/8417 [1:06:15<54:55,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:47 | 200 |   180.28363ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5034/8417 [1:06:16<55:08,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:48 | 200 |  177.778377ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5035/8417 [1:06:17<55:36,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:49 | 200 |  175.058176ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5036/8417 [1:06:18<55:10,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:50 | 200 |  162.725646ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5037/8417 [1:06:19<55:11,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:51 | 200 |  113.174755ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5038/8417 [1:06:19<54:06,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:52 | 200 |  167.097715ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5039/8417 [1:06:20<54:04,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:53 | 200 |  170.040276ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5040/8417 [1:06:21<53:55,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:54 | 200 |  177.539116ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5041/8417 [1:06:22<54:25,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:54 | 200 |  144.532966ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5042/8417 [1:06:23<53:58,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:55 | 200 |  173.354198ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5043/8417 [1:06:24<54:08,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:56 | 200 |   155.98765ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5044/8417 [1:06:25<54:27,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:57 | 200 |  147.357196ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5045/8417 [1:06:26<54:27,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:58 | 200 |  136.599969ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5046/8417 [1:06:27<53:45,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:30:59 | 200 |  115.712108ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5047/8417 [1:06:28<54:11,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:00 | 200 |  192.926608ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5048/8417 [1:06:29<56:18,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:01 | 200 |  136.081321ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5049/8417 [1:06:30<55:36,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:02 | 200 |  179.129877ms |       127.0.0.1 | POST     "/api/chat"

 60%|█████▉    | 5050/8417 [1:06:31<55:41,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:03 | 200 |  143.029746ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5051/8417 [1:06:32<55:09,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:04 | 200 |  142.106559ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5052/8417 [1:06:33<54:04,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:05 | 200 |  137.774025ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5053/8417 [1:06:34<53:33,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:06 | 200 |  181.802283ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5054/8417 [1:06:35<53:44,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:07 | 200 |  142.762641ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5055/8417 [1:06:36<53:21,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:08 | 200 |   142.47892ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5056/8417 [1:06:37<52:53,  1.06it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:09 | 200 |   118.66738ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5057/8417 [1:06:38<52:31,  1.07it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:10 | 200 |  178.357395ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5058/8417 [1:06:39<53:38,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:11 | 200 |  147.066721ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5059/8417 [1:06:40<53:41,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:12 | 200 |  137.610628ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5060/8417 [1:06:41<53:18,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:13 | 200 |  145.482668ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5061/8417 [1:06:42<53:30,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:14 | 200 |  137.713218ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5062/8417 [1:06:43<53:17,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:15 | 200 |  138.434879ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5063/8417 [1:06:44<53:06,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:16 | 200 |  144.992957ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5064/8417 [1:06:44<53:21,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:17 | 200 |  176.209079ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5065/8417 [1:06:45<53:27,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:18 | 200 |  154.788429ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5066/8417 [1:06:46<53:14,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:19 | 200 |  146.323951ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5067/8417 [1:06:47<53:03,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:20 | 200 |  165.941791ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5068/8417 [1:06:48<53:49,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:21 | 200 |  173.627417ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5069/8417 [1:06:49<54:22,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:21 | 200 |  172.842711ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5070/8417 [1:06:50<54:11,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:22 | 200 |   173.30912ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5071/8417 [1:06:51<54:10,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:23 | 200 |  155.321266ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5072/8417 [1:06:52<54:18,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:24 | 200 |  142.210819ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5073/8417 [1:06:53<53:51,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:25 | 200 |   138.33114ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5074/8417 [1:06:54<53:22,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:26 | 200 |  175.662828ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5075/8417 [1:06:55<53:42,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:27 | 200 |  178.327707ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5076/8417 [1:06:56<53:47,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:28 | 200 |   147.73342ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5077/8417 [1:06:57<53:07,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:29 | 200 |  135.926368ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5078/8417 [1:06:58<52:49,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:30 | 200 |  139.918984ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5079/8417 [1:06:59<53:07,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:31 | 200 |   167.57374ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5080/8417 [1:07:00<54:02,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:32 | 200 |  181.053764ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5081/8417 [1:07:01<54:21,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:33 | 200 |  176.742627ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5082/8417 [1:07:02<54:29,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:34 | 200 |  145.183357ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5083/8417 [1:07:03<54:11,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:35 | 200 |    139.7285ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5084/8417 [1:07:04<54:09,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:36 | 200 |  178.301181ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5085/8417 [1:07:05<54:29,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:37 | 200 |    144.5105ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5086/8417 [1:07:06<54:01,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:38 | 200 |  183.297846ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5087/8417 [1:07:07<55:19,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:39 | 200 |  149.511406ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5088/8417 [1:07:08<54:30,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:40 | 200 |  139.611495ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5089/8417 [1:07:09<53:56,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:41 | 200 |   182.03155ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5090/8417 [1:07:10<54:22,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:42 | 200 |  150.506523ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5091/8417 [1:07:11<53:45,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:43 | 200 |  141.707445ms |       127.0.0.1 | POST     "/api/chat"

 60%|██████    | 5092/8417 [1:07:12<53:30,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:44 | 200 |   174.76662ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5093/8417 [1:07:13<53:47,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:45 | 200 |  166.207301ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5094/8417 [1:07:14<53:55,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:46 | 200 |  178.084791ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5095/8417 [1:07:15<54:43,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:47 | 200 |  133.942149ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5096/8417 [1:07:16<54:07,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:48 | 200 |  133.009073ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5097/8417 [1:07:17<53:31,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:49 | 200 |  177.163714ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5098/8417 [1:07:18<53:59,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:50 | 200 |  146.526261ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5099/8417 [1:07:18<53:27,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:51 | 200 |   145.34979ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5100/8417 [1:07:19<53:30,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:52 | 200 |  155.443726ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5101/8417 [1:07:20<53:43,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:53 | 200 |  179.592176ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5102/8417 [1:07:21<54:03,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:54 | 200 |  177.629547ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5103/8417 [1:07:22<54:00,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:55 | 200 |  158.788416ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5104/8417 [1:07:23<53:38,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:55 | 200 |  117.718877ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5105/8417 [1:07:24<52:54,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:56 | 200 |  171.965729ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5106/8417 [1:07:25<53:18,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:57 | 200 |  167.987325ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5107/8417 [1:07:26<54:06,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:58 | 200 |  154.245305ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5108/8417 [1:07:27<53:45,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:31:59 | 200 |  153.355905ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5109/8417 [1:07:28<53:35,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:00 | 200 |  141.408498ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5110/8417 [1:07:29<53:42,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:01 | 200 |   177.04584ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5111/8417 [1:07:30<54:24,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:02 | 200 |  142.751282ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5112/8417 [1:07:31<53:22,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:03 | 200 |  154.333477ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5113/8417 [1:07:32<55:01,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:04 | 200 |  191.460982ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5114/8417 [1:07:33<55:02,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:05 | 200 |  146.455992ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5115/8417 [1:07:34<54:09,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:06 | 200 |  144.176532ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5116/8417 [1:07:35<53:36,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:07 | 200 |  151.771156ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5117/8417 [1:07:36<53:16,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:08 | 200 |  179.360999ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5118/8417 [1:07:37<53:31,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:09 | 200 |  159.607938ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5119/8417 [1:07:38<53:28,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:10 | 200 |  138.219814ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5120/8417 [1:07:39<53:43,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:11 | 200 |  177.991386ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5121/8417 [1:07:40<53:45,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:12 | 200 |  148.554954ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5122/8417 [1:07:41<53:42,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:13 | 200 |  138.434463ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5123/8417 [1:07:42<53:18,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:14 | 200 |  143.833058ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5124/8417 [1:07:43<52:45,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:15 | 200 |  163.536288ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5125/8417 [1:07:44<52:53,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:16 | 200 |  147.830383ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5126/8417 [1:07:45<52:56,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:17 | 200 |  144.405613ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5127/8417 [1:07:46<52:38,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:18 | 200 |  158.341756ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5128/8417 [1:07:47<52:54,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:19 | 200 |  179.594829ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5129/8417 [1:07:48<53:21,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:20 | 200 |  179.287921ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5130/8417 [1:07:49<54:19,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:21 | 200 |  185.840942ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5131/8417 [1:07:50<54:18,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:22 | 200 |  177.154575ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5132/8417 [1:07:51<54:43,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:23 | 200 |  181.254219ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5133/8417 [1:07:52<54:46,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:24 | 200 |  172.856416ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5134/8417 [1:07:53<55:10,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:25 | 200 |  156.704176ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5135/8417 [1:07:54<54:36,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:26 | 200 |  167.556804ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5136/8417 [1:07:55<54:25,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:27 | 200 |   179.41871ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5137/8417 [1:07:56<54:17,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:28 | 200 |  176.840386ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5138/8417 [1:07:57<54:06,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:29 | 200 |  161.877441ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5139/8417 [1:07:58<53:46,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:30 | 200 |  144.300421ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5140/8417 [1:07:59<53:35,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:31 | 200 |  157.321433ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5141/8417 [1:08:00<53:23,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:32 | 200 |   169.40542ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5142/8417 [1:08:01<53:23,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:33 | 200 |   150.89594ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5143/8417 [1:08:02<53:39,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:34 | 200 |  118.237786ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5144/8417 [1:08:03<53:13,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:35 | 200 |  147.578535ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5145/8417 [1:08:04<54:17,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:36 | 200 |  180.275521ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5146/8417 [1:08:05<54:34,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:37 | 200 |  167.032949ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5147/8417 [1:08:06<54:33,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:38 | 200 |  164.107111ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5148/8417 [1:08:07<53:43,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:39 | 200 |  156.022569ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5149/8417 [1:08:08<53:04,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:40 | 200 |  143.020574ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5150/8417 [1:08:08<52:21,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:41 | 200 |  170.083293ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5151/8417 [1:08:09<52:31,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:42 | 200 |  181.153362ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5152/8417 [1:08:10<52:37,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:43 | 200 |  184.509317ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5153/8417 [1:08:11<52:59,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:44 | 200 |  173.544732ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5154/8417 [1:08:12<52:50,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:44 | 200 |  140.512267ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████    | 5155/8417 [1:08:13<52:33,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:45 | 200 |  139.158397ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5156/8417 [1:08:14<52:09,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:46 | 200 |  146.225321ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5157/8417 [1:08:15<51:51,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:47 | 200 |   176.36039ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5158/8417 [1:08:16<52:17,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:48 | 200 |  149.652625ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5159/8417 [1:08:17<51:51,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:49 | 200 |  137.069104ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5160/8417 [1:08:18<52:01,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:50 | 200 |  164.418346ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5161/8417 [1:08:19<52:24,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:51 | 200 |  144.586368ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5162/8417 [1:08:20<52:13,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:52 | 200 |  178.423549ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5163/8417 [1:08:21<52:43,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:53 | 200 |  158.627137ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5164/8417 [1:08:22<52:48,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:54 | 200 |  145.242718ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5165/8417 [1:08:23<52:54,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:55 | 200 |  138.586066ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5166/8417 [1:08:24<52:32,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:56 | 200 |  178.464902ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5167/8417 [1:08:25<53:53,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:57 | 200 |  149.185229ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5168/8417 [1:08:26<52:58,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:58 | 200 |  137.986176ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5169/8417 [1:08:27<52:25,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:32:59 | 200 |  139.319229ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5170/8417 [1:08:28<51:54,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:00 | 200 |  137.043067ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5171/8417 [1:08:29<52:53,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:01 | 200 |  178.662068ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5172/8417 [1:08:30<53:05,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:02 | 200 |   144.64512ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5173/8417 [1:08:31<52:45,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:03 | 200 |  142.753031ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5174/8417 [1:08:32<52:04,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:04 | 200 |  159.466635ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5175/8417 [1:08:33<52:16,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:05 | 200 |  176.090519ms |       127.0.0.1 | POST     "/api/chat"

 61%|██████▏   | 5176/8417 [1:08:34<52:47,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:06 | 200 |  169.705977ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5177/8417 [1:08:35<53:17,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:07 | 200 |  191.952737ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5178/8417 [1:08:36<54:43,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:08 | 200 |  145.251665ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5179/8417 [1:08:37<54:01,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:09 | 200 |  142.236538ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5180/8417 [1:08:38<53:02,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:10 | 200 |  144.834767ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5181/8417 [1:08:39<52:51,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:11 | 200 |   190.36185ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5182/8417 [1:08:40<53:25,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:12 | 200 |  157.017986ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5183/8417 [1:08:41<52:49,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:13 | 200 |  150.926889ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5184/8417 [1:08:42<53:01,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:14 | 200 |  140.793647ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5185/8417 [1:08:43<52:12,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:15 | 200 |  155.755899ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5186/8417 [1:08:44<52:19,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:16 | 200 |  183.026927ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5187/8417 [1:08:45<52:40,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:17 | 200 |  179.317906ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5188/8417 [1:08:46<53:20,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:18 | 200 |  176.538925ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5189/8417 [1:08:47<53:36,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:19 | 200 |  171.128474ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5190/8417 [1:08:48<53:14,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:20 | 200 |  174.050112ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5191/8417 [1:08:49<53:07,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:21 | 200 |   183.63006ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5192/8417 [1:08:50<53:37,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:22 | 200 |  183.917415ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5193/8417 [1:08:51<53:59,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:23 | 200 |   178.99137ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5194/8417 [1:08:52<53:45,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:24 | 200 |  178.687839ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5195/8417 [1:08:53<53:42,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:25 | 200 |  184.726629ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5196/8417 [1:08:54<54:16,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:26 | 200 |  169.398162ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5197/8417 [1:08:55<53:58,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:27 | 200 |  171.354471ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5198/8417 [1:08:56<53:31,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:28 | 200 |  171.322135ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5199/8417 [1:08:57<53:02,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:29 | 200 |  179.243252ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5200/8417 [1:08:57<52:43,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:30 | 200 |  152.809796ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5201/8417 [1:08:58<52:06,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:31 | 200 |  145.742148ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5202/8417 [1:08:59<52:03,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:32 | 200 |    164.9824ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5203/8417 [1:09:00<52:06,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:33 | 200 |  174.541831ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5204/8417 [1:09:01<52:19,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:34 | 200 |  170.717976ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5205/8417 [1:09:02<52:19,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:35 | 200 |  170.744225ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5206/8417 [1:09:03<52:15,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:35 | 200 |  130.251765ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5207/8417 [1:09:04<51:35,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:36 | 200 |  180.466487ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5208/8417 [1:09:05<52:26,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:37 | 200 |  145.737199ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5209/8417 [1:09:06<52:04,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:38 | 200 |  155.989027ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5210/8417 [1:09:07<52:28,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:39 | 200 |  178.115796ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5211/8417 [1:09:08<52:43,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:40 | 200 |  147.808225ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5212/8417 [1:09:09<52:45,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:41 | 200 |  165.496893ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5213/8417 [1:09:10<52:37,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:42 | 200 |   176.50288ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5214/8417 [1:09:11<52:22,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:43 | 200 |  173.769195ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5215/8417 [1:09:12<52:34,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:44 | 200 |  168.127621ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5216/8417 [1:09:13<52:45,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:45 | 200 |   163.11144ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5217/8417 [1:09:14<52:28,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:46 | 200 |  146.943194ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5218/8417 [1:09:15<52:14,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:47 | 200 |   138.86301ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5219/8417 [1:09:16<51:32,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:48 | 200 |  139.465364ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5220/8417 [1:09:17<50:55,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:49 | 200 |  179.104936ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5221/8417 [1:09:18<51:22,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:50 | 200 |  146.640203ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5222/8417 [1:09:19<51:08,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:51 | 200 |  171.008067ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5223/8417 [1:09:20<51:10,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:52 | 200 |  157.312024ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5224/8417 [1:09:21<51:10,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:53 | 200 |  155.999805ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5225/8417 [1:09:22<51:05,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:54 | 200 |  179.186094ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5226/8417 [1:09:23<51:34,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:55 | 200 |  136.197993ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5227/8417 [1:09:24<51:00,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:56 | 200 |  180.126878ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5228/8417 [1:09:25<51:42,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:57 | 200 |  149.455552ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5229/8417 [1:09:26<51:18,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:58 | 200 |  147.703167ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5230/8417 [1:09:27<51:04,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:33:59 | 200 |  142.900304ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5231/8417 [1:09:28<51:13,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:00 | 200 |  120.207512ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5232/8417 [1:09:29<50:20,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:01 | 200 |  180.357262ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5233/8417 [1:09:30<51:23,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:02 | 200 |  145.526339ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5234/8417 [1:09:31<51:39,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:03 | 200 |   144.19447ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5235/8417 [1:09:31<51:44,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:04 | 200 |  143.268604ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5236/8417 [1:09:32<51:16,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:05 | 200 |  183.737846ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5237/8417 [1:09:33<52:13,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:06 | 200 |  177.123616ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5238/8417 [1:09:34<52:08,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:07 | 200 |  162.726214ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5239/8417 [1:09:35<51:47,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:08 | 200 |  117.405617ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5240/8417 [1:09:36<50:59,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:09 | 200 |  179.067183ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5241/8417 [1:09:37<51:30,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:10 | 200 |  167.303208ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5242/8417 [1:09:38<52:23,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:11 | 200 |  159.252337ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5243/8417 [1:09:39<52:47,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:12 | 200 |  175.372208ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5244/8417 [1:09:40<52:27,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:12 | 200 |  148.558693ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5245/8417 [1:09:41<51:43,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:13 | 200 |  148.851084ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5246/8417 [1:09:42<51:15,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:14 | 200 |  176.547054ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5247/8417 [1:09:43<51:25,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:15 | 200 |  144.099828ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5248/8417 [1:09:44<51:10,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:16 | 200 |  141.213057ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5249/8417 [1:09:45<51:17,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:17 | 200 |   134.40091ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5250/8417 [1:09:46<51:18,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:18 | 200 |  156.502217ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5251/8417 [1:09:47<51:05,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:19 | 200 |  177.751862ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5252/8417 [1:09:48<51:23,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:20 | 200 |  136.735633ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5253/8417 [1:09:49<51:11,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:21 | 200 |  182.906367ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5254/8417 [1:09:50<51:23,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:22 | 200 |  146.404185ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5255/8417 [1:09:51<51:03,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:23 | 200 |  140.286942ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5256/8417 [1:09:52<50:29,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:24 | 200 |  132.950254ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5257/8417 [1:09:53<51:04,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:25 | 200 |  173.847873ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5258/8417 [1:09:54<51:26,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:26 | 200 |  181.614495ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5259/8417 [1:09:55<51:37,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:27 | 200 |   161.41836ms |       127.0.0.1 | POST     "/api/chat"

 62%|██████▏   | 5260/8417 [1:09:56<51:37,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:28 | 200 |  144.314718ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5261/8417 [1:09:57<51:18,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:29 | 200 |  137.290651ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5262/8417 [1:09:58<51:02,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:30 | 200 |  175.904104ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5263/8417 [1:09:59<51:36,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:31 | 200 |  145.911688ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5264/8417 [1:10:00<51:15,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:32 | 200 |  155.181261ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5265/8417 [1:10:01<51:00,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:33 | 200 |  142.334351ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5266/8417 [1:10:02<50:34,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:34 | 200 |  138.484873ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5267/8417 [1:10:03<50:08,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:35 | 200 |   179.13021ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5268/8417 [1:10:04<50:37,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:36 | 200 |  155.448163ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5269/8417 [1:10:05<50:51,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:37 | 200 |  179.218759ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5270/8417 [1:10:06<51:47,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:38 | 200 |  159.804186ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5271/8417 [1:10:07<51:39,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:39 | 200 |  166.112675ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5272/8417 [1:10:08<51:29,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:40 | 200 |  188.133679ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5273/8417 [1:10:09<52:10,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:41 | 200 |  183.563568ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5274/8417 [1:10:10<52:55,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:42 | 200 |  192.209493ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5275/8417 [1:10:11<52:54,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:43 | 200 |  146.318765ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5276/8417 [1:10:12<52:06,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:44 | 200 |   170.09569ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5277/8417 [1:10:13<52:13,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:45 | 200 |  163.782483ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5278/8417 [1:10:14<52:08,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:46 | 200 |  176.064099ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5279/8417 [1:10:15<51:58,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:47 | 200 |  180.303505ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5280/8417 [1:10:16<52:09,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:48 | 200 |  180.333258ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5281/8417 [1:10:17<52:02,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:49 | 200 |  182.459803ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5282/8417 [1:10:18<52:13,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:50 | 200 |  175.637434ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5283/8417 [1:10:19<51:55,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:51 | 200 |  175.707356ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5284/8417 [1:10:20<52:03,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:52 | 200 |  156.750828ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5285/8417 [1:10:21<51:57,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:53 | 200 |  153.465098ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5286/8417 [1:10:22<51:42,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:54 | 200 |  139.381047ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5287/8417 [1:10:23<51:15,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:55 | 200 |  132.534946ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5288/8417 [1:10:23<50:51,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:56 | 200 |  167.290878ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5289/8417 [1:10:24<50:58,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:57 | 200 |  169.223496ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5290/8417 [1:10:25<51:11,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:58 | 200 |  174.805043ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5291/8417 [1:10:26<51:29,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:34:59 | 200 |  170.793223ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5292/8417 [1:10:27<51:52,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:00 | 200 |  159.430635ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5293/8417 [1:10:28<51:58,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:01 | 200 |  155.250105ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5294/8417 [1:10:29<51:49,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:02 | 200 |  158.997897ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5295/8417 [1:10:30<51:26,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:03 | 200 |  181.480681ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5296/8417 [1:10:31<51:58,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:04 | 200 |  178.746853ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5297/8417 [1:10:32<51:55,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:05 | 200 |  180.238441ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5298/8417 [1:10:33<51:58,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:06 | 200 |  182.080632ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5299/8417 [1:10:34<52:05,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:07 | 200 |  180.628171ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5300/8417 [1:10:35<52:09,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:08 | 200 |  177.552626ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5301/8417 [1:10:37<52:37,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:09 | 200 |  160.247487ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5302/8417 [1:10:38<52:11,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:10 | 200 |   124.75478ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5303/8417 [1:10:38<51:36,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:11 | 200 |  152.103161ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5304/8417 [1:10:39<51:40,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:12 | 200 |  179.067295ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5305/8417 [1:10:41<52:05,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:13 | 200 |  163.242225ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5306/8417 [1:10:42<52:01,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:14 | 200 |  143.370575ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5307/8417 [1:10:42<51:36,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:15 | 200 |  178.505243ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5308/8417 [1:10:44<51:52,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:16 | 200 |  180.428617ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5309/8417 [1:10:45<52:32,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:17 | 200 |  167.591024ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5310/8417 [1:10:46<52:15,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:18 | 200 |  157.244827ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5311/8417 [1:10:47<52:18,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:19 | 200 |  142.603168ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5312/8417 [1:10:48<51:55,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:20 | 200 |  171.857731ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5313/8417 [1:10:49<52:00,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:21 | 200 |  167.162214ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5314/8417 [1:10:50<51:36,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:22 | 200 |   177.80619ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5315/8417 [1:10:51<52:26,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:23 | 200 |  149.196543ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5316/8417 [1:10:52<51:36,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:24 | 200 |  164.905407ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5317/8417 [1:10:53<51:39,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:25 | 200 |  180.028712ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5318/8417 [1:10:54<51:37,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:26 | 200 |  144.204881ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5319/8417 [1:10:55<50:50,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:27 | 200 |  181.969646ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5320/8417 [1:10:55<50:57,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:28 | 200 |  150.017233ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5321/8417 [1:10:56<50:21,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:29 | 200 |  115.867455ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5322/8417 [1:10:57<49:32,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:29 | 200 |  139.709278ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5323/8417 [1:10:58<49:26,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:30 | 200 |   178.03345ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5324/8417 [1:10:59<50:02,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:31 | 200 |  146.419281ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5325/8417 [1:11:00<49:53,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:32 | 200 |  136.713318ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5326/8417 [1:11:01<49:29,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:33 | 200 |  178.630813ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5327/8417 [1:11:02<49:48,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:34 | 200 |  150.315891ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5328/8417 [1:11:03<49:39,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:35 | 200 |  147.259697ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5329/8417 [1:11:04<49:36,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:36 | 200 |  137.879152ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5330/8417 [1:11:05<49:34,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:37 | 200 |  141.939948ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5331/8417 [1:11:06<49:31,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:38 | 200 |  179.128679ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5332/8417 [1:11:07<50:28,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:39 | 200 |  144.854425ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5333/8417 [1:11:08<50:27,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:40 | 200 |  146.377618ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5334/8417 [1:11:09<50:24,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:41 | 200 |   159.64421ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5335/8417 [1:11:10<49:58,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:42 | 200 |   180.01551ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5336/8417 [1:11:11<50:08,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:43 | 200 |  178.697743ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5337/8417 [1:11:12<50:13,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:44 | 200 |  173.859672ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5338/8417 [1:11:13<50:56,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:45 | 200 |  161.814538ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5339/8417 [1:11:14<51:04,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:46 | 200 |  174.788785ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5340/8417 [1:11:15<50:56,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:47 | 200 |  166.160519ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5341/8417 [1:11:16<51:19,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:48 | 200 |  188.649447ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5342/8417 [1:11:17<51:31,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:49 | 200 |  176.798882ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5343/8417 [1:11:18<51:13,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:50 | 200 |  175.084353ms |       127.0.0.1 | POST     "/api/chat"

 63%|██████▎   | 5344/8417 [1:11:19<51:12,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:51 | 200 |  167.253361ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5345/8417 [1:11:20<50:48,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:52 | 200 |  152.273841ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5346/8417 [1:11:21<50:39,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:53 | 200 |  138.892851ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5347/8417 [1:11:22<50:38,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:54 | 200 |  143.602528ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5348/8417 [1:11:23<50:19,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:55 | 200 |  179.857164ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5349/8417 [1:11:24<50:27,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:56 | 200 |  144.476753ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5350/8417 [1:11:25<49:56,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:57 | 200 |  144.919628ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5351/8417 [1:11:26<49:53,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:58 | 200 |  126.835304ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5352/8417 [1:11:27<50:01,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:35:59 | 200 |  177.398801ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5353/8417 [1:11:28<50:20,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:00 | 200 |  165.543445ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5354/8417 [1:11:29<50:35,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:01 | 200 |  180.042019ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5355/8417 [1:11:30<50:44,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:02 | 200 |  136.845099ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5356/8417 [1:11:31<50:29,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:03 | 200 |  145.606686ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5357/8417 [1:11:32<50:16,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:04 | 200 |  169.365329ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5358/8417 [1:11:33<51:02,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:05 | 200 |  159.030664ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5359/8417 [1:11:34<50:46,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:06 | 200 |  144.759114ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5360/8417 [1:11:35<50:23,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:07 | 200 |  120.665584ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5361/8417 [1:11:36<49:08,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:08 | 200 |  176.370752ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5362/8417 [1:11:37<50:00,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:09 | 200 |  172.191328ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5363/8417 [1:11:38<50:13,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:10 | 200 |  159.905452ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5364/8417 [1:11:39<50:43,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:11 | 200 |  178.954239ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▎   | 5365/8417 [1:11:40<50:48,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:12 | 200 |  159.731232ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5366/8417 [1:11:41<50:49,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:13 | 200 |  147.262902ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5367/8417 [1:11:42<50:10,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:14 | 200 |  146.509225ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5368/8417 [1:11:43<49:44,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:15 | 200 |   176.90971ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5369/8417 [1:11:44<50:29,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:16 | 200 |  175.560496ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5370/8417 [1:11:45<51:08,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:17 | 200 |   199.71488ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5371/8417 [1:11:46<51:15,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:18 | 200 |   169.06877ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5372/8417 [1:11:47<51:27,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:19 | 200 |  148.297929ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5373/8417 [1:11:48<50:54,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:20 | 200 |  165.847927ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5374/8417 [1:11:49<50:54,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:21 | 200 |  186.641073ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5375/8417 [1:11:50<51:25,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:22 | 200 |  146.013661ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5376/8417 [1:11:51<50:27,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:23 | 200 |   167.78208ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5377/8417 [1:11:52<50:27,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:24 | 200 |  179.525466ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5378/8417 [1:11:53<50:25,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:25 | 200 |  175.540029ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5379/8417 [1:11:54<50:49,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:26 | 200 |  185.791418ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5380/8417 [1:11:55<50:37,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:27 | 200 |  174.062897ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5381/8417 [1:11:56<50:14,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:28 | 200 |  176.016382ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5382/8417 [1:11:57<50:18,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:29 | 200 |  169.300067ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5383/8417 [1:11:58<50:19,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:30 | 200 |  123.521182ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5384/8417 [1:11:59<49:57,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:31 | 200 |   199.54202ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5385/8417 [1:12:00<50:26,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:32 | 200 |  147.282273ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5386/8417 [1:12:01<49:47,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:33 | 200 |   136.07471ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5387/8417 [1:12:02<49:01,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:34 | 200 |  177.641937ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5388/8417 [1:12:03<49:56,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:35 | 200 |  146.745484ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5389/8417 [1:12:04<49:39,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:36 | 200 |  136.172921ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5390/8417 [1:12:05<49:01,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:37 | 200 |  118.414064ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5391/8417 [1:12:05<48:09,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:38 | 200 |  140.945481ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5392/8417 [1:12:06<48:11,  1.05it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:39 | 200 |  174.664641ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5393/8417 [1:12:07<48:33,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:40 | 200 |   176.53312ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5394/8417 [1:12:08<49:24,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:41 | 200 |  169.131678ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5395/8417 [1:12:09<49:40,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:42 | 200 |  173.903962ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5396/8417 [1:12:10<49:49,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:43 | 200 |  170.620166ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5397/8417 [1:12:11<49:42,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:44 | 200 |  166.857525ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5398/8417 [1:12:12<50:00,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:45 | 200 |  179.394681ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5399/8417 [1:12:13<50:23,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:46 | 200 |  181.041725ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5400/8417 [1:12:14<50:20,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:47 | 200 |  187.988076ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5401/8417 [1:12:15<50:29,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:48 | 200 |  171.497915ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5402/8417 [1:12:16<51:03,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:49 | 200 |  144.340051ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5403/8417 [1:12:17<50:33,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:50 | 200 |  135.463898ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5404/8417 [1:12:18<49:58,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:51 | 200 |  185.663006ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5405/8417 [1:12:19<50:15,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:52 | 200 |  174.604442ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5406/8417 [1:12:20<50:15,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:53 | 200 |  172.748824ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5407/8417 [1:12:21<49:56,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:54 | 200 |  179.256681ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5408/8417 [1:12:22<50:10,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:55 | 200 |  178.238418ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5409/8417 [1:12:23<50:02,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:56 | 200 |  142.070514ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5410/8417 [1:12:24<49:31,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:57 | 200 |  178.194361ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5411/8417 [1:12:25<49:33,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:58 | 200 |  144.771866ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5412/8417 [1:12:26<49:26,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:36:59 | 200 |  146.294236ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5413/8417 [1:12:27<49:32,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:00 | 200 |  145.521726ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5414/8417 [1:12:28<49:26,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:01 | 200 |  173.868356ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5415/8417 [1:12:29<50:35,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:02 | 200 |  149.987464ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5416/8417 [1:12:30<49:57,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:03 | 200 |  133.331903ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5417/8417 [1:12:31<49:51,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:04 | 200 |  182.628362ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5418/8417 [1:12:32<49:59,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:05 | 200 |  141.459298ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5419/8417 [1:12:33<49:16,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:06 | 200 |  177.614033ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5420/8417 [1:12:34<49:28,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:06 | 200 |  142.098151ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5421/8417 [1:12:35<49:21,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:07 | 200 |  140.795337ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5422/8417 [1:12:36<48:49,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:08 | 200 |  166.203336ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5423/8417 [1:12:37<49:12,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:09 | 200 |  179.141551ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5424/8417 [1:12:38<49:46,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:10 | 200 |  168.438494ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5425/8417 [1:12:39<49:54,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:11 | 200 |  174.217657ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5426/8417 [1:12:40<49:39,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:12 | 200 |  178.666033ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5427/8417 [1:12:41<49:43,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:13 | 200 |  175.660511ms |       127.0.0.1 | POST     "/api/chat"

 64%|██████▍   | 5428/8417 [1:12:42<49:45,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:15 | 200 |  181.377912ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5429/8417 [1:12:43<50:35,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:15 | 200 |  115.980338ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5430/8417 [1:12:44<49:59,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:17 | 200 |   179.92393ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5431/8417 [1:12:45<50:07,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:18 | 200 |  147.833912ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5432/8417 [1:12:46<50:06,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:18 | 200 |  114.601639ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5433/8417 [1:12:47<50:24,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:20 | 200 |  188.180701ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5434/8417 [1:12:48<50:35,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:21 | 200 |  151.113816ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5435/8417 [1:12:49<50:13,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:22 | 200 |  144.859776ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5436/8417 [1:12:50<49:50,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:23 | 200 |  178.006149ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5437/8417 [1:12:51<49:44,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:24 | 200 |   140.63313ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5438/8417 [1:12:52<49:17,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:25 | 200 |  170.508724ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5439/8417 [1:12:53<49:23,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:26 | 200 |  152.390366ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5440/8417 [1:12:54<49:13,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:27 | 200 |  177.908819ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5441/8417 [1:12:55<49:29,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:28 | 200 |  172.681883ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5442/8417 [1:12:56<49:27,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:28 | 200 |  168.253803ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5443/8417 [1:12:57<49:06,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:29 | 200 |   166.97719ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5444/8417 [1:12:58<49:02,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:30 | 200 |  186.359286ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5445/8417 [1:12:59<49:36,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:32 | 200 |  180.521794ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5446/8417 [1:13:00<49:56,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:33 | 200 |   157.13758ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5447/8417 [1:13:01<49:36,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:34 | 200 |  177.973459ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5448/8417 [1:13:02<49:42,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:35 | 200 |  178.488696ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5449/8417 [1:13:03<49:38,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:36 | 200 |  173.248356ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5450/8417 [1:13:04<49:28,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:37 | 200 |  174.749898ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5451/8417 [1:13:05<49:32,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:38 | 200 |  179.938652ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5452/8417 [1:13:06<49:40,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:39 | 200 |  182.896819ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5453/8417 [1:13:07<49:32,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:40 | 200 |  182.411017ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5454/8417 [1:13:08<49:57,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:41 | 200 |  174.329096ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5455/8417 [1:13:09<50:24,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:42 | 200 |  143.882869ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5456/8417 [1:13:10<50:01,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:43 | 200 |  149.363369ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5457/8417 [1:13:11<49:39,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:44 | 200 |  167.258853ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5458/8417 [1:13:12<49:59,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:45 | 200 |  149.379122ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5459/8417 [1:13:13<49:17,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:46 | 200 |  117.750689ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5460/8417 [1:13:14<48:55,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:47 | 200 |  174.531257ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5461/8417 [1:13:15<49:13,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:48 | 200 |  134.632284ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5462/8417 [1:13:16<48:30,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:49 | 200 |  170.143996ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5463/8417 [1:13:17<48:33,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:50 | 200 |  179.012568ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5464/8417 [1:13:18<49:09,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:51 | 200 |  181.344416ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5465/8417 [1:13:19<50:05,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:52 | 200 |  202.443973ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5466/8417 [1:13:21<50:58,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:53 | 200 |  117.598046ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5467/8417 [1:13:22<50:13,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:54 | 200 |  180.145506ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5468/8417 [1:13:23<50:14,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:55 | 200 |  117.221591ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5469/8417 [1:13:24<49:13,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:56 | 200 |  181.985766ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5470/8417 [1:13:25<49:44,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:57 | 200 |  145.339477ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▍   | 5471/8417 [1:13:26<49:26,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:58 | 200 |  138.422959ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5472/8417 [1:13:27<49:10,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:37:59 | 200 |  176.385479ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5473/8417 [1:13:28<49:25,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:00 | 200 |  139.871798ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5474/8417 [1:13:29<48:42,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:01 | 200 |   180.71372ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5475/8417 [1:13:30<48:59,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:02 | 200 |  148.302022ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5476/8417 [1:13:31<49:13,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:03 | 200 |  148.799368ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5477/8417 [1:13:32<49:09,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:04 | 200 |  145.535773ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5478/8417 [1:13:33<48:58,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:05 | 200 |  184.381874ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5479/8417 [1:13:34<49:14,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:06 | 200 |  146.356713ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5480/8417 [1:13:35<49:15,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:07 | 200 |  135.691281ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5481/8417 [1:13:36<48:09,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:08 | 200 |  152.966877ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5482/8417 [1:13:36<47:53,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:09 | 200 |  175.997103ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5483/8417 [1:13:37<48:02,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:10 | 200 |  173.469046ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5484/8417 [1:13:38<48:07,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:11 | 200 |  174.345417ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5485/8417 [1:13:39<48:17,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:12 | 200 |  148.586886ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5486/8417 [1:13:40<47:42,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:13 | 200 |  129.227174ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5487/8417 [1:13:41<47:21,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:13 | 200 |  175.086567ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5488/8417 [1:13:42<47:46,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:14 | 200 |  147.800032ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5489/8417 [1:13:43<47:32,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:15 | 200 |  146.580317ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5490/8417 [1:13:44<47:35,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:16 | 200 |  153.036123ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5491/8417 [1:13:45<47:36,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:17 | 200 |  177.701901ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5492/8417 [1:13:46<47:42,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:18 | 200 |   118.51265ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5493/8417 [1:13:47<47:01,  1.04it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:19 | 200 |  174.659417ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5494/8417 [1:13:48<47:35,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:20 | 200 |  150.055156ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5495/8417 [1:13:49<48:03,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:21 | 200 |  141.250035ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5496/8417 [1:13:50<48:22,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:22 | 200 |  191.542953ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5497/8417 [1:13:51<48:22,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:23 | 200 |  146.733157ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5498/8417 [1:13:52<48:04,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:24 | 200 |  142.865592ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5499/8417 [1:13:53<47:34,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:25 | 200 |  146.887787ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5500/8417 [1:13:54<47:19,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:26 | 200 |  178.342879ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5501/8417 [1:13:55<47:57,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:27 | 200 |  133.351865ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5502/8417 [1:13:56<47:32,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:28 | 200 |  137.825381ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5503/8417 [1:13:57<47:21,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:29 | 200 |  173.455102ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5504/8417 [1:13:58<47:34,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:30 | 200 |  149.632567ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5505/8417 [1:13:59<47:53,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:31 | 200 |  139.858889ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5506/8417 [1:14:00<47:29,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:32 | 200 |  179.265962ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5507/8417 [1:14:01<48:06,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:33 | 200 |  150.441471ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5508/8417 [1:14:02<47:55,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:34 | 200 |   143.38652ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5509/8417 [1:14:03<48:07,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:35 | 200 |  159.674268ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5510/8417 [1:14:04<47:48,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:36 | 200 |  182.059555ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5511/8417 [1:14:05<48:02,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:37 | 200 |  178.203635ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5512/8417 [1:14:06<48:06,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:38 | 200 |  181.340117ms |       127.0.0.1 | POST     "/api/chat"

 65%|██████▌   | 5513/8417 [1:14:07<48:36,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:39 | 200 |  168.134332ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5514/8417 [1:14:08<48:32,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:40 | 200 |  147.405094ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5515/8417 [1:14:09<48:28,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:41 | 200 |  177.966311ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5516/8417 [1:14:10<48:33,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:42 | 200 |  170.565552ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5517/8417 [1:14:11<48:25,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:43 | 200 |  154.820574ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5518/8417 [1:14:12<47:51,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:44 | 200 |  159.446851ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5519/8417 [1:14:13<47:46,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:45 | 200 |  178.867108ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5520/8417 [1:14:14<48:12,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:46 | 200 |  184.709334ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5521/8417 [1:14:15<48:36,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:47 | 200 |  176.834556ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5522/8417 [1:14:16<48:42,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:48 | 200 |  181.974022ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5523/8417 [1:14:17<48:39,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:49 | 200 |  164.723954ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5524/8417 [1:14:18<48:31,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:50 | 200 |  178.593524ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5525/8417 [1:14:19<48:41,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:51 | 200 |   178.32693ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5526/8417 [1:14:20<48:36,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:52 | 200 |  153.759074ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5527/8417 [1:14:21<48:06,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:53 | 200 |  169.855773ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5528/8417 [1:14:22<48:50,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:54 | 200 |  189.635895ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5529/8417 [1:14:23<49:07,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:55 | 200 |  142.901244ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5530/8417 [1:14:24<49:05,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:56 | 200 |  115.025657ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5531/8417 [1:14:25<48:17,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:57 | 200 |  166.486546ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5532/8417 [1:14:26<48:13,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:58 | 200 |  150.447115ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5533/8417 [1:14:27<47:50,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:38:59 | 200 |  133.825403ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5534/8417 [1:14:28<47:11,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:00 | 200 |  142.370333ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5535/8417 [1:14:29<47:08,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:01 | 200 |  177.202748ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5536/8417 [1:14:30<47:42,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:02 | 200 |   173.46769ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5537/8417 [1:14:31<47:43,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:03 | 200 |  172.622105ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5538/8417 [1:14:32<47:53,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:04 | 200 |  178.127386ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5539/8417 [1:14:33<48:03,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:05 | 200 |  176.651655ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5540/8417 [1:14:34<48:04,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:06 | 200 |  179.097555ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5541/8417 [1:14:35<48:26,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:07 | 200 |  180.337081ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5542/8417 [1:14:36<48:17,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:08 | 200 |  180.107611ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5543/8417 [1:14:37<48:50,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:09 | 200 |  149.568203ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5544/8417 [1:14:38<48:24,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:10 | 200 |  141.031168ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5545/8417 [1:14:39<48:07,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:11 | 200 |  165.179458ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5546/8417 [1:14:40<47:58,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:12 | 200 |  178.870819ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5547/8417 [1:14:41<47:55,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:13 | 200 |  174.737695ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5548/8417 [1:14:42<47:59,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:14 | 200 |   174.56771ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5549/8417 [1:14:43<47:50,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:15 | 200 |  171.208642ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5550/8417 [1:14:44<47:48,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:16 | 200 |   174.20952ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5551/8417 [1:14:45<47:55,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:17 | 200 |  168.315445ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5552/8417 [1:14:46<47:48,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:18 | 200 |  185.439917ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5553/8417 [1:14:47<47:43,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:19 | 200 |  178.324555ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5554/8417 [1:14:48<47:39,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:20 | 200 |  181.759431ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5555/8417 [1:14:49<48:15,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:21 | 200 |  168.578645ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5556/8417 [1:14:50<48:08,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:22 | 200 |   158.16728ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5557/8417 [1:14:51<48:23,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:23 | 200 |   147.47307ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5558/8417 [1:14:52<47:47,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:24 | 200 |  114.588392ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5559/8417 [1:14:53<46:52,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:25 | 200 |  195.734872ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5560/8417 [1:14:54<48:06,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:26 | 200 |  185.228921ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5561/8417 [1:14:55<48:14,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:27 | 200 |  145.439286ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5562/8417 [1:14:56<47:47,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:28 | 200 |  122.671336ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5563/8417 [1:14:57<46:49,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:29 | 200 |  152.319218ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5564/8417 [1:14:58<47:17,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:30 | 200 |  179.373726ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5565/8417 [1:14:59<47:48,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:31 | 200 |  179.404419ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5566/8417 [1:15:00<47:43,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:32 | 200 |  176.770221ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5567/8417 [1:15:01<47:43,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:33 | 200 |  161.525008ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5568/8417 [1:15:02<47:31,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:34 | 200 |  177.606856ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5569/8417 [1:15:03<47:40,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:35 | 200 |  142.893944ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5570/8417 [1:15:04<47:20,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:36 | 200 |  145.427862ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5571/8417 [1:15:05<46:46,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:37 | 200 |  174.798335ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5572/8417 [1:15:06<46:56,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:38 | 200 |  157.287437ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5573/8417 [1:15:07<46:49,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:39 | 200 |  120.971523ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5574/8417 [1:15:08<46:16,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:40 | 200 |  144.715077ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5575/8417 [1:15:09<46:44,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:41 | 200 |  183.985372ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▌   | 5576/8417 [1:15:10<47:29,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:42 | 200 |  146.668995ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5577/8417 [1:15:11<46:58,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:43 | 200 |  140.011764ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5578/8417 [1:15:12<46:42,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:44 | 200 |  171.299305ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5579/8417 [1:15:13<46:52,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:45 | 200 |  148.818453ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5580/8417 [1:15:14<47:16,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:46 | 200 |  156.343152ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5581/8417 [1:15:15<46:58,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:47 | 200 |  166.220234ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5582/8417 [1:15:16<46:52,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:48 | 200 |  170.063721ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5583/8417 [1:15:17<47:11,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:49 | 200 |  143.017587ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5584/8417 [1:15:18<46:47,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:50 | 200 |  184.855376ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5585/8417 [1:15:19<48:27,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:51 | 200 |  120.984927ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5586/8417 [1:15:20<47:30,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:52 | 200 |  142.231402ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5587/8417 [1:15:21<47:00,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:53 | 200 |  174.737734ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5588/8417 [1:15:22<47:04,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:54 | 200 |  151.964737ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5589/8417 [1:15:23<46:57,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:55 | 200 |  152.926018ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5590/8417 [1:15:24<47:01,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:56 | 200 |  185.269987ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5591/8417 [1:15:25<48:06,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:57 | 200 |  173.342594ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5592/8417 [1:15:26<48:04,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:58 | 200 |  142.724875ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5593/8417 [1:15:27<47:26,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:39:59 | 200 |  136.348107ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5594/8417 [1:15:28<46:49,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:00 | 200 |  177.810758ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5595/8417 [1:15:29<47:25,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:01 | 200 |  117.985106ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5596/8417 [1:15:30<46:40,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:02 | 200 |  187.564458ms |       127.0.0.1 | POST     "/api/chat"

 66%|██████▋   | 5597/8417 [1:15:31<47:09,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:03 | 200 |  148.181133ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5598/8417 [1:15:32<46:50,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:04 | 200 |   147.03694ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5599/8417 [1:15:33<46:42,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:05 | 200 |   172.31361ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5600/8417 [1:15:34<46:56,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:06 | 200 |  153.067877ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5601/8417 [1:15:35<46:40,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:07 | 200 |  150.545446ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5602/8417 [1:15:36<46:46,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:08 | 200 |   176.18136ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5603/8417 [1:15:37<47:00,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:09 | 200 |  155.904893ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5604/8417 [1:15:38<47:02,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:10 | 200 |  145.641521ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5605/8417 [1:15:39<47:19,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:11 | 200 |  177.386141ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5606/8417 [1:15:40<47:18,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:12 | 200 |  118.226445ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5607/8417 [1:15:41<46:41,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:13 | 200 |  136.970422ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5608/8417 [1:15:42<46:27,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:14 | 200 |  180.611066ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5609/8417 [1:15:43<47:07,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:15 | 200 |  152.675511ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5610/8417 [1:15:44<47:08,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:16 | 200 |  155.070508ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5611/8417 [1:15:45<47:15,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:17 | 200 |  144.323746ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5612/8417 [1:15:46<47:03,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:18 | 200 |  177.904159ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5613/8417 [1:15:47<47:10,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:19 | 200 |  121.085808ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5614/8417 [1:15:48<46:12,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:20 | 200 |  166.635242ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5615/8417 [1:15:49<46:53,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:21 | 200 |  173.994863ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5616/8417 [1:15:50<47:03,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:22 | 200 |   150.08615ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5617/8417 [1:15:51<46:38,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:23 | 200 |  140.117028ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5618/8417 [1:15:52<46:06,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:24 | 200 |  117.725596ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5619/8417 [1:15:53<45:28,  1.03it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:25 | 200 |  175.735867ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5620/8417 [1:15:54<46:07,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:26 | 200 |  153.680338ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5621/8417 [1:15:55<46:52,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:27 | 200 |  180.901842ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5622/8417 [1:15:56<47:59,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:28 | 200 |  150.027954ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5623/8417 [1:15:57<47:55,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:29 | 200 |  140.905004ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5624/8417 [1:15:58<47:10,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:30 | 200 |   138.89031ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5625/8417 [1:15:59<46:48,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:31 | 200 |  177.494124ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5626/8417 [1:16:00<46:45,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:32 | 200 |  143.234559ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5627/8417 [1:16:01<46:17,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:33 | 200 |   117.20054ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5628/8417 [1:16:02<45:47,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:34 | 200 |  147.799914ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5629/8417 [1:16:03<45:49,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:35 | 200 |  180.621638ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5630/8417 [1:16:04<46:26,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:36 | 200 |   167.86638ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5631/8417 [1:16:05<47:25,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:37 | 200 |  150.611552ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5632/8417 [1:16:06<47:08,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:38 | 200 |  141.247619ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5633/8417 [1:16:07<46:40,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:39 | 200 |   177.36366ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5634/8417 [1:16:08<46:46,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:40 | 200 |  144.934161ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5635/8417 [1:16:09<46:53,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:41 | 200 |  153.600461ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5636/8417 [1:16:10<46:44,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:42 | 200 |  175.737977ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5637/8417 [1:16:11<46:58,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:43 | 200 |  154.145721ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5638/8417 [1:16:12<46:30,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:44 | 200 |   136.64019ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5639/8417 [1:16:13<45:52,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:45 | 200 |  175.565113ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5640/8417 [1:16:14<47:03,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:46 | 200 |   146.87504ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5641/8417 [1:16:15<46:36,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:47 | 200 |   118.32357ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5642/8417 [1:16:16<45:58,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:48 | 200 |  180.342726ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5643/8417 [1:16:17<46:30,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:49 | 200 |  143.794635ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5644/8417 [1:16:18<45:55,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:50 | 200 |  140.650069ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5645/8417 [1:16:19<46:01,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:51 | 200 |  172.172289ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5646/8417 [1:16:20<45:58,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:52 | 200 |  158.470065ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5647/8417 [1:16:21<45:59,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:53 | 200 |  148.711096ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5648/8417 [1:16:22<45:58,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:54 | 200 |  171.868402ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5649/8417 [1:16:23<45:49,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:55 | 200 |  181.271681ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5650/8417 [1:16:24<46:01,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:56 | 200 |  177.657067ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5651/8417 [1:16:25<46:20,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:57 | 200 |  178.639713ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5652/8417 [1:16:26<46:30,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:58 | 200 |  152.602519ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5653/8417 [1:16:27<46:25,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:40:59 | 200 |  142.900597ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5654/8417 [1:16:28<46:46,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:00 | 200 |  192.872299ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5655/8417 [1:16:29<47:28,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:02 | 200 |  142.453988ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5656/8417 [1:16:30<47:12,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:03 | 200 |  140.175277ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5657/8417 [1:16:31<46:42,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:04 | 200 |  168.556226ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5658/8417 [1:16:32<46:48,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:05 | 200 |   153.05308ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5659/8417 [1:16:33<46:18,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:06 | 200 |   148.19718ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5660/8417 [1:16:34<46:04,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:06 | 200 |  114.182176ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5661/8417 [1:16:35<45:32,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:07 | 200 |  180.228061ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5662/8417 [1:16:36<45:53,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:08 | 200 |  146.040147ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5663/8417 [1:16:37<45:38,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:09 | 200 |  140.735326ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5664/8417 [1:16:38<45:43,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:11 | 200 |  183.329002ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5665/8417 [1:16:39<46:21,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:12 | 200 |  145.074073ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5666/8417 [1:16:40<45:46,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:12 | 200 |  140.633305ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5667/8417 [1:16:41<45:24,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:13 | 200 |  175.547323ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5668/8417 [1:16:42<45:48,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:14 | 200 |   118.40577ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5669/8417 [1:16:43<45:15,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:15 | 200 |  170.825509ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5670/8417 [1:16:44<45:37,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:16 | 200 |  175.957411ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5671/8417 [1:16:45<45:47,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:17 | 200 |  145.742824ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5672/8417 [1:16:46<45:34,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:18 | 200 |  141.260794ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5673/8417 [1:16:47<45:19,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:19 | 200 |  154.101701ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5674/8417 [1:16:48<45:06,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:20 | 200 |  142.587776ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5675/8417 [1:16:49<45:17,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:21 | 200 |  172.828056ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5676/8417 [1:16:50<45:39,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:22 | 200 |  177.022272ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5677/8417 [1:16:51<46:13,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:23 | 200 |  168.235225ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5678/8417 [1:16:52<46:14,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:24 | 200 |  151.063146ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5679/8417 [1:16:53<45:51,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:25 | 200 |  142.181267ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5680/8417 [1:16:54<45:25,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:26 | 200 |  156.091892ms |       127.0.0.1 | POST     "/api/chat"

 67%|██████▋   | 5681/8417 [1:16:55<45:20,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:28 | 200 |  178.194482ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5682/8417 [1:16:56<46:12,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:29 | 200 |  161.167862ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5683/8417 [1:16:57<46:15,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:30 | 200 |  142.918451ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5684/8417 [1:16:58<45:42,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:30 | 200 |   142.35099ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5685/8417 [1:16:59<45:48,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:32 | 200 |  179.126144ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5686/8417 [1:17:00<46:22,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:33 | 200 |  165.409119ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5687/8417 [1:17:01<46:12,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:34 | 200 |  140.820703ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5688/8417 [1:17:02<45:55,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:35 | 200 |  182.751117ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5689/8417 [1:17:03<46:05,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:36 | 200 |  141.293526ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5690/8417 [1:17:04<45:53,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:37 | 200 |  142.153371ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5691/8417 [1:17:05<45:36,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:38 | 200 |  177.888059ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5692/8417 [1:17:06<46:02,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:39 | 200 |  142.674762ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5693/8417 [1:17:07<45:55,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:40 | 200 |  139.857227ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5694/8417 [1:17:08<45:53,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:41 | 200 |  179.371789ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5695/8417 [1:17:10<45:51,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:42 | 200 |  139.464097ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5696/8417 [1:17:10<45:12,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:43 | 200 |   148.30047ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5697/8417 [1:17:11<45:18,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:44 | 200 |  169.989204ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5698/8417 [1:17:12<45:24,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:45 | 200 |  143.601239ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5699/8417 [1:17:14<45:35,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:46 | 200 |  142.205517ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5700/8417 [1:17:14<45:15,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:47 | 200 |  175.809734ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5701/8417 [1:17:16<46:04,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:48 | 200 |  154.452971ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5702/8417 [1:17:17<45:46,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:49 | 200 |  155.226194ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5703/8417 [1:17:18<45:26,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:50 | 200 |  110.140594ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5704/8417 [1:17:18<44:32,  1.02it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:51 | 200 |  151.136836ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5705/8417 [1:17:19<44:46,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:52 | 200 |  180.197019ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5706/8417 [1:17:21<45:37,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:53 | 200 |  152.247398ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5707/8417 [1:17:22<45:35,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:54 | 200 |  115.421832ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5708/8417 [1:17:22<44:44,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:55 | 200 |  148.472502ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5709/8417 [1:17:23<44:51,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:56 | 200 |  139.145747ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5710/8417 [1:17:24<44:38,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:57 | 200 |  141.815342ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5711/8417 [1:17:25<44:52,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:58 | 200 |  177.977456ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5712/8417 [1:17:27<45:29,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:41:59 | 200 |  139.516236ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5713/8417 [1:17:27<45:09,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:00 | 200 |  178.208918ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5714/8417 [1:17:29<45:55,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:01 | 200 |   144.30428ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5715/8417 [1:17:30<45:26,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:02 | 200 |  137.325424ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5716/8417 [1:17:31<45:03,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:03 | 200 |  172.642934ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5717/8417 [1:17:32<45:55,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:04 | 200 |  159.179543ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5718/8417 [1:17:33<45:49,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:05 | 200 |  145.592714ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5719/8417 [1:17:34<45:41,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:06 | 200 |  177.533679ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5720/8417 [1:17:35<46:38,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:07 | 200 |  153.024022ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5721/8417 [1:17:36<46:09,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:08 | 200 |  143.754803ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5722/8417 [1:17:37<45:25,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:09 | 200 |  122.197361ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5723/8417 [1:17:38<44:40,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:10 | 200 |  178.356247ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5724/8417 [1:17:39<45:06,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:11 | 200 |  161.295111ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5725/8417 [1:17:40<45:07,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:12 | 200 |  181.261119ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5726/8417 [1:17:41<45:09,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:13 | 200 |  175.861517ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5727/8417 [1:17:42<45:24,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:14 | 200 |  161.818134ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5728/8417 [1:17:43<45:15,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:15 | 200 |  152.098813ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5729/8417 [1:17:44<45:06,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:16 | 200 |  166.466746ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5730/8417 [1:17:45<45:11,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:17 | 200 |  170.930583ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5731/8417 [1:17:46<45:01,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:18 | 200 |  141.368525ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5732/8417 [1:17:47<44:51,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:19 | 200 |  164.838051ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5733/8417 [1:17:48<44:46,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:20 | 200 |  180.877579ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5734/8417 [1:17:49<44:51,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:21 | 200 |  162.280142ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5735/8417 [1:17:50<44:59,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:22 | 200 |  159.176724ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5736/8417 [1:17:51<45:16,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:23 | 200 |  157.437236ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5737/8417 [1:17:52<45:22,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:24 | 200 |  182.563786ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5738/8417 [1:17:53<45:41,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:25 | 200 |  148.930581ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5739/8417 [1:17:54<44:57,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:26 | 200 |  139.668928ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5740/8417 [1:17:55<44:24,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:27 | 200 |  168.016241ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5741/8417 [1:17:56<44:25,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:28 | 200 |  159.026583ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5742/8417 [1:17:57<44:34,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:29 | 200 |  145.947795ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5743/8417 [1:17:58<44:24,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:30 | 200 |  143.513636ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5744/8417 [1:17:59<44:45,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:31 | 200 |  180.442098ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5745/8417 [1:18:00<45:04,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:32 | 200 |  145.953969ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5746/8417 [1:18:01<44:39,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:33 | 200 |  143.319436ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5747/8417 [1:18:02<44:29,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:34 | 200 |   176.14073ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5748/8417 [1:18:03<45:32,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:35 | 200 |  155.108675ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5749/8417 [1:18:04<45:21,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:36 | 200 |  136.117691ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5750/8417 [1:18:05<45:00,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:37 | 200 |  175.348953ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5751/8417 [1:18:06<44:49,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:38 | 200 |  140.285195ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5752/8417 [1:18:07<44:16,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:39 | 200 |  143.354111ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5753/8417 [1:18:08<44:26,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:40 | 200 |  168.622314ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5754/8417 [1:18:09<44:33,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:41 | 200 |  141.993523ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5755/8417 [1:18:10<44:30,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:42 | 200 |  143.204846ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5756/8417 [1:18:11<44:43,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:43 | 200 |  140.141119ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5757/8417 [1:18:12<44:36,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:44 | 200 |  174.121216ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5758/8417 [1:18:13<45:00,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:45 | 200 |  147.567272ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5759/8417 [1:18:14<44:47,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:46 | 200 |  115.714315ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5760/8417 [1:18:15<44:09,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:47 | 200 |  179.232988ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5761/8417 [1:18:16<44:24,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:48 | 200 |  147.695392ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5762/8417 [1:18:17<44:32,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:49 | 200 |  139.924229ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5763/8417 [1:18:18<44:12,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:50 | 200 |   173.99934ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5764/8417 [1:18:19<44:34,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:51 | 200 |  141.255439ms |       127.0.0.1 | POST     "/api/chat"

 68%|██████▊   | 5765/8417 [1:18:20<44:24,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:52 | 200 |  140.474705ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5766/8417 [1:18:21<44:08,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:53 | 200 |  173.957909ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5767/8417 [1:18:22<44:28,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:54 | 200 |  144.813701ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5768/8417 [1:18:23<44:45,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:55 | 200 |  175.080506ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5769/8417 [1:18:24<44:45,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:56 | 200 |  162.151493ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5770/8417 [1:18:25<45:15,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:57 | 200 |  180.888303ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5771/8417 [1:18:26<45:11,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:58 | 200 |  126.530653ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5772/8417 [1:18:27<44:36,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:42:59 | 200 |   178.51848ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5773/8417 [1:18:28<44:56,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:00 | 200 |  144.440307ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5774/8417 [1:18:29<44:54,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:01 | 200 |  146.083845ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5775/8417 [1:18:30<44:25,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:02 | 200 |  179.251561ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5776/8417 [1:18:31<44:37,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:03 | 200 |  147.428067ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5777/8417 [1:18:32<44:28,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:04 | 200 |  144.214095ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5778/8417 [1:18:33<44:17,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:05 | 200 |  174.050763ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5779/8417 [1:18:34<44:42,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:06 | 200 |  188.902699ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5780/8417 [1:18:35<45:12,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:07 | 200 |  142.261737ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5781/8417 [1:18:36<44:55,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:08 | 200 |  141.596871ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5782/8417 [1:18:37<44:38,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:09 | 200 |  177.709543ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5783/8417 [1:18:38<44:50,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:10 | 200 |   180.50064ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5784/8417 [1:18:39<45:17,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:11 | 200 |   177.68182ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5785/8417 [1:18:40<45:08,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:12 | 200 |   148.46203ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▊   | 5786/8417 [1:18:41<44:57,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:13 | 200 |  143.686089ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5787/8417 [1:18:42<44:51,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:15 | 200 |  182.347094ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5788/8417 [1:18:43<44:54,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:16 | 200 |   147.61126ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5789/8417 [1:18:44<44:38,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:17 | 200 |  141.045959ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5790/8417 [1:18:45<44:19,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:18 | 200 |  174.309069ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5791/8417 [1:18:46<44:30,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:19 | 200 |  142.894349ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5792/8417 [1:18:47<44:10,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:20 | 200 |  135.447563ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5793/8417 [1:18:48<44:02,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:21 | 200 |  181.372111ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5794/8417 [1:18:49<44:57,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:22 | 200 |  177.262273ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5795/8417 [1:18:51<45:23,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:23 | 200 |  155.848839ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5796/8417 [1:18:52<44:42,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:24 | 200 |  142.374682ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5797/8417 [1:18:53<44:37,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:25 | 200 |  196.668634ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5798/8417 [1:18:54<45:14,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:26 | 200 |  141.002532ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5799/8417 [1:18:55<44:55,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:27 | 200 |  143.859421ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5800/8417 [1:18:56<44:52,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:28 | 200 |  167.296591ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5801/8417 [1:18:57<44:44,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:29 | 200 |  167.201017ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5802/8417 [1:18:58<44:51,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:30 | 200 |   179.45168ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5803/8417 [1:18:59<45:15,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:31 | 200 |   153.07147ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5804/8417 [1:19:00<44:55,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:32 | 200 |  151.107652ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5805/8417 [1:19:01<44:16,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:33 | 200 |  173.628496ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5806/8417 [1:19:02<44:04,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:34 | 200 |  147.528493ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5807/8417 [1:19:03<43:39,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:35 | 200 |  141.973893ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5808/8417 [1:19:04<43:13,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:36 | 200 |  171.946326ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5809/8417 [1:19:05<43:36,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:37 | 200 |  177.558331ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5810/8417 [1:19:06<44:16,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:38 | 200 |   145.39418ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5811/8417 [1:19:07<44:03,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:39 | 200 |  178.426562ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5812/8417 [1:19:08<44:00,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:40 | 200 |  146.029989ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5813/8417 [1:19:09<43:53,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:41 | 200 |  184.537569ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5814/8417 [1:19:10<44:17,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:42 | 200 |  145.200668ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5815/8417 [1:19:11<44:03,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:43 | 200 |  140.685275ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5816/8417 [1:19:12<43:43,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:44 | 200 |  181.495107ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5817/8417 [1:19:13<43:47,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:45 | 200 |  142.544781ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5818/8417 [1:19:14<43:26,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:46 | 200 |  141.093395ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5819/8417 [1:19:15<43:18,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:47 | 200 |  183.494095ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5820/8417 [1:19:16<43:28,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:48 | 200 |  144.711162ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5821/8417 [1:19:17<43:23,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:49 | 200 |  145.664874ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5822/8417 [1:19:18<43:16,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:50 | 200 |  113.823071ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5823/8417 [1:19:19<43:08,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:51 | 200 |  186.096857ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5824/8417 [1:19:20<43:30,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:52 | 200 |  141.887662ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5825/8417 [1:19:21<43:08,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:53 | 200 |  138.281727ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5826/8417 [1:19:22<43:13,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:54 | 200 |  176.459558ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5827/8417 [1:19:23<43:39,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:55 | 200 |  147.496373ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5828/8417 [1:19:24<43:22,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:56 | 200 |  135.537247ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5829/8417 [1:19:25<43:01,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:57 | 200 |  179.019228ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5830/8417 [1:19:26<43:46,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:58 | 200 |  119.974075ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5831/8417 [1:19:27<43:20,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:43:59 | 200 |  185.318102ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5832/8417 [1:19:28<43:51,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:00 | 200 |   145.97751ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5833/8417 [1:19:29<43:57,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:01 | 200 |  144.415738ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5834/8417 [1:19:30<43:37,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:02 | 200 |  179.405202ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5835/8417 [1:19:31<43:44,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:03 | 200 |  175.643317ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5836/8417 [1:19:32<43:44,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:04 | 200 |  180.356866ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5837/8417 [1:19:33<44:06,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:05 | 200 |  163.605959ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5838/8417 [1:19:34<43:59,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:06 | 200 |  121.952824ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5839/8417 [1:19:35<43:14,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:07 | 200 |  177.312401ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5840/8417 [1:19:36<43:20,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:08 | 200 |  159.628075ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5841/8417 [1:19:37<43:11,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:09 | 200 |  141.796662ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5842/8417 [1:19:38<43:18,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:10 | 200 |  173.691753ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5843/8417 [1:19:39<43:56,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:11 | 200 |  156.858263ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5844/8417 [1:19:40<43:43,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:12 | 200 |  141.841319ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5845/8417 [1:19:41<43:53,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:13 | 200 |  138.645255ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5846/8417 [1:19:42<43:08,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:14 | 200 |  175.630747ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5847/8417 [1:19:43<43:21,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:15 | 200 |  143.594851ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5848/8417 [1:19:44<43:08,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:16 | 200 |  140.984558ms |       127.0.0.1 | POST     "/api/chat"

 69%|██████▉   | 5849/8417 [1:19:45<42:49,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:17 | 200 |  144.139803ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5850/8417 [1:19:46<42:56,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:18 | 200 |  174.392133ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5851/8417 [1:19:47<42:48,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:19 | 200 |  119.244233ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5852/8417 [1:19:48<42:08,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:20 | 200 |  145.414254ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5853/8417 [1:19:49<42:47,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:21 | 200 |  178.860806ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5854/8417 [1:19:50<43:07,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:22 | 200 |  149.902772ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5855/8417 [1:19:51<42:52,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:23 | 200 |   142.03629ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5856/8417 [1:19:52<42:35,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:24 | 200 |  181.336553ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5857/8417 [1:19:53<42:52,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:25 | 200 |  148.725735ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5858/8417 [1:19:54<42:52,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:26 | 200 |  158.283445ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5859/8417 [1:19:55<42:41,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:27 | 200 |  175.936709ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5860/8417 [1:19:56<42:52,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:28 | 200 |   144.59342ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5861/8417 [1:19:57<42:39,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:29 | 200 |  142.905482ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5862/8417 [1:19:58<42:20,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:30 | 200 |  180.355442ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5863/8417 [1:19:59<43:17,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:31 | 200 |    145.5189ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5864/8417 [1:20:00<43:18,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:32 | 200 |  138.893172ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5865/8417 [1:20:01<42:55,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:33 | 200 |  140.317451ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5866/8417 [1:20:02<42:41,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:34 | 200 |  132.981161ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5867/8417 [1:20:03<42:23,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:35 | 200 |  178.638713ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5868/8417 [1:20:04<42:59,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:36 | 200 |  118.999291ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5869/8417 [1:20:05<42:24,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:37 | 200 |  179.665923ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5870/8417 [1:20:06<42:53,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:38 | 200 |  144.603025ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5871/8417 [1:20:07<42:41,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:39 | 200 |  139.486692ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5872/8417 [1:20:08<42:16,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:40 | 200 |  173.345165ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5873/8417 [1:20:09<43:38,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:41 | 200 |  156.070497ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5874/8417 [1:20:10<43:20,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:43 | 200 |  182.341254ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5875/8417 [1:20:11<43:21,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:44 | 200 |  164.032484ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5876/8417 [1:20:12<43:29,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:45 | 200 |  154.416056ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5877/8417 [1:20:13<43:26,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:46 | 200 |  141.946693ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5878/8417 [1:20:15<43:39,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:47 | 200 |  143.417466ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5879/8417 [1:20:16<43:03,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:48 | 200 |  174.199526ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5880/8417 [1:20:17<43:08,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:49 | 200 |  142.441359ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5881/8417 [1:20:18<42:43,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:50 | 200 |  136.884203ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5882/8417 [1:20:19<42:25,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:51 | 200 |  179.214756ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5883/8417 [1:20:20<42:45,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:52 | 200 |  138.612087ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5884/8417 [1:20:21<42:30,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:53 | 200 |  135.473124ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5885/8417 [1:20:22<42:11,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:54 | 200 |  160.510965ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5886/8417 [1:20:23<42:21,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:55 | 200 |  150.674335ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5887/8417 [1:20:24<42:12,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:56 | 200 |  138.513057ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5888/8417 [1:20:25<42:05,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:57 | 200 |  167.736228ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5889/8417 [1:20:26<42:24,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:58 | 200 |  152.452291ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5890/8417 [1:20:27<42:24,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:44:59 | 200 |   138.28479ms |       127.0.0.1 | POST     "/api/chat"

 70%|██████▉   | 5891/8417 [1:20:28<41:57,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:00 | 200 |  173.845279ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5892/8417 [1:20:29<42:12,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:01 | 200 |  148.293027ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5893/8417 [1:20:30<42:09,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:02 | 200 |  115.479098ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5894/8417 [1:20:31<41:43,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:03 | 200 |  142.357227ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5895/8417 [1:20:32<41:43,  1.01it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:04 | 200 |   177.56664ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5896/8417 [1:20:33<42:13,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:05 | 200 |  154.780058ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5897/8417 [1:20:34<43:03,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:06 | 200 |  140.051308ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5898/8417 [1:20:35<42:42,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:07 | 200 |  177.944455ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5899/8417 [1:20:36<42:44,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:08 | 200 |   159.04017ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5900/8417 [1:20:37<42:45,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:09 | 200 |  183.499585ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5901/8417 [1:20:38<42:51,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:10 | 200 |  179.392431ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5902/8417 [1:20:39<43:09,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:11 | 200 |  171.397728ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5903/8417 [1:20:40<43:14,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:12 | 200 |  139.552412ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5904/8417 [1:20:41<43:23,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:13 | 200 |  154.712519ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5905/8417 [1:20:42<43:21,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:14 | 200 |  172.494219ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5906/8417 [1:20:43<43:21,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:15 | 200 |  182.558337ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5907/8417 [1:20:44<43:21,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:16 | 200 |  178.909504ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5908/8417 [1:20:45<43:20,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:17 | 200 |  150.944483ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5909/8417 [1:20:46<42:49,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:18 | 200 |  145.577077ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5910/8417 [1:20:47<42:23,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:19 | 200 |  182.099647ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5911/8417 [1:20:48<42:41,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:20 | 200 |   142.25662ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5912/8417 [1:20:49<42:43,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:21 | 200 |  140.627782ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5913/8417 [1:20:50<42:41,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:22 | 200 |  138.075933ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5914/8417 [1:20:51<42:15,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:23 | 200 |  177.724184ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5915/8417 [1:20:52<42:32,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:24 | 200 |  144.261239ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5916/8417 [1:20:53<42:20,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:25 | 200 |  119.744624ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5917/8417 [1:20:54<42:06,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:26 | 200 |  179.302302ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5918/8417 [1:20:55<42:44,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:27 | 200 |  183.264225ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5919/8417 [1:20:56<42:53,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:28 | 200 |  129.224899ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5920/8417 [1:20:57<42:22,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:29 | 200 |  171.664504ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5921/8417 [1:20:58<42:34,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:30 | 200 |  154.193463ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5922/8417 [1:20:59<42:40,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:31 | 200 |  145.935061ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5923/8417 [1:21:00<42:13,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:32 | 200 |  179.616822ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5924/8417 [1:21:01<42:33,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:33 | 200 |  145.295815ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5925/8417 [1:21:02<42:09,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:34 | 200 |  130.737755ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5926/8417 [1:21:03<41:41,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:35 | 200 |  181.064318ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5927/8417 [1:21:04<42:05,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:36 | 200 |  146.588231ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5928/8417 [1:21:05<41:54,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:37 | 200 |  139.817079ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5929/8417 [1:21:06<41:48,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:38 | 200 |  143.144141ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5930/8417 [1:21:07<41:42,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:39 | 200 |  174.328583ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5931/8417 [1:21:08<42:10,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:40 | 200 |  137.217003ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5932/8417 [1:21:09<42:22,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:42 | 200 |  176.751496ms |       127.0.0.1 | POST     "/api/chat"

 70%|███████   | 5933/8417 [1:21:10<42:34,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:43 | 200 |  187.504561ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5934/8417 [1:21:11<42:47,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:44 | 200 |  148.885259ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5935/8417 [1:21:12<42:58,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:45 | 200 |  163.175983ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5936/8417 [1:21:14<42:55,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:46 | 200 |  135.987861ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5937/8417 [1:21:15<42:24,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:47 | 200 |  158.945405ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5938/8417 [1:21:16<42:17,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:48 | 200 |  147.210589ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5939/8417 [1:21:17<42:03,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:49 | 200 |  181.477069ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5940/8417 [1:21:18<42:30,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:50 | 200 |  175.015308ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5941/8417 [1:21:19<42:33,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:51 | 200 |  187.023302ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5942/8417 [1:21:20<42:47,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:52 | 200 |  119.921162ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5943/8417 [1:21:21<42:02,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:53 | 200 |  178.466499ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5944/8417 [1:21:22<42:12,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:54 | 200 |  148.516039ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5945/8417 [1:21:23<42:09,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:55 | 200 |  112.987202ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5946/8417 [1:21:24<41:29,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:56 | 200 |   182.63317ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5947/8417 [1:21:25<42:05,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:57 | 200 |  143.046563ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5948/8417 [1:21:26<42:06,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:58 | 200 |  177.315301ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5949/8417 [1:21:27<42:19,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:45:59 | 200 |  182.821612ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5950/8417 [1:21:28<42:54,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:00 | 200 |  147.814365ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5951/8417 [1:21:29<42:54,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:01 | 200 |  138.847638ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5952/8417 [1:21:30<42:35,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:02 | 200 |  143.262665ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5953/8417 [1:21:31<42:20,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:03 | 200 |  165.619983ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5954/8417 [1:21:32<42:13,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:04 | 200 |  133.646088ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5955/8417 [1:21:33<41:32,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:05 | 200 |  179.793437ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5956/8417 [1:21:34<41:38,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:06 | 200 |  147.214892ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5957/8417 [1:21:35<41:04,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:07 | 200 |  140.375639ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5958/8417 [1:21:36<40:55,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:08 | 200 |  138.222002ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5959/8417 [1:21:37<41:00,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:09 | 200 |  175.585057ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5960/8417 [1:21:38<41:34,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:10 | 200 |  145.786288ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5961/8417 [1:21:39<41:37,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:11 | 200 |  177.647184ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5962/8417 [1:21:40<41:41,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:12 | 200 |  182.888749ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5963/8417 [1:21:41<42:22,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:13 | 200 |  150.824546ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5964/8417 [1:21:42<41:49,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:14 | 200 |  144.784934ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5965/8417 [1:21:43<41:45,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:15 | 200 |  180.381931ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5966/8417 [1:21:44<42:28,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:16 | 200 |  157.672294ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5967/8417 [1:21:45<42:29,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:17 | 200 |  170.761708ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5968/8417 [1:21:46<42:10,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:18 | 200 |  181.290845ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5969/8417 [1:21:47<42:03,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:19 | 200 |  142.582644ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5970/8417 [1:21:48<41:46,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:20 | 200 |   178.38765ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5971/8417 [1:21:49<42:10,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:22 | 200 |  144.196241ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5972/8417 [1:21:50<41:45,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:23 | 200 |  138.699082ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5973/8417 [1:21:51<41:24,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:24 | 200 |  146.861001ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5974/8417 [1:21:52<41:18,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:25 | 200 |  180.160091ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5975/8417 [1:21:53<41:34,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:26 | 200 |  126.442093ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5976/8417 [1:21:54<41:56,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:27 | 200 |  180.209098ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5977/8417 [1:21:56<41:52,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:28 | 200 |  142.611966ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5978/8417 [1:21:57<41:30,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:29 | 200 |  183.359889ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5979/8417 [1:21:58<42:32,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:30 | 200 |  142.879724ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5980/8417 [1:21:59<42:04,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:31 | 200 |  147.710781ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5981/8417 [1:22:00<41:30,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:32 | 200 |  172.977994ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5982/8417 [1:22:01<41:55,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:33 | 200 |  140.164189ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5983/8417 [1:22:02<41:48,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:34 | 200 |   168.73077ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5984/8417 [1:22:03<41:31,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:35 | 200 |  178.577452ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5985/8417 [1:22:04<41:38,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:36 | 200 |  181.218258ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5986/8417 [1:22:05<41:43,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:37 | 200 |  166.237854ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5987/8417 [1:22:06<41:42,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:38 | 200 |  117.470202ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5988/8417 [1:22:07<40:55,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:39 | 200 |  161.295251ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5989/8417 [1:22:08<40:55,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:40 | 200 |  140.765461ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5990/8417 [1:22:09<40:55,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:41 | 200 |  174.434299ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5991/8417 [1:22:10<41:05,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:42 | 200 |  143.929037ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5992/8417 [1:22:11<40:54,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:43 | 200 |  144.104741ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5993/8417 [1:22:12<41:05,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:44 | 200 |  174.212455ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5994/8417 [1:22:13<41:46,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:45 | 200 |  148.312051ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5995/8417 [1:22:14<41:16,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:46 | 200 |  125.625845ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5996/8417 [1:22:15<41:02,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:47 | 200 |  193.905545ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████   | 5997/8417 [1:22:16<41:45,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:48 | 200 |   155.36248ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 5998/8417 [1:22:17<41:33,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:49 | 200 |  177.605939ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 5999/8417 [1:22:18<41:47,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:50 | 200 |  148.876583ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6000/8417 [1:22:19<41:56,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:51 | 200 |  141.647375ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6001/8417 [1:22:20<41:47,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:52 | 200 |  176.058009ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6002/8417 [1:22:21<41:40,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:53 | 200 |  180.681396ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6003/8417 [1:22:22<41:28,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:54 | 200 |  175.086234ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6004/8417 [1:22:23<41:28,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:55 | 200 |  170.602867ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6005/8417 [1:22:24<41:33,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:56 | 200 |  142.467287ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6006/8417 [1:22:25<41:05,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:57 | 200 |  140.856517ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6007/8417 [1:22:26<41:13,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:46:58 | 200 |  181.035432ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6008/8417 [1:22:27<41:34,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:00 | 200 |  153.002943ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6009/8417 [1:22:28<41:17,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:01 | 200 |  179.304984ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6010/8417 [1:22:29<41:39,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:02 | 200 |  178.982326ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6011/8417 [1:22:30<41:42,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:03 | 200 |  147.074396ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6012/8417 [1:22:32<41:31,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:04 | 200 |  141.592466ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6013/8417 [1:22:33<40:58,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:05 | 200 |    177.2865ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6014/8417 [1:22:34<41:06,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:06 | 200 |  144.586895ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6015/8417 [1:22:35<41:01,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:07 | 200 |  140.735268ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6016/8417 [1:22:36<40:32,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:08 | 200 |  139.030429ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6017/8417 [1:22:37<40:11,  1.00s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:09 | 200 |   137.56898ms |       127.0.0.1 | POST     "/api/chat"

 71%|███████▏  | 6018/8417 [1:22:38<39:58,  1.00it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:10 | 200 |  182.926383ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6019/8417 [1:22:39<40:44,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:11 | 200 |  145.505554ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6020/8417 [1:22:40<40:29,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:12 | 200 |  138.883034ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6021/8417 [1:22:41<40:27,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:13 | 200 |  169.144058ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6022/8417 [1:22:42<40:43,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:14 | 200 |  158.114855ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6023/8417 [1:22:43<40:37,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:15 | 200 |  181.556742ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6024/8417 [1:22:44<40:52,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:16 | 200 |  177.316584ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6025/8417 [1:22:45<41:07,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 72%|███████▏  | 6026/8417 [1:22:46<40:53,  1.03s/it]

[GIN] 2025/06/27 - 00:47:17 | 200 |  156.093556ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:18 | 200 |  137.729092ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6027/8417 [1:22:47<41:02,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:19 | 200 |  195.489471ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6028/8417 [1:22:48<41:30,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:20 | 200 |  147.758302ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6029/8417 [1:22:49<41:51,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:21 | 200 |  179.503146ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6030/8417 [1:22:50<41:42,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:22 | 200 |  143.474415ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6031/8417 [1:22:51<41:02,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:23 | 200 |  142.819092ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6032/8417 [1:22:52<41:15,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:24 | 200 |  134.075271ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6033/8417 [1:22:53<40:48,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:25 | 200 |  174.190231ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6034/8417 [1:22:54<40:48,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:26 | 200 |  148.931137ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6035/8417 [1:22:55<40:35,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:27 | 200 |   179.38424ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6036/8417 [1:22:56<40:48,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:28 | 200 |  175.765529ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6037/8417 [1:22:57<40:45,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:29 | 200 |  178.345403ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6038/8417 [1:22:58<41:08,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:30 | 200 |  140.896142ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6039/8417 [1:22:59<41:02,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:31 | 200 |  142.885393ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6040/8417 [1:23:00<40:37,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:32 | 200 |  135.461083ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6041/8417 [1:23:01<39:59,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:33 | 200 |  174.760707ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6042/8417 [1:23:02<40:02,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:34 | 200 |  143.846233ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6043/8417 [1:23:03<39:50,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:35 | 200 |  142.159455ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6044/8417 [1:23:04<40:05,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:36 | 200 |  169.088221ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6045/8417 [1:23:05<40:10,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:37 | 200 |    149.0507ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6046/8417 [1:23:06<40:16,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:38 | 200 |  117.507631ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6047/8417 [1:23:07<39:46,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:39 | 200 |  173.930705ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6048/8417 [1:23:08<40:17,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:40 | 200 |  158.355227ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6049/8417 [1:23:09<40:20,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:42 | 200 |  175.727965ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6050/8417 [1:23:10<40:48,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:43 | 200 |  162.381467ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6051/8417 [1:23:11<40:53,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:44 | 200 |  148.417844ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6052/8417 [1:23:12<40:37,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:45 | 200 |  144.170541ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6053/8417 [1:23:13<40:21,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:46 | 200 |  135.137897ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6054/8417 [1:23:14<39:55,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:47 | 200 |  179.184517ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6055/8417 [1:23:16<40:58,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:48 | 200 |  155.093096ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6056/8417 [1:23:17<40:36,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:49 | 200 |  180.549882ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6057/8417 [1:23:18<40:44,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:50 | 200 |  161.110856ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6058/8417 [1:23:19<41:21,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:51 | 200 |  136.907596ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6059/8417 [1:23:20<40:59,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:52 | 200 |  177.675228ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6060/8417 [1:23:21<40:59,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:53 | 200 |  176.365333ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6061/8417 [1:23:22<40:52,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:54 | 200 |   174.10992ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6062/8417 [1:23:23<40:54,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:55 | 200 |  145.333502ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6063/8417 [1:23:24<40:12,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:56 | 200 |  143.282084ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6064/8417 [1:23:25<40:26,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:57 | 200 |  180.273792ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6065/8417 [1:23:26<40:42,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:58 | 200 |  116.332404ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6066/8417 [1:23:27<39:46,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:47:59 | 200 |  144.825138ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6067/8417 [1:23:28<40:06,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:00 | 200 |  135.770886ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6068/8417 [1:23:29<40:22,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:01 | 200 |  183.236399ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6069/8417 [1:23:30<40:38,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:02 | 200 |  175.957323ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6070/8417 [1:23:31<40:48,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:03 | 200 |   144.09547ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6071/8417 [1:23:32<40:08,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:04 | 200 |  135.732484ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6072/8417 [1:23:33<39:51,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:05 | 200 |  177.012207ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6073/8417 [1:23:34<40:17,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:06 | 200 |  147.285835ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6074/8417 [1:23:35<40:09,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:07 | 200 |  134.137908ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6075/8417 [1:23:36<39:52,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:08 | 200 |  184.859358ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6076/8417 [1:23:37<40:21,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:09 | 200 |  177.628809ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6077/8417 [1:23:38<40:43,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:10 | 200 |  146.272478ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6078/8417 [1:23:39<40:52,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:12 | 200 |  140.903065ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6079/8417 [1:23:40<40:26,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:13 | 200 |  175.247284ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6080/8417 [1:23:41<40:34,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:14 | 200 |  171.655653ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6081/8417 [1:23:42<40:30,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:15 | 200 |  178.702049ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6082/8417 [1:23:44<40:37,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:16 | 200 |  151.073656ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6083/8417 [1:23:45<40:19,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:17 | 200 |  143.981308ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6084/8417 [1:23:46<40:16,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:18 | 200 |   144.54395ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6085/8417 [1:23:47<40:17,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:19 | 200 |  142.505883ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6086/8417 [1:23:48<40:16,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:20 | 200 |  180.980775ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6087/8417 [1:23:49<40:32,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:21 | 200 |  172.677701ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6088/8417 [1:23:50<41:17,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:22 | 200 |   176.67228ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6089/8417 [1:23:51<41:21,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:23 | 200 |  177.821813ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6090/8417 [1:23:52<41:39,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:24 | 200 |  146.030187ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6091/8417 [1:23:53<41:00,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:25 | 200 |  140.075562ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6092/8417 [1:23:54<40:25,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:26 | 200 |  168.344545ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6093/8417 [1:23:55<40:18,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:27 | 200 |  150.054407ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6094/8417 [1:23:56<40:08,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:28 | 200 |   178.36634ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6095/8417 [1:23:57<40:13,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:29 | 200 |  132.553032ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6096/8417 [1:23:58<39:48,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:30 | 200 |  179.631391ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6097/8417 [1:23:59<40:34,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:31 | 200 |  152.461475ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6098/8417 [1:24:00<40:43,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:32 | 200 |  175.877974ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6099/8417 [1:24:01<40:51,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:33 | 200 |  162.050807ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6100/8417 [1:24:02<40:13,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:35 | 200 |  151.231544ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6101/8417 [1:24:03<40:24,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:36 | 200 |   144.51287ms |       127.0.0.1 | POST     "/api/chat"

 72%|███████▏  | 6102/8417 [1:24:04<39:58,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:37 | 200 |   141.19712ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6103/8417 [1:24:06<40:24,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:38 | 200 |  169.802021ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6104/8417 [1:24:07<41:16,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:39 | 200 |  127.874537ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6105/8417 [1:24:08<40:12,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:40 | 200 |  170.545596ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6106/8417 [1:24:09<40:00,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:41 | 200 |  169.016195ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6107/8417 [1:24:10<39:47,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:42 | 200 |   142.29873ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6108/8417 [1:24:11<39:30,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:43 | 200 |  138.085505ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6109/8417 [1:24:12<39:15,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:44 | 200 |  143.805818ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6110/8417 [1:24:13<38:57,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:45 | 200 |  176.108656ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6111/8417 [1:24:14<39:11,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:46 | 200 |  140.243334ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6112/8417 [1:24:15<38:59,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:47 | 200 |  173.991044ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6113/8417 [1:24:16<39:33,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:48 | 200 |  139.668075ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6114/8417 [1:24:17<39:16,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:49 | 200 |  142.157226ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6115/8417 [1:24:18<39:05,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:50 | 200 |  179.016734ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6116/8417 [1:24:19<39:31,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:51 | 200 |  153.087678ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6117/8417 [1:24:20<39:24,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:52 | 200 |  144.127583ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6118/8417 [1:24:21<39:02,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:53 | 200 |  137.869939ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6119/8417 [1:24:22<39:37,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:54 | 200 |   185.72222ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6120/8417 [1:24:23<39:51,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:55 | 200 |  173.451288ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6121/8417 [1:24:24<40:23,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:56 | 200 |  142.688315ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6122/8417 [1:24:25<40:13,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:57 | 200 |  141.211564ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6123/8417 [1:24:26<39:36,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:58 | 200 |  174.337382ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6124/8417 [1:24:27<39:38,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:48:59 | 200 |  154.740266ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6125/8417 [1:24:28<39:25,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:00 | 200 |  184.543553ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6126/8417 [1:24:29<39:59,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:01 | 200 |  181.943683ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6127/8417 [1:24:30<40:03,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:02 | 200 |  146.713791ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6128/8417 [1:24:31<39:33,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:03 | 200 |  140.245453ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6129/8417 [1:24:32<39:40,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:05 | 200 |  175.902419ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6130/8417 [1:24:33<39:43,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:06 | 200 |  175.790652ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6131/8417 [1:24:35<40:05,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:07 | 200 |  144.637678ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6132/8417 [1:24:36<39:52,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:08 | 200 |  144.318935ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6133/8417 [1:24:37<39:32,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:09 | 200 |  174.384895ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6134/8417 [1:24:38<39:39,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:10 | 200 |  162.868078ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6135/8417 [1:24:39<39:46,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:11 | 200 |  192.295455ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6136/8417 [1:24:40<40:09,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:12 | 200 |  146.816216ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6137/8417 [1:24:41<39:33,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:13 | 200 |  132.835995ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6138/8417 [1:24:42<38:51,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:14 | 200 |  182.689397ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6139/8417 [1:24:43<39:01,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:15 | 200 |  142.449505ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6140/8417 [1:24:44<38:59,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:16 | 200 |  139.759277ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6141/8417 [1:24:45<38:54,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:17 | 200 |  179.030186ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6142/8417 [1:24:46<39:07,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:18 | 200 |  180.925242ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6143/8417 [1:24:47<39:40,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:19 | 200 |  146.211527ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6144/8417 [1:24:48<39:33,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:20 | 200 |  141.511127ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6145/8417 [1:24:49<39:25,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:21 | 200 |  138.641033ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6146/8417 [1:24:50<39:02,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:22 | 200 |  171.181485ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6147/8417 [1:24:51<39:06,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:23 | 200 |  176.336579ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6148/8417 [1:24:52<39:24,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:24 | 200 |  164.598745ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6149/8417 [1:24:53<39:59,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:25 | 200 |  171.690845ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6150/8417 [1:24:54<40:14,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:26 | 200 |  176.691082ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6151/8417 [1:24:55<39:59,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:28 | 200 |  161.786554ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6152/8417 [1:24:56<39:58,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:29 | 200 |  143.899049ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6153/8417 [1:24:57<39:31,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:30 | 200 |   145.34049ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6154/8417 [1:24:58<39:05,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:31 | 200 |  142.144315ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6155/8417 [1:24:59<38:52,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:32 | 200 |  175.547339ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6156/8417 [1:25:01<39:12,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:33 | 200 |   176.83728ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6157/8417 [1:25:02<39:25,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:34 | 200 |  152.635665ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6158/8417 [1:25:03<39:03,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:35 | 200 |  150.258921ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6159/8417 [1:25:04<38:50,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:36 | 200 |  175.902908ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6160/8417 [1:25:05<39:29,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:37 | 200 |  155.601977ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6161/8417 [1:25:06<39:16,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:38 | 200 |  182.907191ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6162/8417 [1:25:07<39:25,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:39 | 200 |  143.065834ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6163/8417 [1:25:08<39:22,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:40 | 200 |  138.414481ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6164/8417 [1:25:09<38:54,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:41 | 200 |  136.800968ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6165/8417 [1:25:10<38:45,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:42 | 200 |   143.23406ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6166/8417 [1:25:11<38:49,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:43 | 200 |  174.830093ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6167/8417 [1:25:12<38:54,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:44 | 200 |  178.285948ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6168/8417 [1:25:13<38:55,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:45 | 200 |  130.679362ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6169/8417 [1:25:14<38:28,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:46 | 200 |  181.738931ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6170/8417 [1:25:15<39:02,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:47 | 200 |  149.244116ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6171/8417 [1:25:16<38:26,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:48 | 200 |  136.888857ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6172/8417 [1:25:17<38:04,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:49 | 200 |  177.507572ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6173/8417 [1:25:18<38:45,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:50 | 200 |  165.395003ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6174/8417 [1:25:19<39:09,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:51 | 200 |  175.586781ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6175/8417 [1:25:20<39:15,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:52 | 200 |  117.830747ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6176/8417 [1:25:21<38:47,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:53 | 200 |   180.90386ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6177/8417 [1:25:22<38:52,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:54 | 200 |  147.648966ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6178/8417 [1:25:23<38:51,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:56 | 200 |  177.893396ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6179/8417 [1:25:24<39:09,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:57 | 200 |  190.178506ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6180/8417 [1:25:26<39:22,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:58 | 200 |  144.623332ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6181/8417 [1:25:27<39:06,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:49:59 | 200 |  144.908106ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6182/8417 [1:25:28<38:46,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:00 | 200 |  176.527469ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6183/8417 [1:25:29<38:54,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:01 | 200 |  200.905793ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6184/8417 [1:25:30<39:09,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:02 | 200 |  152.821824ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6185/8417 [1:25:31<39:11,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:03 | 200 |  140.923832ms |       127.0.0.1 | POST     "/api/chat"

 73%|███████▎  | 6186/8417 [1:25:32<38:46,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:04 | 200 |  174.622266ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6187/8417 [1:25:33<38:54,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:05 | 200 |  174.033614ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6188/8417 [1:25:34<39:05,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:06 | 200 |  145.235942ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6189/8417 [1:25:35<38:37,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:07 | 200 |  144.435646ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6190/8417 [1:25:36<38:18,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:08 | 200 |  143.863682ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6191/8417 [1:25:37<38:14,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:09 | 200 |  138.902588ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6192/8417 [1:25:38<38:11,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:10 | 200 |  142.122302ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6193/8417 [1:25:39<38:21,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:11 | 200 |  175.940026ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6194/8417 [1:25:40<38:27,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:12 | 200 |  179.249223ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6195/8417 [1:25:41<38:46,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:13 | 200 |  147.638976ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6196/8417 [1:25:42<38:25,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:14 | 200 |  144.474184ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6197/8417 [1:25:43<38:00,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:15 | 200 |  175.426136ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6198/8417 [1:25:44<38:08,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:16 | 200 |  112.754556ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6199/8417 [1:25:45<37:48,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:17 | 200 |  175.779593ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6200/8417 [1:25:46<38:11,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:18 | 200 |  164.883571ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6201/8417 [1:25:47<38:16,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:19 | 200 |  168.354502ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6202/8417 [1:25:48<38:28,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:20 | 200 |  150.816208ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6203/8417 [1:25:49<38:26,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:22 | 200 |  142.081009ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6204/8417 [1:25:50<38:09,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:23 | 200 |  140.820351ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6205/8417 [1:25:51<38:22,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:24 | 200 |  178.896299ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6206/8417 [1:25:53<39:03,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:25 | 200 |  146.679727ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▎  | 6207/8417 [1:25:54<38:42,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:26 | 200 |  136.974382ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6208/8417 [1:25:55<38:12,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:27 | 200 |  172.242011ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6209/8417 [1:25:56<38:06,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:28 | 200 |  157.703285ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6210/8417 [1:25:57<38:46,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:29 | 200 |  193.219022ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6211/8417 [1:25:58<39:06,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:30 | 200 |  143.312815ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6212/8417 [1:25:59<38:48,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:31 | 200 |  144.896047ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6213/8417 [1:26:00<38:18,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:32 | 200 |  181.002567ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6214/8417 [1:26:01<38:26,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:33 | 200 |  178.717922ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6215/8417 [1:26:02<38:28,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:34 | 200 |  120.570336ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6216/8417 [1:26:03<38:04,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:35 | 200 |  142.500834ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6217/8417 [1:26:04<37:51,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:36 | 200 |  175.203172ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6218/8417 [1:26:05<38:14,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:37 | 200 |  147.547846ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6219/8417 [1:26:06<38:03,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:38 | 200 |  178.572242ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6220/8417 [1:26:07<38:09,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:39 | 200 |  179.797956ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6221/8417 [1:26:08<38:21,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:40 | 200 |   145.75021ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6222/8417 [1:26:09<38:29,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:41 | 200 |  140.279169ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6223/8417 [1:26:10<38:16,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:42 | 200 |  140.955691ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6224/8417 [1:26:11<37:55,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:44 | 200 |  176.644645ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6225/8417 [1:26:12<38:27,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:45 | 200 |  145.951674ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6226/8417 [1:26:13<38:18,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:46 | 200 |  140.503653ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6227/8417 [1:26:14<38:00,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:47 | 200 |  135.194203ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6228/8417 [1:26:16<37:48,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:48 | 200 |  175.762968ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6229/8417 [1:26:17<38:06,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:49 | 200 |  187.610528ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6230/8417 [1:26:18<38:26,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:50 | 200 |  140.810735ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6231/8417 [1:26:19<39:03,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:51 | 200 |  182.165422ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6232/8417 [1:26:20<38:51,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:52 | 200 |  153.864679ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6233/8417 [1:26:21<38:35,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:53 | 200 |  139.388626ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6234/8417 [1:26:22<38:45,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:54 | 200 |  179.326072ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6235/8417 [1:26:23<38:56,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:55 | 200 |  171.502223ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6236/8417 [1:26:24<38:35,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:56 | 200 |  146.596113ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6237/8417 [1:26:25<38:54,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:57 | 200 |  178.958219ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6238/8417 [1:26:26<39:22,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:58 | 200 |  144.685086ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6239/8417 [1:26:27<39:02,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:50:59 | 200 |  151.405299ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6240/8417 [1:26:28<39:00,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:01 | 200 |  180.369007ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6241/8417 [1:26:29<39:05,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:02 | 200 |  118.690568ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6242/8417 [1:26:31<38:21,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:03 | 200 |  183.324518ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6243/8417 [1:26:32<38:38,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:04 | 200 |  127.248116ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6244/8417 [1:26:33<37:44,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:05 | 200 |  141.583089ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6245/8417 [1:26:34<37:20,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:06 | 200 |  177.758173ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6246/8417 [1:26:35<37:22,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:07 | 200 |  143.342582ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6247/8417 [1:26:36<37:05,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:08 | 200 |  179.398081ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6248/8417 [1:26:37<37:19,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:09 | 200 |  176.641894ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6249/8417 [1:26:38<37:31,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:10 | 200 |  147.835869ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6250/8417 [1:26:39<37:22,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:11 | 200 |  144.094428ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6251/8417 [1:26:40<37:00,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:12 | 200 |  137.579632ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6252/8417 [1:26:41<36:40,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:13 | 200 |  141.288909ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6253/8417 [1:26:42<36:31,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:14 | 200 |  171.781748ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6254/8417 [1:26:43<37:01,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:15 | 200 |   116.88016ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6255/8417 [1:26:44<36:42,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:16 | 200 |  170.613413ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6256/8417 [1:26:45<36:56,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:17 | 200 |  179.583152ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6257/8417 [1:26:46<37:19,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:18 | 200 |  151.335713ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6258/8417 [1:26:47<37:15,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:19 | 200 |  147.452899ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6259/8417 [1:26:48<37:11,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:20 | 200 |  141.517086ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6260/8417 [1:26:49<36:57,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:21 | 200 |  163.992372ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6261/8417 [1:26:50<37:01,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:22 | 200 |  153.469586ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6262/8417 [1:26:51<36:56,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:23 | 200 |  176.252987ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6263/8417 [1:26:52<37:05,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:24 | 200 |  182.159716ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6264/8417 [1:26:53<37:18,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:25 | 200 |  153.389041ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6265/8417 [1:26:54<36:59,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:26 | 200 |  146.032406ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6266/8417 [1:26:55<36:58,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:27 | 200 |  112.125279ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6267/8417 [1:26:56<36:22,  1.01s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:28 | 200 |  182.537943ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6268/8417 [1:26:57<36:49,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:29 | 200 |  146.265521ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6269/8417 [1:26:58<36:39,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:30 | 200 |  145.959749ms |       127.0.0.1 | POST     "/api/chat"

 74%|███████▍  | 6270/8417 [1:26:59<37:24,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:31 | 200 |  179.308661ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6271/8417 [1:27:00<37:26,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:33 | 200 |  153.191045ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6272/8417 [1:27:01<37:08,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:34 | 200 |  142.112754ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6273/8417 [1:27:02<36:58,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:35 | 200 |  137.364302ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6274/8417 [1:27:03<37:01,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:36 | 200 |  176.733717ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6275/8417 [1:27:05<37:10,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:37 | 200 |  175.007227ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6276/8417 [1:27:06<37:17,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:38 | 200 |  151.191415ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6277/8417 [1:27:07<36:52,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:39 | 200 |  141.528794ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6278/8417 [1:27:08<36:32,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:40 | 200 |  178.800068ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6279/8417 [1:27:09<36:40,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:41 | 200 |  172.383436ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6280/8417 [1:27:10<37:07,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:42 | 200 |  179.532773ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6281/8417 [1:27:11<37:09,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:43 | 200 |  182.735702ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6282/8417 [1:27:12<37:20,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:44 | 200 |  118.110551ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6283/8417 [1:27:13<36:40,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:45 | 200 |  184.387798ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6284/8417 [1:27:14<36:50,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:46 | 200 |  146.090756ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6285/8417 [1:27:15<36:43,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:47 | 200 |  140.747255ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6286/8417 [1:27:16<37:08,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:48 | 200 |  174.957043ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6287/8417 [1:27:17<37:27,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:49 | 200 |  159.756368ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6288/8417 [1:27:18<37:38,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:50 | 200 |  119.692595ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6289/8417 [1:27:19<37:22,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:51 | 200 |   178.63554ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6290/8417 [1:27:20<37:23,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:52 | 200 |   179.88589ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6291/8417 [1:27:21<37:26,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:53 | 200 |  144.209628ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6292/8417 [1:27:22<37:15,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:54 | 200 |  139.783806ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6293/8417 [1:27:23<36:51,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:55 | 200 |  139.119015ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6294/8417 [1:27:24<36:47,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:57 | 200 |  177.882675ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6295/8417 [1:27:25<37:05,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:58 | 200 |  168.309418ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6296/8417 [1:27:26<36:59,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:51:59 | 200 |  147.563634ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6297/8417 [1:27:28<36:51,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:00 | 200 |  148.850338ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6298/8417 [1:27:29<36:53,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:01 | 200 |  175.994427ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6299/8417 [1:27:30<37:00,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:02 | 200 |  146.111081ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6300/8417 [1:27:31<36:56,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:03 | 200 |  191.420227ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6301/8417 [1:27:32<37:33,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:04 | 200 |  146.164111ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6302/8417 [1:27:33<37:31,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:05 | 200 |  169.025446ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6303/8417 [1:27:34<37:27,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:06 | 200 |  149.648834ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6304/8417 [1:27:35<37:04,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:07 | 200 |  118.738241ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6305/8417 [1:27:36<36:21,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:08 | 200 |  176.850964ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6306/8417 [1:27:37<36:37,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:09 | 200 |  146.204555ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6307/8417 [1:27:38<36:22,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:10 | 200 |  176.185755ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6308/8417 [1:27:39<36:52,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:11 | 200 |  177.448983ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6309/8417 [1:27:40<36:58,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:12 | 200 |  144.611354ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6310/8417 [1:27:41<36:37,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:13 | 200 |  179.717354ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6311/8417 [1:27:42<36:51,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:14 | 200 |  158.090086ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▍  | 6312/8417 [1:27:43<36:47,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:15 | 200 |  171.598534ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6313/8417 [1:27:44<36:58,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:16 | 200 |   156.65444ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6314/8417 [1:27:45<36:50,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:18 | 200 |  140.961406ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6315/8417 [1:27:46<36:40,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:19 | 200 |  134.225958ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6316/8417 [1:27:47<36:19,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:20 | 200 |  139.460342ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6317/8417 [1:27:48<36:15,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:21 | 200 |  187.195925ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6318/8417 [1:27:50<36:38,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:22 | 200 |   129.99688ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6319/8417 [1:27:51<36:08,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:23 | 200 |  141.737473ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6320/8417 [1:27:52<36:23,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:24 | 200 |  170.548142ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6321/8417 [1:27:53<36:31,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:25 | 200 |  152.172455ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6322/8417 [1:27:54<36:21,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:26 | 200 |  176.924726ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6323/8417 [1:27:55<36:36,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:27 | 200 |  152.554719ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6324/8417 [1:27:56<36:20,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:28 | 200 |  148.494628ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6325/8417 [1:27:57<36:09,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:29 | 200 |    141.0962ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6326/8417 [1:27:58<35:58,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:30 | 200 |   119.50861ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6327/8417 [1:27:59<35:38,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:31 | 200 |  168.350257ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6328/8417 [1:28:00<36:07,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:32 | 200 |  165.894894ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6329/8417 [1:28:01<36:00,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:33 | 200 |  176.046312ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6330/8417 [1:28:02<36:18,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:34 | 200 |  154.022091ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6331/8417 [1:28:03<36:57,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:35 | 200 |  149.710387ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6332/8417 [1:28:04<36:45,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:36 | 200 |  140.151958ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6333/8417 [1:28:05<36:24,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:37 | 200 |  180.273013ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6334/8417 [1:28:06<36:54,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:38 | 200 |  142.446971ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6335/8417 [1:28:07<36:33,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:39 | 200 |  182.784153ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6336/8417 [1:28:08<36:38,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:41 | 200 |  181.501288ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6337/8417 [1:28:09<36:58,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:42 | 200 |  141.514396ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6338/8417 [1:28:10<36:30,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:43 | 200 |  141.334109ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6339/8417 [1:28:12<36:13,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:44 | 200 |   178.91918ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6340/8417 [1:28:13<36:37,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:45 | 200 |  140.398215ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6341/8417 [1:28:14<36:16,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:46 | 200 |  172.260198ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6342/8417 [1:28:15<36:15,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:47 | 200 |  153.511705ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6343/8417 [1:28:16<36:07,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:48 | 200 |  139.775892ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6344/8417 [1:28:17<35:51,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:49 | 200 |  184.614799ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6345/8417 [1:28:18<36:14,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:50 | 200 |  180.186875ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6346/8417 [1:28:19<36:23,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:51 | 200 |  143.790328ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6347/8417 [1:28:20<36:10,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:52 | 200 |  141.778043ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6348/8417 [1:28:21<36:01,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:53 | 200 |  176.388961ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6349/8417 [1:28:22<36:15,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:54 | 200 |  177.470192ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6350/8417 [1:28:23<36:37,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:55 | 200 |  149.493613ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6351/8417 [1:28:24<36:13,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:56 | 200 |  138.815935ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6352/8417 [1:28:25<36:05,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:57 | 200 |   178.10125ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6353/8417 [1:28:26<36:15,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:58 | 200 |  134.956347ms |       127.0.0.1 | POST     "/api/chat"

 75%|███████▌  | 6354/8417 [1:28:27<36:07,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:52:59 | 200 |  141.776553ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6355/8417 [1:28:28<35:42,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:00 | 200 |  182.648282ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6356/8417 [1:28:29<36:12,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:02 | 200 |  141.610345ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6357/8417 [1:28:30<36:08,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:03 | 200 |  178.466561ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6358/8417 [1:28:31<36:17,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:04 | 200 |   146.17849ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6359/8417 [1:28:33<36:02,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:05 | 200 |  137.385786ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6360/8417 [1:28:34<35:57,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:06 | 200 |  156.785811ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6361/8417 [1:28:35<36:22,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:07 | 200 |  196.057244ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6362/8417 [1:28:36<36:43,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:08 | 200 |   148.50026ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6363/8417 [1:28:37<36:16,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:09 | 200 |  146.546519ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6364/8417 [1:28:38<36:13,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:10 | 200 |  181.488834ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6365/8417 [1:28:39<37:02,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:11 | 200 |  145.994283ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6366/8417 [1:28:40<36:28,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:12 | 200 |  177.165554ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6367/8417 [1:28:41<36:18,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:13 | 200 |  143.018698ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6368/8417 [1:28:42<36:14,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:14 | 200 |  175.202713ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6369/8417 [1:28:43<36:22,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:15 | 200 |  147.483365ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6370/8417 [1:28:44<36:11,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:16 | 200 |  177.767894ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6371/8417 [1:28:45<36:44,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:18 | 200 |   150.43215ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6372/8417 [1:28:46<36:30,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:19 | 200 |  177.460114ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6373/8417 [1:28:48<36:34,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:20 | 200 |  178.751872ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6374/8417 [1:28:49<36:23,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:21 | 200 |  145.850638ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6375/8417 [1:28:50<35:51,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:22 | 200 |  137.464556ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6376/8417 [1:28:51<35:19,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:23 | 200 |  173.775874ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6377/8417 [1:28:52<35:29,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:24 | 200 |  142.083974ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6378/8417 [1:28:53<35:07,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:25 | 200 |  179.378351ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6379/8417 [1:28:54<35:19,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:26 | 200 |  177.637924ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6380/8417 [1:28:55<35:31,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:27 | 200 |  146.085747ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6381/8417 [1:28:56<35:21,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:28 | 200 |  143.751978ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6382/8417 [1:28:57<35:12,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:29 | 200 |  140.367579ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6383/8417 [1:28:58<34:56,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:30 | 200 |  174.504567ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6384/8417 [1:28:59<35:28,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:31 | 200 |  143.217562ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6385/8417 [1:29:00<35:19,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:32 | 200 |  177.488779ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6386/8417 [1:29:01<35:25,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:33 | 200 |  145.309879ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6387/8417 [1:29:02<35:07,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:34 | 200 |  143.369892ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6388/8417 [1:29:03<34:59,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:35 | 200 |  138.578592ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6389/8417 [1:29:04<34:43,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:36 | 200 |   171.96594ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6390/8417 [1:29:05<34:55,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 76%|███████▌  | 6391/8417 [1:29:06<35:28,  1.05s/it]

[GIN] 2025/06/27 - 00:53:37 | 200 |  188.855983ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:38 | 200 |  148.869435ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6392/8417 [1:29:07<35:10,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:39 | 200 |   142.48376ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6393/8417 [1:29:08<34:55,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:40 | 200 |  139.657829ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6394/8417 [1:29:09<35:09,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:41 | 200 |  174.595398ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6395/8417 [1:29:10<35:18,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:43 | 200 |   182.14907ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6396/8417 [1:29:11<35:20,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:44 | 200 |  147.056203ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6397/8417 [1:29:12<35:16,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:45 | 200 |  120.620943ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6398/8417 [1:29:13<34:50,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:46 | 200 |  176.431941ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6399/8417 [1:29:15<35:25,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:47 | 200 |  181.904056ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6400/8417 [1:29:16<35:36,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:48 | 200 |  151.330911ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6401/8417 [1:29:17<35:33,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:49 | 200 |  140.130304ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6402/8417 [1:29:18<35:05,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:50 | 200 |  178.512558ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6403/8417 [1:29:19<35:35,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:51 | 200 |  176.393106ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6404/8417 [1:29:20<35:41,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:52 | 200 |  154.891937ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6405/8417 [1:29:21<35:31,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:53 | 200 |   146.07499ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6406/8417 [1:29:22<35:12,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:54 | 200 |  175.589956ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6407/8417 [1:29:23<35:20,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:55 | 200 |  178.693486ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6408/8417 [1:29:24<35:28,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:56 | 200 |  147.435106ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6409/8417 [1:29:25<35:12,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:57 | 200 |  137.233898ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6410/8417 [1:29:26<34:55,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:58 | 200 |  177.054724ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6411/8417 [1:29:27<35:07,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:53:59 | 200 |  137.403717ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6412/8417 [1:29:28<34:45,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:00 | 200 |   177.93267ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6413/8417 [1:29:29<35:13,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:01 | 200 |  142.279988ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6414/8417 [1:29:30<34:54,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:02 | 200 |  139.339736ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6415/8417 [1:29:31<34:36,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:04 | 200 |  180.401678ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6416/8417 [1:29:32<35:01,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:05 | 200 |  168.707247ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▌  | 6417/8417 [1:29:34<35:09,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:06 | 200 |  149.520816ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6418/8417 [1:29:35<34:46,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:07 | 200 |  114.356071ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6419/8417 [1:29:36<34:07,  1.02s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:08 | 200 |  144.251537ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6420/8417 [1:29:37<34:19,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:09 | 200 |  161.203485ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6421/8417 [1:29:38<35:00,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:10 | 200 |  173.424804ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6422/8417 [1:29:39<35:07,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:11 | 200 |  145.883343ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6423/8417 [1:29:40<35:05,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:12 | 200 |  134.202869ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6424/8417 [1:29:41<34:48,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:13 | 200 |   177.50005ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6425/8417 [1:29:42<34:56,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:14 | 200 |  178.220149ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6426/8417 [1:29:43<34:57,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:15 | 200 |  145.604405ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6427/8417 [1:29:44<34:44,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:16 | 200 |  115.527321ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6428/8417 [1:29:45<34:16,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:17 | 200 |  140.110072ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6429/8417 [1:29:46<34:08,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:18 | 200 |  173.569811ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6430/8417 [1:29:47<34:42,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:19 | 200 |  177.403843ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6431/8417 [1:29:48<34:50,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:20 | 200 |   148.90103ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6432/8417 [1:29:49<35:01,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:21 | 200 |  144.739569ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6433/8417 [1:29:50<34:33,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:22 | 200 |  143.380822ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6434/8417 [1:29:51<34:27,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:23 | 200 |  184.795525ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6435/8417 [1:29:52<34:38,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:24 | 200 |  168.477964ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6436/8417 [1:29:53<34:48,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:26 | 200 |  150.474716ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6437/8417 [1:29:54<34:39,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:27 | 200 |  142.604642ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6438/8417 [1:29:55<34:26,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:28 | 200 |  166.486684ms |       127.0.0.1 | POST     "/api/chat"

 76%|███████▋  | 6439/8417 [1:29:57<34:38,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:29 | 200 |  182.992874ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6440/8417 [1:29:58<34:43,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:30 | 200 |  148.882709ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6441/8417 [1:29:59<34:41,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:31 | 200 |  152.192907ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6442/8417 [1:30:00<35:09,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:32 | 200 |  177.227015ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6443/8417 [1:30:01<35:12,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:33 | 200 |  118.523886ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6444/8417 [1:30:02<34:33,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:34 | 200 |  185.150234ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6445/8417 [1:30:03<34:37,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:35 | 200 |  120.700887ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6446/8417 [1:30:04<33:59,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:36 | 200 |  181.844543ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6447/8417 [1:30:05<34:35,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:37 | 200 |  182.186466ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6448/8417 [1:30:06<34:44,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:38 | 200 |   145.79359ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6449/8417 [1:30:07<34:35,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:39 | 200 |  144.215353ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6450/8417 [1:30:08<34:37,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:40 | 200 |  144.321239ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6451/8417 [1:30:09<35:02,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:41 | 200 |  188.678439ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6452/8417 [1:30:10<35:16,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:43 | 200 |  160.493129ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6453/8417 [1:30:11<35:16,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:44 | 200 |  145.957553ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6454/8417 [1:30:12<34:54,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:45 | 200 |  144.606464ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6455/8417 [1:30:14<34:53,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:46 | 200 |  177.202891ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6456/8417 [1:30:15<34:58,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:47 | 200 |  175.786587ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6457/8417 [1:30:16<35:02,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:48 | 200 |  132.745185ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6458/8417 [1:30:17<35:03,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:49 | 200 |  182.331744ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6459/8417 [1:30:18<35:03,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:50 | 200 |  161.628485ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6460/8417 [1:30:19<35:01,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:51 | 200 |  144.088725ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6461/8417 [1:30:20<34:35,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:52 | 200 |  141.819479ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6462/8417 [1:30:21<34:30,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:53 | 200 |    178.6392ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6463/8417 [1:30:22<34:41,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:54 | 200 |  138.422923ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6464/8417 [1:30:23<34:29,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:55 | 200 |  171.494431ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6465/8417 [1:30:24<34:21,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:56 | 200 |  159.507119ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6466/8417 [1:30:25<34:27,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:57 | 200 |  181.926427ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6467/8417 [1:30:26<34:52,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:54:58 | 200 |  147.086218ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6468/8417 [1:30:27<34:40,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:00 | 200 |  180.960939ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6469/8417 [1:30:28<34:46,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:01 | 200 |  165.914545ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6470/8417 [1:30:30<34:53,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:02 | 200 |  141.097184ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6471/8417 [1:30:31<34:31,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:03 | 200 |  180.876196ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6472/8417 [1:30:32<35:00,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:04 | 200 |  143.536971ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6473/8417 [1:30:33<34:41,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:05 | 200 |  146.975249ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6474/8417 [1:30:34<34:32,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:06 | 200 |  179.304518ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6475/8417 [1:30:35<34:41,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:07 | 200 |  141.577915ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6476/8417 [1:30:36<34:15,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:08 | 200 |  150.591694ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6477/8417 [1:30:37<34:23,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:09 | 200 |  141.683847ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6478/8417 [1:30:38<34:28,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:10 | 200 |  180.859375ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6479/8417 [1:30:39<34:53,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:11 | 200 |  150.356457ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6480/8417 [1:30:40<35:07,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:13 | 200 |  187.214459ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6481/8417 [1:30:41<35:37,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:14 | 200 |  143.702134ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6482/8417 [1:30:42<34:56,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:15 | 200 |  139.617385ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6483/8417 [1:30:44<34:49,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:16 | 200 |  184.418355ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6484/8417 [1:30:45<34:52,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:17 | 200 |  148.270654ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6485/8417 [1:30:46<34:44,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:18 | 200 |  184.516515ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6486/8417 [1:30:47<34:57,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:19 | 200 |  144.074476ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6487/8417 [1:30:48<34:33,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:20 | 200 |  176.938724ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6488/8417 [1:30:49<34:50,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:21 | 200 |  153.868947ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6489/8417 [1:30:50<34:13,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:22 | 200 |  143.161908ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6490/8417 [1:30:51<35:09,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:23 | 200 |  144.307912ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6491/8417 [1:30:52<35:05,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:24 | 200 |  166.243798ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6492/8417 [1:30:53<34:36,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:25 | 200 |  169.112242ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6493/8417 [1:30:54<34:18,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:26 | 200 |  183.672867ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6494/8417 [1:30:55<34:11,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:28 | 200 |  147.539673ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6495/8417 [1:30:56<33:48,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:29 | 200 |   140.21957ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6496/8417 [1:30:57<33:29,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:30 | 200 |  170.037721ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6497/8417 [1:30:59<33:34,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:31 | 200 |  156.691272ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6498/8417 [1:31:00<33:34,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:32 | 200 |  179.857107ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6499/8417 [1:31:01<33:47,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:33 | 200 |  146.813719ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6500/8417 [1:31:02<33:32,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:34 | 200 |  145.334074ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6501/8417 [1:31:03<33:17,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:35 | 200 |  173.601543ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6502/8417 [1:31:04<33:28,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:36 | 200 |  168.069882ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6503/8417 [1:31:05<33:37,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:37 | 200 |  149.856272ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6504/8417 [1:31:06<33:25,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:38 | 200 |  139.640584ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6505/8417 [1:31:07<33:05,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:39 | 200 |  133.585488ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6506/8417 [1:31:08<32:50,  1.03s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:40 | 200 |  138.320734ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6507/8417 [1:31:09<33:05,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:41 | 200 |  139.930998ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6508/8417 [1:31:10<33:03,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:42 | 200 |  142.431582ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6509/8417 [1:31:11<33:03,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:43 | 200 |  181.081324ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6510/8417 [1:31:12<33:45,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:44 | 200 |  168.762372ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6511/8417 [1:31:13<34:43,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:45 | 200 |  143.702344ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6512/8417 [1:31:14<34:05,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:46 | 200 |  171.349314ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6513/8417 [1:31:15<34:01,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:48 | 200 |  177.546876ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6514/8417 [1:31:17<34:37,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:49 | 200 |  148.459649ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6515/8417 [1:31:18<34:05,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:50 | 200 |  177.219059ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6516/8417 [1:31:19<34:26,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:51 | 200 |  157.206079ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6517/8417 [1:31:20<34:12,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:52 | 200 |  151.909124ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6518/8417 [1:31:21<33:58,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:53 | 200 |  179.731072ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6519/8417 [1:31:22<33:54,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:54 | 200 |  144.379545ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6520/8417 [1:31:23<33:23,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:55 | 200 |  143.652273ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6521/8417 [1:31:24<33:12,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:56 | 200 |  171.670214ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6522/8417 [1:31:25<33:17,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:57 | 200 |  184.650461ms |       127.0.0.1 | POST     "/api/chat"

 77%|███████▋  | 6523/8417 [1:31:26<33:24,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:58 | 200 |   149.62375ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6524/8417 [1:31:27<33:15,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:55:59 | 200 |   116.46979ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6525/8417 [1:31:28<32:45,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:00 | 200 |  174.899258ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6526/8417 [1:31:29<33:21,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:01 | 200 |  170.784701ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6527/8417 [1:31:30<33:13,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:02 | 200 |  149.721798ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6528/8417 [1:31:31<33:08,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:03 | 200 |  148.299143ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6529/8417 [1:31:32<33:02,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:04 | 200 |  139.252212ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6530/8417 [1:31:33<32:53,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:06 | 200 |  184.770164ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6531/8417 [1:31:34<33:18,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:07 | 200 |  135.035252ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6532/8417 [1:31:36<32:59,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:08 | 200 |  152.715498ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6533/8417 [1:31:37<32:55,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:09 | 200 |  160.192493ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6534/8417 [1:31:38<32:46,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:10 | 200 |  122.281966ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6535/8417 [1:31:39<32:54,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:11 | 200 |  200.246669ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6536/8417 [1:31:40<33:25,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:12 | 200 |  142.924097ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6537/8417 [1:31:41<33:16,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:13 | 200 |    141.8922ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6538/8417 [1:31:42<33:03,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:14 | 200 |  181.562548ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6539/8417 [1:31:43<33:13,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:15 | 200 |  148.774697ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6540/8417 [1:31:44<33:31,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:16 | 200 |  149.231867ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6541/8417 [1:31:45<33:22,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:17 | 200 |   187.99797ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6542/8417 [1:31:46<33:24,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:18 | 200 |  145.038318ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6543/8417 [1:31:47<33:08,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:19 | 200 |  142.269271ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6544/8417 [1:31:48<33:03,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:20 | 200 |  174.601668ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6545/8417 [1:31:49<33:26,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:21 | 200 |  139.294638ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6546/8417 [1:31:50<33:05,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:23 | 200 |  179.664346ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6547/8417 [1:31:51<33:23,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:24 | 200 |  154.717852ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6548/8417 [1:31:53<33:12,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:25 | 200 |  162.323676ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6549/8417 [1:31:54<33:23,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:26 | 200 |  144.016376ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6550/8417 [1:31:55<33:02,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:27 | 200 |  181.073625ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6551/8417 [1:31:56<33:10,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:28 | 200 |  139.054228ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6552/8417 [1:31:57<32:55,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:29 | 200 |  141.673652ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6553/8417 [1:31:58<32:34,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:30 | 200 |  179.868283ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6554/8417 [1:31:59<32:53,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:31 | 200 |  144.800391ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6555/8417 [1:32:00<32:39,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:32 | 200 |  181.475029ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6556/8417 [1:32:01<32:45,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:33 | 200 |  150.615163ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6557/8417 [1:32:02<32:42,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:34 | 200 |  144.869584ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6558/8417 [1:32:03<32:26,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:35 | 200 |  142.980607ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6559/8417 [1:32:04<32:25,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:36 | 200 |  181.358898ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6560/8417 [1:32:05<32:32,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:37 | 200 |  168.486702ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6561/8417 [1:32:06<32:35,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:38 | 200 |   142.70033ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6562/8417 [1:32:07<32:17,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:39 | 200 |  133.743523ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6563/8417 [1:32:08<32:06,  1.04s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:40 | 200 |   179.67317ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6564/8417 [1:32:09<32:43,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:42 | 200 |  178.142072ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6565/8417 [1:32:10<32:50,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:43 | 200 |  144.341072ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6566/8417 [1:32:12<32:37,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:44 | 200 |  143.644894ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6567/8417 [1:32:13<32:31,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:45 | 200 |  178.898825ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6568/8417 [1:32:14<32:56,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:46 | 200 |  142.161153ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6569/8417 [1:32:15<32:40,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:47 | 200 |  146.410847ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6570/8417 [1:32:16<32:40,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:48 | 200 |  196.280809ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6571/8417 [1:32:17<32:58,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:49 | 200 |  151.070755ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6572/8417 [1:32:18<32:41,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:50 | 200 |  141.685845ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6573/8417 [1:32:19<32:48,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:51 | 200 |  177.951281ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6574/8417 [1:32:20<32:48,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:52 | 200 |  149.782117ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6575/8417 [1:32:21<32:32,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:53 | 200 |  137.699964ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6576/8417 [1:32:22<32:19,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:54 | 200 |  166.288902ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6577/8417 [1:32:23<32:21,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:55 | 200 |   175.63621ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6578/8417 [1:32:24<32:34,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:56 | 200 |  146.820664ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6579/8417 [1:32:25<32:19,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:57 | 200 |  138.331222ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6580/8417 [1:32:26<32:04,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:56:59 | 200 |  177.937297ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6581/8417 [1:32:27<32:22,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:00 | 200 |  180.456768ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6582/8417 [1:32:29<32:55,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:01 | 200 |  155.966436ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6583/8417 [1:32:30<32:47,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:02 | 200 |  178.667597ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6584/8417 [1:32:31<33:00,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:03 | 200 |  145.299096ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6585/8417 [1:32:32<32:44,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:04 | 200 |  143.412836ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6586/8417 [1:32:33<32:35,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:05 | 200 |  177.190287ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6587/8417 [1:32:34<32:34,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:06 | 200 |  150.668041ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6588/8417 [1:32:35<32:18,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:07 | 200 |  138.796743ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6589/8417 [1:32:36<32:17,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:08 | 200 |  179.086003ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6590/8417 [1:32:37<32:45,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:09 | 200 |  131.673254ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6591/8417 [1:32:38<32:16,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:10 | 200 |  176.087179ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6592/8417 [1:32:39<33:00,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:11 | 200 |  176.939854ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6593/8417 [1:32:40<33:09,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:12 | 200 |  145.537506ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6594/8417 [1:32:41<32:59,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:14 | 200 |  179.487848ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6595/8417 [1:32:43<32:54,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:15 | 200 |  151.034377ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6596/8417 [1:32:44<32:43,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:16 | 200 |  138.984532ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6597/8417 [1:32:45<32:30,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:17 | 200 |  180.363352ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6598/8417 [1:32:46<32:41,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:18 | 200 |  149.487657ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6599/8417 [1:32:47<33:03,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:19 | 200 |  143.039344ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6600/8417 [1:32:48<33:06,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:20 | 200 |  169.721956ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6601/8417 [1:32:49<33:18,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:21 | 200 |  153.407464ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6602/8417 [1:32:50<33:00,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:22 | 200 |   140.45942ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6603/8417 [1:32:51<32:35,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:23 | 200 |  142.085458ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6604/8417 [1:32:52<32:16,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:24 | 200 |  180.783154ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6605/8417 [1:32:53<32:47,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:26 | 200 |  156.399142ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6606/8417 [1:32:54<33:05,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:27 | 200 |  143.648876ms |       127.0.0.1 | POST     "/api/chat"

 78%|███████▊  | 6607/8417 [1:32:56<33:02,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:28 | 200 |  168.549292ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6608/8417 [1:32:57<32:46,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:29 | 200 |  152.070867ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6609/8417 [1:32:58<32:17,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:30 | 200 |  170.810734ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6610/8417 [1:32:59<32:18,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:31 | 200 |  183.199052ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6611/8417 [1:33:00<32:22,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:32 | 200 |  141.788447ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6612/8417 [1:33:01<32:00,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:33 | 200 |  179.350163ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6613/8417 [1:33:02<31:59,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:34 | 200 |  150.345537ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6614/8417 [1:33:03<32:09,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:35 | 200 |  178.163381ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6615/8417 [1:33:04<32:26,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:36 | 200 |  175.763505ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6616/8417 [1:33:05<32:32,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:37 | 200 |  147.221323ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6617/8417 [1:33:06<32:02,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:38 | 200 |  141.803104ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6618/8417 [1:33:07<31:36,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:39 | 200 |  116.367421ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6619/8417 [1:33:08<31:25,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:40 | 200 |  173.842453ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6620/8417 [1:33:09<32:01,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:42 | 200 |  163.781671ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6621/8417 [1:33:10<31:56,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:43 | 200 |  139.984238ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6622/8417 [1:33:12<31:41,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:44 | 200 |  141.058954ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6623/8417 [1:33:13<31:35,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:45 | 200 |  141.191957ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6624/8417 [1:33:14<31:45,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:46 | 200 |  175.579314ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6625/8417 [1:33:15<31:52,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:47 | 200 |  151.565854ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6626/8417 [1:33:16<31:39,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:48 | 200 |  177.380112ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6627/8417 [1:33:17<32:03,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:49 | 200 |  153.216932ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▊  | 6628/8417 [1:33:18<31:53,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:50 | 200 |  169.174021ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6629/8417 [1:33:19<32:36,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:51 | 200 |  153.825496ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6630/8417 [1:33:20<32:22,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:52 | 200 |  168.194026ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6631/8417 [1:33:21<32:07,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:53 | 200 |  161.819717ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6632/8417 [1:33:22<31:58,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:54 | 200 |   143.37671ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6633/8417 [1:33:23<31:45,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:55 | 200 |  142.639338ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6634/8417 [1:33:24<31:35,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:57 | 200 |   176.18454ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6635/8417 [1:33:25<31:50,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:58 | 200 |  145.990265ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6636/8417 [1:33:27<31:52,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:57:59 | 200 |  140.689614ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6637/8417 [1:33:28<31:23,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:00 | 200 |  180.911743ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6638/8417 [1:33:29<31:29,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:01 | 200 |  175.366585ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6639/8417 [1:33:30<31:41,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:02 | 200 |  112.965871ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6640/8417 [1:33:31<31:04,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:03 | 200 |  168.974559ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6641/8417 [1:33:32<31:26,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:04 | 200 |  175.060733ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6642/8417 [1:33:33<31:42,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:05 | 200 |  150.207665ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6643/8417 [1:33:34<31:33,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:06 | 200 |  177.851561ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6644/8417 [1:33:35<31:27,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:07 | 200 |  178.007998ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6645/8417 [1:33:36<31:24,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:08 | 200 |  147.924258ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6646/8417 [1:33:37<31:37,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:09 | 200 |  139.256832ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6647/8417 [1:33:38<31:28,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:10 | 200 |  175.744289ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6648/8417 [1:33:39<31:41,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:11 | 200 |  144.935989ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6649/8417 [1:33:40<31:25,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:13 | 200 |  146.073113ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6650/8417 [1:33:41<31:11,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:14 | 200 |  181.478479ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6651/8417 [1:33:42<31:12,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:15 | 200 |  154.899012ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6652/8417 [1:33:44<31:11,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:16 | 200 |  148.473755ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6653/8417 [1:33:45<30:59,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:17 | 200 |  139.397918ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6654/8417 [1:33:46<31:03,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:18 | 200 |  180.657688ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6655/8417 [1:33:47<31:11,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:19 | 200 |   145.55931ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6656/8417 [1:33:48<31:03,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:20 | 200 |  139.909267ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6657/8417 [1:33:49<31:03,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:21 | 200 |  179.072706ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6658/8417 [1:33:50<31:38,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:22 | 200 |  178.156966ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6659/8417 [1:33:51<31:55,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:23 | 200 |  136.626209ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6660/8417 [1:33:52<31:33,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:24 | 200 |  179.444386ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6661/8417 [1:33:53<31:49,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:25 | 200 |   143.15193ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6662/8417 [1:33:54<31:25,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:26 | 200 |  174.866247ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6663/8417 [1:33:55<31:14,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:27 | 200 |  124.342499ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6664/8417 [1:33:56<30:41,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:29 | 200 |    180.3991ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6665/8417 [1:33:57<31:04,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:30 | 200 |  147.035091ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6666/8417 [1:33:59<31:06,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:31 | 200 |  186.579206ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6667/8417 [1:34:00<31:28,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:32 | 200 |  115.739611ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6668/8417 [1:34:01<31:05,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:33 | 200 |  183.152461ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6669/8417 [1:34:02<31:25,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:34 | 200 |   176.67918ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6670/8417 [1:34:03<31:34,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:35 | 200 |  137.296938ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6671/8417 [1:34:04<31:06,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:36 | 200 |  179.850476ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6672/8417 [1:34:05<31:10,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:37 | 200 |  151.407162ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6673/8417 [1:34:06<31:00,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:38 | 200 |  136.128229ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6674/8417 [1:34:07<30:39,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:39 | 200 |  173.865445ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6675/8417 [1:34:08<30:44,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:40 | 200 |  177.209484ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6676/8417 [1:34:09<31:06,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:41 | 200 |  147.740037ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6677/8417 [1:34:10<30:58,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:42 | 200 |   176.11738ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6678/8417 [1:34:11<31:03,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:44 | 200 |  176.279105ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6679/8417 [1:34:12<31:12,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:45 | 200 |  144.164995ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6680/8417 [1:34:14<31:11,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:46 | 200 |  178.153541ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6681/8417 [1:34:15<31:18,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:47 | 200 |   140.99322ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6682/8417 [1:34:16<30:59,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:48 | 200 |  138.009723ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6683/8417 [1:34:17<30:49,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:49 | 200 |  181.056992ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6684/8417 [1:34:18<31:14,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:50 | 200 |  146.203771ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6685/8417 [1:34:19<31:16,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:51 | 200 |   143.37138ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6686/8417 [1:34:20<31:05,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:52 | 200 |   171.33604ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6687/8417 [1:34:21<31:24,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:53 | 200 |  169.611663ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6688/8417 [1:34:22<31:24,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:54 | 200 |  178.563249ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6689/8417 [1:34:23<31:22,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:55 | 200 |  146.297164ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6690/8417 [1:34:24<31:11,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:57 | 200 |  137.830263ms |       127.0.0.1 | POST     "/api/chat"

 79%|███████▉  | 6691/8417 [1:34:25<30:59,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:58 | 200 |  145.690439ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6692/8417 [1:34:26<30:44,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:58:59 | 200 |  176.657054ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6693/8417 [1:34:28<30:53,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:00 | 200 |  174.468894ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6694/8417 [1:34:29<31:15,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:01 | 200 |  139.755142ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6695/8417 [1:34:30<31:22,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:02 | 200 |  180.286633ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6696/8417 [1:34:31<31:34,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:03 | 200 |  142.999136ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6697/8417 [1:34:32<31:04,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:04 | 200 |  174.934727ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6698/8417 [1:34:33<31:06,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:05 | 200 |  180.566545ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6699/8417 [1:34:34<31:46,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:06 | 200 |  171.039073ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6700/8417 [1:34:35<31:29,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:07 | 200 |  144.401097ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6701/8417 [1:34:36<31:11,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:08 | 200 |  141.231731ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6702/8417 [1:34:37<30:43,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:10 | 200 |  177.249118ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6703/8417 [1:34:38<30:42,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:11 | 200 |  136.855054ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6704/8417 [1:34:40<30:41,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:12 | 200 |  176.562612ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6705/8417 [1:34:41<30:44,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:13 | 200 |  176.937482ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6706/8417 [1:34:42<30:43,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:14 | 200 |  119.283524ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6707/8417 [1:34:43<30:08,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:15 | 200 |   179.34102ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6708/8417 [1:34:44<30:11,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:16 | 200 |  137.503757ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6709/8417 [1:34:45<29:57,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:17 | 200 |  178.623466ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6710/8417 [1:34:46<30:12,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:18 | 200 |  159.347411ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6711/8417 [1:34:47<30:09,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:19 | 200 |  146.670426ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6712/8417 [1:34:48<30:05,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:20 | 200 |  144.394593ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6713/8417 [1:34:49<30:16,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:21 | 200 |  185.252533ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6714/8417 [1:34:50<30:34,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:22 | 200 |  144.232834ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6715/8417 [1:34:51<30:16,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:23 | 200 |  137.663476ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6716/8417 [1:34:52<30:08,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:25 | 200 |  205.697612ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6717/8417 [1:34:53<31:01,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:26 | 200 |  167.291901ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6718/8417 [1:34:55<30:45,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:27 | 200 |  149.105335ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6719/8417 [1:34:56<30:34,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:28 | 200 |  139.420935ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6720/8417 [1:34:57<30:12,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:29 | 200 |  181.359463ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6721/8417 [1:34:58<30:20,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:30 | 200 |  171.635942ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6722/8417 [1:34:59<30:43,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:31 | 200 |  140.672998ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6723/8417 [1:35:00<30:26,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:32 | 200 |  180.066544ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6724/8417 [1:35:01<30:30,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:33 | 200 |  142.829413ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6725/8417 [1:35:02<29:58,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:34 | 200 |  141.695832ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6726/8417 [1:35:03<29:59,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:35 | 200 |  172.817986ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6727/8417 [1:35:04<30:12,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:36 | 200 |  124.553636ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6728/8417 [1:35:05<29:53,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:37 | 200 |  171.837278ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6729/8417 [1:35:06<29:59,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:38 | 200 |  125.279618ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6730/8417 [1:35:07<29:38,  1.05s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:39 | 200 |  180.023864ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6731/8417 [1:35:08<29:58,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:41 | 200 |   141.33545ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6732/8417 [1:35:09<29:50,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:42 | 200 |  139.354798ms |       127.0.0.1 | POST     "/api/chat"

 80%|███████▉  | 6733/8417 [1:35:11<29:38,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:43 | 200 |  179.717798ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6734/8417 [1:35:12<29:49,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:44 | 200 |  163.194255ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6735/8417 [1:35:13<29:48,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:45 | 200 |  145.588771ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6736/8417 [1:35:14<29:49,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:46 | 200 |  171.016166ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6737/8417 [1:35:15<29:50,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:47 | 200 |  178.620854ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6738/8417 [1:35:16<30:11,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:48 | 200 |  145.133161ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6739/8417 [1:35:17<29:58,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:49 | 200 |  176.538496ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6740/8417 [1:35:18<30:01,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:50 | 200 |  150.672561ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6741/8417 [1:35:19<29:55,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:51 | 200 |  141.171257ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6742/8417 [1:35:20<29:51,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:52 | 200 |  177.162174ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6743/8417 [1:35:21<30:08,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:53 | 200 |  147.509763ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6744/8417 [1:35:22<30:09,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:54 | 200 |   120.24129ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6745/8417 [1:35:23<30:12,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:56 | 200 |  177.461262ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6746/8417 [1:35:25<30:40,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:57 | 200 |  152.096672ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6747/8417 [1:35:26<30:24,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:58 | 200 |  175.711616ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6748/8417 [1:35:27<30:13,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 00:59:59 | 200 |  140.421349ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6749/8417 [1:35:28<30:28,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:00 | 200 |  174.895345ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6750/8417 [1:35:29<30:34,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:01 | 200 |  141.054653ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6751/8417 [1:35:30<29:58,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:02 | 200 |  179.071984ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6752/8417 [1:35:31<30:06,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:03 | 200 |  149.019857ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6753/8417 [1:35:32<29:57,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:04 | 200 |  141.211834ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6754/8417 [1:35:33<29:50,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:05 | 200 |  179.367408ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6755/8417 [1:35:34<29:58,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:06 | 200 |  145.165257ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6756/8417 [1:35:35<29:39,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:08 | 200 |  142.974507ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6757/8417 [1:35:37<30:30,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:09 | 200 |  172.567487ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6758/8417 [1:35:38<30:15,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:10 | 200 |  171.636232ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6759/8417 [1:35:39<30:08,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:11 | 200 |  120.026755ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6760/8417 [1:35:40<29:54,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:12 | 200 |  177.170749ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6761/8417 [1:35:41<29:49,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:13 | 200 |  180.628302ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6762/8417 [1:35:42<29:49,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:14 | 200 |  143.568217ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6763/8417 [1:35:43<29:36,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:15 | 200 |  141.553737ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6764/8417 [1:35:44<30:05,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:16 | 200 |  174.928149ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6765/8417 [1:35:45<30:03,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:17 | 200 |   136.69188ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6766/8417 [1:35:46<29:36,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:18 | 200 |  178.928452ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6767/8417 [1:35:47<30:07,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:20 | 200 |   148.07884ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6768/8417 [1:35:48<29:42,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:21 | 200 |  182.071651ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6769/8417 [1:35:50<29:49,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:22 | 200 |  162.220381ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6770/8417 [1:35:51<29:34,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:23 | 200 |  141.742148ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6771/8417 [1:35:52<29:13,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:24 | 200 |   184.31357ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6772/8417 [1:35:53<29:28,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:25 | 200 |  172.530671ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6773/8417 [1:35:54<29:44,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:26 | 200 |  144.000502ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6774/8417 [1:35:55<29:32,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:27 | 200 |  168.037884ms |       127.0.0.1 | POST     "/api/chat"

 80%|████████  | 6775/8417 [1:35:56<30:15,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:28 | 200 |  178.371899ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6776/8417 [1:35:57<30:10,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:29 | 200 |  143.732546ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6777/8417 [1:35:58<29:49,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:30 | 200 |  114.425509ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6778/8417 [1:35:59<29:29,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:31 | 200 |  178.488048ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6779/8417 [1:36:00<29:39,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:33 | 200 |  143.637472ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6780/8417 [1:36:01<29:24,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:34 | 200 |   138.80376ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6781/8417 [1:36:02<29:05,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:35 | 200 |   179.44635ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6782/8417 [1:36:04<29:14,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:36 | 200 |  147.001819ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6783/8417 [1:36:05<29:11,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:37 | 200 |  146.606519ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6784/8417 [1:36:06<29:11,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:38 | 200 |  183.150999ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6785/8417 [1:36:07<29:32,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:39 | 200 |  146.266121ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6786/8417 [1:36:08<29:13,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:40 | 200 |  126.797572ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6787/8417 [1:36:09<29:19,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:41 | 200 |  170.951282ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6788/8417 [1:36:10<29:55,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:42 | 200 |  167.428909ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6789/8417 [1:36:11<29:59,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:43 | 200 |  122.851887ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6790/8417 [1:36:12<29:14,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:44 | 200 |  172.230018ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6791/8417 [1:36:13<29:09,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:45 | 200 |  156.711365ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6792/8417 [1:36:14<28:58,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:47 | 200 |  178.681484ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6793/8417 [1:36:15<28:59,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:48 | 200 |  118.879395ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6794/8417 [1:36:16<28:36,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:49 | 200 |  176.260676ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6795/8417 [1:36:18<29:01,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:50 | 200 |  176.541455ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6796/8417 [1:36:19<29:11,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:51 | 200 |  169.638043ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6797/8417 [1:36:20<29:13,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:52 | 200 |  180.433416ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6798/8417 [1:36:21<29:21,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:53 | 200 |  142.356732ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6799/8417 [1:36:22<28:54,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:54 | 200 |  145.821676ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6800/8417 [1:36:23<28:43,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:55 | 200 |  182.758002ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6801/8417 [1:36:24<28:58,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:56 | 200 |   150.56884ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6802/8417 [1:36:25<28:46,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:57 | 200 |  144.207828ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6803/8417 [1:36:26<28:46,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:58 | 200 |  179.507667ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6804/8417 [1:36:27<29:08,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:00:59 | 200 |  162.393067ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6805/8417 [1:36:28<29:17,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:01 | 200 |  142.481958ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6806/8417 [1:36:29<29:07,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:02 | 200 |  142.095387ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6807/8417 [1:36:31<28:44,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:03 | 200 |  184.147848ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6808/8417 [1:36:32<28:57,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:04 | 200 |  169.593696ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6809/8417 [1:36:33<28:54,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:05 | 200 |  158.293077ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6810/8417 [1:36:34<28:48,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:06 | 200 |  133.606162ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6811/8417 [1:36:35<28:25,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:07 | 200 |  174.937051ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6812/8417 [1:36:36<28:35,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:08 | 200 |  147.980741ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6813/8417 [1:36:37<28:35,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:09 | 200 |  115.837118ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6814/8417 [1:36:38<28:17,  1.06s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:10 | 200 |  173.509687ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6815/8417 [1:36:39<28:37,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:11 | 200 |  179.974452ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6816/8417 [1:36:40<28:33,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:12 | 200 |  148.175042ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6817/8417 [1:36:41<28:33,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:13 | 200 |  175.846332ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6818/8417 [1:36:42<28:37,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:14 | 200 |  146.220319ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6819/8417 [1:36:43<28:46,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:16 | 200 |  144.742383ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6820/8417 [1:36:44<28:50,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:17 | 200 |  179.096637ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6821/8417 [1:36:46<28:47,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:18 | 200 |    145.0748ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6822/8417 [1:36:47<28:25,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:19 | 200 |  176.021674ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6823/8417 [1:36:48<28:46,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:20 | 200 |  118.451967ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6824/8417 [1:36:49<28:30,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:21 | 200 |  178.782601ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6825/8417 [1:36:50<28:40,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:22 | 200 |  177.049956ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6826/8417 [1:36:51<29:41,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:23 | 200 |  179.199433ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6827/8417 [1:36:52<30:09,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:24 | 200 |  174.594609ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6828/8417 [1:36:53<29:42,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:25 | 200 |  143.240824ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6829/8417 [1:36:54<29:09,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:27 | 200 |  136.469363ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6830/8417 [1:36:55<28:50,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:28 | 200 |  177.348682ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6831/8417 [1:36:57<28:49,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:29 | 200 |  164.372801ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6832/8417 [1:36:58<28:32,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:30 | 200 |  146.176828ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6833/8417 [1:36:59<28:29,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:31 | 200 |  223.166006ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6834/8417 [1:37:00<29:19,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:32 | 200 |  156.650316ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6835/8417 [1:37:01<29:04,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:33 | 200 |  139.361715ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6836/8417 [1:37:02<28:50,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:34 | 200 |  142.593745ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6837/8417 [1:37:03<28:40,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:35 | 200 |  182.442977ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████  | 6838/8417 [1:37:04<29:09,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:36 | 200 |  155.813501ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6839/8417 [1:37:05<28:51,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:37 | 200 |  179.792015ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6840/8417 [1:37:06<28:50,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:39 | 200 |  148.077719ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6841/8417 [1:37:08<28:54,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:40 | 200 |  178.651574ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6842/8417 [1:37:09<28:56,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:41 | 200 |  171.164964ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6843/8417 [1:37:10<28:54,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:42 | 200 |  147.794728ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6844/8417 [1:37:11<28:23,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:43 | 200 |  179.613891ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6845/8417 [1:37:12<28:24,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:44 | 200 |  147.486592ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6846/8417 [1:37:13<28:20,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:45 | 200 |  178.022897ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6847/8417 [1:37:14<28:20,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:46 | 200 |  122.629835ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6848/8417 [1:37:15<27:59,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:47 | 200 |  180.532404ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6849/8417 [1:37:16<28:01,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:48 | 200 |  185.046306ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6850/8417 [1:37:17<28:14,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:49 | 200 |  147.811392ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6851/8417 [1:37:18<27:59,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:50 | 200 |  141.843008ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6852/8417 [1:37:19<27:59,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:52 | 200 |  183.108123ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6853/8417 [1:37:20<28:07,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:53 | 200 |  146.663225ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6854/8417 [1:37:22<28:07,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:54 | 200 |  177.038538ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6855/8417 [1:37:23<28:10,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:55 | 200 |  146.290362ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6856/8417 [1:37:24<28:15,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:56 | 200 |  180.272254ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6857/8417 [1:37:25<29:06,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:57 | 200 |  138.822015ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6858/8417 [1:37:26<28:38,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:58 | 200 |  181.850563ms |       127.0.0.1 | POST     "/api/chat"

 81%|████████▏ | 6859/8417 [1:37:27<28:44,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:01:59 | 200 |  145.946386ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6860/8417 [1:37:28<28:34,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:00 | 200 |  176.261684ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6861/8417 [1:37:29<28:43,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:01 | 200 |  118.020384ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6862/8417 [1:37:30<28:08,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:03 | 200 |  186.817687ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6863/8417 [1:37:31<28:16,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:04 | 200 |  140.368314ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6864/8417 [1:37:33<28:09,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:05 | 200 |  179.941622ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6865/8417 [1:37:34<28:18,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:06 | 200 |  165.216918ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6866/8417 [1:37:35<28:09,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:07 | 200 |  147.550727ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6867/8417 [1:37:36<28:00,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:08 | 200 |  136.194079ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6868/8417 [1:37:37<27:57,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:09 | 200 |  177.857616ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6869/8417 [1:37:38<28:02,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:10 | 200 |  118.568605ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6870/8417 [1:37:39<28:14,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:11 | 200 |  177.545232ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6871/8417 [1:37:40<28:31,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:12 | 200 |  175.029448ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6872/8417 [1:37:41<28:32,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:14 | 200 |  146.948266ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6873/8417 [1:37:42<28:43,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:15 | 200 |  181.297133ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6874/8417 [1:37:44<28:47,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:16 | 200 |  144.906333ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6875/8417 [1:37:45<28:23,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:17 | 200 |  177.995718ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6876/8417 [1:37:46<28:28,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:18 | 200 |  140.108017ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6877/8417 [1:37:47<28:08,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:19 | 200 |  175.123393ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6878/8417 [1:37:48<28:42,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:20 | 200 |  166.331589ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6879/8417 [1:37:49<29:17,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:21 | 200 |  114.160351ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6880/8417 [1:37:50<28:23,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:22 | 200 |  176.236557ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6881/8417 [1:37:51<28:06,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:23 | 200 |  148.320351ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6882/8417 [1:37:52<27:46,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:24 | 200 |  138.231543ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6883/8417 [1:37:53<27:26,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:26 | 200 |  179.313999ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6884/8417 [1:37:55<27:42,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:27 | 200 |  152.838242ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6885/8417 [1:37:56<27:44,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:28 | 200 |  153.723934ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6886/8417 [1:37:57<27:32,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:29 | 200 |  180.999514ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6887/8417 [1:37:58<27:38,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:30 | 200 |  148.426425ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6888/8417 [1:37:59<27:29,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:31 | 200 |   181.51023ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6889/8417 [1:38:00<27:45,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:32 | 200 |  155.114198ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6890/8417 [1:38:01<27:27,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:33 | 200 |  143.902177ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6891/8417 [1:38:02<27:38,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:34 | 200 |  198.281934ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6892/8417 [1:38:03<28:07,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:35 | 200 |  153.787017ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6893/8417 [1:38:04<28:08,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:36 | 200 |  116.904893ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6894/8417 [1:38:05<27:37,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:38 | 200 |  177.514378ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6895/8417 [1:38:07<27:41,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:39 | 200 |  180.250887ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6896/8417 [1:38:08<27:42,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:40 | 200 |  149.272928ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6897/8417 [1:38:09<27:28,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:41 | 200 |  181.270789ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6898/8417 [1:38:10<28:02,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:42 | 200 |  118.692165ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6899/8417 [1:38:11<27:27,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:43 | 200 |  178.988754ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6900/8417 [1:38:12<27:32,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:44 | 200 |  158.263946ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6901/8417 [1:38:13<27:28,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:45 | 200 |  148.765191ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6902/8417 [1:38:14<27:20,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:46 | 200 |   180.49662ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6903/8417 [1:38:15<27:32,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:47 | 200 |  146.468722ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6904/8417 [1:38:16<27:25,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:48 | 200 |  179.056629ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6905/8417 [1:38:17<27:32,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:50 | 200 |  142.517495ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6906/8417 [1:38:19<27:21,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:51 | 200 |    181.2815ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6907/8417 [1:38:20<27:47,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:52 | 200 |  146.894936ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6908/8417 [1:38:21<27:42,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:53 | 200 |  181.100404ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6909/8417 [1:38:22<27:35,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:54 | 200 |  141.024491ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6910/8417 [1:38:23<27:20,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:55 | 200 |  141.565859ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6911/8417 [1:38:24<27:34,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:56 | 200 |  176.403529ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6912/8417 [1:38:25<27:35,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:57 | 200 |  151.170413ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6913/8417 [1:38:26<27:23,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:58 | 200 |  180.356487ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6914/8417 [1:38:27<27:22,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:02:59 | 200 |  138.804691ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6915/8417 [1:38:28<27:09,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:01 | 200 |  182.807259ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6916/8417 [1:38:30<27:30,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:02 | 200 |  145.294699ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6917/8417 [1:38:31<27:10,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:03 | 200 |  179.319439ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6918/8417 [1:38:32<27:32,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:04 | 200 |  138.907873ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6919/8417 [1:38:33<27:14,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:05 | 200 |  178.799512ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6920/8417 [1:38:34<27:32,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:06 | 200 |  166.740342ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6921/8417 [1:38:35<27:34,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:07 | 200 |  178.445118ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6922/8417 [1:38:36<27:27,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:08 | 200 |  144.193271ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6923/8417 [1:38:37<27:14,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:09 | 200 |  180.933159ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6924/8417 [1:38:38<27:19,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:10 | 200 |  152.274841ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6925/8417 [1:38:39<27:45,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:12 | 200 |  179.335755ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6926/8417 [1:38:41<27:37,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:13 | 200 |  143.697996ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6927/8417 [1:38:42<27:14,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:14 | 200 |  175.495199ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6928/8417 [1:38:43<27:12,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:15 | 200 |  148.426794ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6929/8417 [1:38:44<27:04,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:16 | 200 |  143.659613ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6930/8417 [1:38:45<26:57,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:17 | 200 |  179.376893ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6931/8417 [1:38:46<27:07,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:18 | 200 |  143.902521ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6932/8417 [1:38:47<26:54,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:19 | 200 |  180.548313ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6933/8417 [1:38:48<26:59,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:20 | 200 |  118.564791ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6934/8417 [1:38:49<26:48,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:21 | 200 |  177.119903ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6935/8417 [1:38:50<27:06,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:22 | 200 |  145.657447ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6936/8417 [1:38:51<26:54,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:24 | 200 |  143.399361ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6937/8417 [1:38:52<26:41,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:25 | 200 |  167.470854ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6938/8417 [1:38:54<26:44,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:26 | 200 |  153.497367ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6939/8417 [1:38:55<26:38,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:27 | 200 |  178.342957ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6940/8417 [1:38:56<26:49,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:28 | 200 |   149.26705ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6941/8417 [1:38:57<26:39,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:29 | 200 |  136.410185ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6942/8417 [1:38:58<26:50,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:30 | 200 |  172.037552ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6943/8417 [1:38:59<27:13,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:31 | 200 |  153.845178ms |       127.0.0.1 | POST     "/api/chat"

 82%|████████▏ | 6944/8417 [1:39:00<26:59,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:32 | 200 |  147.898274ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6945/8417 [1:39:01<26:42,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:33 | 200 |  149.652467ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6946/8417 [1:39:02<26:35,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:34 | 200 |  181.101403ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6947/8417 [1:39:03<27:01,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:36 | 200 |  140.073299ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6948/8417 [1:39:05<27:06,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:37 | 200 |  172.070176ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6949/8417 [1:39:06<27:20,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:38 | 200 |  145.519406ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6950/8417 [1:39:07<27:19,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:39 | 200 |  138.121749ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6951/8417 [1:39:08<26:58,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:40 | 200 |  179.191645ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6952/8417 [1:39:09<27:17,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:41 | 200 |  153.453951ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6953/8417 [1:39:10<27:12,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:42 | 200 |  176.879698ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6954/8417 [1:39:11<27:25,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:43 | 200 |  129.005884ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6955/8417 [1:39:12<26:58,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:45 | 200 |  176.547863ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6956/8417 [1:39:13<27:06,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:46 | 200 |  143.846159ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6957/8417 [1:39:15<27:06,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:47 | 200 |  185.320169ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6958/8417 [1:39:16<27:26,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:48 | 200 |   140.53289ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6959/8417 [1:39:17<27:05,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:49 | 200 |  172.832529ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6960/8417 [1:39:18<27:03,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:50 | 200 |  175.254325ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6961/8417 [1:39:19<27:17,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:51 | 200 |  145.260823ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6962/8417 [1:39:20<27:19,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:52 | 200 |  173.779641ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6963/8417 [1:39:21<27:06,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:53 | 200 |   166.43765ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6964/8417 [1:39:22<26:50,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:55 | 200 |  143.953993ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6965/8417 [1:39:23<26:32,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:56 | 200 |  141.027486ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6966/8417 [1:39:25<26:21,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:57 | 200 |  179.485655ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6967/8417 [1:39:26<26:27,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:58 | 200 |  141.066256ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6968/8417 [1:39:27<26:12,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:03:59 | 200 |  183.091615ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6969/8417 [1:39:28<26:19,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:00 | 200 |  152.549918ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6970/8417 [1:39:29<26:20,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:01 | 200 |   143.96874ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6971/8417 [1:39:30<26:13,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:02 | 200 |  178.448604ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6972/8417 [1:39:31<26:19,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:03 | 200 |   140.54922ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6973/8417 [1:39:32<26:14,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:04 | 200 |  178.624992ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6974/8417 [1:39:33<26:23,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:05 | 200 |  147.781429ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6975/8417 [1:39:34<26:10,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:07 | 200 |   179.63043ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6976/8417 [1:39:36<26:20,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:08 | 200 |  146.556097ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6977/8417 [1:39:37<26:06,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:09 | 200 |  195.083576ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6978/8417 [1:39:38<26:24,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:10 | 200 |  148.326941ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6979/8417 [1:39:39<26:23,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:11 | 200 |   176.21259ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6980/8417 [1:39:40<26:36,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:12 | 200 |  150.829905ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6981/8417 [1:39:41<26:24,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:13 | 200 |  176.756635ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6982/8417 [1:39:42<26:33,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:14 | 200 |  146.821816ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6983/8417 [1:39:43<26:15,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:15 | 200 |  182.328847ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6984/8417 [1:39:44<26:18,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:16 | 200 |  160.616906ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6985/8417 [1:39:45<26:08,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:18 | 200 |  168.382516ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6986/8417 [1:39:46<25:57,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:19 | 200 |   164.11628ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6987/8417 [1:39:48<25:56,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:20 | 200 |   138.25167ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6988/8417 [1:39:49<25:39,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:21 | 200 |  208.004895ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6989/8417 [1:39:50<26:10,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:22 | 200 |  151.726199ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6990/8417 [1:39:51<25:53,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:23 | 200 |    180.5791ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6991/8417 [1:39:52<26:01,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:24 | 200 |  138.783279ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6992/8417 [1:39:53<25:48,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:25 | 200 |  178.332881ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6993/8417 [1:39:54<25:54,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:26 | 200 |   170.44662ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6994/8417 [1:39:55<25:54,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:27 | 200 |  141.337604ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6995/8417 [1:39:56<25:40,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:28 | 200 |  180.490457ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6996/8417 [1:39:57<25:46,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:30 | 200 |  141.150135ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6997/8417 [1:39:58<25:40,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:31 | 200 |    188.3453ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6998/8417 [1:40:00<26:03,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:32 | 200 |  145.879452ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 6999/8417 [1:40:01<25:44,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:33 | 200 |  177.016722ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7000/8417 [1:40:02<25:44,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:34 | 200 |  154.902435ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7001/8417 [1:40:03<25:28,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:35 | 200 |  149.607586ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7002/8417 [1:40:04<25:26,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:36 | 200 |  182.934331ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7003/8417 [1:40:05<25:53,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:37 | 200 |  145.162561ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7004/8417 [1:40:06<25:44,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:38 | 200 |  139.632549ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7005/8417 [1:40:07<25:21,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:39 | 200 |  184.110636ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7006/8417 [1:40:08<25:49,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:40 | 200 |  160.985834ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7007/8417 [1:40:09<26:04,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:42 | 200 |  140.867352ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7008/8417 [1:40:10<25:41,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:43 | 200 |  183.114246ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7009/8417 [1:40:12<25:47,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:44 | 200 |  148.155616ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7010/8417 [1:40:13<25:35,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:45 | 200 |  141.412698ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7011/8417 [1:40:14<25:24,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:46 | 200 |  176.591364ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7012/8417 [1:40:15<25:30,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:47 | 200 |  142.148724ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7013/8417 [1:40:16<25:32,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:48 | 200 |  180.356333ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7014/8417 [1:40:17<25:37,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:49 | 200 |  146.527652ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7015/8417 [1:40:18<25:30,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:50 | 200 |  178.094696ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7016/8417 [1:40:19<25:48,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:51 | 200 |  145.008808ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7017/8417 [1:40:20<25:39,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:53 | 200 |  167.178963ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7018/8417 [1:40:21<25:44,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:54 | 200 |  149.117966ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7019/8417 [1:40:23<25:24,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:55 | 200 |  182.191387ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7020/8417 [1:40:24<25:33,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:56 | 200 |  140.481719ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7021/8417 [1:40:25<25:22,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:57 | 200 |  142.959256ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7022/8417 [1:40:26<25:08,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:58 | 200 |  179.739624ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7023/8417 [1:40:27<25:23,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:04:59 | 200 |   119.17811ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7024/8417 [1:40:28<25:10,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:00 | 200 |  176.404077ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7025/8417 [1:40:29<25:22,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:01 | 200 |  145.895751ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7026/8417 [1:40:30<25:14,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:02 | 200 |  136.554766ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7027/8417 [1:40:31<25:00,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:03 | 200 |  181.126124ms |       127.0.0.1 | POST     "/api/chat"

 83%|████████▎ | 7028/8417 [1:40:32<25:25,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:04 | 200 |  144.716461ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7029/8417 [1:40:33<25:17,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:06 | 200 |  147.725572ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7030/8417 [1:40:34<25:06,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:07 | 200 |  134.651735ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7031/8417 [1:40:36<24:46,  1.07s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:08 | 200 |  180.251854ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7032/8417 [1:40:37<25:02,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:09 | 200 |  160.949451ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7033/8417 [1:40:38<25:02,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:10 | 200 |  136.035835ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7034/8417 [1:40:39<25:04,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:11 | 200 |  183.065048ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7035/8417 [1:40:40<25:15,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:12 | 200 |  170.146299ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7036/8417 [1:40:41<25:19,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:13 | 200 |  179.178049ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7037/8417 [1:40:42<25:17,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:14 | 200 |  148.983085ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7038/8417 [1:40:43<25:02,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:15 | 200 |  168.967276ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7039/8417 [1:40:44<25:08,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:16 | 200 |  150.868326ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7040/8417 [1:40:45<24:52,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:18 | 200 |  155.725267ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7041/8417 [1:40:47<25:04,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:19 | 200 |  176.265469ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7042/8417 [1:40:48<25:10,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:20 | 200 |   152.54246ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7043/8417 [1:40:49<24:55,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:21 | 200 |   196.52729ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7044/8417 [1:40:50<25:07,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:22 | 200 |  139.935465ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7045/8417 [1:40:51<25:01,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:23 | 200 |  180.861809ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7046/8417 [1:40:52<25:02,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:24 | 200 |  137.073683ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7047/8417 [1:40:53<24:57,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:25 | 200 |  182.222145ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7048/8417 [1:40:54<25:03,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:26 | 200 |  151.382576ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▎ | 7049/8417 [1:40:55<24:59,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:27 | 200 |  173.296978ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7050/8417 [1:40:56<25:07,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:29 | 200 |  153.204927ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7051/8417 [1:40:57<24:59,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:30 | 200 |  167.725499ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7052/8417 [1:40:59<25:02,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:31 | 200 |  173.896302ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7053/8417 [1:41:00<25:27,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:32 | 200 |  142.028748ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7054/8417 [1:41:01<25:12,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:33 | 200 |  141.518536ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7055/8417 [1:41:02<25:09,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:34 | 200 |  175.357645ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7056/8417 [1:41:03<25:19,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:35 | 200 |   158.24732ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7057/8417 [1:41:04<25:20,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:36 | 200 |  143.078891ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7058/8417 [1:41:05<25:03,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:37 | 200 |  166.479865ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7059/8417 [1:41:06<25:07,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:39 | 200 |  151.505227ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7060/8417 [1:41:07<25:02,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:40 | 200 |  178.382506ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7061/8417 [1:41:09<25:06,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:41 | 200 |  152.615273ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7062/8417 [1:41:10<24:54,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:42 | 200 |  179.852144ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7063/8417 [1:41:11<24:55,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:43 | 200 |  142.024532ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7064/8417 [1:41:12<25:08,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:44 | 200 |  166.350827ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7065/8417 [1:41:13<25:03,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:45 | 200 |  180.689211ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7066/8417 [1:41:14<24:58,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:46 | 200 |  175.847699ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7067/8417 [1:41:15<24:57,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:47 | 200 |  146.886865ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7068/8417 [1:41:16<24:46,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:49 | 200 |  180.227516ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7069/8417 [1:41:17<25:05,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:50 | 200 |  140.886281ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7070/8417 [1:41:19<24:43,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:51 | 200 |  183.654603ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7071/8417 [1:41:20<24:45,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:52 | 200 |  146.950502ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7072/8417 [1:41:21<24:39,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:53 | 200 |  141.986457ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7073/8417 [1:41:22<24:29,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:54 | 200 |  142.209715ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7074/8417 [1:41:23<24:35,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:55 | 200 |  176.661999ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7075/8417 [1:41:24<25:00,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:56 | 200 |  141.481886ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7076/8417 [1:41:25<24:35,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:57 | 200 |  179.571697ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7077/8417 [1:41:26<24:38,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:05:58 | 200 |  150.200653ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7078/8417 [1:41:27<24:23,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:00 | 200 |  177.368144ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7079/8417 [1:41:28<24:36,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:01 | 200 |  144.575761ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7080/8417 [1:41:30<24:32,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:02 | 200 |  180.392145ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7081/8417 [1:41:31<24:27,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:03 | 200 |   147.54099ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7082/8417 [1:41:32<24:14,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:04 | 200 |  141.926976ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7083/8417 [1:41:33<24:13,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:05 | 200 |  177.877573ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7084/8417 [1:41:34<24:30,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:06 | 200 |  145.469038ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7085/8417 [1:41:35<24:19,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:07 | 200 |  140.770014ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7086/8417 [1:41:36<24:10,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:08 | 200 |  138.619839ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7087/8417 [1:41:37<24:01,  1.08s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:09 | 200 |  180.055818ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7088/8417 [1:41:38<24:22,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:10 | 200 |  146.365193ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7089/8417 [1:41:39<24:28,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:12 | 200 |  179.326901ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7090/8417 [1:41:41<24:29,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:13 | 200 |  144.279855ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7091/8417 [1:41:42<24:12,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:14 | 200 |  180.573908ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7092/8417 [1:41:43<24:21,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:15 | 200 |  156.097668ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7093/8417 [1:41:44<24:28,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:16 | 200 |   189.31607ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7094/8417 [1:41:45<24:34,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:17 | 200 |  142.466827ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7095/8417 [1:41:46<24:19,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:18 | 200 |  180.221155ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7096/8417 [1:41:47<24:18,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:19 | 200 |  149.517441ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7097/8417 [1:41:48<24:05,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:20 | 200 |  179.078623ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7098/8417 [1:41:49<24:15,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:22 | 200 |  146.997615ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7099/8417 [1:41:50<24:16,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:23 | 200 |  141.506593ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7100/8417 [1:41:52<23:59,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:24 | 200 |  183.277134ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7101/8417 [1:41:53<24:14,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:25 | 200 |  180.236711ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7102/8417 [1:41:54<24:15,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:26 | 200 |  147.099582ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7103/8417 [1:41:55<24:07,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:27 | 200 |  176.129384ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7104/8417 [1:41:56<24:08,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:28 | 200 |  140.975496ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7105/8417 [1:41:57<23:51,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:29 | 200 |  181.398652ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7106/8417 [1:41:58<24:05,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:30 | 200 |  145.181127ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7107/8417 [1:41:59<24:23,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:32 | 200 |  176.674361ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7108/8417 [1:42:00<24:37,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:33 | 200 |  172.047481ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7109/8417 [1:42:02<24:36,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:34 | 200 |   139.20212ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7110/8417 [1:42:03<24:10,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:35 | 200 |  180.793959ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7111/8417 [1:42:04<24:11,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:36 | 200 |  152.576531ms |       127.0.0.1 | POST     "/api/chat"

 84%|████████▍ | 7112/8417 [1:42:05<23:58,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:37 | 200 |  174.807048ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7113/8417 [1:42:06<23:56,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:38 | 200 |  144.320357ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7114/8417 [1:42:07<24:04,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:39 | 200 |  144.546117ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7115/8417 [1:42:08<24:15,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:40 | 200 |  137.434238ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7116/8417 [1:42:09<24:17,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:42 | 200 |  179.911524ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7117/8417 [1:42:10<24:14,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:43 | 200 |  143.706228ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7118/8417 [1:42:12<24:01,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:44 | 200 |  178.740982ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7119/8417 [1:42:13<24:01,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:45 | 200 |  146.855222ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7120/8417 [1:42:14<23:47,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:46 | 200 |  179.369551ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7121/8417 [1:42:15<24:12,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:47 | 200 |  152.057071ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7122/8417 [1:42:16<24:08,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:48 | 200 |  172.128347ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7123/8417 [1:42:17<24:11,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:49 | 200 |  179.267084ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7124/8417 [1:42:18<24:10,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:50 | 200 |   141.98687ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7125/8417 [1:42:19<24:10,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:52 | 200 |  169.809512ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7126/8417 [1:42:21<24:13,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:53 | 200 |  162.856651ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7127/8417 [1:42:22<24:07,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:54 | 200 |  148.826348ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7128/8417 [1:42:23<23:46,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:55 | 200 |  177.092142ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7129/8417 [1:42:24<23:52,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:56 | 200 |  147.328262ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7130/8417 [1:42:25<23:43,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:57 | 200 |  177.716624ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7131/8417 [1:42:26<23:55,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:58 | 200 |  143.344456ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7132/8417 [1:42:27<23:49,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:06:59 | 200 |  180.383778ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7133/8417 [1:42:28<23:55,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:01 | 200 |   144.17038ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7134/8417 [1:42:30<24:20,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:02 | 200 |  140.379603ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7135/8417 [1:42:31<24:15,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:03 | 200 |  170.997309ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7136/8417 [1:42:32<24:17,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:04 | 200 |  169.141046ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7137/8417 [1:42:33<23:58,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:05 | 200 |  143.902945ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7138/8417 [1:42:34<23:40,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:06 | 200 |  140.231253ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7139/8417 [1:42:35<23:26,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:07 | 200 |  180.454836ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7140/8417 [1:42:36<23:40,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:08 | 200 |  147.164754ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7141/8417 [1:42:37<23:23,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:09 | 200 |  176.607941ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7142/8417 [1:42:38<23:32,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:10 | 200 |  140.342711ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7143/8417 [1:42:39<23:28,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:12 | 200 |  179.927989ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7144/8417 [1:42:41<23:34,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:13 | 200 |   143.48123ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7145/8417 [1:42:42<23:22,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:14 | 200 |  176.318218ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7146/8417 [1:42:43<23:22,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:15 | 200 |  146.359475ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7147/8417 [1:42:44<23:26,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:16 | 200 |  139.899086ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7148/8417 [1:42:45<23:13,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:17 | 200 |  170.617843ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7149/8417 [1:42:46<23:47,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:18 | 200 |  158.509871ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7150/8417 [1:42:47<23:54,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 85%|████████▍ | 7151/8417 [1:42:48<23:14,  1.10s/it]

[GIN] 2025/06/27 - 01:07:19 | 200 |  116.879059ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:21 | 200 |  179.009147ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7152/8417 [1:42:49<23:23,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:22 | 200 |  180.355827ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7153/8417 [1:42:51<23:24,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:23 | 200 |  147.578675ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▍ | 7154/8417 [1:42:52<23:20,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:24 | 200 |  178.510289ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7155/8417 [1:42:53<23:32,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:25 | 200 |  150.115095ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7156/8417 [1:42:54<23:18,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:26 | 200 |  147.151965ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7157/8417 [1:42:55<23:14,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:27 | 200 |   138.75265ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7158/8417 [1:42:56<23:00,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:28 | 200 |  179.393264ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7159/8417 [1:42:57<23:07,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:29 | 200 |  149.727148ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7160/8417 [1:42:58<23:05,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:31 | 200 |  180.321868ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7161/8417 [1:42:59<23:35,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:32 | 200 |  134.263662ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7162/8417 [1:43:01<23:16,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:33 | 200 |  175.410226ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7163/8417 [1:43:02<23:08,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:34 | 200 |  162.061917ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7164/8417 [1:43:03<23:08,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:35 | 200 |  144.212457ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7165/8417 [1:43:04<23:00,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:36 | 200 |  141.143721ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7166/8417 [1:43:05<22:48,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:37 | 200 |  176.773634ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7167/8417 [1:43:06<23:13,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:38 | 200 |  162.628325ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7168/8417 [1:43:07<23:00,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:39 | 200 |  143.575757ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7169/8417 [1:43:08<22:45,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:40 | 200 |  177.621172ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7170/8417 [1:43:09<23:19,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:42 | 200 |  123.174478ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7171/8417 [1:43:11<23:00,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:43 | 200 |  173.445938ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7172/8417 [1:43:12<23:01,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:44 | 200 |  148.237875ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7173/8417 [1:43:13<22:54,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:45 | 200 |  177.079387ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7174/8417 [1:43:14<22:59,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:46 | 200 |  147.025652ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7175/8417 [1:43:15<22:50,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:47 | 200 |  179.790587ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7176/8417 [1:43:16<23:10,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:48 | 200 |  144.873114ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7177/8417 [1:43:17<23:00,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:49 | 200 |  195.832029ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7178/8417 [1:43:18<23:53,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:51 | 200 |  140.140172ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7179/8417 [1:43:20<23:38,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:52 | 200 |  175.566865ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7180/8417 [1:43:21<23:35,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:53 | 200 |  147.488593ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7181/8417 [1:43:22<23:16,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:54 | 200 |  145.932312ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7182/8417 [1:43:23<22:55,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:55 | 200 |  139.759312ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7183/8417 [1:43:24<22:43,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:56 | 200 |  181.951518ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7184/8417 [1:43:25<22:57,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:57 | 200 |   143.32166ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7185/8417 [1:43:26<22:45,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:58 | 200 |   177.05852ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7186/8417 [1:43:27<23:02,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:07:59 | 200 |  157.214505ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7187/8417 [1:43:28<22:59,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:01 | 200 |  146.681144ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7188/8417 [1:43:30<22:45,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:02 | 200 |  176.177479ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7189/8417 [1:43:31<22:45,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:03 | 200 |  145.724233ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7190/8417 [1:43:32<22:44,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:04 | 200 |  141.033238ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7191/8417 [1:43:33<22:34,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:05 | 200 |  182.303708ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7192/8417 [1:43:34<22:42,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:06 | 200 |  173.785714ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7193/8417 [1:43:35<22:43,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:07 | 200 |  143.876523ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7194/8417 [1:43:36<22:41,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:08 | 200 |  148.786856ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7195/8417 [1:43:37<22:33,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:09 | 200 |   173.15021ms |       127.0.0.1 | POST     "/api/chat"

 85%|████████▌ | 7196/8417 [1:43:38<22:35,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:11 | 200 |  189.697494ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7197/8417 [1:43:40<22:50,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:12 | 200 |  157.430415ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7198/8417 [1:43:41<22:46,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:13 | 200 |  142.118793ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7199/8417 [1:43:42<22:35,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:14 | 200 |  176.252714ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7200/8417 [1:43:43<22:38,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:15 | 200 |  147.067402ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7201/8417 [1:43:44<22:33,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:16 | 200 |  178.780241ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7202/8417 [1:43:45<22:41,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:17 | 200 |  137.568374ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7203/8417 [1:43:46<22:55,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:19 | 200 |  176.301155ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7204/8417 [1:43:47<22:56,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:20 | 200 |  174.291422ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7205/8417 [1:43:49<22:58,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:21 | 200 |  173.146143ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7206/8417 [1:43:50<23:25,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:22 | 200 |  148.206769ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7207/8417 [1:43:51<23:22,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:23 | 200 |  112.601421ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7208/8417 [1:43:52<23:14,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:24 | 200 |  143.819014ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7209/8417 [1:43:53<23:19,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:25 | 200 |  142.343142ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7210/8417 [1:43:54<22:43,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:27 | 200 |  167.476031ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7211/8417 [1:43:55<22:31,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:28 | 200 |  188.531746ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7212/8417 [1:43:57<22:35,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:29 | 200 |   145.34852ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7213/8417 [1:43:58<22:12,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:30 | 200 |  178.165615ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7214/8417 [1:43:59<22:25,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:31 | 200 |  148.617716ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7215/8417 [1:44:00<22:12,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:32 | 200 |  178.941225ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7216/8417 [1:44:01<22:14,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:33 | 200 |  121.259263ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7217/8417 [1:44:02<22:05,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:34 | 200 |  172.936124ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7218/8417 [1:44:03<22:02,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:35 | 200 |  147.170242ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7219/8417 [1:44:04<21:56,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:36 | 200 |  181.274142ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7220/8417 [1:44:05<21:55,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:38 | 200 |  138.651424ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7221/8417 [1:44:06<21:51,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:39 | 200 |  181.965581ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7222/8417 [1:44:08<22:04,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:40 | 200 |  118.789227ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7223/8417 [1:44:09<21:46,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:41 | 200 |  210.689596ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7224/8417 [1:44:10<22:03,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:42 | 200 |  145.111158ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7225/8417 [1:44:11<21:59,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:43 | 200 |  180.824254ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7226/8417 [1:44:12<22:01,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:44 | 200 |  150.893788ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7227/8417 [1:44:13<21:56,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:45 | 200 |   181.73831ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7228/8417 [1:44:14<22:00,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:46 | 200 |  143.026161ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7229/8417 [1:44:15<22:02,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:48 | 200 |  146.085248ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7230/8417 [1:44:16<21:48,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:49 | 200 |  114.380091ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7231/8417 [1:44:18<21:33,  1.09s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:50 | 200 |  180.537675ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7232/8417 [1:44:19<21:50,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:51 | 200 |  164.895071ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7233/8417 [1:44:20<21:53,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:52 | 200 |  180.997817ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7234/8417 [1:44:21<22:14,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:53 | 200 |  141.510113ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7235/8417 [1:44:22<22:08,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:54 | 200 |  176.850133ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7236/8417 [1:44:23<22:04,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:55 | 200 |  177.096251ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7237/8417 [1:44:24<21:59,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:56 | 200 |  150.395851ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7238/8417 [1:44:25<21:48,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:58 | 200 |  179.015194ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7239/8417 [1:44:27<21:54,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:08:59 | 200 |  144.155293ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7240/8417 [1:44:28<21:39,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:00 | 200 |  189.318906ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7241/8417 [1:44:29<21:55,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:01 | 200 |  142.555904ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7242/8417 [1:44:30<21:51,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:02 | 200 |  172.398466ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7243/8417 [1:44:31<21:52,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:03 | 200 |  174.050421ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7244/8417 [1:44:32<21:55,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:04 | 200 |  144.968665ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7245/8417 [1:44:33<21:40,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:05 | 200 |  143.721989ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7246/8417 [1:44:34<21:31,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:06 | 200 |  137.668565ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7247/8417 [1:44:35<21:21,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:07 | 200 |  135.669461ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7248/8417 [1:44:36<21:20,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:09 | 200 |  174.159484ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7249/8417 [1:44:38<21:25,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:10 | 200 |   143.77708ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7250/8417 [1:44:39<21:30,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:11 | 200 |  178.822373ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7251/8417 [1:44:40<21:56,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:12 | 200 |  179.236351ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7252/8417 [1:44:41<21:53,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:13 | 200 |  149.756039ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7253/8417 [1:44:42<21:38,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:14 | 200 |  144.564151ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7254/8417 [1:44:43<21:25,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:15 | 200 |  140.292058ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7255/8417 [1:44:44<21:18,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:16 | 200 |  166.371854ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7256/8417 [1:44:45<21:27,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:18 | 200 |   148.43434ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7257/8417 [1:44:46<21:20,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:19 | 200 |  139.385823ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7258/8417 [1:44:48<21:09,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:20 | 200 |  132.324539ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▌ | 7259/8417 [1:44:49<21:15,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:21 | 200 |  165.641478ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7260/8417 [1:44:50<21:25,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:22 | 200 |  170.965749ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7261/8417 [1:44:51<21:22,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:23 | 200 |  164.471268ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7262/8417 [1:44:52<21:34,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:24 | 200 |  152.924892ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7263/8417 [1:44:53<21:35,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:25 | 200 |  196.880696ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7264/8417 [1:44:54<21:52,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:26 | 200 |  137.815584ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7265/8417 [1:44:55<21:36,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:28 | 200 |  171.064376ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7266/8417 [1:44:57<21:29,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:29 | 200 |  162.038209ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7267/8417 [1:44:58<21:19,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:30 | 200 |  179.669973ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7268/8417 [1:44:59<21:24,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:31 | 200 |  148.932912ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7269/8417 [1:45:00<21:14,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:32 | 200 |  147.354415ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7270/8417 [1:45:01<21:03,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:33 | 200 |  181.773105ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7271/8417 [1:45:02<21:10,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:34 | 200 |  178.280643ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7272/8417 [1:45:03<21:09,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:35 | 200 |  146.559815ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7273/8417 [1:45:04<21:03,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:36 | 200 |   186.36441ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7274/8417 [1:45:05<21:09,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:38 | 200 |  116.588849ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7275/8417 [1:45:06<20:52,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:39 | 200 |  175.765527ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7276/8417 [1:45:08<20:59,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:40 | 200 |  146.885662ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7277/8417 [1:45:09<21:02,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:41 | 200 |  176.064613ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7278/8417 [1:45:10<21:26,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:42 | 200 |  148.871568ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7279/8417 [1:45:11<21:11,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:43 | 200 |  146.710476ms |       127.0.0.1 | POST     "/api/chat"

 86%|████████▋ | 7280/8417 [1:45:12<21:04,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:44 | 200 |  142.970358ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7281/8417 [1:45:13<20:58,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:45 | 200 |  176.153397ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7282/8417 [1:45:14<21:03,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:46 | 200 |   155.44057ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7283/8417 [1:45:15<21:06,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:48 | 200 |  145.481662ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7284/8417 [1:45:17<21:01,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:49 | 200 |  176.273061ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7285/8417 [1:45:18<21:19,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:50 | 200 |     118.187ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7286/8417 [1:45:19<20:55,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:51 | 200 |  145.680178ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7287/8417 [1:45:20<21:00,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:52 | 200 |  177.459014ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7288/8417 [1:45:21<21:03,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:53 | 200 |  144.866238ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7289/8417 [1:45:22<21:02,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:54 | 200 |  186.013837ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7290/8417 [1:45:23<21:16,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:55 | 200 |  145.366538ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7291/8417 [1:45:25<21:41,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:57 | 200 |  165.408117ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7292/8417 [1:45:26<21:39,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:58 | 200 |  175.451436ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7293/8417 [1:45:27<21:24,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:09:59 | 200 |  151.375967ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7294/8417 [1:45:28<21:20,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:00 | 200 |  170.799676ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7295/8417 [1:45:29<21:12,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:01 | 200 |  153.776793ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7296/8417 [1:45:30<20:58,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:02 | 200 |  143.772769ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7297/8417 [1:45:31<20:45,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:03 | 200 |  173.962625ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7298/8417 [1:45:32<20:52,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:04 | 200 |  145.176685ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7299/8417 [1:45:33<20:39,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:06 | 200 |  175.812864ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7300/8417 [1:45:35<20:41,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:07 | 200 |  149.499078ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7301/8417 [1:45:36<20:35,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:08 | 200 |  140.851345ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7302/8417 [1:45:37<20:26,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:09 | 200 |  137.576392ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7303/8417 [1:45:38<20:21,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:10 | 200 |  184.086963ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7304/8417 [1:45:39<20:44,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:11 | 200 |  143.672353ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7305/8417 [1:45:40<20:39,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:12 | 200 |  178.512215ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7306/8417 [1:45:41<20:35,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:13 | 200 |   185.45101ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7307/8417 [1:45:42<20:38,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:14 | 200 |  147.400861ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7308/8417 [1:45:43<20:29,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:16 | 200 |  179.446866ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7309/8417 [1:45:45<20:41,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:17 | 200 |  143.674215ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7310/8417 [1:45:46<20:31,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:18 | 200 |  175.768831ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7311/8417 [1:45:47<20:40,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:19 | 200 |  153.790419ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7312/8417 [1:45:48<20:40,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:20 | 200 |  117.318979ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7313/8417 [1:45:49<20:28,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:21 | 200 |  175.999967ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7314/8417 [1:45:50<20:27,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:22 | 200 |  143.864908ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7315/8417 [1:45:51<20:25,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:23 | 200 |   179.91673ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7316/8417 [1:45:52<20:34,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:25 | 200 |  148.070897ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7317/8417 [1:45:53<20:23,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:26 | 200 |  178.811621ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7318/8417 [1:45:55<20:28,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:27 | 200 |  149.991752ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7319/8417 [1:45:56<20:41,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:28 | 200 |    191.0436ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7320/8417 [1:45:57<20:55,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:29 | 200 |  150.137251ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7321/8417 [1:45:58<20:40,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:30 | 200 |  148.935728ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7322/8417 [1:45:59<20:39,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:31 | 200 |  139.592757ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7323/8417 [1:46:00<20:22,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:32 | 200 |  178.781335ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7324/8417 [1:46:01<20:24,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:34 | 200 |  144.578677ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7325/8417 [1:46:02<20:11,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:35 | 200 |  180.921021ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7326/8417 [1:46:04<20:21,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:36 | 200 |  115.754261ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7327/8417 [1:46:05<20:14,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:37 | 200 |  177.983748ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7328/8417 [1:46:06<20:13,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:38 | 200 |  145.213442ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7329/8417 [1:46:07<19:59,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:39 | 200 |  180.878284ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7330/8417 [1:46:08<20:02,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:40 | 200 |  119.194683ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7331/8417 [1:46:09<20:01,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:41 | 200 |  175.377776ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7332/8417 [1:46:10<20:15,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:42 | 200 |  117.780907ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7333/8417 [1:46:11<20:06,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:44 | 200 |  181.039853ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7334/8417 [1:46:13<20:13,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:45 | 200 |  178.417985ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7335/8417 [1:46:14<20:19,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:46 | 200 |  147.318394ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7336/8417 [1:46:15<20:12,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:47 | 200 |   144.66878ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7337/8417 [1:46:16<20:27,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:48 | 200 |  175.186279ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7338/8417 [1:46:17<20:30,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:49 | 200 |  142.701628ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7339/8417 [1:46:18<20:14,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:50 | 200 |  177.612708ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7340/8417 [1:46:19<20:19,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:51 | 200 |  153.954207ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7341/8417 [1:46:20<20:08,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:53 | 200 |  140.618388ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7342/8417 [1:46:22<20:00,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:54 | 200 |  177.245713ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7343/8417 [1:46:23<20:09,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:55 | 200 |  143.710113ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7344/8417 [1:46:24<19:57,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:56 | 200 |  176.911737ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7345/8417 [1:46:25<20:10,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:57 | 200 |  142.974303ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7346/8417 [1:46:26<20:00,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:58 | 200 |   152.07868ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7347/8417 [1:46:27<20:00,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:10:59 | 200 |  198.242467ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7348/8417 [1:46:28<20:11,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:00 | 200 |   114.98379ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7349/8417 [1:46:29<19:53,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:02 | 200 |  181.914692ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7350/8417 [1:46:31<20:11,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:03 | 200 |  170.763002ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7351/8417 [1:46:32<20:01,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:04 | 200 |  146.295447ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7352/8417 [1:46:33<19:50,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:05 | 200 |  170.356302ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7353/8417 [1:46:34<19:51,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:06 | 200 |   148.18462ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7354/8417 [1:46:35<19:42,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:07 | 200 |  184.396866ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7355/8417 [1:46:36<19:45,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:08 | 200 |   134.16369ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7356/8417 [1:46:37<19:29,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:09 | 200 |  186.352666ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7357/8417 [1:46:38<19:36,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:10 | 200 |  142.045372ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7358/8417 [1:46:39<19:37,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:12 | 200 |   176.25052ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7359/8417 [1:46:41<19:42,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:13 | 200 |  144.419731ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7360/8417 [1:46:42<19:30,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:14 | 200 |  142.429265ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7361/8417 [1:46:43<19:29,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:15 | 200 |  177.764806ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7362/8417 [1:46:44<19:44,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:16 | 200 |  143.106417ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7363/8417 [1:46:45<19:44,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:17 | 200 |  177.116428ms |       127.0.0.1 | POST     "/api/chat"

 87%|████████▋ | 7364/8417 [1:46:46<19:42,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:18 | 200 |  145.293606ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7365/8417 [1:46:47<19:35,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:19 | 200 |  185.443331ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7366/8417 [1:46:48<19:53,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:21 | 200 |  182.164315ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7367/8417 [1:46:50<19:57,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:22 | 200 |  146.035928ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7368/8417 [1:46:51<19:48,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:23 | 200 |  181.012919ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7369/8417 [1:46:52<19:49,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:24 | 200 |  180.345419ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7370/8417 [1:46:53<19:46,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:25 | 200 |  143.984139ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7371/8417 [1:46:54<19:25,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:26 | 200 |   183.62746ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7372/8417 [1:46:55<19:54,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:27 | 200 |  177.852136ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7373/8417 [1:46:56<19:57,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:29 | 200 |  149.890707ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7374/8417 [1:46:58<19:56,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:30 | 200 |  178.506121ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7375/8417 [1:46:59<20:12,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:31 | 200 |  189.519265ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7376/8417 [1:47:00<20:00,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:32 | 200 |  182.922572ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7377/8417 [1:47:01<19:44,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:33 | 200 |  114.708834ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7378/8417 [1:47:02<19:16,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:34 | 200 |  175.194714ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7379/8417 [1:47:03<19:16,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:35 | 200 |  148.796516ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7380/8417 [1:47:04<19:10,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:36 | 200 |  179.224198ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7381/8417 [1:47:05<19:15,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:38 | 200 |  144.028803ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7382/8417 [1:47:07<19:09,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:39 | 200 |  180.330242ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7383/8417 [1:47:08<19:11,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:40 | 200 |  147.630712ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7384/8417 [1:47:09<19:07,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:41 | 200 |  169.226492ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7385/8417 [1:47:10<19:11,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:42 | 200 |  143.815851ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7386/8417 [1:47:11<18:58,  1.10s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:43 | 200 |  176.139181ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7387/8417 [1:47:12<19:07,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:44 | 200 |  151.266637ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7388/8417 [1:47:13<19:03,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:45 | 200 |    143.1162ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7389/8417 [1:47:14<18:59,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:47 | 200 |  178.563866ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7390/8417 [1:47:15<19:26,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:48 | 200 |  143.061835ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7391/8417 [1:47:17<19:09,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:49 | 200 |  146.723576ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7392/8417 [1:47:18<18:57,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:50 | 200 |  147.444937ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7393/8417 [1:47:19<19:03,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:51 | 200 |  174.428712ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7394/8417 [1:47:20<19:17,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:52 | 200 |  179.866092ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7395/8417 [1:47:21<19:17,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:53 | 200 |  148.718311ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7396/8417 [1:47:22<19:08,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:54 | 200 |  172.518286ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7397/8417 [1:47:23<19:05,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:55 | 200 |  148.494331ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7398/8417 [1:47:24<19:03,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:57 | 200 |  145.630996ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7399/8417 [1:47:26<18:57,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:58 | 200 |  180.166749ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7400/8417 [1:47:27<19:02,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:11:59 | 200 |  141.641427ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7401/8417 [1:47:28<18:51,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:00 | 200 |  180.165867ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7402/8417 [1:47:29<19:10,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:01 | 200 |  118.679828ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7403/8417 [1:47:30<18:55,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:02 | 200 |  196.325071ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7404/8417 [1:47:31<19:16,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:03 | 200 |  177.095993ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7405/8417 [1:47:32<19:08,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:05 | 200 |  159.808919ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7406/8417 [1:47:33<19:09,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:06 | 200 |  142.481122ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7407/8417 [1:47:35<18:56,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:07 | 200 |  173.707397ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7408/8417 [1:47:36<18:53,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:08 | 200 |  124.406326ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7409/8417 [1:47:37<18:46,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:09 | 200 |  140.341658ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7410/8417 [1:47:38<18:47,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:10 | 200 |  171.757846ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7411/8417 [1:47:39<18:54,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:11 | 200 |  149.277448ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7412/8417 [1:47:40<18:44,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:12 | 200 |  176.823619ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7413/8417 [1:47:41<18:50,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:13 | 200 |  145.764118ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7414/8417 [1:47:42<18:39,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:15 | 200 |  179.110255ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7415/8417 [1:47:44<18:42,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:16 | 200 |  121.518863ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7416/8417 [1:47:45<18:30,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:17 | 200 |  177.985119ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7417/8417 [1:47:46<18:33,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:18 | 200 |  147.155218ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7418/8417 [1:47:47<18:26,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:19 | 200 |  141.803428ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7419/8417 [1:47:48<18:38,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:20 | 200 |  175.704316ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7420/8417 [1:47:49<18:47,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:21 | 200 |  145.567398ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7421/8417 [1:47:50<18:41,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:22 | 200 |  177.454735ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7422/8417 [1:47:51<18:43,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:24 | 200 |  143.329926ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7423/8417 [1:47:52<18:32,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:25 | 200 |   171.94655ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7424/8417 [1:47:54<18:43,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:26 | 200 |  180.831042ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7425/8417 [1:47:55<18:41,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:27 | 200 |  146.063457ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7426/8417 [1:47:56<18:27,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:28 | 200 |  180.273901ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7427/8417 [1:47:57<18:27,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:29 | 200 |  150.802383ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7428/8417 [1:47:58<18:27,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:30 | 200 |  142.687546ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7429/8417 [1:47:59<18:32,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:31 | 200 |  181.637863ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7430/8417 [1:48:00<18:32,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:33 | 200 |  142.592687ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7431/8417 [1:48:01<18:22,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:34 | 200 |  201.440529ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7432/8417 [1:48:03<18:42,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:35 | 200 |  155.769212ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7433/8417 [1:48:04<18:35,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:36 | 200 |  120.102705ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7434/8417 [1:48:05<18:17,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:37 | 200 |  181.270312ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7435/8417 [1:48:06<18:19,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:38 | 200 |  145.660758ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7436/8417 [1:48:07<18:07,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:39 | 200 |   177.32675ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7437/8417 [1:48:08<18:13,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:40 | 200 |  149.198636ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7438/8417 [1:48:09<18:20,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:41 | 200 |  166.512518ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7439/8417 [1:48:10<18:14,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:43 | 200 |  155.518412ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7440/8417 [1:48:12<18:07,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:44 | 200 |  153.493997ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7441/8417 [1:48:13<18:00,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:45 | 200 |  145.375842ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7442/8417 [1:48:14<17:58,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:46 | 200 |  148.290494ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7443/8417 [1:48:15<17:56,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:47 | 200 |   172.40346ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7444/8417 [1:48:16<17:58,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:48 | 200 |   148.40865ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7445/8417 [1:48:17<17:58,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:49 | 200 |  183.025965ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7446/8417 [1:48:18<18:19,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:50 | 200 |  146.138896ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7447/8417 [1:48:19<18:25,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:52 | 200 |  118.452268ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7448/8417 [1:48:21<18:25,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:53 | 200 |  181.862721ms |       127.0.0.1 | POST     "/api/chat"

 88%|████████▊ | 7449/8417 [1:48:22<18:38,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:54 | 200 |  178.957918ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7450/8417 [1:48:23<18:30,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:55 | 200 |  124.444716ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7451/8417 [1:48:24<18:18,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:56 | 200 |   181.49154ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7452/8417 [1:48:25<18:28,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:57 | 200 |  174.590302ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7453/8417 [1:48:26<18:30,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:12:59 | 200 |  161.194731ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7454/8417 [1:48:27<18:29,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:00 | 200 |  148.031441ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7455/8417 [1:48:29<18:20,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:01 | 200 |  153.345869ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7456/8417 [1:48:30<18:07,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:02 | 200 |  177.517127ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7457/8417 [1:48:31<18:09,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:03 | 200 |  147.147539ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7458/8417 [1:48:32<17:58,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:04 | 200 |  175.979167ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7459/8417 [1:48:33<18:02,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:05 | 200 |  161.777713ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7460/8417 [1:48:34<18:11,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:07 | 200 |  141.015062ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7461/8417 [1:48:36<19:17,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:08 | 200 |   176.75809ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7462/8417 [1:48:37<18:53,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:09 | 200 |  169.758108ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7463/8417 [1:48:38<18:36,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:10 | 200 |  149.466381ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7464/8417 [1:48:39<18:22,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:11 | 200 |  176.366493ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7465/8417 [1:48:40<18:14,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:12 | 200 |   166.75242ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7466/8417 [1:48:41<18:03,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:13 | 200 |  148.323861ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7467/8417 [1:48:42<17:52,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:15 | 200 |  175.535491ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7468/8417 [1:48:44<17:54,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:16 | 200 |  149.579621ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7469/8417 [1:48:45<17:59,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:17 | 200 |  148.517508ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▊ | 7470/8417 [1:48:46<17:43,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:18 | 200 |  183.833122ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7471/8417 [1:48:47<17:50,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:19 | 200 |  145.440223ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7472/8417 [1:48:48<17:41,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:20 | 200 |  178.231374ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7473/8417 [1:48:49<17:55,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:21 | 200 |  149.301787ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7474/8417 [1:48:50<17:51,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:23 | 200 |  181.316584ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7475/8417 [1:48:51<17:59,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:24 | 200 |  176.522324ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7476/8417 [1:48:53<18:00,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:25 | 200 |  179.593951ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7477/8417 [1:48:54<18:08,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:26 | 200 |  164.769765ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7478/8417 [1:48:55<18:00,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:27 | 200 |   145.91313ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7479/8417 [1:48:56<17:43,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:28 | 200 |  177.983545ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7480/8417 [1:48:57<17:39,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:29 | 200 |  151.302844ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7481/8417 [1:48:58<17:33,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:30 | 200 |  139.518377ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7482/8417 [1:48:59<17:27,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:32 | 200 |  140.720562ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7483/8417 [1:49:01<17:30,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:33 | 200 |  173.867997ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7484/8417 [1:49:02<17:33,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:34 | 200 |  178.807011ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7485/8417 [1:49:03<17:35,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:35 | 200 |  143.948315ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7486/8417 [1:49:04<17:25,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:36 | 200 |  182.345027ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7487/8417 [1:49:05<17:45,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:37 | 200 |  175.277015ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7488/8417 [1:49:06<17:41,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:38 | 200 |  157.334698ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7489/8417 [1:49:07<17:31,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:39 | 200 |  141.671135ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7490/8417 [1:49:08<17:23,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:41 | 200 |  179.847838ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7491/8417 [1:49:10<17:32,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:42 | 200 |  142.059016ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7492/8417 [1:49:11<17:21,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:43 | 200 |  174.701913ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7493/8417 [1:49:12<17:25,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:44 | 200 |  159.996241ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7494/8417 [1:49:13<17:44,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:45 | 200 |  142.354647ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7495/8417 [1:49:14<17:31,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:46 | 200 |  178.200586ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7496/8417 [1:49:15<17:28,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:47 | 200 |  173.086888ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7497/8417 [1:49:16<17:32,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:49 | 200 |  158.189149ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7498/8417 [1:49:18<17:22,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:50 | 200 |  144.077122ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7499/8417 [1:49:19<17:14,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:51 | 200 |   180.85476ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7500/8417 [1:49:20<17:25,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:52 | 200 |  145.890576ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7501/8417 [1:49:21<17:21,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:53 | 200 |  143.999302ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7502/8417 [1:49:22<17:18,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:54 | 200 |  179.454585ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7503/8417 [1:49:23<17:22,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:55 | 200 |  153.799597ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7504/8417 [1:49:24<17:13,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:57 | 200 |  139.240766ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7505/8417 [1:49:26<17:02,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:58 | 200 |  180.043203ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7506/8417 [1:49:27<17:06,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:13:59 | 200 |  121.819604ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7507/8417 [1:49:28<16:55,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:00 | 200 |  177.746786ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7508/8417 [1:49:29<17:14,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:01 | 200 |   152.24765ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7509/8417 [1:49:30<17:04,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:02 | 200 |  147.839928ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7510/8417 [1:49:31<16:56,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:03 | 200 |  175.887007ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7511/8417 [1:49:32<17:00,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:04 | 200 |  146.108369ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7512/8417 [1:49:33<17:04,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:06 | 200 |  145.061278ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7513/8417 [1:49:35<16:56,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:07 | 200 |  139.468791ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7514/8417 [1:49:36<16:48,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:08 | 200 |  171.479276ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7515/8417 [1:49:37<17:15,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:09 | 200 |  183.075125ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7516/8417 [1:49:38<17:18,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:10 | 200 |  177.042735ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7517/8417 [1:49:39<17:22,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:11 | 200 |  147.382504ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7518/8417 [1:49:40<17:08,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:12 | 200 |  146.978634ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7519/8417 [1:49:41<16:59,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:14 | 200 |  169.907642ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7520/8417 [1:49:43<16:57,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:15 | 200 |  148.825337ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7521/8417 [1:49:44<16:55,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:16 | 200 |  141.463513ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7522/8417 [1:49:45<16:50,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:17 | 200 |  179.908453ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7523/8417 [1:49:46<16:58,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:18 | 200 |  143.274728ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7524/8417 [1:49:47<16:46,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:19 | 200 |  171.727569ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7525/8417 [1:49:48<16:59,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:20 | 200 |  174.983099ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7526/8417 [1:49:49<17:02,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:22 | 200 |  117.446664ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7527/8417 [1:49:50<16:50,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:23 | 200 |  176.320094ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7528/8417 [1:49:52<16:59,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:24 | 200 |  179.957819ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7529/8417 [1:49:53<17:17,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:25 | 200 |  130.557443ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7530/8417 [1:49:54<17:01,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:26 | 200 |   177.76843ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7531/8417 [1:49:55<16:59,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:27 | 200 |   117.65781ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7532/8417 [1:49:56<16:37,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:28 | 200 |  179.091724ms |       127.0.0.1 | POST     "/api/chat"

 89%|████████▉ | 7533/8417 [1:49:57<16:56,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:30 | 200 |  155.903655ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7534/8417 [1:49:59<16:47,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:31 | 200 |  145.551296ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7535/8417 [1:50:00<16:43,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:32 | 200 |  180.703928ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7536/8417 [1:50:01<16:37,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:33 | 200 |  142.795802ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7537/8417 [1:50:02<16:32,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:34 | 200 |  174.632911ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7538/8417 [1:50:03<16:30,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:35 | 200 |  159.614496ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7539/8417 [1:50:04<16:28,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:36 | 200 |  147.059276ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7540/8417 [1:50:05<16:23,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:37 | 200 |  181.798317ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7541/8417 [1:50:06<16:25,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:39 | 200 |  147.604715ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7542/8417 [1:50:08<16:22,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:40 | 200 |  185.252806ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7543/8417 [1:50:09<16:44,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:41 | 200 |  169.670616ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7544/8417 [1:50:10<16:42,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:42 | 200 |  179.957027ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7545/8417 [1:50:11<16:41,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:43 | 200 |   144.12703ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7546/8417 [1:50:12<16:58,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:44 | 200 |  141.482893ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7547/8417 [1:50:13<16:50,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:46 | 200 |  181.372556ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7548/8417 [1:50:15<16:49,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:47 | 200 |  165.642788ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7549/8417 [1:50:16<16:39,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:48 | 200 |  161.469253ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7550/8417 [1:50:17<16:31,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:49 | 200 |  144.956845ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7551/8417 [1:50:18<16:19,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:50 | 200 |  179.474462ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7552/8417 [1:50:19<16:25,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:51 | 200 |  126.579375ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7553/8417 [1:50:20<16:11,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:52 | 200 |     178.601ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7554/8417 [1:50:21<16:13,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:53 | 200 |  152.758208ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7555/8417 [1:50:22<16:18,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:55 | 200 |  142.152238ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7556/8417 [1:50:24<16:27,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:56 | 200 |  187.191327ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7557/8417 [1:50:25<16:30,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:57 | 200 |  176.003552ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7558/8417 [1:50:26<16:23,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:58 | 200 |  158.431256ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7559/8417 [1:50:27<16:18,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:14:59 | 200 |  148.526532ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7560/8417 [1:50:28<16:17,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:00 | 200 |  169.133781ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7561/8417 [1:50:29<16:21,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:01 | 200 |  153.382263ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7562/8417 [1:50:30<16:14,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:03 | 200 |   149.57038ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7563/8417 [1:50:32<16:06,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:04 | 200 |  173.156061ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7564/8417 [1:50:33<16:12,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:05 | 200 |  170.482426ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7565/8417 [1:50:34<16:13,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:06 | 200 |  145.315882ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7566/8417 [1:50:35<16:08,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:07 | 200 |  143.774668ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7567/8417 [1:50:36<16:05,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:08 | 200 |  174.960545ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7568/8417 [1:50:37<16:03,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:09 | 200 |  147.428171ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7569/8417 [1:50:38<15:57,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:11 | 200 |  174.317214ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7570/8417 [1:50:40<16:11,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:12 | 200 |   167.05904ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7571/8417 [1:50:41<16:10,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:13 | 200 |  147.397187ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7572/8417 [1:50:42<15:59,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:14 | 200 |  175.608498ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7573/8417 [1:50:43<16:06,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:15 | 200 |  179.144501ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7574/8417 [1:50:44<16:09,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:16 | 200 |   123.11235ms |       127.0.0.1 | POST     "/api/chat"

 90%|████████▉ | 7575/8417 [1:50:45<15:55,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:17 | 200 |  178.729344ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7576/8417 [1:50:46<15:59,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:19 | 200 |  182.007162ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7577/8417 [1:50:48<16:12,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:20 | 200 |  175.747709ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7578/8417 [1:50:49<16:13,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:21 | 200 |   144.45565ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7579/8417 [1:50:50<16:04,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:22 | 200 |  142.779533ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7580/8417 [1:50:51<15:59,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:23 | 200 |  172.970344ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7581/8417 [1:50:52<16:01,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:24 | 200 |  166.668865ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7582/8417 [1:50:53<16:00,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:25 | 200 |  142.804808ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7583/8417 [1:50:54<15:46,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:27 | 200 |  171.519647ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7584/8417 [1:50:56<15:49,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:28 | 200 |  152.873446ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7585/8417 [1:50:57<15:42,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:29 | 200 |  143.786795ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7586/8417 [1:50:58<15:47,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:30 | 200 |  181.895143ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7587/8417 [1:50:59<16:00,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:31 | 200 |  175.814489ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7588/8417 [1:51:00<15:54,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:32 | 200 |  152.736885ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7589/8417 [1:51:01<15:44,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:33 | 200 |  142.806016ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7590/8417 [1:51:02<15:34,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:35 | 200 |  177.035285ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7591/8417 [1:51:04<15:39,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:36 | 200 |   143.32405ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7592/8417 [1:51:05<15:47,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:37 | 200 |  143.845915ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7593/8417 [1:51:06<15:36,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:38 | 200 |  178.412039ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7594/8417 [1:51:07<15:37,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:39 | 200 |   144.40863ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7595/8417 [1:51:08<15:31,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:40 | 200 |  181.046844ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7596/8417 [1:51:09<15:45,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:41 | 200 |  175.566944ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7597/8417 [1:51:10<15:44,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:43 | 200 |  177.474354ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7598/8417 [1:51:12<15:53,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:44 | 200 |  152.728293ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7599/8417 [1:51:13<15:45,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:45 | 200 |  179.727657ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7600/8417 [1:51:14<15:50,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:46 | 200 |  148.071529ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7601/8417 [1:51:15<15:39,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:47 | 200 |  174.864476ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7602/8417 [1:51:16<15:47,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:48 | 200 |  137.276646ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7603/8417 [1:51:17<15:29,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:50 | 200 |  176.639328ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7604/8417 [1:51:19<15:35,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:51 | 200 |  161.547324ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7605/8417 [1:51:20<15:35,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:52 | 200 |  179.242892ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7606/8417 [1:51:21<15:44,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:53 | 200 |  179.248602ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7607/8417 [1:51:22<15:47,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:54 | 200 |  152.701059ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7608/8417 [1:51:23<15:44,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:55 | 200 |  137.236838ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7609/8417 [1:51:24<15:37,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:57 | 200 |  185.688533ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7610/8417 [1:51:26<15:45,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:58 | 200 |  150.043152ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7611/8417 [1:51:27<15:40,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:15:59 | 200 |  177.847708ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7612/8417 [1:51:28<15:31,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:00 | 200 |  121.668451ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7613/8417 [1:51:29<15:14,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:01 | 200 |  166.926534ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7614/8417 [1:51:30<15:09,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:02 | 200 |  155.217132ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7615/8417 [1:51:31<15:04,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:03 | 200 |  137.880436ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7616/8417 [1:51:32<15:00,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:04 | 200 |  149.898841ms |       127.0.0.1 | POST     "/api/chat"

 90%|█████████ | 7617/8417 [1:51:33<15:00,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:06 | 200 |  189.086009ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7618/8417 [1:51:35<15:10,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:07 | 200 |  149.159866ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7619/8417 [1:51:36<14:58,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:08 | 200 |  176.762329ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7620/8417 [1:51:37<15:00,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:09 | 200 |  144.578423ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7621/8417 [1:51:38<14:55,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:10 | 200 |  176.930027ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7622/8417 [1:51:39<15:14,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:11 | 200 |  161.762091ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7623/8417 [1:51:40<15:06,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:12 | 200 |  137.171979ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7624/8417 [1:51:41<14:55,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:14 | 200 |  174.595751ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7625/8417 [1:51:43<14:59,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:15 | 200 |  200.076922ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7626/8417 [1:51:44<15:16,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:16 | 200 |  158.826081ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7627/8417 [1:51:45<15:10,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:17 | 200 |  139.439113ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7628/8417 [1:51:46<15:01,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:18 | 200 |  177.859795ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7629/8417 [1:51:47<15:11,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:19 | 200 |  168.984935ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7630/8417 [1:51:48<15:08,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:21 | 200 |  153.823847ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7631/8417 [1:51:50<15:04,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:22 | 200 |  146.016128ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7632/8417 [1:51:51<14:52,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:23 | 200 |  181.692824ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7633/8417 [1:51:52<14:55,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:24 | 200 |  146.646284ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7634/8417 [1:51:53<14:53,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:25 | 200 |  176.298486ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7635/8417 [1:51:54<14:55,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:26 | 200 |  170.716763ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7636/8417 [1:51:55<14:50,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:27 | 200 |  157.951003ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7637/8417 [1:51:56<14:46,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:28 | 200 |  118.766119ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7638/8417 [1:51:57<14:29,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:30 | 200 |  175.693586ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7639/8417 [1:51:59<14:31,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:31 | 200 |  148.189294ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7640/8417 [1:52:00<14:25,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:32 | 200 |  178.028576ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7641/8417 [1:52:01<14:28,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:33 | 200 |  145.318599ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7642/8417 [1:52:02<14:23,  1.11s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:34 | 200 |  178.771374ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7643/8417 [1:52:03<14:33,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:35 | 200 |  138.389066ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7644/8417 [1:52:04<14:28,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:36 | 200 |  139.767719ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7645/8417 [1:52:05<14:25,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:37 | 200 |  176.625431ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7646/8417 [1:52:06<14:25,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:39 | 200 |  145.861807ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7647/8417 [1:52:07<14:21,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:40 | 200 |  174.240825ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7648/8417 [1:52:09<14:30,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:41 | 200 |  171.577534ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7649/8417 [1:52:10<14:34,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:42 | 200 |  145.604727ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7650/8417 [1:52:11<14:28,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:43 | 200 |  173.365415ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7651/8417 [1:52:12<14:28,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:44 | 200 |     157.848ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7652/8417 [1:52:13<14:31,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:45 | 200 |  141.129402ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7653/8417 [1:52:14<14:23,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:46 | 200 |  178.932715ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7654/8417 [1:52:15<14:27,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:48 | 200 |  157.804151ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7655/8417 [1:52:17<14:24,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:49 | 200 |  145.340376ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7656/8417 [1:52:18<14:23,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:50 | 200 |  176.059698ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7657/8417 [1:52:19<14:33,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:51 | 200 |  171.981745ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7658/8417 [1:52:20<14:33,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:52 | 200 |   144.11738ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7659/8417 [1:52:21<14:25,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:53 | 200 |  144.882001ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7660/8417 [1:52:22<14:23,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:54 | 200 |  178.362096ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7661/8417 [1:52:23<14:26,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:56 | 200 |  138.088772ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7662/8417 [1:52:25<14:21,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:57 | 200 |  188.419356ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7663/8417 [1:52:26<14:21,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:58 | 200 |  160.639998ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7664/8417 [1:52:27<14:16,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:16:59 | 200 |  145.732191ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7665/8417 [1:52:28<14:09,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:00 | 200 |  148.569894ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7666/8417 [1:52:29<14:08,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:01 | 200 |  181.711844ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7667/8417 [1:52:30<14:17,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:02 | 200 |  120.200138ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7668/8417 [1:52:31<14:09,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:04 | 200 |  174.753431ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7669/8417 [1:52:33<14:12,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:05 | 200 |  187.935002ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7670/8417 [1:52:34<14:13,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:06 | 200 |  123.124395ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7671/8417 [1:52:35<14:01,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:07 | 200 |  178.752641ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7672/8417 [1:52:36<14:14,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:08 | 200 |  136.681862ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7673/8417 [1:52:37<13:59,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:09 | 200 |  179.105558ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7674/8417 [1:52:38<14:07,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:10 | 200 |  147.740782ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7675/8417 [1:52:39<14:07,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:12 | 200 |  174.016967ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7676/8417 [1:52:41<14:09,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:13 | 200 |  168.451597ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7677/8417 [1:52:42<14:09,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:14 | 200 |  144.874499ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7678/8417 [1:52:43<14:18,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:15 | 200 |   136.46108ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7679/8417 [1:52:44<14:07,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:16 | 200 |    137.3229ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████ | 7680/8417 [1:52:45<13:59,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:17 | 200 |  142.847006ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7681/8417 [1:52:46<14:05,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:19 | 200 |  189.433125ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7682/8417 [1:52:47<14:10,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:20 | 200 |  155.171453ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7683/8417 [1:52:49<14:04,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:21 | 200 |  204.347009ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7684/8417 [1:52:50<14:10,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:22 | 200 |  177.203622ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7685/8417 [1:52:51<14:11,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:23 | 200 |  157.213813ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7686/8417 [1:52:52<14:03,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:24 | 200 |  147.691327ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7687/8417 [1:52:53<13:54,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:25 | 200 |  178.562749ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7688/8417 [1:52:54<14:04,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:27 | 200 |  175.887682ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7689/8417 [1:52:56<14:01,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:28 | 200 |  143.239717ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7690/8417 [1:52:57<13:58,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:29 | 200 |  140.137824ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7691/8417 [1:52:58<13:51,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:30 | 200 |  177.973902ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7692/8417 [1:52:59<14:05,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:31 | 200 |  180.751967ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7693/8417 [1:53:00<14:23,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:32 | 200 |  149.632935ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7694/8417 [1:53:01<14:08,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:34 | 200 |  180.851055ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7695/8417 [1:53:03<14:33,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:35 | 200 |  147.790557ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7696/8417 [1:53:04<14:24,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:36 | 200 |   143.87461ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7697/8417 [1:53:05<14:07,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:37 | 200 |  180.730619ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7698/8417 [1:53:06<13:57,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:38 | 200 |  148.899377ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7699/8417 [1:53:07<13:43,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:39 | 200 |  180.762076ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7700/8417 [1:53:08<13:44,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:41 | 200 |  155.899948ms |       127.0.0.1 | POST     "/api/chat"

 91%|█████████▏| 7701/8417 [1:53:10<13:43,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:42 | 200 |  141.590166ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7702/8417 [1:53:11<13:31,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:43 | 200 |  179.656899ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7703/8417 [1:53:12<13:38,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:44 | 200 |  157.300553ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7704/8417 [1:53:13<13:36,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:45 | 200 |  139.094923ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7705/8417 [1:53:14<13:29,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:46 | 200 |   181.51779ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7706/8417 [1:53:15<13:41,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:48 | 200 |  178.127277ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7707/8417 [1:53:17<13:43,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:49 | 200 |  179.265499ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7708/8417 [1:53:18<13:50,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:50 | 200 |  154.850556ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7709/8417 [1:53:19<13:49,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:51 | 200 |  140.408793ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7710/8417 [1:53:20<13:38,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:52 | 200 |  180.751329ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7711/8417 [1:53:21<13:36,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:53 | 200 |  173.545985ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7712/8417 [1:53:22<13:35,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:54 | 200 |   129.97616ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7713/8417 [1:53:23<13:21,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:56 | 200 |  181.576105ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7714/8417 [1:53:25<13:25,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:57 | 200 |  174.748131ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7715/8417 [1:53:26<13:23,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:58 | 200 |  158.592511ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7716/8417 [1:53:27<13:19,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:17:59 | 200 |  150.524513ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7717/8417 [1:53:28<13:16,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:00 | 200 |  178.705312ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7718/8417 [1:53:29<13:21,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:01 | 200 |  158.528188ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7719/8417 [1:53:30<13:28,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:02 | 200 |  148.679963ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7720/8417 [1:53:31<13:23,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:04 | 200 |  147.107911ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7721/8417 [1:53:33<13:22,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:05 | 200 |  181.810556ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7722/8417 [1:53:34<13:29,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:06 | 200 |  185.621777ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7723/8417 [1:53:35<13:34,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:07 | 200 |   184.12992ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7724/8417 [1:53:36<13:41,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:08 | 200 |  165.174879ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7725/8417 [1:53:37<13:37,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:10 | 200 |   177.04818ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7726/8417 [1:53:39<13:41,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:11 | 200 |  187.052241ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7727/8417 [1:53:40<13:36,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:12 | 200 |  138.527059ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7728/8417 [1:53:41<13:23,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:13 | 200 |  171.335577ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7729/8417 [1:53:42<13:26,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:14 | 200 |  142.192366ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7730/8417 [1:53:43<13:13,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:15 | 200 |  177.687967ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7731/8417 [1:53:44<13:13,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:16 | 200 |  154.666482ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7732/8417 [1:53:45<13:06,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:18 | 200 |  149.219963ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7733/8417 [1:53:47<13:04,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:19 | 200 |  180.435399ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7734/8417 [1:53:48<13:10,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:20 | 200 |  179.537229ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7735/8417 [1:53:49<13:16,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:21 | 200 |  139.955926ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7736/8417 [1:53:50<13:07,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:22 | 200 |  146.601621ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7737/8417 [1:53:51<13:01,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:23 | 200 |  178.491459ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7738/8417 [1:53:52<13:10,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:25 | 200 |  186.921581ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7739/8417 [1:53:54<13:09,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:26 | 200 |  176.386652ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7740/8417 [1:53:55<13:04,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:27 | 200 |  140.243684ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7741/8417 [1:53:56<12:59,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:28 | 200 |  173.050497ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7742/8417 [1:53:57<13:01,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:29 | 200 |  171.358714ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7743/8417 [1:53:58<13:02,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:30 | 200 |  178.329977ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7744/8417 [1:53:59<13:01,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:32 | 200 |  149.584179ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7745/8417 [1:54:01<12:50,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:33 | 200 |   141.94969ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7746/8417 [1:54:02<12:41,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:34 | 200 |  179.696701ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7747/8417 [1:54:03<12:46,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:35 | 200 |  145.298528ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7748/8417 [1:54:04<12:40,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:36 | 200 |   139.90445ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7749/8417 [1:54:05<12:34,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:37 | 200 |  179.216836ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7750/8417 [1:54:06<12:40,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:38 | 200 |  150.235697ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7751/8417 [1:54:07<12:38,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:39 | 200 |  145.094495ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7752/8417 [1:54:08<12:35,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:41 | 200 |  145.675348ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7753/8417 [1:54:10<12:34,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:42 | 200 |  170.464878ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7754/8417 [1:54:11<12:35,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:43 | 200 |  143.776949ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7755/8417 [1:54:12<12:33,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:44 | 200 |  181.450895ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7756/8417 [1:54:13<12:37,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:45 | 200 |  143.944051ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7757/8417 [1:54:14<12:35,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:46 | 200 |  178.200369ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7758/8417 [1:54:15<12:39,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:48 | 200 |  164.068987ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7759/8417 [1:54:17<12:41,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:49 | 200 |  181.592909ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7760/8417 [1:54:18<12:48,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:50 | 200 |  177.325225ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7761/8417 [1:54:19<12:59,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:51 | 200 |  184.951462ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7762/8417 [1:54:20<13:08,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:52 | 200 |  181.275899ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7763/8417 [1:54:21<13:13,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:54 | 200 |  157.951998ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7764/8417 [1:54:23<13:07,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:55 | 200 |  153.321827ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7765/8417 [1:54:24<13:01,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:56 | 200 |  184.074256ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7766/8417 [1:54:25<13:25,  1.24s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:57 | 200 |  174.678008ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7767/8417 [1:54:26<13:15,  1.22s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:18:59 | 200 |  172.593233ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7768/8417 [1:54:28<13:06,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:00 | 200 |  156.960086ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7769/8417 [1:54:29<12:50,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:01 | 200 |   165.71922ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7770/8417 [1:54:30<12:38,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:02 | 200 |  184.199659ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7771/8417 [1:54:31<12:35,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:03 | 200 |  173.213788ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7772/8417 [1:54:32<12:33,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:04 | 200 |  125.326127ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7773/8417 [1:54:33<12:25,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:05 | 200 |  176.828046ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7774/8417 [1:54:34<12:23,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:07 | 200 |  140.662437ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7775/8417 [1:54:36<12:19,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:08 | 200 |  177.776476ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7776/8417 [1:54:37<12:19,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:09 | 200 |  119.662398ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7777/8417 [1:54:38<12:07,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:10 | 200 |  177.516768ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7778/8417 [1:54:39<12:14,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:11 | 200 |  157.587516ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7779/8417 [1:54:40<12:15,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:12 | 200 |  117.604858ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7780/8417 [1:54:41<12:02,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:13 | 200 |  177.976234ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7781/8417 [1:54:42<12:07,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:15 | 200 |   171.32804ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7782/8417 [1:54:44<12:11,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:16 | 200 |  150.332097ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7783/8417 [1:54:45<12:07,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:17 | 200 |  145.823606ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7784/8417 [1:54:46<12:09,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:18 | 200 |  186.963388ms |       127.0.0.1 | POST     "/api/chat"

 92%|█████████▏| 7785/8417 [1:54:47<12:13,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:19 | 200 |  167.070379ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7786/8417 [1:54:48<12:12,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:20 | 200 |  165.088612ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7787/8417 [1:54:49<12:12,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:21 | 200 |  145.845584ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7788/8417 [1:54:50<12:03,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:23 | 200 |  179.631301ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7789/8417 [1:54:52<12:06,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:24 | 200 |   171.90958ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7790/8417 [1:54:53<12:14,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:25 | 200 |  193.745594ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7791/8417 [1:54:54<12:13,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:26 | 200 |  177.855793ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7792/8417 [1:54:55<12:12,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:27 | 200 |  160.975372ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7793/8417 [1:54:56<12:07,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:29 | 200 |  132.635973ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7794/8417 [1:54:58<12:07,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:30 | 200 |  184.962345ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7795/8417 [1:54:59<12:08,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:31 | 200 |  126.275378ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7796/8417 [1:55:00<11:56,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:32 | 200 |  181.670447ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7797/8417 [1:55:01<11:57,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:33 | 200 |  141.671841ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7798/8417 [1:55:02<12:02,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:34 | 200 |  132.824962ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7799/8417 [1:55:03<11:49,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:35 | 200 |  176.878693ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7800/8417 [1:55:04<11:50,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:37 | 200 |  166.994861ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7801/8417 [1:55:06<11:57,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:38 | 200 |  163.619408ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7802/8417 [1:55:07<11:53,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:39 | 200 |  138.825055ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7803/8417 [1:55:08<11:44,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:40 | 200 |  186.317714ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7804/8417 [1:55:09<11:54,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:41 | 200 |  178.414487ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7805/8417 [1:55:10<11:59,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:42 | 200 |  178.142038ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7806/8417 [1:55:11<11:57,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:44 | 200 |  177.049724ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7807/8417 [1:55:13<11:59,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:45 | 200 |  164.967229ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7808/8417 [1:55:14<11:56,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:46 | 200 |  139.655334ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7809/8417 [1:55:15<11:48,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:47 | 200 |  180.354045ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7810/8417 [1:55:16<11:51,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:48 | 200 |  146.585625ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7811/8417 [1:55:17<11:41,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:49 | 200 |  181.513337ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7812/8417 [1:55:18<11:41,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:51 | 200 |  149.016842ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7813/8417 [1:55:20<11:41,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:52 | 200 |   142.38311ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7814/8417 [1:55:21<11:34,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:53 | 200 |  175.203599ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7815/8417 [1:55:22<11:34,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:54 | 200 |  180.381888ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7816/8417 [1:55:23<11:34,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:55 | 200 |  116.246581ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7817/8417 [1:55:24<11:40,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:56 | 200 |  199.246608ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7818/8417 [1:55:25<11:43,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:58 | 200 |  139.739576ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7819/8417 [1:55:27<11:53,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:19:59 | 200 |   146.68365ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7820/8417 [1:55:28<11:41,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:00 | 200 |  178.169086ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7821/8417 [1:55:29<11:44,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:01 | 200 |   147.09855ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7822/8417 [1:55:30<11:35,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:02 | 200 |  177.789367ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7823/8417 [1:55:31<11:32,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:03 | 200 |  166.522365ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7824/8417 [1:55:32<11:28,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:05 | 200 |   143.04219ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7825/8417 [1:55:34<11:24,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:06 | 200 |  175.924983ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7826/8417 [1:55:35<11:25,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:07 | 200 |  177.524616ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7827/8417 [1:55:36<11:26,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:08 | 200 |  179.008984ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7828/8417 [1:55:37<11:29,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:09 | 200 |  152.609716ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7829/8417 [1:55:38<11:28,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:10 | 200 |  144.678332ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7830/8417 [1:55:39<11:24,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:12 | 200 |  182.787048ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7831/8417 [1:55:41<11:28,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:13 | 200 |  143.286016ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7832/8417 [1:55:42<11:22,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:14 | 200 |  184.334087ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7833/8417 [1:55:43<11:29,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:15 | 200 |  179.353868ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7834/8417 [1:55:44<11:35,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:16 | 200 |  172.362682ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7835/8417 [1:55:45<11:35,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:18 | 200 |  146.487042ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7836/8417 [1:55:47<11:27,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:19 | 200 |  177.435299ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7837/8417 [1:55:48<11:44,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:20 | 200 |  145.027396ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7838/8417 [1:55:49<11:35,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:21 | 200 |  147.965894ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7839/8417 [1:55:50<11:18,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:22 | 200 |  176.646009ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7840/8417 [1:55:51<11:20,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:23 | 200 |  142.741487ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7841/8417 [1:55:52<11:08,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:25 | 200 |  177.552727ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7842/8417 [1:55:54<11:06,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:26 | 200 |  179.054738ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7843/8417 [1:55:55<11:09,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:27 | 200 |   181.44573ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7844/8417 [1:55:56<11:13,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:28 | 200 |  151.885829ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7845/8417 [1:55:57<11:07,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:29 | 200 |  140.997062ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7846/8417 [1:55:58<10:59,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:30 | 200 |  176.873805ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7847/8417 [1:55:59<11:02,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:32 | 200 |  181.881619ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7848/8417 [1:56:01<11:05,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:33 | 200 |  173.007467ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7849/8417 [1:56:02<11:02,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:34 | 200 |  164.704568ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7850/8417 [1:56:03<10:58,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:35 | 200 |  134.274129ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7851/8417 [1:56:04<10:49,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:36 | 200 |  177.919593ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7852/8417 [1:56:05<10:47,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:37 | 200 |  170.321605ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7853/8417 [1:56:06<10:46,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:38 | 200 |  141.668415ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7854/8417 [1:56:07<10:41,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:40 | 200 |  146.939246ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7855/8417 [1:56:09<10:41,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:41 | 200 |  202.474044ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7856/8417 [1:56:10<10:46,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:42 | 200 |  143.560994ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7857/8417 [1:56:11<10:39,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:43 | 200 |  117.214659ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7858/8417 [1:56:12<10:27,  1.12s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:44 | 200 |  176.654455ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7859/8417 [1:56:13<10:33,  1.13s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:45 | 200 |  142.968431ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7860/8417 [1:56:14<10:32,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:46 | 200 |  145.155975ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7861/8417 [1:56:15<10:32,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:48 | 200 |  175.919355ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7862/8417 [1:56:17<10:34,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:49 | 200 |  143.870036ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7863/8417 [1:56:18<10:34,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:50 | 200 |  144.750693ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7864/8417 [1:56:19<10:35,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:51 | 200 |  180.002702ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7865/8417 [1:56:20<10:40,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:52 | 200 |  178.407493ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7866/8417 [1:56:21<10:49,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:54 | 200 |  177.932275ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7867/8417 [1:56:23<10:49,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:55 | 200 |  180.276204ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7868/8417 [1:56:24<10:49,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:56 | 200 |  164.207874ms |       127.0.0.1 | POST     "/api/chat"

 93%|█████████▎| 7869/8417 [1:56:25<10:44,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:57 | 200 |  156.589446ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7870/8417 [1:56:26<10:38,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:58 | 200 |  140.035455ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7871/8417 [1:56:27<10:38,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:20:59 | 200 |  185.259222ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7872/8417 [1:56:28<10:38,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:01 | 200 |  175.134152ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7873/8417 [1:56:30<10:39,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:02 | 200 |  171.105506ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7874/8417 [1:56:31<10:32,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:03 | 200 |  156.744948ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7875/8417 [1:56:32<10:31,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:04 | 200 |   145.49998ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7876/8417 [1:56:33<10:27,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:05 | 200 |  179.757005ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7877/8417 [1:56:34<10:31,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:06 | 200 |  166.044255ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7878/8417 [1:56:35<10:28,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:08 | 200 |  178.163115ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7879/8417 [1:56:37<10:28,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:09 | 200 |  159.892785ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7880/8417 [1:56:38<10:26,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:10 | 200 |  137.950286ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7881/8417 [1:56:39<10:21,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:11 | 200 |  180.327078ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7882/8417 [1:56:40<10:21,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:12 | 200 |  173.843339ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7883/8417 [1:56:41<10:22,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:13 | 200 |   179.38393ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7884/8417 [1:56:42<10:28,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:15 | 200 |  178.956174ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7885/8417 [1:56:44<10:35,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:16 | 200 |  180.026915ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7886/8417 [1:56:45<10:30,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:17 | 200 |  139.874877ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7887/8417 [1:56:46<10:18,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:18 | 200 |  168.011844ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7888/8417 [1:56:47<10:16,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:19 | 200 |  153.372445ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7889/8417 [1:56:48<10:10,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:20 | 200 |   141.56039ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▎| 7890/8417 [1:56:49<10:08,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:21 | 200 |  172.934887ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7891/8417 [1:56:50<10:06,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:23 | 200 |   118.75234ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7892/8417 [1:56:52<09:59,  1.14s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:24 | 200 |  178.337387ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7893/8417 [1:56:53<10:03,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:25 | 200 |  174.122011ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7894/8417 [1:56:54<10:08,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:26 | 200 |  164.959695ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7895/8417 [1:56:55<10:08,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:27 | 200 |  145.218955ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7896/8417 [1:56:56<09:59,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:28 | 200 |   171.97486ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7897/8417 [1:56:57<10:01,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:30 | 200 |  173.215485ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7898/8417 [1:56:59<10:07,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:31 | 200 |  205.950709ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7899/8417 [1:57:00<10:11,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:32 | 200 |  181.683432ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7900/8417 [1:57:01<10:08,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:33 | 200 |  144.583132ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7901/8417 [1:57:02<10:01,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:34 | 200 |  171.724937ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7902/8417 [1:57:03<09:57,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:35 | 200 |  152.272016ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7903/8417 [1:57:04<09:54,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:37 | 200 |  176.577444ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7904/8417 [1:57:06<09:55,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:38 | 200 |  161.815418ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7905/8417 [1:57:07<09:52,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:39 | 200 |  113.230681ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7906/8417 [1:57:08<09:50,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:40 | 200 |  172.682867ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7907/8417 [1:57:09<09:54,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:41 | 200 |  174.380303ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7908/8417 [1:57:10<09:54,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:42 | 200 |  179.333241ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7909/8417 [1:57:11<09:55,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:44 | 200 |  164.630766ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7910/8417 [1:57:13<09:53,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:45 | 200 |  148.725049ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7911/8417 [1:57:14<09:50,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:46 | 200 |  139.320858ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7912/8417 [1:57:15<09:45,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:47 | 200 |   181.26363ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7913/8417 [1:57:16<09:51,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:48 | 200 |  151.661591ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7914/8417 [1:57:17<09:48,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:49 | 200 |  181.812382ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7915/8417 [1:57:18<09:50,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:51 | 200 |   180.77973ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7916/8417 [1:57:20<09:59,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:52 | 200 |  176.342841ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7917/8417 [1:57:21<09:56,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:53 | 200 |  186.879937ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7918/8417 [1:57:22<10:03,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:54 | 200 |  142.271508ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7919/8417 [1:57:23<09:52,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:55 | 200 |  142.324129ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7920/8417 [1:57:24<09:43,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:57 | 200 |  137.813334ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7921/8417 [1:57:26<09:36,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:58 | 200 |  178.416884ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7922/8417 [1:57:27<09:35,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:21:59 | 200 |  168.500648ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7923/8417 [1:57:28<09:32,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:00 | 200 |  161.748317ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7924/8417 [1:57:29<09:32,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:01 | 200 |  145.097334ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7925/8417 [1:57:30<09:34,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:02 | 200 |  154.125438ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7926/8417 [1:57:31<09:32,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:04 | 200 |   179.22081ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7927/8417 [1:57:33<09:55,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:05 | 200 |  179.139807ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7928/8417 [1:57:34<09:47,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:06 | 200 |  160.682013ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7929/8417 [1:57:35<09:40,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:07 | 200 |  141.319117ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7930/8417 [1:57:36<09:30,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:08 | 200 |  165.179711ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7931/8417 [1:57:37<09:24,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:09 | 200 |  183.658586ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7932/8417 [1:57:39<09:26,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:11 | 200 |  144.529205ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7933/8417 [1:57:40<09:26,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:12 | 200 |  140.158303ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7934/8417 [1:57:41<09:19,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:13 | 200 |  179.002733ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7935/8417 [1:57:42<09:22,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:14 | 200 |  167.521665ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7936/8417 [1:57:43<09:20,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:15 | 200 |  184.503243ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7937/8417 [1:57:44<09:23,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:17 | 200 |  174.679607ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7938/8417 [1:57:46<09:19,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:18 | 200 |  142.333002ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7939/8417 [1:57:47<09:13,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:19 | 200 |  183.638191ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7940/8417 [1:57:48<09:13,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:20 | 200 |  165.486555ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7941/8417 [1:57:49<09:15,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:21 | 200 |   179.72453ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7942/8417 [1:57:50<09:11,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:22 | 200 |  153.791914ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7943/8417 [1:57:51<09:10,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:23 | 200 |  146.464858ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7944/8417 [1:57:52<09:07,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:25 | 200 |  139.814232ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7945/8417 [1:57:54<09:10,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:26 | 200 |  174.658387ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7946/8417 [1:57:55<09:12,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:27 | 200 |  178.489083ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7947/8417 [1:57:56<09:10,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:28 | 200 |    175.0722ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7948/8417 [1:57:57<09:09,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:29 | 200 |  161.648267ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7949/8417 [1:57:58<09:08,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:30 | 200 |  139.236963ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7950/8417 [1:57:59<09:03,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:32 | 200 |  182.327637ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7951/8417 [1:58:01<09:03,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:33 | 200 |  167.406823ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7952/8417 [1:58:02<09:12,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:34 | 200 |  202.101827ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7953/8417 [1:58:03<09:19,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:35 | 200 |   143.05376ms |       127.0.0.1 | POST     "/api/chat"

 94%|█████████▍| 7954/8417 [1:58:04<09:10,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:36 | 200 |  152.294232ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7955/8417 [1:58:05<09:04,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:38 | 200 |   183.42586ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7956/8417 [1:58:07<09:08,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:39 | 200 |  171.923116ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7957/8417 [1:58:08<09:04,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:40 | 200 |  179.462726ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7958/8417 [1:58:09<09:09,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:41 | 200 |    174.0478ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7959/8417 [1:58:10<09:06,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:42 | 200 |  177.209845ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7960/8417 [1:58:11<09:09,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:44 | 200 |  178.152716ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7961/8417 [1:58:13<09:07,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:45 | 200 |  179.919025ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7962/8417 [1:58:14<08:59,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:46 | 200 |  154.542235ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7963/8417 [1:58:15<08:52,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:47 | 200 |   143.61889ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7964/8417 [1:58:16<08:42,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:48 | 200 |  139.232823ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7965/8417 [1:58:17<08:39,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:49 | 200 |  174.525801ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7966/8417 [1:58:18<08:42,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:51 | 200 |  142.714015ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7967/8417 [1:58:20<08:41,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:52 | 200 |  181.647419ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7968/8417 [1:58:21<08:40,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:53 | 200 |  166.145741ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7969/8417 [1:58:22<08:39,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:54 | 200 |  175.253799ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7970/8417 [1:58:23<08:40,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:55 | 200 |  151.435139ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7971/8417 [1:58:24<08:41,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:56 | 200 |  137.742603ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7972/8417 [1:58:25<08:38,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:58 | 200 |  179.233719ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7973/8417 [1:58:27<08:39,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:22:59 | 200 |  149.604341ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7974/8417 [1:58:28<08:36,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:00 | 200 |  179.116939ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7975/8417 [1:58:29<08:40,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:01 | 200 |  174.151457ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7976/8417 [1:58:30<08:38,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:02 | 200 |  131.862225ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7977/8417 [1:58:31<08:29,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:03 | 200 |  182.370951ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7978/8417 [1:58:32<08:31,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:05 | 200 |  144.154013ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7979/8417 [1:58:34<08:34,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:06 | 200 |  184.106606ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7980/8417 [1:58:35<08:39,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:07 | 200 |  149.006344ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7981/8417 [1:58:36<08:32,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:08 | 200 |  179.924629ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7982/8417 [1:58:37<08:33,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:09 | 200 |  176.659354ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7983/8417 [1:58:38<08:32,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:11 | 200 |  180.253039ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7984/8417 [1:58:40<08:36,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:12 | 200 |  175.965998ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7985/8417 [1:58:41<08:33,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:13 | 200 |  173.137814ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7986/8417 [1:58:42<08:36,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:14 | 200 |  182.611116ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7987/8417 [1:58:43<08:34,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:15 | 200 |  170.142274ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7988/8417 [1:58:44<08:33,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:17 | 200 |  160.537085ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7989/8417 [1:58:46<08:30,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:18 | 200 |  157.320955ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7990/8417 [1:58:47<08:29,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:19 | 200 |  144.592207ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7991/8417 [1:58:48<08:25,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:20 | 200 |  137.161568ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7992/8417 [1:58:49<08:23,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:21 | 200 |  184.829999ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7993/8417 [1:58:50<08:24,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:23 | 200 |  154.619481ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7994/8417 [1:58:52<08:31,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:24 | 200 |  140.155171ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7995/8417 [1:58:53<08:23,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:25 | 200 |  178.175932ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▍| 7996/8417 [1:58:54<08:31,  1.22s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:26 | 200 |  151.808359ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 7997/8417 [1:58:55<08:29,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:27 | 200 |  152.892093ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 7998/8417 [1:58:56<08:30,  1.22s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:29 | 200 |  176.963281ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 7999/8417 [1:58:58<08:47,  1.26s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:30 | 200 |  142.224919ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8000/8417 [1:58:59<08:32,  1.23s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:31 | 200 |  177.996211ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8001/8417 [1:59:00<08:22,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:32 | 200 |  151.861346ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8002/8417 [1:59:01<08:13,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:33 | 200 |  181.184941ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8003/8417 [1:59:02<08:08,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:34 | 200 |  149.078427ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8004/8417 [1:59:03<08:00,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:36 | 200 |  142.391321ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8005/8417 [1:59:05<07:56,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:37 | 200 |   185.30631ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8006/8417 [1:59:06<07:59,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:38 | 200 |  177.395851ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8007/8417 [1:59:07<07:59,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:39 | 200 |  159.321966ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8008/8417 [1:59:08<07:58,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:40 | 200 |  139.406464ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8009/8417 [1:59:09<07:56,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:42 | 200 |   182.37637ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8010/8417 [1:59:11<07:59,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:43 | 200 |  149.029566ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8011/8417 [1:59:12<07:51,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:44 | 200 |  183.826753ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8012/8417 [1:59:13<07:52,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:45 | 200 |  162.859556ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8013/8417 [1:59:14<07:48,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:46 | 200 |  142.993932ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8014/8417 [1:59:15<07:47,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:47 | 200 |  144.863877ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8015/8417 [1:59:16<07:45,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:48 | 200 |   180.48208ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8016/8417 [1:59:17<07:46,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:50 | 200 |  173.809498ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8017/8417 [1:59:19<07:45,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:51 | 200 |  168.787396ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8018/8417 [1:59:20<07:52,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:52 | 200 |  174.678821ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8019/8417 [1:59:21<07:48,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:53 | 200 |  148.205511ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8020/8417 [1:59:22<07:42,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:54 | 200 |  141.170722ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8021/8417 [1:59:23<07:41,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:55 | 200 |  179.061908ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8022/8417 [1:59:25<07:42,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:57 | 200 |  175.591597ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8023/8417 [1:59:26<07:42,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:58 | 200 |  180.356001ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8024/8417 [1:59:27<07:44,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:23:59 | 200 |  175.128931ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8025/8417 [1:59:28<07:40,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:00 | 200 |  147.328991ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8026/8417 [1:59:29<07:40,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:01 | 200 |  139.878753ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8027/8417 [1:59:30<07:35,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:03 | 200 |  181.619351ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8028/8417 [1:59:32<07:40,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:04 | 200 |  145.199097ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8029/8417 [1:59:33<07:34,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:05 | 200 |  181.719252ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8030/8417 [1:59:34<07:37,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:06 | 200 |  155.094009ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8031/8417 [1:59:35<07:40,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:07 | 200 |    154.4852ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8032/8417 [1:59:36<07:41,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:09 | 200 |  185.045401ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8033/8417 [1:59:38<07:37,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:10 | 200 |  181.904162ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8034/8417 [1:59:39<07:40,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:11 | 200 |  184.713272ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8035/8417 [1:59:40<07:38,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:12 | 200 |   162.20162ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8036/8417 [1:59:41<07:32,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:13 | 200 |  177.492786ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8037/8417 [1:59:42<07:30,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:14 | 200 |  171.414092ms |       127.0.0.1 | POST     "/api/chat"

 95%|█████████▌| 8038/8417 [1:59:44<07:27,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:16 | 200 |  146.248494ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8039/8417 [1:59:45<07:22,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:17 | 200 |  143.503069ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8040/8417 [1:59:46<07:25,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:18 | 200 |  143.143249ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8041/8417 [1:59:47<07:25,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:19 | 200 |  179.241249ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8042/8417 [1:59:48<07:22,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:20 | 200 |  152.784033ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8043/8417 [1:59:49<07:20,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:22 | 200 |  182.775852ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8044/8417 [1:59:51<07:21,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:23 | 200 |  175.199957ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8045/8417 [1:59:52<07:18,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:24 | 200 |  177.668964ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8046/8417 [1:59:53<07:16,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:25 | 200 |  140.042788ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8047/8417 [1:59:54<07:10,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:26 | 200 |  184.312563ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8048/8417 [1:59:55<07:12,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:27 | 200 |  149.961422ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8049/8417 [1:59:56<07:08,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:29 | 200 |  179.402303ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8050/8417 [1:59:58<07:09,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:30 | 200 |  178.895524ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8051/8417 [1:59:59<07:11,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:31 | 200 |  151.667889ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8052/8417 [2:00:00<07:07,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:32 | 200 |  138.930886ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8053/8417 [2:00:01<07:00,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:33 | 200 |  179.289572ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8054/8417 [2:00:02<07:04,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:34 | 200 |  170.059988ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8055/8417 [2:00:03<07:04,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:36 | 200 |  179.115352ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8056/8417 [2:00:05<07:02,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:37 | 200 |  181.296068ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8057/8417 [2:00:06<07:01,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:38 | 200 |   151.07565ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8058/8417 [2:00:07<06:57,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:39 | 200 |  144.129237ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8059/8417 [2:00:08<07:03,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:40 | 200 |  200.485207ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8060/8417 [2:00:09<07:09,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:41 | 200 |  118.331356ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8061/8417 [2:00:11<06:59,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:43 | 200 |  180.300758ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8062/8417 [2:00:12<06:57,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:44 | 200 |  128.815148ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8063/8417 [2:00:13<06:54,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:45 | 200 |  179.376624ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8064/8417 [2:00:14<07:01,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:46 | 200 |  166.488599ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8065/8417 [2:00:15<07:01,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:47 | 200 |  155.769114ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8066/8417 [2:00:16<06:57,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:49 | 200 |  177.383163ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8067/8417 [2:00:18<06:52,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:50 | 200 |  135.178791ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8068/8417 [2:00:19<06:47,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:51 | 200 |  176.640536ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8069/8417 [2:00:20<06:45,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:52 | 200 |   149.16858ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8070/8417 [2:00:21<06:44,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:53 | 200 |   179.82586ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8071/8417 [2:00:22<06:44,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:54 | 200 |  178.340128ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8072/8417 [2:00:23<06:47,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:56 | 200 |  164.375978ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8073/8417 [2:00:25<06:45,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:57 | 200 |  160.212801ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8074/8417 [2:00:26<06:42,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:58 | 200 |  147.677483ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8075/8417 [2:00:27<06:37,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:24:59 | 200 |  175.637696ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8076/8417 [2:00:28<06:37,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:00 | 200 |  178.565027ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8077/8417 [2:00:29<06:40,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:02 | 200 |  179.406048ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8078/8417 [2:00:31<06:42,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:03 | 200 |  185.350122ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8079/8417 [2:00:32<06:40,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:04 | 200 |  142.791761ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8080/8417 [2:00:33<06:34,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:05 | 200 |  137.374777ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8081/8417 [2:00:34<06:28,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:06 | 200 |  174.976548ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8082/8417 [2:00:35<06:31,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:07 | 200 |  163.314035ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8083/8417 [2:00:36<06:27,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:08 | 200 |  178.534545ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8084/8417 [2:00:37<06:27,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:10 | 200 |  125.063884ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8085/8417 [2:00:39<06:22,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:11 | 200 |  154.007109ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8086/8417 [2:00:40<06:26,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:12 | 200 |  175.873963ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8087/8417 [2:00:41<06:24,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:13 | 200 |  164.313352ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8088/8417 [2:00:42<06:25,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:14 | 200 |  177.773935ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8089/8417 [2:00:43<06:25,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:16 | 200 |  175.428672ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8090/8417 [2:00:45<06:24,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:17 | 200 |  162.711997ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8091/8417 [2:00:46<06:22,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:18 | 200 |  141.901412ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8092/8417 [2:00:47<06:17,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:19 | 200 |  167.352785ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8093/8417 [2:00:48<06:17,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:20 | 200 |  166.002172ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8094/8417 [2:00:49<06:20,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:21 | 200 |  144.132227ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8095/8417 [2:00:50<06:15,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:22 | 200 |  145.182564ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8096/8417 [2:00:51<06:12,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:24 | 200 |  170.634027ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8097/8417 [2:00:53<06:11,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:25 | 200 |  143.770064ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8098/8417 [2:00:54<06:09,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:26 | 200 |  181.720248ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8099/8417 [2:00:55<06:12,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:27 | 200 |  178.419471ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8100/8417 [2:00:56<06:12,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:28 | 200 |  139.280069ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▌| 8101/8417 [2:00:57<06:08,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:29 | 200 |  167.320824ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8102/8417 [2:00:59<06:07,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

 96%|█████████▋| 8103/8417 [2:01:00<06:07,  1.17s/it]

[GIN] 2025/06/27 - 01:25:31 | 200 |  152.135241ms |       127.0.0.1 | POST     "/api/chat"

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:32 | 200 |  142.983939ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8104/8417 [2:01:01<06:01,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:33 | 200 |  178.696319ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8105/8417 [2:01:02<06:01,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:34 | 200 |   156.00162ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8106/8417 [2:01:03<06:01,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:35 | 200 |   137.28297ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8107/8417 [2:01:04<05:59,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:36 | 200 |  186.116041ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8108/8417 [2:01:05<06:01,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:38 | 200 |  154.742132ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8109/8417 [2:01:07<05:57,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:39 | 200 |  172.219783ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8110/8417 [2:01:08<05:57,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:40 | 200 |  158.579059ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8111/8417 [2:01:09<05:57,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:41 | 200 |  137.785031ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8112/8417 [2:01:10<05:54,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:42 | 200 |  180.558717ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8113/8417 [2:01:11<05:59,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:43 | 200 |  153.560361ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8114/8417 [2:01:13<05:56,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:45 | 200 |  149.523643ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8115/8417 [2:01:14<05:52,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:46 | 200 |  141.072757ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8116/8417 [2:01:15<05:48,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:47 | 200 |  182.499497ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8117/8417 [2:01:16<05:48,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:48 | 200 |  150.563909ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8118/8417 [2:01:17<05:45,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:49 | 200 |  147.074031ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8119/8417 [2:01:18<05:42,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:50 | 200 |  175.664113ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8120/8417 [2:01:19<05:46,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:52 | 200 |  146.813177ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8121/8417 [2:01:21<05:44,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:53 | 200 |  124.157197ms |       127.0.0.1 | POST     "/api/chat"

 96%|█████████▋| 8122/8417 [2:01:22<05:41,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:54 | 200 |  178.673975ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8123/8417 [2:01:23<05:43,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:55 | 200 |  147.451625ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8124/8417 [2:01:24<05:42,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:56 | 200 |  180.145496ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8125/8417 [2:01:25<05:44,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:58 | 200 |  182.039928ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8126/8417 [2:01:27<05:50,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:25:59 | 200 |  138.903392ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8127/8417 [2:01:28<05:45,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:00 | 200 |  178.098632ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8128/8417 [2:01:29<05:47,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:01 | 200 |  160.767671ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8129/8417 [2:01:30<05:45,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:02 | 200 |  153.483073ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8130/8417 [2:01:31<05:40,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:03 | 200 |  175.065019ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8131/8417 [2:01:32<05:37,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:05 | 200 |  155.801901ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8132/8417 [2:01:34<05:38,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:06 | 200 |  121.847037ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8133/8417 [2:01:35<05:36,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:07 | 200 |  179.557767ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8134/8417 [2:01:36<05:37,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:08 | 200 |  148.937905ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8135/8417 [2:01:37<05:46,  1.23s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:09 | 200 |   144.25296ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8136/8417 [2:01:39<05:36,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:11 | 200 |  178.284419ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8137/8417 [2:01:40<05:35,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:12 | 200 |  163.079809ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8138/8417 [2:01:41<05:29,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:13 | 200 |  143.207493ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8139/8417 [2:01:42<05:24,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:14 | 200 |  201.601383ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8140/8417 [2:01:43<05:28,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:15 | 200 |   170.74972ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8141/8417 [2:01:44<05:25,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:17 | 200 |  149.857231ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8142/8417 [2:01:46<05:21,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:18 | 200 |  176.905476ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8143/8417 [2:01:47<05:19,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:19 | 200 |  151.152156ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8144/8417 [2:01:48<05:16,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:20 | 200 |  149.040076ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8145/8417 [2:01:49<05:15,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:21 | 200 |  178.835842ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8146/8417 [2:01:50<05:17,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:22 | 200 |   179.96652ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8147/8417 [2:01:51<05:16,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:24 | 200 |  167.525084ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8148/8417 [2:01:53<05:15,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:25 | 200 |  161.763232ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8149/8417 [2:01:54<05:13,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:26 | 200 |  143.991799ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8150/8417 [2:01:55<05:10,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:27 | 200 |  188.608144ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8151/8417 [2:01:56<05:11,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:28 | 200 |  156.880784ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8152/8417 [2:01:57<05:09,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:29 | 200 |  145.645083ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8153/8417 [2:01:58<05:06,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:31 | 200 |  180.396432ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8154/8417 [2:02:00<05:07,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:32 | 200 |  134.088997ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8155/8417 [2:02:01<05:04,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:33 | 200 |  179.821983ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8156/8417 [2:02:02<05:04,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:34 | 200 |  146.870937ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8157/8417 [2:02:03<05:03,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:35 | 200 |   178.85431ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8158/8417 [2:02:04<05:01,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:36 | 200 |  183.494292ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8159/8417 [2:02:05<05:04,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:38 | 200 |  177.957422ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8160/8417 [2:02:07<05:03,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:39 | 200 |  154.013096ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8161/8417 [2:02:08<05:03,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:40 | 200 |  183.214015ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8162/8417 [2:02:09<05:02,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:41 | 200 |  121.705035ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8163/8417 [2:02:10<04:57,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:42 | 200 |  140.384389ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8164/8417 [2:02:11<04:54,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:43 | 200 |  173.049988ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8165/8417 [2:02:12<04:53,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:45 | 200 |  170.732334ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8166/8417 [2:02:14<04:52,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:46 | 200 |  160.061903ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8167/8417 [2:02:15<04:54,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:47 | 200 |  181.383145ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8168/8417 [2:02:16<04:54,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:48 | 200 |  150.784229ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8169/8417 [2:02:17<04:50,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:49 | 200 |  122.967645ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8170/8417 [2:02:18<04:45,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:50 | 200 |  173.989966ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8171/8417 [2:02:19<04:49,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:52 | 200 |  181.076884ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8172/8417 [2:02:21<04:50,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:53 | 200 |  179.106708ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8173/8417 [2:02:22<04:48,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:54 | 200 |  173.920599ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8174/8417 [2:02:23<04:47,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:55 | 200 |  144.699148ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8175/8417 [2:02:24<04:42,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:56 | 200 |   139.71047ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8176/8417 [2:02:25<04:39,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:57 | 200 |  175.290663ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8177/8417 [2:02:26<04:40,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:26:59 | 200 |  182.156293ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8178/8417 [2:02:28<04:40,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:00 | 200 |  179.151433ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8179/8417 [2:02:29<04:40,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:01 | 200 |   160.92955ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8180/8417 [2:02:30<04:37,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:02 | 200 |  139.401038ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8181/8417 [2:02:31<04:34,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:03 | 200 |  183.874406ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8182/8417 [2:02:32<04:35,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:04 | 200 |  151.234095ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8183/8417 [2:02:34<04:33,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:06 | 200 |  173.442606ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8184/8417 [2:02:35<04:32,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:07 | 200 |  175.611749ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8185/8417 [2:02:36<04:31,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:08 | 200 |  149.657451ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8186/8417 [2:02:37<04:29,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:09 | 200 |  142.291991ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8187/8417 [2:02:38<04:25,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:10 | 200 |  176.907155ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8188/8417 [2:02:39<04:28,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:12 | 200 |  177.738251ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8189/8417 [2:02:41<04:28,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:13 | 200 |  179.205196ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8190/8417 [2:02:42<04:27,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:14 | 200 |  175.494727ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8191/8417 [2:02:43<04:25,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:15 | 200 |  163.316511ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8192/8417 [2:02:44<04:25,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:16 | 200 |  142.511688ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8193/8417 [2:02:45<04:24,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:17 | 200 |  153.096876ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8194/8417 [2:02:46<04:24,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:19 | 200 |  180.926418ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8195/8417 [2:02:48<04:25,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:20 | 200 |  149.354126ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8196/8417 [2:02:49<04:23,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:21 | 200 |  148.304002ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8197/8417 [2:02:50<04:19,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:22 | 200 |  179.803532ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8198/8417 [2:02:51<04:19,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:23 | 200 |  145.111196ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8199/8417 [2:02:52<04:16,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:25 | 200 |  179.771801ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8200/8417 [2:02:54<04:18,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:26 | 200 |  169.884731ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8201/8417 [2:02:55<04:17,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:27 | 200 |  182.084599ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8202/8417 [2:02:56<04:16,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:28 | 200 |  171.960066ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8203/8417 [2:02:57<04:15,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:29 | 200 |   177.28524ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8204/8417 [2:02:58<04:14,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:31 | 200 |  180.987621ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8205/8417 [2:03:00<04:15,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:32 | 200 |  179.947528ms |       127.0.0.1 | POST     "/api/chat"

 97%|█████████▋| 8206/8417 [2:03:01<04:12,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:33 | 200 |  179.042963ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8207/8417 [2:03:02<04:10,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:34 | 200 |  170.589235ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8208/8417 [2:03:03<04:08,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:35 | 200 |  149.002214ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8209/8417 [2:03:04<04:07,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:36 | 200 |  137.510286ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8210/8417 [2:03:05<04:01,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:38 | 200 |  175.095513ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8211/8417 [2:03:07<04:00,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:39 | 200 |  186.301492ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8212/8417 [2:03:08<04:00,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:40 | 200 |  179.892732ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8213/8417 [2:03:09<04:00,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:41 | 200 |  152.914443ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8214/8417 [2:03:10<03:58,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:42 | 200 |  139.769322ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8215/8417 [2:03:11<03:55,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:43 | 200 |  146.549593ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8216/8417 [2:03:12<03:53,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:45 | 200 |  177.512547ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8217/8417 [2:03:14<03:51,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:46 | 200 |  132.090751ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8218/8417 [2:03:15<03:48,  1.15s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:47 | 200 |  181.306614ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8219/8417 [2:03:16<03:49,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:48 | 200 |  144.069125ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8220/8417 [2:03:17<03:51,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:49 | 200 |  161.206437ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8221/8417 [2:03:18<03:49,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:50 | 200 |  174.690121ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8222/8417 [2:03:19<03:49,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:52 | 200 |  185.931041ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8223/8417 [2:03:21<03:49,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:53 | 200 |   182.13863ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8224/8417 [2:03:22<03:47,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:54 | 200 |  176.055426ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8225/8417 [2:03:23<03:46,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:55 | 200 |   152.26501ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8226/8417 [2:03:24<03:44,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:56 | 200 |  142.916048ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8227/8417 [2:03:25<03:41,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:58 | 200 |  189.545957ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8228/8417 [2:03:27<03:42,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:27:59 | 200 |  143.813779ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8229/8417 [2:03:28<03:40,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:00 | 200 |    181.4209ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8230/8417 [2:03:29<03:40,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:01 | 200 |  185.746534ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8231/8417 [2:03:30<03:40,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:02 | 200 |  180.142918ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8232/8417 [2:03:31<03:38,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:03 | 200 |  172.452357ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8233/8417 [2:03:32<03:38,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:05 | 200 |  168.591788ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8234/8417 [2:03:34<03:36,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:06 | 200 |  140.783144ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8235/8417 [2:03:35<03:33,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:07 | 200 |  183.175055ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8236/8417 [2:03:36<03:33,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:08 | 200 |  150.138632ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8237/8417 [2:03:37<03:31,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:09 | 200 |  143.625938ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8238/8417 [2:03:38<03:28,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:10 | 200 |  177.984723ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8239/8417 [2:03:39<03:29,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:12 | 200 |  125.297966ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8240/8417 [2:03:41<03:25,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:13 | 200 |  186.615618ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8241/8417 [2:03:42<03:27,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:14 | 200 |   146.73017ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8242/8417 [2:03:43<03:24,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:15 | 200 |  145.006682ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8243/8417 [2:03:44<03:26,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:16 | 200 |  181.138298ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8244/8417 [2:03:45<03:25,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:18 | 200 |  146.211566ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8245/8417 [2:03:47<03:22,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:19 | 200 |  140.540655ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8246/8417 [2:03:48<03:21,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:20 | 200 |  185.350933ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8247/8417 [2:03:49<03:26,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:21 | 200 |  184.477352ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8248/8417 [2:03:50<03:24,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:22 | 200 |  143.864588ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8249/8417 [2:03:51<03:20,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:24 | 200 |  181.754151ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8250/8417 [2:03:53<03:22,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:25 | 200 |  160.809128ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8251/8417 [2:03:54<03:18,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:26 | 200 |  145.905861ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8252/8417 [2:03:55<03:16,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:27 | 200 |  181.693332ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8253/8417 [2:03:56<03:16,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:28 | 200 |  181.947924ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8254/8417 [2:03:57<03:15,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:30 | 200 |  179.276021ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8255/8417 [2:03:59<03:13,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:31 | 200 |  207.619743ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8256/8417 [2:04:00<03:14,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:32 | 200 |  156.495347ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8257/8417 [2:04:01<03:11,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:33 | 200 |  178.701861ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8258/8417 [2:04:02<03:09,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:34 | 200 |   158.75381ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8259/8417 [2:04:03<03:07,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:36 | 200 |  146.852057ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8260/8417 [2:04:05<03:05,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:37 | 200 |  138.840061ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8261/8417 [2:04:06<03:03,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:38 | 200 |   182.95964ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8262/8417 [2:04:07<03:02,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:39 | 200 |   157.42298ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8263/8417 [2:04:08<03:02,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:40 | 200 |   147.86599ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8264/8417 [2:04:09<03:01,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:41 | 200 |  149.395936ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8265/8417 [2:04:10<02:58,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:43 | 200 |  181.032689ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8266/8417 [2:04:12<02:57,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:44 | 200 |  142.767832ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8267/8417 [2:04:13<02:55,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:45 | 200 |  180.697744ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8268/8417 [2:04:14<02:55,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:46 | 200 |  146.632219ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8269/8417 [2:04:15<02:54,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:47 | 200 |  149.231774ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8270/8417 [2:04:16<02:53,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:48 | 200 |  174.800265ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8271/8417 [2:04:17<02:52,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:50 | 200 |  179.835752ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8272/8417 [2:04:19<02:51,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:51 | 200 |  201.021856ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8273/8417 [2:04:20<02:52,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:52 | 200 |  185.633673ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8274/8417 [2:04:21<02:53,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:53 | 200 |  127.937045ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8275/8417 [2:04:22<02:52,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:54 | 200 |  176.903735ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8276/8417 [2:04:24<02:49,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:56 | 200 |  162.385901ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8277/8417 [2:04:25<02:47,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:57 | 200 |  180.906403ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8278/8417 [2:04:26<02:45,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:58 | 200 |  177.188334ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8279/8417 [2:04:27<02:43,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:28:59 | 200 |  166.477717ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8280/8417 [2:04:28<02:41,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:00 | 200 |  141.695456ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8281/8417 [2:04:29<02:40,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:02 | 200 |  184.026951ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8282/8417 [2:04:31<02:38,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:03 | 200 |  142.012759ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8283/8417 [2:04:32<02:37,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:04 | 200 |  188.074172ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8284/8417 [2:04:33<02:37,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:05 | 200 |  166.062642ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8285/8417 [2:04:34<02:36,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:06 | 200 |  184.803113ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8286/8417 [2:04:35<02:36,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:07 | 200 |  182.420272ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8287/8417 [2:04:37<02:34,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:09 | 200 |  179.648294ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8288/8417 [2:04:38<02:34,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:10 | 200 |  178.400372ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8289/8417 [2:04:39<02:35,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:11 | 200 |  168.899429ms |       127.0.0.1 | POST     "/api/chat"

 98%|█████████▊| 8290/8417 [2:04:40<02:34,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:12 | 200 |  152.431024ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8291/8417 [2:04:41<02:30,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:13 | 200 |  141.048944ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8292/8417 [2:04:43<02:27,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:15 | 200 |  145.419348ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8293/8417 [2:04:44<02:26,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:16 | 200 |  176.825835ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8294/8417 [2:04:45<02:26,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:17 | 200 |  152.365056ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8295/8417 [2:04:46<02:24,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:18 | 200 |  148.944197ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8296/8417 [2:04:47<02:21,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:19 | 200 |  179.977493ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8297/8417 [2:04:48<02:22,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:21 | 200 |   126.39759ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8298/8417 [2:04:50<02:19,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:22 | 200 |  180.491007ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8299/8417 [2:04:51<02:19,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:23 | 200 |  179.444546ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8300/8417 [2:04:52<02:20,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:24 | 200 |  154.300545ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8301/8417 [2:04:53<02:18,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:25 | 200 |  176.012973ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8302/8417 [2:04:54<02:17,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:27 | 200 |  179.315627ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8303/8417 [2:04:56<02:15,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:28 | 200 |  178.154338ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8304/8417 [2:04:57<02:15,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:29 | 200 |   177.31072ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8305/8417 [2:04:58<02:15,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:30 | 200 |  137.649567ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8306/8417 [2:04:59<02:12,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:31 | 200 |  183.173564ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8307/8417 [2:05:00<02:12,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:33 | 200 |    163.5568ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8308/8417 [2:05:02<02:09,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:34 | 200 |  183.606391ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8309/8417 [2:05:03<02:09,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:35 | 200 |  174.775663ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8310/8417 [2:05:04<02:07,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:36 | 200 |   162.40077ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▊| 8311/8417 [2:05:05<02:05,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:37 | 200 |  140.784513ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8312/8417 [2:05:06<02:02,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:38 | 200 |   183.64399ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8313/8417 [2:05:07<02:01,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:40 | 200 |  161.675402ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8314/8417 [2:05:09<02:00,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:41 | 200 |   202.38781ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8315/8417 [2:05:10<02:01,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:42 | 200 |  150.110424ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8316/8417 [2:05:11<01:59,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:43 | 200 |  187.481652ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8317/8417 [2:05:12<01:59,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:44 | 200 |  171.868438ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8318/8417 [2:05:13<01:57,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:46 | 200 |   166.41092ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8319/8417 [2:05:15<01:56,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:47 | 200 |  152.323233ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8320/8417 [2:05:16<01:54,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:48 | 200 |  141.052152ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8321/8417 [2:05:17<01:52,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:49 | 200 |   180.23875ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8322/8417 [2:05:18<01:51,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:50 | 200 |  151.388161ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8323/8417 [2:05:19<01:50,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:51 | 200 |  179.441143ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8324/8417 [2:05:20<01:50,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:53 | 200 |  183.207234ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8325/8417 [2:05:22<01:48,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:54 | 200 |  177.345059ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8326/8417 [2:05:23<01:48,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:55 | 200 |  197.098898ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8327/8417 [2:05:24<01:49,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:56 | 200 |  152.993605ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8328/8417 [2:05:25<01:46,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:57 | 200 |  142.219376ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8329/8417 [2:05:26<01:44,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:29:59 | 200 |  179.213638ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8330/8417 [2:05:28<01:43,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:00 | 200 |  176.418397ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8331/8417 [2:05:29<01:42,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:01 | 200 |    158.0654ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8332/8417 [2:05:30<01:40,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:02 | 200 |  139.601867ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8333/8417 [2:05:31<01:38,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:03 | 200 |  179.443121ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8334/8417 [2:05:32<01:40,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:05 | 200 |  152.985331ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8335/8417 [2:05:34<01:37,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:06 | 200 |  147.474812ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8336/8417 [2:05:35<01:35,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:07 | 200 |  113.025247ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8337/8417 [2:05:36<01:33,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:08 | 200 |  180.162126ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8338/8417 [2:05:37<01:32,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:09 | 200 |  166.469116ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8339/8417 [2:05:38<01:31,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:10 | 200 |  147.111259ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8340/8417 [2:05:39<01:30,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:12 | 200 |  141.808016ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8341/8417 [2:05:41<01:28,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:13 | 200 |  182.453419ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8342/8417 [2:05:42<01:28,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:14 | 200 |    153.5977ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8343/8417 [2:05:43<01:27,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:15 | 200 |  145.877779ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8344/8417 [2:05:44<01:26,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:16 | 200 |  181.327374ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8345/8417 [2:05:45<01:25,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:18 | 200 |  171.087524ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8346/8417 [2:05:47<01:24,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:19 | 200 |  179.869232ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8347/8417 [2:05:48<01:23,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:20 | 200 |   137.13882ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8348/8417 [2:05:49<01:22,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:21 | 200 |  143.709181ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8349/8417 [2:05:50<01:20,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:22 | 200 |  172.506037ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8350/8417 [2:05:51<01:18,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:23 | 200 |  146.954239ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8351/8417 [2:05:52<01:17,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:25 | 200 |  148.868031ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8352/8417 [2:05:54<01:15,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:26 | 200 |  182.172157ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8353/8417 [2:05:55<01:16,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:27 | 200 |  157.490881ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8354/8417 [2:05:56<01:15,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:28 | 200 |  150.883632ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8355/8417 [2:05:57<01:13,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:29 | 200 |  141.725828ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8356/8417 [2:05:58<01:11,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:31 | 200 |  147.171905ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8357/8417 [2:06:00<01:10,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:32 | 200 |  179.255174ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8358/8417 [2:06:01<01:09,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:33 | 200 |   144.03741ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8359/8417 [2:06:02<01:08,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:34 | 200 |  136.972268ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8360/8417 [2:06:03<01:06,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:35 | 200 |  180.935369ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8361/8417 [2:06:04<01:06,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:36 | 200 |  159.317445ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8362/8417 [2:06:05<01:04,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:38 | 200 |  142.187845ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8363/8417 [2:06:07<01:03,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:39 | 200 |  172.300834ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8364/8417 [2:06:08<01:02,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:40 | 200 |  181.515079ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8365/8417 [2:06:09<01:01,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:41 | 200 |   161.63944ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8366/8417 [2:06:10<01:00,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:42 | 200 |  153.588721ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8367/8417 [2:06:11<00:58,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:43 | 200 |  142.079557ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8368/8417 [2:06:12<00:57,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:45 | 200 |  180.381108ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8369/8417 [2:06:14<00:56,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:46 | 200 |   150.06763ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8370/8417 [2:06:15<00:55,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:47 | 200 |  179.712985ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8371/8417 [2:06:16<00:54,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:48 | 200 |   185.36056ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8372/8417 [2:06:17<00:53,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:49 | 200 |  177.085931ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8373/8417 [2:06:18<00:52,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:51 | 200 |  146.817708ms |       127.0.0.1 | POST     "/api/chat"

 99%|█████████▉| 8374/8417 [2:06:20<00:50,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:52 | 200 |   171.77689ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8375/8417 [2:06:21<00:49,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:53 | 200 |  141.015288ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8376/8417 [2:06:22<00:48,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:54 | 200 |  144.008554ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8377/8417 [2:06:23<00:47,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:55 | 200 |  148.203291ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8378/8417 [2:06:24<00:45,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:56 | 200 |  178.445734ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8379/8417 [2:06:25<00:44,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:58 | 200 |  174.873507ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8380/8417 [2:06:27<00:45,  1.22s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:30:59 | 200 |  161.721665ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8381/8417 [2:06:28<00:43,  1.21s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:00 | 200 |  143.732368ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8382/8417 [2:06:29<00:42,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:01 | 200 |  181.756506ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8383/8417 [2:06:30<00:40,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:02 | 200 |    119.5999ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8384/8417 [2:06:31<00:38,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:04 | 200 |   170.10057ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8385/8417 [2:06:33<00:37,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:05 | 200 |   163.24749ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8386/8417 [2:06:34<00:36,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:06 | 200 |  138.849188ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8387/8417 [2:06:35<00:35,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:07 | 200 |  138.784301ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8388/8417 [2:06:36<00:33,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:08 | 200 |  175.505675ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8389/8417 [2:06:37<00:32,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:09 | 200 |  142.408208ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8390/8417 [2:06:38<00:31,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:11 | 200 |  175.845292ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8391/8417 [2:06:40<00:30,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:12 | 200 |  150.406137ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8392/8417 [2:06:41<00:29,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:13 | 200 |   146.35184ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8393/8417 [2:06:42<00:27,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:14 | 200 |  174.555462ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8394/8417 [2:06:43<00:26,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:15 | 200 |   174.76176ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8395/8417 [2:06:44<00:25,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:16 | 200 |  170.743425ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8396/8417 [2:06:45<00:24,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:18 | 200 |  157.284873ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8397/8417 [2:06:47<00:23,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:19 | 200 |  141.129446ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8398/8417 [2:06:48<00:22,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:20 | 200 |  174.785986ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8399/8417 [2:06:49<00:21,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:21 | 200 |  166.648862ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8400/8417 [2:06:50<00:20,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:22 | 200 |  145.921346ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8401/8417 [2:06:51<00:18,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:24 | 200 |  178.629398ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8402/8417 [2:06:53<00:17,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:25 | 200 |  181.044115ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8403/8417 [2:06:54<00:16,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:26 | 200 |  175.604398ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8404/8417 [2:06:55<00:15,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:27 | 200 |  144.375341ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8405/8417 [2:06:56<00:14,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:28 | 200 |  170.614407ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8406/8417 [2:06:57<00:13,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:29 | 200 |  139.402921ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8407/8417 [2:06:58<00:11,  1.19s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:31 | 200 |   183.59032ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8408/8417 [2:07:00<00:10,  1.20s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:32 | 200 |  148.107797ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8409/8417 [2:07:01<00:09,  1.18s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:33 | 200 |    140.7798ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8410/8417 [2:07:02<00:08,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:34 | 200 |  171.077505ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8411/8417 [2:07:03<00:07,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:35 | 200 |  170.826203ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8412/8417 [2:07:04<00:05,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:36 | 200 |  158.665548ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8413/8417 [2:07:05<00:04,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:38 | 200 |  145.883555ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8414/8417 [2:07:07<00:03,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:39 | 200 |  180.007803ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8415/8417 [2:07:08<00:02,  1.16s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:40 | 200 |  177.185215ms |       127.0.0.1 | POST     "/api/chat"

100%|█████████▉| 8416/8417 [2:07:09<00:01,  1.17s/it]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

[GIN] 2025/06/27 - 01:31:41 | 200 |  145.170664ms |       127.0.0.1 | POST     "/api/chat"

100%|██████████| 8417/8417 [2:07:10<00:00,  1.10it/s]

Saved classified results to classified_cases.csv

In [11]:
# Display the results
classified_df = pd.read_csv("/kaggle/working/classified_cases.csv")
classified_df.head()

cases_df["predictions"] = classified_df["predicted_class"]
cases_df.head()

,Unnamed: 0,text,label,predictions
0,0,halliburton oil cementing v walker mrearl babc...,209,5.0
1,1,rehearing denied dec mrclaude t barnes salt la...,63,2.0
2,2,rehearing denied dec appeal district court uni...,216,2.0
3,3,mr walter j cummings jr washington dc petition...,108,9.0
4,4,mra devitt vaneck washington dc petitioner mr ...,196,6.0

In [12]:
from sklearn.metrics import accuracy_score

# Ensure there are no NaNs in either column
valid_rows = cases_df.dropna(subset=["predictions", "label"])

# Compute and print accuracy
accuracy = accuracy_score(valid_rows["label"], valid_rows["predictions"])
print(f"Classification Accuracy: {accuracy:.4f}")

Classification Accuracy: 0.0056